_includes/docs/2.5/ajax-api.html, _includes/docs/2.5/sidebar.html
=> Add documentation on how to schedule a flow using the AJAX API

_includes/docs/2.5/ajax-api.html, _includes/docs/2.5/sidebar.html
=> Added documentation for unschedule a flow using the AJAX API

azkaban-execserver/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-execserver/src/test/java/azkaban/execapp/event/BlockingStatusTest.java
=> FlowRunnerManager.CleanerThread dies without a log/stacktrace

azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java, azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/main/java/azkaban/project/validator/XmlValidatorManager.java, azkaban-common/src/main/java/azkaban/utils/DirectoryFlowLoader.java, azkaban-common/src/main/java/azkaban/utils/SystemMemoryInfo.java, azkaban-common/src/main/java/azkaban/utils/Utils.java, azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java, azkaban-common/src/test/java/azkaban/utils/DirectoryFlowLoaderTest.java, azkaban-common/src/test/java/azkaban/utils/MemUtilsTest.java, azkaban-execserver/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerTest2.java, azkaban-webserver/src/main/java/azkaban/webapp/AzkabanWebServer.java
=> add system memory awareness to Azkaban

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-common/src/main/java/azkaban/project/ProjectWhitelist.java, azkaban-common/src/main/java/azkaban/project/validator/ProjectValidator.java, azkaban-common/src/main/java/azkaban/project/validator/ValidatorManager.java, azkaban-common/src/main/java/azkaban/project/validator/XmlValidatorManager.java, azkaban-common/src/main/java/azkaban/utils/DirectoryFlowLoader.java, azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java, azkaban-common/src/test/java/azkaban/utils/DirectoryFlowLoaderTest.java, azkaban-execserver/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerTest2.java, azkaban-webserver/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
=> project whitelist support

azkaban-execserver/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
=> adding a config to allow specifying Jetty HeaderBufferSize in ExecServer: pull request

_includes/docs/latest/ajax-api.html, _includes/docs/latest/database-setup.html, _includes/docs/latest/hadoopjava-type.html, _includes/docs/latest/job-configuration.html, _includes/docs/latest/new-hive-type.html, _includes/docs/latest/pig-type.html, _includes/docs/latest/reload-jobtypes.html, _includes/docs/latest/sidebar.html, docs/latest/index.html
=> Added the missing changes from 2.5

azkaban-common/src/main/java/azkaban/executor/selector/CandidateComparator.java, azkaban-common/src/main/java/azkaban/executor/selector/CandidateFilter.java, azkaban-common/src/main/java/azkaban/executor/selector/CandidateSelector.java, azkaban-common/src/main/java/azkaban/executor/selector/FactorComparator.java, azkaban-common/src/main/java/azkaban/executor/selector/FactorFilter.java, azkaban-common/src/main/java/azkaban/executor/selector/Selector.java, azkaban-common/src/test/java/azkaban/executor/SelectorTest.java
=> Rename classes and disable the setter and getter for filters and comparator

azkaban-execserver/src/main/java/azkaban/execapp/ServerStatisticsServlet.java
as the atomic procedure is now fast enough, switching back to the single thread mode.
=> switch the process to collect statistics data back into single thread mode

azkaban-common/src/main/java/azkaban/executor/selector/CandidateComparator.java, azkaban-common/src/main/java/azkaban/executor/selector/CandidateSelector.java, azkaban-common/src/main/java/azkaban/executor/selector/ExecutorFilter.java, azkaban-common/src/main/java/azkaban/executor/selector/ExecutorSelector.java, azkaban-common/src/main/java/azkaban/executor/selector/Selector.java
change some of the interface from asking for List to Collection object so that the caller doesn't need to do conversion if it maintains an object of type Set.
=> Adjust data type for some of the interfaces for easy consumption.

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
increasing executors refresh interval to 10 sec and using remaining executors instead of all executors
=> set refresh interval to 10 sec and using remaining executors

azkaban-common/src/main/java/azkaban/executor/selector/ExecutorFilter.java
=> Fix typo in filter name .

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
* Removing cached ExecutorInfos
* changing default params for maxDispatchingErrors
=> Removing cached ExecutorInfos and changing defaults

azkaban-execserver/src/main/java/azkaban/execapp/ServerStatisticsServlet.java, azkaban-execserver/src/test/java/azkaban/execapp/StatisticsServletTest.java
fix the free memory calculation in the executor server.
=> Fix the free memory calculation on the executor box.

azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java, azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-common/src/main/java/azkaban/project/validator/XmlValidatorManager.java, azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java, azkaban-common/src/test/java/azkaban/project/DirectoryFlowLoaderTest.java, azkaban-common/src/test/java/azkaban/utils/cache/CacheTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java, azkaban-execserver/src/test/java/azkaban/execapp/FlowRunnerTest2.java
=> Move DirectoryFlowLoader to azkaban.project.

.travis.yml
Also, upgrade to Travis's container-based infrastructure.
Fixes #547
=> Run Travis CI against both JDK 7 and 8.

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
Added plugin directory to the property before resolving as needed by new TDCH jobs
=> Added plugin directory to the property before resolving as needed by new TDCH jobs

azkaban-webserver/src/main/java/azkaban/webapp/servlet/ProjectServlet.java
enhancing ProjectServlet: adding ajax api fetchallprojects, and fetchuserprojects
=> enhancing ProjectServlet: adding ajax api fetchallprojects, and fetchuserprojects

azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java, azkaban-common/src/main/java/azkaban/trigger/builtin/NyxTriggerChecker.java, azkaban-common/src/main/java/azkaban/utils/NyxUtils.java, azkaban-webserver/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/triggerpanel.vm, azkaban-webserver/src/web/js/azkaban/view/schedule-trigger.js, azkaban-webserver/src/web/js/azkaban/view/scheduled.js
Add data pipeline and UI to show trigger status in azkaban
=> 	Add data pipeline and UI to show trigger status in azkaban

azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-webserver/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
Fixes Issue #632
File handles are correctly closed during project upload.
=> Fixes leaked file handles during Project Upload

azkaban-common/src/main/java/azkaban/scheduler/Schedule.java, azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java, azkaban-common/src/main/java/azkaban/trigger/builtin/NyxTriggerChecker.java, azkaban-common/src/main/java/azkaban/utils/NyxUtils.java, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/triggerpanel.vm, azkaban-webserver/src/web/js/azkaban/view/schedule-trigger.js
Bug fix - not to register trigger when the schedule is set, add feature to disable Trigger status button when the nyxTrigger doesnot exist in the project pack, some ui updates etc
=> Merge from individual branch for bug fix	

_includes/docs/latest/hadoopshell-type.html, _includes/docs/latest/property-override.html, _includes/docs/latest/sidebar.html, docs/latest/index.html
Documenting user-facing aspects of hadoopShell jobtype and uncovering mysteries of property overrides in azkaban.
=> HadoopShell jobtype and property override documentation

_includes/docs/latest/azkaban-webserver.html
add lockdown.upload.project documentation
=> adding lockdown.upload.project documentation

_includes/docs/latest/ajax-api.html
documentation should explain the scheduletime  time zone info
=> documentation should explain the scheduletime  time zone info

azkaban-common/build.gradle, azkaban-common/src/main/java/azkaban/scheduler/Schedule.java, azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java, azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java, azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java, azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java, azkaban-common/src/main/java/azkaban/utils/Utils.java, azkaban-common/src/test/java/azkaban/trigger/BasicTimeCheckerTest.java, azkaban-common/src/test/java/azkaban/trigger/ConditionTest.java, azkaban-common/src/test/java/azkaban/trigger/JdbcTriggerLoaderTest.java, azkaban-common/src/test/java/azkaban/trigger/TriggerTest.java, azkaban-execserver/src/test/java/azkaban/execapp/event/BlockingStatusTest.java, azkaban-migration/src/main/java/azkaban/migration/schedule2trigger/Schedule2Trigger.java, azkaban-webserver/build.gradle, azkaban-webserver/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java, azkaban-webserver/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm, azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanelDeprecated.vm, azkaban-webserver/src/web/js/azkaban/view/schedule-panel.js, azkaban-webserver/src/web/js/azkaban/view/schedule-panelDeprecated.js
This pull request is to fix issue #693 .
Before this change, Azkaban users can not flexibly schedule a job (described in document in issue #693). This code patch uses quartz library to import cron settings to enhance the scheduling capability. A new schedule UI is brought for users.  Besides, this change also fixed daylight saving change bug #727 .
=> Final squash Flexible Scheduling

_includes/docs/latest/ajax-api.html
Close #709 
This pull request is to write API documentation for Cron Schedule.
=> Flexible schedule api Documentation

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm, azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js
Add a warning description in top of Schedule Page. Users would be able to know the limitations of Quartz Cron by this. Also fixed reset behaviors by modifying html.
=> Add dst warning to schedule page

_includes/docs/latest/ajax-api.html, _includes/docs/latest/building-from-source.html, _includes/docs/latest/sidebar.html
Removed the deprecated building methods, and updated to the latest gradle building to there.
=> Fix build source doc

_config.yml
Followed the instructions in #697 . Fixed. 
Has to be varied by merging this pull request.
=> fix github page warning by replacing highlighter value

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
Our production AZ is filled with these redundant logs, and needs a cleanup.
Verified in local environment.
=> removing redundant logs

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
Failed uploads through Ajax interface reported HTTP code 200 when it
should be 400. There are other similar errors in this module, but this
commit only fixes failed uploads.
=> Made failed uploads return a HTTP 400 response (#792)

azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js, azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js
Tired of clicking exit "X" every time when I don't want to schedule or execute a flow.
This pull request maps escape key to exit popup window.
Verified in my local environment
=> pressing ESC key to help escapte the execute flow option and schedulePage

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/test/java/azkaban/jobExecutor/AllJobExecutorTests.java, azkaban-common/src/test/java/azkaban/jobExecutor/JavaProcessJobTest.java, azkaban-common/src/test/java/azkaban/jobExecutor/ProcessJobTest.java
Combined common code to configure job properties in one method.
Changes based on comments in Pull request #807.
=> Consolidate common code808

azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java, azkaban-web-server/src/main/less/navbar.less, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/nav.vm
Currently there is no way of finding the Azkaban version of the web UI. With this patch the version will show up under the Azkaban logo and will persist on every page.
I have attached a preview below on how it looks
=> Show version number in Azkaban logo in Web server UI

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
https://github.com/azkaban/azkaban/issues/564
=> Issue #564 - Improve error message of scheduleFlow API

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/ProjectVersion.java
1. make rename operation atomic (#831)
2. only active deployment is allowed to perform deletion of projects
This is the prequisite of making project directory as shared among multiple deployments
=> shared project directory

_includes/docs/latest/how-to.html
Added some information on how to use Kafka logging for user logs.
=> Added documentation on Kafka logging

.gitignore, GemFile, README.md, _config.yml, _includes/docs/latest/building-from-source.html, _includes/docs/latest/solo-setup.html
Added instructions to build and run documentation site on systems with higher level of security.
Updated documentation to get started with solo server. Also updated building from source with more info.
=> Updated readme and getting started documentation

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
FlowRunnerManager should be inactive until explicitly activating it from API.
=> active is initialized to false when constructing FlowRunnerManager.

azkaban-common/build.gradle, azkaban-spi/README.md, azkaban-spi/build.gradle, azkaban-spi/src/main/java/com/linkedin/azkaban/spi/AzkabanException.java, azkaban-spi/src/main/java/com/linkedin/azkaban/spi/KeyAlreadyExistsException.java, azkaban-spi/src/main/java/com/linkedin/azkaban/spi/KeyDoesNotExistException.java, azkaban-spi/src/main/java/com/linkedin/azkaban/spi/Storage.java, azkaban-spi/src/main/java/com/linkedin/azkaban/spi/StorageException.java
Creating the azkaban-spi package which is intended to be the contract against different Azkaban modules.
Added a Storage interface and related exception class hierarchy.
=> Creating the azkaban-spi sub-module and Storage Interface

azkaban-common/src/main/bash/util.sh
If all attempts to killing the web server/executor fail to kill the process, we will do a force kill (kill -9).
=> Shutdown the process with kill -9 at the end in shutdown scripts

azkaban-common/src/main/bash/util.sh, azkaban-solo-server/build.gradle, azkaban-solo-server/src/main/bash/azkaban-solo-shutdown.sh, azkaban-solo-server/src/main/bash/azkaban-solo-start.sh
Changes
- shutdown script was updated with the new shared logic
- launch script was refactored
- launch script to fail if server already started.
=> Fixed bash scripts for solo server.

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
Adding a log statement to capture plugin details and the classpath which is used to create the classloader for loading plugins.
=> Added logging for classpath information while loading plugins

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
Similar pull requests are following.
https://github.com/azkaban/azkaban/pull/890
https://github.com/azkaban/azkaban/pull/905
=> Add stacktrace when exception occurs in ScheduleServlet

azkaban-common/src/main/bash/util.sh, azkaban-common/src/test/bash/test_util.shunit2, azkaban-solo-server/src/main/bash/azkaban-solo-start.sh
This PR will fix the azkaban-solo startup problem reported in issue #957. Additionally, I have included a few shunit2 unit tests for utils.sh.  With future PR's, we should request the contributor make additions to the unit tests.
shunit2 can easily be installed with brew on os X or your favorite package manager.
=> Issue #957 - fixes to azkaban-solo start & shunit2 unit tests

_includes/docs/latest/ajax-api.html, _includes/docs/latest/sidebar.html
=> Add fetchSchedule API document

_includes/docs/latest/ajax-api.html, _includes/docs/latest/sidebar.html
setSla
Honestly, setSla document is difficult to write but better than nothing.
ref: https://github.com/azkaban/azkaban/issues/603
slaInfo
=> Add setSla and slaInfo API documents

azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java
Testing: 
All unit tests passed.
=> Delete unused DB related methods

azkaban-web-server/.gitignore
They are created by the unit test process.
=> Ignore node modules

.gitignore
Ignore the following:
.DS_Store
.bundle/
Gemfile.lock
vendor/
=> Ignore a few more files

.gitignore
There are log files tracked by Git
e.g. under azkaban.test.executions.logtest
=> Remove *.log from the top level .gitignore file

azkaban-common/src/test/java/azkaban/metrics/CommonMetricsTest.java
#1009
Will work on finding a better solution.
=> Disable flaky metrics related tests for now.

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-common/src/main/java/azkaban/project/ProjectManagerException.java, azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java, azkaban-common/src/main/java/azkaban/storage/LocalStorage.java, azkaban-common/src/main/java/azkaban/storage/StorageManager.java, azkaban-common/src/test/java/azkaban/project/JdbcProjectLoaderTest.java, azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java, azkaban-common/src/test/java/azkaban/project/ProjectManagerTest.java, azkaban-common/src/test/java/azkaban/storage/DatabaseStorageTest.java, azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java, azkaban-spi/src/main/java/azkaban/spi/Storage.java, azkaban-spi/src/main/java/azkaban/spi/StorageMetadata.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
Refactored Upload code to route upload files via the new Storage APIs.
Changes
- Implemented `put` API in `DatabaseStorage`
- Wired StorageManager to take in all upload requests. All requests are routed to the `DatabaseStorage` by default.
- Add injections for `ProjectManager`
- Updated `ProjectLoader` API
=> Implemented put API for Database Storage

azkaban-common/src/main/java/azkaban/database/AbstractJdbcLoader.java, azkaban-common/src/main/java/azkaban/database/AzkabanDatabaseSetup.java, azkaban-common/src/main/java/azkaban/database/AzkabanDatabaseUpdater.java
Found some never-used code, remove it. Also, refactor a little a bit in
these classes.
=> light refactor in existing database module

.gitignore
This is used by Intellij Shelf feature.
=> Ignore .shelf

azkaban-common/src/test/java/azkaban/jobExecutor/WordCountLocal.java
Warnings:
azkaban/azkaban-common/src/test/java/azkaban/jobExecutor/WordCountLocal.java:59: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
new BufferedReader(new InputStreamReader(new FileInputStream(_input)));
^
(see http://errorprone.info/bugpattern/DefaultCharset)
Did you mean 'new BufferedReader(new InputStreamReader(new FileInputStream(_input), UTF_8));' or 'new BufferedReader(new InputStreamReader(new FileInputStream(_input), Charset.defaultCharset()));'?
azkaban/azkaban-common/src/test/java/azkaban/jobExecutor/WordCountLocal.java:83: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being …
=> Fix warnings in azkaban.jobExecutor.WordCountLocal test

azkaban-sql/src/sql/upgrade.3.20.0.to.3.21.0.sql
Context: PR #1024 introduces a new column to 'project_versions' table
=> Adding DB Migration script for release > 3.20.0

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-web-server/build.gradle, azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java, azkaban-web-server/src/test/resources/azkaban-users.xml
Changes:
- Added `ExecutorLoader` binding to `AzkabanCommonModule`
- Added a test to ensure that instantiation of WebServer is successful
- Removed duplicate and derived dependencies from web-server build.gradle
=> Minor Refactor. Added a unit test for Web server instantiation

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java, azkaban-common/src/main/java/azkaban/AzkabanCommonModuleConfig.java, azkaban-common/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectLoader.java, azkaban-common/src/main/java/azkaban/storage/LocalStorage.java, azkaban-common/src/main/java/azkaban/storage/StorageManager.java, azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java, azkaban-common/src/test/java/azkaban/storage/DatabaseStorageTest.java, azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java, azkaban-spi/src/main/java/azkaban/spi/Storage.java, azkaban-spi/src/main/java/azkaban/spi/StorageMetadata.java
Changes:
- refactored Storage API to throw IOException
- extracted hash computation code to StorageManager
- Changed ProjectLoader API to accept hash as parameter
=> Storage Refactor. Changed filename to include hash of file

azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
Adding end date feature to Azkaban scheduler needs to modify ScheduleManager class. Before making it, we refactor this class ScheduleManager:
* remove unused code
* refactor code per intellij's advice
=> refactor ScheduleManager

azkaban-common/src/main/java/azkaban/trigger/Trigger.java
reformat trigger class by intellij plugin `save actions`
=> reformat trigger class

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
(based on 3rd commit of https://github.com/azkaban/azkaban/pull/1150)
Simplify and remove duplicate code in `FlowRunnerTestBase` (I was a bit lazy when creating this class and just trying to get the tests to pass).
=> Test cleanup: FlowRunnerTestBase

azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
As discussed in https://github.com/azkaban/azkaban/pull/1129#pullrequestreview-41944642, this doesn't need to be `public`.
=> Change InteractiveTestJob.testJobs back to private

azkaban-exec-server/src/test/java/azkaban/execapp/EventCollectorListener.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
(requires https://github.com/azkaban/azkaban/pull/1152 first. this PR is "about the second commit")
Test cleanup: rename checkEventExists -> assertEvents
=> Test cleanup: rename checkEventExists -> assertEvents

azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/AzkabanProcess.java, azkaban-common/src/main/java/azkaban/storage/LocalStorage.java, azkaban-common/src/main/java/azkaban/storage/StorageManager.java, azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java, azkaban-common/src/test/java/azkaban/executor/JavaJobRunnerMain.java, azkaban-common/src/test/java/azkaban/executor/SleepJavaJob.java, azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java
Used #1045 to base changes off of.
Didn't bring JdbcExecutorLoader up to date with intellij auto-formatting while @kunkun-tang finishes working on it.
=> Fixing DefaultCharset warnings in azkaban-common

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-exec-server/src/main/java/azkaban/execapp/ServerStatisticsServlet.java, azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackRequestMaker.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
Making changes similar to #1164 
Based changes off of #1045
=> Fixing DefaultCharset warnings in azkaban-web-server and azkaban-exec-server

azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerImpl.java
http://errorprone.info/bugpattern/ClassCanBeStatic
=> Fixing ClassCanBeStatic warning in azkaban-common

azkaban-web-server/src/main/java/azkaban/webapp/servlet/HistoryServlet.java
http://errorprone.info/bugpattern/ReferenceEquality
Any thoughts on unintended consequences?
=> Fixing ReferenceEquality warnings

azkaban-common/src/main/java/azkaban/utils/SystemMemoryInfo.java
There is no more warning in this file after this change.
=> Fix check style warning in SystemMemoryInfo

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java
http://errorprone.info/bugpattern/ImmutableEnumChecker
=> Guicing ExecMetrics and fixing related ImmutableEnumChecker warning

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
Step 1 of refactoring the log4j appender logic
related to #1224 
Use Idea's refactoring tool only to do this.
=> Move the pattern json object creation logic to a method.

build.gradle
see https://docs.gradle.org/current/userguide/comparing_builds.html
Testing:
Checked the generated result.
Upgrading to gradle 4.0 seems to generate the same result.
=> Add the comparingBuilds plugin

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java, azkaban-exec-server/src/main/java/azkaban/execapp/LogUtil.java
Step 2 of refactoring the log4j appender logic
Use Idea's refactoring tool only to do this.
=> Move the createLogPatternLayoutJsonObject to a separate class

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
http://errorprone.info/bugpattern/DoubleCheckedLocking
Collaborated with @suvodeep-pyne
=> Fix DoubleCheckedLocking warning in HadoopSecurityManager_H_2_0

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
loadFlow API was removed in https://github.com/azkaban/azkaban/pull/1182
But, there is no API to  get all schedule data.
I think that loadFlow API without stats will be acceptable.
=> Restore loadFlow API without stats

build.gradle
This reverts PR #1225 (commit e1f6d3942b29d917aa2afdd94cd2f7ce51a6f9e3)
This currently fails our internal build
=> Revert "Add the project-report gradle plugin (#1225)"

azkaban-common/src/main/java/azkaban/trigger/Trigger.java
submitted user should be deserialized from json instead of a constant value.
=> fix submitted user name for trigger when deserializing from json blob

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/test/java/azkaban/jobExecutor/ProcessJobTest.java
1. add unit test for #1253
2. minor fix for ProcessJob to make getProgress() work. getProgress() will be used in the unit test.
=> add unit test for #1253

_includes/docs/latest/azkaban-webserver.html
Updated documentation for property 'lockdown.upload.projects' to reflect the new behavior.
=> Updated documentation for block project uploads property.

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
refactor TriggerManager by smart Intellij
=> refactor TriggerManager by smart Intellij

azkaban-common/src/main/java/azkaban/executor/AlerterHolder.java, azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java, azkaban-common/src/main/java/azkaban/utils/Emailer.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java, azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java, azkaban-common/src/test/java/azkaban/utils/EmailerTest.java, azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java
Tested the metrics output/ingraph on localhost.
Guicified Emailer class and modified related test cases.
//TODO: refactor ExecutorManangerTest
=> Add metrics for sending email successs/failure.

azkaban-common/src/main/java/azkaban/server/session/Session.java, azkaban-common/src/main/java/azkaban/user/User.java
this would reduce the memory overhead for session to some extend so that we can increase the size of session cache more.
=> remove unused member variables in Session and User class

azkaban-common/src/main/java/azkaban/utils/AbstractMailer.java, azkaban-common/src/main/java/azkaban/utils/Emailer.java, azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecutorServerTest.java
Added default config in Emailer.
Removed unused configs in AbstractMailer.
Added test case on executor side for guicifying Emailer.
=> Add default config to Emailer

azkaban-web-server/src/main/java/azkaban/webapp/WebServerProvider.java
No logic change has been introduced
=> Refactoring the `ServerProvider` logic into separate methods

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/TriggerPluginLoader.java
=> Refactoring loadTriggerPlugins() method to `TriggerPluginLoader` class

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/PluginCheckerAndActionsLoader.java
=> Extracted loadPluginCheckerAndActions method to PluginCheckerAndActionsLoader class

_includes/docs/latest/schedule-flow.html
update related doc for https://github.com/azkaban/azkaban/pull/1092
=> update doc for SLA change

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
The motivation is to make it easy to add more routes to the web server. A lot of static code exists which makes it difficult to access dependent classes directly.
Refactor details:
- `prepareAndStartServer` and related methods were converted to instance method
- deprecating the `app` member which is a static reference to `AzkabanWebServer`. Not removing it because it may be used by downstream code.
=> Refactoring Web Server and related code.

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
Working on a bug related to this class and I don't want to make a PR with both changes, so sending off a quick PR for just running the SaveAction command on the ProcessJob class first.
=> Running SaveAction on ProcessJob

azkaban-common/build.gradle, azkaban-exec-server/build.gradle, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/Status.java, azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatusServlet.java
Current features:
- version
- used Memory
- Max memory: XMX value
- Database availability: SELECT 1 check
- Map of current executors
Example:
```
{
"version": "3.33.0-11-g1ac90f03",
"usedMemory": 65144664,
"xmx": 3817865216,
"isDatabaseUp": true,
"executorStatusMap": {
"104": {
"id": 104,
"host": "abc.def.company.com",
"port": 15462,
"isActive": true
}
}
}
```
=> New Status API for obtaining runtime information about Azkaban instance.

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
1. apply save plugin
2. make duplicate log construction logic an util method
=> a little refactor on job retry log

azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java, azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
Do the refactor before changing JDBC Executor Loader code.
=> Use Intellij Refactor plugin for the two JDBC classes

azkaban-common/src/main/java/azkaban/executor/ActiveExecutingFlowsDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionJobDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutorEventsDao.java, azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java, azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/test/java/azkaban/executor/JdbcExecutorLoaderTest.java, azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java
Even though this PR looks big, I actually use Intellij's `Delegate-refactor` feature to automate moving related member methods to delegate classes, which is also automatically created by Intellij. Didn't change the implementation yet, will change it after all moving process completes.
Added Guice Tests to guarantee guice functionality.
=> Use Intellij's Delegate feature to automate refactor process.

azkaban-common/src/main/java/azkaban/scheduler/Schedule.java
code reformatting on Schedule.java by save plugin.
=> apply save plugin on Schedule.java

azkaban-common/src/main/java/azkaban/scheduler/Schedule.java
=> format: reformat schedule.java only

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
As a follow-up of #1345, I'm rewriting fetchQueuedFlows and fetchRecentlyFinishedFlows methods in order to leverage new DB API.
Added corresponding unit tests.
=> rewrite fetchQueuedFlows and fetchRecentlyFinishedFlows

azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/main/java/azkaban/executor/NumExecutionsDao.java, azkaban-common/src/test/java/azkaban/executor/JdbcExecutorLoaderTest.java, azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java
As a follow-up of #1345, I'm rewriting fetchNumExecutableFlows and fetchNumExecutableNodes methods in order to leverage new DB API.
Added corresponding unit tests.
=> create num execution DAO class

build.gradle
See the change history at https://github.com/tbroyer/gradle-errorprone-plugin/commits/master
=> build: update error-prone gradle plugin to 0.0.11

azkaban-common/src/main/java/azkaban/Constants.java
Add `<p>` tags to add new lines.
see
https://stackoverflow.com/questions/5077382/javadoc-line-breaks-without-html-tags
https://stackoverflow.com/questions/11053144/how-to-see-javadoc-in-intellij-idea
=> format: properly format the javadoc for the azkaban.Constants class

azkaban-common/src/main/java/azkaban/database/EncodingType.java, azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java, azkaban-common/src/main/java/azkaban/utils/GZIPUtils.java
This code patch is basically a refactor, which consolidate common code into an utility method.
=> Consolidate duplicate transformByte To Object code

CONTRIBUTING.md, README.md
- Adopt content from https://azkaban.github.io/contributing.html
- Move the style guide from the README
See
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
=> doc: create a contribution guide

azkaban-common/src/main/java/azkaban/jobExecutor/Job.java
- Conform to the Google style guide.
See https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment
- Remove unnecessary descriptions. They are not the essence of the
contract.
=> Update the Javadoc for the Job interface

azkaban-common/src/test/java/azkaban/test/Utils.java, azkaban-db/src/main/java/azkaban/db/DatabaseSetup.java
constructing Quartz Test, which needs to create tables in h2-in-memory. This PR does:
* Remove unknown code
* simplify logic
=> refactor DatabaseSetup class for Quartz Test being developed [Refactor]

CONTRIBUTING.md
- Use slf4j instead of log4j.
- Add or update the copyright notice for most files.
- Add a link to the dev tips wiki.
- Explain how to use the azkaban-images repo.
=> Update dev guide

azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
The TODO about `seconds=0 or 10` remains because some tests remain with `@Ignore`.
=> Enable JobRunnerTest > testBasicRun

azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
=> Use assertj instead of hamcrest in JobRunnerTest

CONTRIBUTING.md, README.md
- Move IDE setup instructions to the dev guide
- Add the todo style guide
- Add the @Ignore coding convention
=> Doc: update the dev guide and README

azkaban-common/src/test/java/azkaban/executor/QueuedExecutionsTest.java, azkaban-common/src/test/java/azkaban/utils/TestUtils.java
=> Use TestUtils#createExecutableFlow in the QueuedExecutionsTest

azkaban-common/src/main/java/azkaban/utils/Emailer.java
This way already the e-mail title will tell which a) job level SLA, or b) flow level SLA, was triggered.
=> Include job/flow name in SLA alert title

azkaban-common/src/main/java/azkaban/project/AzkabanFlow.java, azkaban-common/src/main/java/azkaban/project/AzkabanJob.java, azkaban-common/src/main/java/azkaban/project/AzkabanNode.java, azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java, azkaban-common/src/main/java/azkaban/project/FlowLoader.java, azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java, azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java, azkaban-common/src/test/resources/sample_flow.flow, test/execution-test-data/basicflowyamltest/basic_flow.flow, test/execution-test-data/embeddedflowyamltest/embedded_flow.flow, test/execution-test-data/multipleflowyamltest/basic_flow.flow, test/execution-test-data/multipleflowyamltest/basic_flow2.flow
1. Removed name and type for parent flow in flow YAML file to simplify the file format. 
2. Added javadoc for some public classes and interfaces.
=> Address comments in PR#1525.

azkaban-common/src/main/java/azkaban/project/JdbcProjectHandlerSet.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java, azkaban-common/src/main/java/azkaban/project/ProjectLoader.java, azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java, azkaban-db/src/main/sql/create.project_flow_files.sql
1. Created project_flow_files DB table to store versioned flow yaml files.
2. Supported uploading flow files to DB and fetching them.
3. Verified DB operations in unit tests.
=> Flow 2.0 design - Create project_flow_files DB table.

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/HistoryServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ServletUtil.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/VelocityUtil.java
Multiple duplicate getProjectName implementation are consolidated into a util class, which will be used by flow trigger(https://github.com/azkaban/azkaban/issues/1526) UI as well.
=> merge duplicate getProjectName code into a util class

azkaban-common/src/main/java/azkaban/utils/EmailMessage.java, azkaban-common/src/main/java/azkaban/utils/Emailer.java
1. Instead of only retrying for MessagingException, retry for all Exception during connecting to SMTP server and sending messages.
2. Add more logging messages to indicate sending email success or failure.
3. Increase retry count from 3 to 5.
=> Enhance retry logic for sending emails.

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java, azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java, azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java, azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectLoader.java, azkaban-common/src/test/java/azkaban/project/AzkabanProjectLoaderTest.java, azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
=> Address comments in PR# 1544

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/project/FlowTriggerBean.java, azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java, azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java, test/execution-test-data/flowtriggeryamltest/flow_trigger_duplicate_dep_props.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_invalid_cron_expression.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_large_max_wait_min.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_no_max_wait_min.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_no_schedule.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_without_dep_name.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_without_dep_type.flow, test/execution-test-data/flowtriggeryamltest/flow_trigger_zero_max_wait_min.flow
The following validation steps are performed when parsing flow yaml file:
1. if specified max wait min must >= 1, if not, allowed max wait min(10 days) is applied.
2. flow trigger schedule cannot be null
3. flow trigger schedule type must be cron
4. flow trigger schedule value must be a valid cron expression
5. flow trigger schedule section contains type and value only
6. dependency name must be unique at flow trigger level
7. dependency config(type + params) must be unique at flow trigger level.
8. if max wait min >= allowed max wait min, it will be automatically set to allowed one(10 days)
9. dependency name/type are required.
=> validate flow trigger definition when parsing the flow trigger section in flow yaml file

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerInstanceServlet.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowtriggerspage.vm
This PR added flow trigger instance servlet and associated template. 
The page consists of currently running trigger instances and recently finished one.
=> flow trigger instance UI

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm, azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js
its better option to open quartz-scheduler.org links in new tab instead leaving  azkaban page?
=> Open quartz-scheduler.org links in new tab

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowtriggerspage.vm
=> change the button style of showing flow trigger properties in flow trigger instance UI

azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java, azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerInstanceLoaderTest.java
Recently finished trigger instances should be retrieved based on end time.  Corrected SQL statement and added associated unit test.
=> recently finished trigger instances fix

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java, azkaban-solo-server/src/test/java/azkaban/soloserver/AzkabanSingleServerTest.java, azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java
As requested by @HappyRay: https://github.com/azkaban/azkaban/pull/1654#discussion_r169998397.
Refactoring only - no functional changes.
=> Move ExecutorManager props to Constants

azkaban-web-server/src/main/less/base.less, azkaban-web-server/src/main/less/flow.less
Hi @HappyRay @ameyamk @kunkun-tang !
I have reopened MR https://github.com/azkaban/azkaban/pull/1650
before:
after:
=> job filter style fixed

azkaban-web-server/package.json
Otherwise, it seems that the build process will remove this line automatically.
=> Remove an extra empty line at the end of the package.json file

az-core/src/main/java/azkaban/Constants.java, azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java, azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
Users should be able to use a custom job log format such as GMT timestamps
=> #1718 Make log layout customizable

azkaban-common/src/main/java/azkaban/utils/AbstractMailer.java, azkaban-common/src/main/java/azkaban/utils/EmailMessage.java, azkaban-common/src/main/java/azkaban/utils/EmailMessageCreator.java, azkaban-common/src/main/java/azkaban/utils/Emailer.java, azkaban-common/src/main/java/azkaban/utils/JavaxMailSender.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java, azkaban-common/src/test/java/azkaban/executor/mail/DefaultMailCreatorTest.java, azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java, azkaban-common/src/test/java/azkaban/utils/AbstractMailerTest.java, azkaban-common/src/test/java/azkaban/utils/EmailMessageCreatorTest.java, azkaban-common/src/test/java/azkaban/utils/EmailMessageTest.java, azkaban-common/src/test/java/azkaban/utils/EmailerTest.java, azkaban-common/src/test/resources/azkaban/executor/mail/errorEmail2.html
These were previously ignored. Some refactoring was needed to inject dependencies.
- Builds on #1690 which should be merged first (1st commit is the same)
- For the actual scope of this PR, see the 2nd commit only: https://github.com/azkaban/azkaban/pull/1691/commits/2f5014b419353af68a3a5f208dbf9958c03a62cf
=> Implement unit tests for Emailer & EmailMessage

azkaban-exec-server/src/test/java/azkaban/dag/StatusTest.java
Even though we have 100% line coverage, the logical coverage is more
limited. This change improves that.
=> Improve tests for Status

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
Replace them with the logger.error call
=> Remove e.printStackTrace

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
These methods never throw ServletException.
=> Remove incorrect throws from ExecutorServlet

az-core/src/test/java/azkaban/utils/UtilsTest.java
This is the fix the comment in PR https://github.com/azkaban/azkaban/pull/1779
=> Clean up the zip file after the test case.

azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java, azkaban-web-server/src/main/java/azkaban/flowtrigger/DependencyInstanceProcessor.java, azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java, azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java
1. use parameterized logging
2. remove some logging to reduce the noise
=> flow trigger service logging improvement

azkaban-exec-server/src/main/java/azkaban/dag/DagBuilder.java
This is the response from a comment in #1759
=> Check duplicate names in DagBuilder before adding the nodeBuilder

azkaban-web-server/src/web/js/azkaban/view/flow-trigger-list.js
Before endtime was showing current time when trigger instance is running,
after:
=> when trigger is still running, endtime should show "-"

az-core/src/test/java/azkaban/utils/ExecutorServiceUtilsTest.java
Fix #1842
Issue:
azkaban.utils.ExecutorServiceUtilsTest > force_shutdown_after_timeout STANDARD_ERROR
log4j:WARN No appenders could be found for logger (azkaban.utils.ExecutorServiceUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
azkaban.utils.ExecutorServiceUtilsTest > force_shutdown_after_timeout FAILED
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at …
=> Fix flaky test force_shutdown_after_timeout

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/nav.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/notepage.vm
A dismiss button is added to banner when it's showing up. After the dismiss button is clicked, the banner will disappear until the browner restarts.
=> add dismiss button to banner

docs/ajaxApi.rst, docs/index.rst
Migrated the ajax API docs to restructured text format. 
Used the tool pandoc to convert existing html docs to rst format. Had to manually edit some text after conversion.
=> Converted ajax API documentation to restructured text format

az-crypto/build.gradle, az-crypto/scripts/encrypt.sh, az-crypto/src/azkaban/crypto/Crypto.java, az-crypto/src/azkaban/crypto/CryptoV1.java, az-crypto/src/azkaban/crypto/CryptoV1_1.java, az-crypto/src/azkaban/crypto/Decryptions.java, az-crypto/src/azkaban/crypto/EncryptionCLI.java, az-crypto/src/azkaban/crypto/ICrypto.java, az-crypto/src/azkaban/crypto/Version.java, az-crypto/test/azkaban/crypto/DecryptionTest.java, az-crypto/test/azkaban/crypto/EncryptionTest.java, build.gradle, settings.gradle
crypto plugin being moved: https://github.com/azkaban/azkaban-plugins/tree/master/plugins/crypto
=> Move crypto plugin from azkaban-plugins repo to main azkaban repo.

az-reportal/src/main/resources/azkaban/viewer/reportal/reportaleditpage.vm
=> Reformat reportalEditPage.vm file with save plugin

az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsExecutionJar.java
We need to disable this test to unblock release in CI environment.
=> Ignore a flaky test

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/main/less/azkaban-graph.less, azkaban-web-server/src/web/js/azkaban/view/svg-graph.js
With this new UI change, if a job has defined condition, the job block will show up differently with condition tag on top of the job name in the flow graph. The color of the condition block will change with the job status as it is today.
See below graphs for demonstration:
=> Conditional workflow UI - add condition block for jobs

CONTRIBUTING.md
See https://github.com/azkaban/azkaban/issues/1920
=> update save action guide

azkaban-common/src/main/java/azkaban/executor/ActiveExecutors.java, azkaban-common/src/main/java/azkaban/executor/ExecutingManagerUpdaterThread.java, azkaban-common/src/main/java/azkaban/executor/ExecutionFinalizer.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManagerUpdaterStage.java, azkaban-common/src/main/java/azkaban/executor/RunningExecutions.java, azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java, azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdaterThread.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java, azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java
After this it'll be possible to create for example a pure unit test for the RunningExecutionsUpdaterThread alone.
TODO: once reviewed, check once more that save actions have been applied on all changed classes
=> Refactor ExecutorManager

az-reportal/src/main/java/azkaban/jobtype/ReportalPrestoRunner.java
This PR adds 1. variable support to reportal presto jobtype 2. support of presto query with trailing semicolon.
=> Enhancement to reportal presto jobtype 

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
- fix broken refs in javadoc
- remove redundant initial field values & make them final
- apply save actions plugin
=> Clean up FlowRunnerManager

azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java, azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java, azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java, azkaban-common/src/test/java/azkaban/executor/RunningExecutionsUpdaterTest.java
1. Create a unit test for RunningExecutionsUpdater
2. Move update request code to ExecutorApiGateway
- Better scope for RunningExecutionsUpdater & cleaner unit tests
=> Create a unit test for RunningExecutionsUpdater + minor refactoring

azkaban-common/src/main/java/azkaban/executor/ExecutableFlowBase.java
=> Delete unused method ExecutableFlowBase#reEnableDependents

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
Executor will be in shutting down mode when its shutdown API is called. Executor will wait for all the ongoing flows to complete then shut itself down. Web server talks to executor periodically to fetch the status of each flow in its running flow cache. This PR accommodates a grace period between completion of all flows and killing the executor process, in order to allow web server to finalize flow status updating.
=> delaying shutting executor down

tools/README.md
=> Update the create_release tool readme

azkaban-web-server/src/main/less/project.less, azkaban-web-server/src/web/js/azkaban/util/flow-loader.js, azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
=> Minor CSS fixes and JS improvements

azkaban-common/src/main/java/azkaban/executor/ConnectorParams.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
=> Remove unused methods in ExecutorManager.

azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java, azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
follow-up of https://github.com/azkaban/azkaban/pull/2017
=> file count sanity check

azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java, azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java, azkaban-common/src/test/java/azkaban/executor/FetchActiveFlowDaoTest.java
Bug was introduced in #1833.
Fix as discussed in https://github.com/azkaban/azkaban/pull/1833#discussion_r237985252.
Improved the test coverage of this SQL query.
=> Fix bug: queued flows included in active flows

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/nav.vm
This PR adds an azkaban official doc tab to make it more exposable to azkaban users as we have heard from internal users that they didn't know some of the useful azkaban features(like auto-retry on job failure) until they did fair amount of researching.
=> Add doc tab

azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/AzkabanProcess.java, azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/ProcessFailureException.java
Reverting changes made on PR (https://github.com/azkaban/azkaban/pull/2075)  because they are causing jobs to hang.  
Commits to revert:
-Remove unused code (https://github.com/azkaban/azkaban/pull/2075/commits/661351f1f82eaf1d2a63dffc50946ac4113fd49c). This is the commit that's causing the issue. It eliminated code that read from the standard output of a subprocess but did nothing with it. That caused the subprocess’ standard output to not be consumed, so when the pipe was full the process blocked trying to write to standard output.
-Log kill command failures when killing jobs (https://github.com/azkaban/azkaban/pull/2075/commits/734f01b049e75701e97c0b3fe97f16676f00c831)
=> Rollback changes on PR #2075:

docs/conditionalFlow.rst
Modify some link and image name.
=> Modify docs for conditional workflow

docs/getStarted.rst
fix not pretty document format in `Property Overrides` of Getting Started chapter
=> Issue #2135 - fix not pretty document format

azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java, azkaban-common/src/test/java/azkaban/metrics/CommonMetricsTest.java, azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-exec-server/src/test/java/azkaban/execapp/ExecMetricsTest.java
Move flowSetupTimer from CommonMetrics to ExecMetrics
=> Move flowSetupTimer from CommonMetrics to ExecMetrics

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/AzkabanProcess.java, azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/ProcessFailureException.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
Reason for deletion is provided in comments below.
=> Remove unnecessary code

docs/configuration.rst
Improve Configurations document page Property format
=> Improve Configurations document page Property format

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/user/ParseConfigFile.java, azkaban-common/src/main/java/azkaban/user/UserUtils.java, azkaban-common/src/main/java/azkaban/user/XmlUserManager.java, azkaban-common/src/test/java/azkaban/user/XmlUserManagerTest.java, azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java, azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerServiceTest.java, azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java
The logic could be extended to reload any configuration file.
It uses WatchService to detect changes in the files.
=> Auto reload azkaban-users.xml if there is any change in it.

azkaban-common/src/main/java/azkaban/user/UserUtils.java, azkaban-common/src/main/java/azkaban/user/XmlUserManager.java
AUto Reload Config : Fix race condition to make sure WatchService is started before its watcher thread starts.
=> Auto Reload Config : Fix race condition to make sure WatchService is started before its watcher thread starts.

azkaban-common/src/test/java/azkaban/server/session/SessionCacheTest.java
There are Session Time Issue. So, It'll be failed sometime while buliding. 
The issue is generated by short session time. I checked disappearing cache variable of SessionCache variable in SessionfindByIP.
So, I changed sessing time and Thread.sleep time in SessionCacheMiss to pass tests.
=> fixed SessionfindByIp TestCase

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
=> Enable web metrics for new dispatching logic.

azkaban-common/src/main/java/azkaban/user/ParseConfigFile.java, azkaban-common/src/main/java/azkaban/user/UserUtils.java, azkaban-common/src/main/java/azkaban/user/XmlUserManager.java, azkaban-common/src/test/java/azkaban/user/XmlUserManagerTest.java
WatchService : Make sure to wait for 1 second before acting on event to avoid multiple reloads
Use style formatter.
Add copyright info to ParseConfigFile interface
=> WatchService : Make sure to wait for 1 second before acting on event to avoid multiple reloads

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java, azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
This is related to PR #1695
1. Added the same logic to dynamically generating job link URL in ExecutionController.
2. Consolidate the code in ExecutorManger and ExecutionController.
3. Added unit tests to verify the functionality.
=> Enable dynamic job link for ExecutionController.

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
For consistency with existing .vm and .js pages, revert the changes to capitalization for flowid/flowId back to the original in ProjectManagerServelet.java
=> revert flowid capitalization in ProjectManagerServlet.java

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopHiveJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopShell.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSparkJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/IHadoopJob.java, azkaban-common/src/main/java/azkaban/jobExecutor/AbstractProcessJob.java, azkaban-common/src/main/java/azkaban/server/IMBeanRegistrable.java, azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java, azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-exec-server/src/main/java/azkaban/execapp/JMXHttpServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/JMXHttpServlet.java
1. resolve the backward incompatible problem in 3.72.0 release.
2. fix an issue in new introduced interface. The object in Interface will be a static object which should be a new introduced bug in v3.72.0.
=> [BUGFIX] Backward Incompatible to some JobTypes

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectManagerServletTest.java
When a new project version is uploaded existing schedules of renamed/deleted flows must be removed.
=> Delete schedule of renamed/deleted flows on project upload.

azkaban-common/src/main/java/azkaban/utils/AuthenticationUtils.java
Users are unable to access hdfs viewer after 24 hours because of kerberos key expiration. 
`java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; `
When dynamic job link url is generated, it creates a new login using keytab file which interferes with the hdfs viewer Kerberos ticket refresh process. To fix the issue, use the same login user created by previous hdfs login and refresh ticket when it expires.
=> Fix HDFS viewer authentication issue.

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
In the new dispatching logic, executors poll executions from DB and submit.
If a flow execution fails to be submitted, e.g. due to some server outage, the current executor should unset the executor id for that flow so that other executors can still pick it up and re-submit. 
This PR implements exponential backoff retries for flow submission failures. Basically, if a flow fails to be submitted, the executor will retry in 1s, 2s, 4s, 8s ... until a successful submission happens, then it will go back to 1s interval. 
Also, use the `update_time` instead of `submit_time` as the ordering in DB so that new flows will get the chance to be submitted.
Verified the PR change in solo server.
=> AZNewDispatchingLogic - Retry mechanism for flow submission failure.

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java
Some jobtypes require this additional signature.
=> Add support to allow ctor with sigs (java.lang.String,azkaban.utils.Props,azkaban.utils.Props,org.apache.log4j.Logger) in HadoopJavaJobRunnerMain

azkaban-common/src/main/java/azkaban/trigger/builtin/SlaChecker.java
Add additional logging to track why once in a while flow level SLA is not honored.
=> Add additional logging to track SLA violation

azkaban-db/src/main/sql/create.project_permissions.sql
=> Add 'isGroup' column to PK of project_permissions table.

azkaban-common/src/main/java/azkaban/storage/StorageCleaner.java, azkaban-common/src/test/java/azkaban/storage/StorageCleanerTest.java
The name of project files (zips) in HDFS is the hash of the file, this is good to avoid duplication of same files because if a user uploads a new project version that's the same as one uploaded previously it will share the project files with the latter. So, when deleting the project files of older versions, it's necessary to ensure the deleted files are not used by versions that are to be kept.
=> Don't delete (from HDFS) project files of old versions if shared with newer versions.

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
**DESCRIPTION**
Adding Job Name and Submitting user to the job metadata(applicationTags) which is passed on to respective job execution platform(MR/SPARK) and from there it is finally passed on to YARN RM at the time of Job submission.
=> Adding Job Name and Submit user to the job metadata

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopHiveJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/JavaJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/PigProcessJob.java, azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java
+ Reorganize the code to move some duplication
+ Add Ramp Dependency ClassPath
=> [FEATURE] Modify JobType PlugIn to take care of Flow Ramp Feature

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSecureHiveWrapper.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSecurePigWrapper.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/JavaJobRunnerMain.java, azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/AzkabanProcess.java
This is to help with debugging of issues.
=> Add logs around execution of external code in job types.

docs/getStarted.rst
remove typo and improve readability
=> [docs] remove typo and improve readability

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java, azkaban-web-server/src/main/java/cloudflow/daos/SpaceDao.java, azkaban-web-server/src/main/java/cloudflow/daos/SpaceDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/daos/SpaceSuperUserDao.java, azkaban-web-server/src/main/java/cloudflow/daos/SpaceSuperUserDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/models/Space.java, azkaban-web-server/src/main/java/cloudflow/readme.md, azkaban-web-server/src/main/java/cloudflow/services/SpaceService.java, azkaban-web-server/src/main/java/cloudflow/services/SpaceServiceImpl.java, azkaban-web-server/src/main/java/cloudflow/servlets/SpaceServlet.java, azkaban-web-server/src/main/java/cloudflow/tables.sql
Implementation of space-api. I have commented out the authentication part to make testing easier. I can revert that in the next PR.
=> [v1] Implementation of space api

azkaban-web-server/src/main/java/cloudflow/daos/SpaceDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/daos/SpaceSuperUserDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/models/Space.java, azkaban-web-server/src/main/java/cloudflow/services/SpaceService.java, azkaban-web-server/src/main/java/cloudflow/services/SpaceServiceImpl.java, azkaban-web-server/src/main/java/cloudflow/servlets/SpaceServlet.java
- made the naming convention consistent
=> [v1] minor space api updates

azkaban-common/src/test/java/azkaban/user/FileWatcherTest.java, azkaban-common/src/test/java/azkaban/user/XmlUserManagerTest.java
The test along with XmlUserManagerTest were using FileWatcher on same directory causing
intermittent failures.
Each test now creates its own directory to watch.
Includes changes done previously by Yuliy.
=> Fixed the flaky FileWatcherTest.

azkaban-common/src/main/java/azkaban/executor/ExecutableRamp.java, azkaban-common/src/test/java/azkaban/executor/ExecutionRampDaoTest.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRampManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
ADD MORE LOGS + FIX ONE BUG WHICH CAUSE THE CACHED STATUS CANNOT BE SAVED INTO DB
=> [TASK] Adding more logs for ramp feature + fixing a bug on saving ramp status to DB

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-web-server/src/main/java/cloudflow/error/CloudFlowException.java, azkaban-web-server/src/main/java/cloudflow/models/ExecutionBasicResponse.java, azkaban-web-server/src/main/java/cloudflow/readme.md, azkaban-web-server/src/main/java/cloudflow/services/ExecutionService.java, azkaban-web-server/src/main/java/cloudflow/services/ExecutionServiceImpl.java, azkaban-web-server/src/main/java/cloudflow/servlets/ExecutionServlet.java
Includes a number of  whitespace changes for formatting to Azkaban coding style. 
Please ignore them by add `?w=1` to the URL during the PR review.
=> Add endpoint for '/execution'

azkaban-db/src/main/sql/create.projects.sql, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java, azkaban-web-server/src/main/java/cloudflow/daos/ProjectAdminDao.java, azkaban-web-server/src/main/java/cloudflow/daos/ProjectAdminDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/daos/ProjectDao.java, azkaban-web-server/src/main/java/cloudflow/daos/ProjectDaoImpl.java, azkaban-web-server/src/main/java/cloudflow/models/Project.java, azkaban-web-server/src/main/java/cloudflow/services/ProjectService.java, azkaban-web-server/src/main/java/cloudflow/services/ProjectServiceImpl.java, azkaban-web-server/src/main/java/cloudflow/servlets/ProjectServlet.java, azkaban-web-server/src/main/java/cloudflow/tables.sql
This change implements
1. POST /projects
2. GET /projects
3. GET /projects/{id}
Tested following endpoints:
Positive testing:
GET /projects
GET /projects/1
POST /projects
Negative testing:
GET /projects/
GET /projects/abc
GET /projects/{invalid_int}
GET /projects/1/
GET /projects/1/1/
POST /projects with invalid json 
POST /projects with project name already present in same space id.
=> REST endpoints for Project.

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
Executions are not getting cleaned up on some servers. For same version, it is working for few hosts. I am adding more logs to debug this issue.
=> Adding logs to debug why executions directories are not getting cleaned up for some executors

az-reportal/src/main/java/azkaban/reportal/util/Reportal.java, az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java, azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java, azkaban-common/src/main/java/azkaban/project/ProjectLoader.java, azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java, azkaban-common/src/main/java/azkaban/storage/ProjectStorageManager.java, azkaban-common/src/test/java/azkaban/project/AzkabanProjectLoaderTest.java, azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java, azkaban-common/src/test/java/azkaban/storage/DatabaseStorageTest.java, azkaban-common/src/test/java/azkaban/storage/HdfsStorageTest.java, azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java, azkaban-db/src/main/sql/create.project_versions.sql, azkaban-db/src/main/sql/upgrade.3.84.0.to.3.85.0.sql, azkaban-spi/src/main/java/azkaban/spi/ProjectStorageMetadata.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java
A new column is added to project_versions table,
uploader_ip_addr varchar(50)
=> Add IP Address of the project uploader to project_versions.

azkaban-common/src/main/java/azkaban/sla/SlaOption.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm, azkaban-web-server/src/web/js/azkaban/view/schedule-sla.js
When a user sets SLA, there are two options,
1. kill action
2. Email action.
User must select one of these two.
If user selects email action, then there must be atleast one email address provided.
Also, make sure SlaOption is not null before serializing it.
=> Make sure SLA options are set correctly.

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm
These files are going to change for the pipeline level 3. I thought I'll make this formatting-only PR separately first.
Assuming I have the right settings for Save Actions:
=> Apply Save Actions on some files that had not been cleaned

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java, az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsFindApplicationIdFromLog.java
Enhance the logic to scan for MR Jobs to kill to handle multiple job log files.
The core logic is in findApplicationIdFromLog()
The test is testMultipleLogFilesMultipleApplicationIds()
Lot of code style updates due to Save Actions.
=> Enhance the logic to scan for MR Jobs to kill to handle multiple logs

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
Disable FileSystem Cache for HadoopSecurityManager.
=> Revert back changes reverted earlier for PR#2502 and PR#2546

azkaban-common/src/main/java/azkaban/project/JdbcDependencyManager.java
getValidationStatuses() gets a DB connection directly from the connection pool
instead of using DatabaseOperator.query. If a connection is fetched directly then
the method is also responsible for managing the lifecycle of the DB connection.
This change adds lifecycle management logic for Connection, ResultSet and
PreparedStatement objects.
Added a TODO to move to DatabaseOperator.query() since it takes care of the
lifecycle management for all these objects. This fix is time sensitive and
hence change to use query() will be done in a follow-up PR.
Tested the fix and verified no DB connection leak is present in getValidationStatuses().
=> Fix DB connection leak in getValidationStatuses

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java, azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java, azkaban-web-server/src/web/js/azkaban/util/ajax.js, azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js, azkaban-web-server/src/web/js/azkaban/view/schedule-options.js
These are the flowOverride related files
=> Formatting only: apply Save Actions on some files

docs/conditionalFlow.rst
This PR fixes grammatical errors.
=> Fix grammatical errors

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
Before, only the "isLocked" attribute was set again so lock messages were lost.
=> Restore flow lock message after project upload.

azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
It will be used to detect when executors stop polling for new executions.
=> Add metric to measure the executor polling frequency

az-hdfs-viewer/src/main/resources/azkaban/viewer/hdfs/velocity/hdfs-file-js.vm, az-hdfs-viewer/src/main/resources/azkaban/viewer/hdfs/velocity/hdfs-proxy-js.vm, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/WebUtils.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/javascript.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/statsPage.vm
Fix #917 
Escape $ in velocity templates
Switch WebUtils from log4j to slf4j
Audit logging: report OAuth username if known instead of <OAuth> placeholder
=> Fix #917 and other startup issues

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/CredentialProvider.java
This reverts commit 92574058fca4b2da2660dadead96ea2947537610.
=> Revert "Add get/set KeyStore methods in CredentialProvider interface."

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/CredentialProvider.java, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/CredentialProviderWithKeyStore.java
Add a new CredentialProviderWithKeyStore interface which extends CredentialProvider interface with KeyStore specific APIs.
Remove the KeyStore get/set APIs from CredentialProvider interface.
=> Add a new CredentialProviderWithKeyStore interface which extends CredentialProvider

azkaban-db/src/main/sql/create.ramp_dependency.sql, azkaban-db/src/main/sql/create.ramp_exceptional_flow_items.sql, azkaban-db/src/main/sql/create.ramp_exceptional_job_items.sql, azkaban-db/src/main/sql/create.ramp_items.sql, azkaban-db/src/main/sql/upgrade.3.104.0.to.3.105.0.sql, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/CredentialProvider.java, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/CredentialProviderWithKeyStore.java, build.gradle
Updaing dependency jopt-simple to 5.0.3
Add a new CredentialProviderWithKeyStore interface which extends CredentialProvider interface with KeyStore specific APIs.  (#2629)
Expand the length of some fields related to Ramp Feature  (#2630)
=> Merging master into cf-engine-k8s

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/ActiveExecutingFlowsDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionJobDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java, azkaban-common/src/main/java/azkaban/executor/KeyStoreManager.java, azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java, azkaban-common/src/test/java/azkaban/executor/KeyStoreManagerTest.java, azkaban-exec-server/build.gradle, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java
- FlowContainer is the starting point of containerized Execution within Azkaban.
- It can be launched in any container with execution ID as it's input param.
-  It performs most of the functions executed by the ExecutorServer and FlowRunnerManager.
Added logic to maintain KeyStore in-memory for reuse and avoid keeping it on disk inside the container when user code kicks in.
=> Introducing FlowContainer.

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
=> Use CredentialProvider instead of CredentialProviderWithKeyStore unless needed.

azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1ServiceBuilder.java, azkaban-common/src/main/resources/azkaban/container/models/v1Service.yaml, azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1ServiceBuilderTest.java, azkaban-common/src/test/resources/azkaban/container/models/v1ServiceTest.yaml
Added a class which will use the template packaged as a resource to create a Service Kubernetes object
=> Added class for creation of kubernetes service object using template

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/ActiveExecutingFlowsDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionJobDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java, azkaban-common/src/main/java/azkaban/executor/KeyStoreManager.java, azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java, azkaban-common/src/test/java/azkaban/executor/KeyStoreManagerTest.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java
Reverted changes to DAOs as most of the loaders and DAO are injected.
Addressed review comments on earlier PRs -- Thanks Janki!
=> Solidified FlowContainer logic with integration testing.

az-core/src/main/java/azkaban/utils/TimeUtils.java, az-core/src/test/java/azkaban/utils/TimeUtilsTest.java, azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java, azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java, azkaban-common/src/main/java/azkaban/executor/ExecutionAttempt.java, azkaban-common/src/main/java/azkaban/flow/Flow.java, azkaban-db/src/main/sql/upgrade.3.85.0.to.3.86.0.sql, azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
-Add a method to format date-time values using the ISO-8601 format "YYYY-MM-DDThh:mm:ssTZD".
-The refactors should help prevent NullPointerException without changing existing code behavior.
=> Add a date-time utility method and do a few refactors.

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
1. Adding a way to setup volume for nscd which is required on Kubernetes.
2. Adding a way to set environment variables in pod spec builder.
=> Adding nscd volume and environment variable for version set id.

az-core/src/main/java/azkaban/Constants.java, azkaban-exec-server/src/main/java/azkaban/container/ContainerizedFlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/AbstractFlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/execapp/ProjectCacheCleaner.java, azkaban-exec-server/src/main/java/azkaban/execapp/ProjectDirectoryMetadata.java, azkaban-exec-server/src/test/java/azkaban/container/ContainerizedFlowPreparerTest.java, azkaban-exec-server/src/test/java/azkaban/container/FlowContainerTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTestBase.java, azkaban-exec-server/src/test/java/azkaban/execapp/ProjectCacheCleanerTest.java
FlowPreparer fetches the project depdendencies from the StorageManager and puts them in execution directory.
Fixed some minor bugs in FlowContainer.
=> Added FlowPreparer for containerized execution.

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java
Use environment to fetch execution id and version set id for the flow execution.
Some cosmetic changes around member variables.
=> Use environment to fetch execution id and version set id for the flow execution.

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageVersionMetadataResponseDTO.java, azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageVersionMetadata.java, azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManager.java, azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java, azkaban-common/src/main/java/azkaban/imagemgmt/version/VersionInfo.java, azkaban-common/src/main/java/azkaban/imagemgmt/version/VersionSet.java, azkaban-common/src/main/java/azkaban/imagemgmt/version/VersionSetBuilder.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java, azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java, azkaban-common/src/test/java/azkaban/imagemgmt/version/JdbcVersionSetLoaderTest.java, azkaban-common/src/test/java/azkaban/imagemgmt/version/VersionSetBuilderTest.java, azkaban-common/src/test/resources/image_management/all_image_types_new_and_rampup_version.json, azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageVersionMetadataService.java, azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageVersionMetadataServiceImpl.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java, azkaban-web-server/src/main/java/azkaban/webapp/ClusterStatus.java, azkaban-web-server/src/main/java/azkaban/webapp/ContainerizedClusterStatus.java, azkaban-web-server/src/main/java/azkaban/webapp/Status.java, azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatusServlet.java
1. Implementation for showing status information(/status page) for containerization.
2. Included image path in VersionSet and ImageRampupManager APIs.
=> Implementation for showing status information(/status page) for containerization. Included image path in VersionSet and ImageRampupManager APIs.

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
Renamed default secret name and secret mount path as the same secret volume will be used for other secrets too.
=> Renamed default secret name and secret mountpath

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
Flow parameter name to set for it: java.enable.debug
Env variable which will be set based on this flow parameter is: JAVA_ENABLE_DEBUG
=> Adding remote debug env varible for flow container based on flow parameter

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/resources/azkaban/container/models/v1Service.yaml, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java, azkaban-common/src/test/resources/azkaban/container/models/v1ServiceTest.yaml
Includes an update to the prefix used in the service template file
=> Add service label to pod spec for routing container API calls

azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageVersionMetadataResponseDTO.java, azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageVersionMetadataServiceImpl.java
Changes for displaying image path on /status page.
=> Changes for displaying image path on /status page.

az-core/src/main/java/azkaban/Constants.java, azkaban-exec-server/src/main/java/azkaban/common/ExecJettyServerModule.java, azkaban-exec-server/src/main/java/azkaban/common/ServletUtils.java, azkaban-exec-server/src/main/java/azkaban/container/ContainerServlet.java, azkaban-exec-server/src/main/java/azkaban/container/ContainerizedFlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/AbstractFlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java, azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/ProjectCacheCleaner.java, azkaban-exec-server/src/main/java/azkaban/execapp/ProjectDirectoryMetadata.java, azkaban-exec-server/src/test/java/azkaban/container/ContainerizedFlowPreparerTest.java, azkaban-exec-server/src/test/java/azkaban/container/FlowContainerTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTestBase.java, azkaban-exec-server/src/test/java/azkaban/execapp/ProjectCacheCleanerTest.java
ff07949badc8f41bd269bf21b55b1edf859143bd
08b2ee4ed59b0318171da36b3255c33e90965237
5ee63082ea7f64faf2aa2f5af057faf3f32306ce
72b8c2176e881eb6a52ea989e63e518259a52bb9
a5548ed4c8abcbc8cf837364110e07ce9a15c792
=> Flow container cherry-pick from cf-engine-k8s

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java, azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java
Changes for putting image management module behind kill switch and will be enabled when dispatch method is set to CONTAINERIZED.
=> Changes for putting image management module behind kill switch and will be enabled when dispatch method is set to CONTAINERIZED.

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
Adding a flow parameter for dev pod request.
Adding validation whether flow parameter is set by admin or not.
Adding validation whether java.enable.debug and enable.dev.pod is valid boolean parameter.
=> Add environment variable for dev pod request

azkaban-exec-server/src/main/java/azkaban/container/ContainerServlet.java, azkaban-exec-server/src/test/java/azkaban/container/ContainerServletTest.java
Added ping method to Servlet
Refactored code to use Switch instead of if/else
Added tests
Corrected Azkaban checkstyle
=> Add ping to the ContainerServlet

docs/ajaxApi.rst, docs/containerization-design.rst, docs/imageMgmtAPI.rst
Add Image Management APIs to index of documentation for easier access.
Fix the reference to Containerization Design Doc in the Image Management API page.
=> Add Image Management APIs to index of documentation for easier access.

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java, azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java, azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java, azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java, azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java, azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java
This Change is already merged in the cf-engine-k8s branch as part of https://github.com/azkaban/azkaban/pull/2773
, but can be added to the master.
=> Changed start status to READY instead of PREPARING for poll based dispatch

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
Merge Flow and server logs for containerized execution.
Some code cleanup in FlowContainer around EventReporter.
=> Merge Flow and server logs for containerized execution.

az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/AvroFileViewer.java, az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/ParquetFileViewer.java, build.gradle
Most of the code is picked from reference PR #2809.
With contribution from srramach.
=> Use Apache's Parquet-Avro which uses Avro 1.9.2

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
Introducing new flow parameter called dispatch.execution.to.container. If it's value is set to true then execution will be dispatched to CONTAINERIZED method.
=> Adding support for dispatching execution in container through flow parameter

azkaban-common/src/main/java/azkaban/HadoopModule.java
The scheme of the configured Hadoop file system will be used instead.
This is a follow up on #2803.
=> Remove hard-coded HDFS scheme from the Thin Zip cache URI validation.

az-core/src/main/java/azkaban/Constants.java, azkaban-exec-server/src/main/java/azkaban/common/ServerUtils.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java, azkaban-exec-server/src/test/java/azkaban/container/FlowContainerTest.java
Implemented callback mechanism in FlowContainer.
Use log4j instead of slf4j in FlowContainer.
Added ServerUtils class to refactor common code across AzkabanExecutorServer and FlowContainer.
=> Implemented callback mechanism in FlowContainer.

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageVersion.java, azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManager.java, azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java, azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java, azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageVersionServiceImpl.java
[Azkaban containerization CICD] Introduce a TEST state for image version and allow flow override of a test version while executing flow
Note: This TEST version will be registered to specified Azkaban cluster as part of Azkaban containerization CICD (Orca Job) using image management API. Allow this TEST version to be passed as flow parameter override so that acceptance test flows can executed using this TEST version.
=> [Azkaban containerization CICD] Introduce a TEST state for image version and allow flow override of a test version while executing flow.

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/executor/container/watch/AzPodStatusDrivingListener.java, azkaban-common/src/main/java/azkaban/executor/container/watch/KubernetesWatch.java, azkaban-common/src/main/java/azkaban/executor/container/watch/WatchUtils.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java, azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java, azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
Also adds a property for enabling launch of the pod watch:
`azkaban.kubernetes.watch.enabled`.
=> Add guice bindings for pod watch invocation

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/TriggerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/action/KillExecutionAction.java
Enable TriggerManager in containerized executions.
FlowContainer now implements EventListener class to handle FlowRunner events.
=> Enable TriggerManager in containerized executions.

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java, azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java
Refactored Routings to a method.
Added test to verify routing.
=> Add image related routing paths only when containerization is enabled

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerProxyUserCriteria.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java, azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java, azkaban-web-server/src/main/java/azkaban/webapp/ContainerizedClusterStatus.java, azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java, azkaban-web-server/src/test/java/azkaban/webapp/StatusServiceTest.java, azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java, azkaban-web-server/src/test/resources/azkaban/webapp/containerized_cluster_status
=> Add a criteria to dispatch flow by poll instead of containerization based on denylist of user.to.proxy

azkaban-exec-server/src/main/java/azkaban/common/ServerUtils.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
Make VersionSet readable in the logs.
Move the formatting logic to ServerUtils.
=> Make VersionSet readable in the logs.

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
"azkaban.job.cluster.classpaths" and "azkaban.job.cluster.nativelib" are two critical job properties that ensure jobs are executed properly when a cluster router is enabled.
However, jobs can accidentally override these properties, resulting in job failures. For example, some HadoopJava jobs may output every one of its job properties as its output property, including these two.
When a downstream job starts, it gets them as its own job properties (nodes gets output properties from their in-nodes), which may be incorrect.
These two are meant to be generated by the cluster router per job and stay private within a job.
Here we essentially always allow the router to generate "azkaban.job.cluster.classpaths" and "azkaban.job.cluster.nativelib"
=> Stop router-specific admin properties from being overridden by jobs

build.gradle
See this PR for reference on how to swith the repo:
https://github.com/linkedin/datahub-gma/pull/105/files
=> Bintray.com has been sunset. Consume Pegasus artifacts from jfrog.io instead

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
Fix the following bug in the "retry all failed jobs" logic. 
While going over the DAG to prepare failed jobs for a new execution if a node in DISABLED status or an embedded flow in READY status (hasn't been executed yet) is found then the flow execution incorrectly transitions from RUNNING to READY status and no jobs are retried. The execution then remains in READY status until it finishes.
Tested locally using flows written with Flow 1.0 and Flow 2.0. Now the flow execution stays in RUNNING status and jobs that should be retried are correctly marked and rerun.
=> Take into consideration DISABLED and READY node status when retrying all failed jobs.

azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
Tested on holdem 6 web server.
=> Fixed containerization metrics initialization

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
`Failed with 6 inputs with exception e = java.lang.NoSuchMethodException: azkaban.jobtype.HadoopShell.<init>(java.lang.String, azkaban.utils.Props, azkaban.utils.Props, azkaban.utils.Props, org.apache.log4j.Logger)`
It is benign but misleading and is sometimes blamed if job fails elsewhere. I don't think we need that line in the logs if it is fully expected.
Also, minor cosmetic refactoring to avoid nested try{} and to eliminate duplicate catch(){}.
=> Users are needlessly spooked by ominous cryptic line in job logs:

azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java, azkaban-common/src/main/java/azkaban/executor/container/watch/WatchEventLogger.java
This will help setup the logging properties such that events can
logged in a dedicated log file.
=> Add a class for logging of kubernetes watch events

azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
Enabling retryFailures were added as part of PR https://github.com/azkaban/azkaban/pull/2916
However, that covers only the ContainerServlet side of changes. This change makes sure that ContainerizedDispatchManager is also supporting retryFailures.
=> Add support for retryFailures in ContainerizedDispatchManager

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
Tested alternative approach on containerized cluster by adding nscd volume on pod-spec-template.
=> Remove the nscd setup by default from code

azkaban-db/src/main/sql/updgrade.2ab81c191047f14a77adbfe8eda3bcaa56974cfd.sql, azkaban-db/src/main/sql/upgrade.3.85.0.to.3.86.0.sql, azkaban-db/src/main/sql/upgrade.3.90.0.to.4.0.0.sql
Fixing / cleaning up after these PRs:
- https://github.com/azkaban/azkaban/pull/2688/files#r699318660
- https://github.com/azkaban/azkaban/pull/2779/files#r699317153
=> Fix DB upgrades of execution_flows

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
This is for creating a metric to measure the time duration between creating/submitting flow and starting flow.
=> Calculate flow wait duration in containerized executions

docs/ajaxApi.rst
This API was undocumented but I found it by looking through
the code and I'm using it, so I thought we should add docs.
Here is a screenshot of the rendered HTML after running make html:
=> Add API documentation for fetchuserprojects.

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java, azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java, azkaban-common/src/test/java/azkaban/project/AzkabanProjectLoaderTest.java
This ensures that properties have correct version.
=> Set project version in Project object before project properties are  uploaded

azkaban-common/src/main/java/azkaban/alert/Alerter.java, azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java, azkaban-common/src/main/java/azkaban/flow/CommonJobProperties.java, azkaban-common/src/main/java/azkaban/flow/Flow.java, azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java, azkaban-common/src/main/java/azkaban/project/ProjectManager.java, azkaban-common/src/main/java/azkaban/utils/Emailer.java, azkaban-common/src/test/java/azkaban/project/ProjectManagerTest.java, azkaban-common/src/test/java/azkaban/utils/EmailerTest.java
1. User need to add override.emails : abc@companyXYZ.com in the .properties (flow 1.0) or .flow (flow 2.0) files
2. when a job property is overridden, an email notification will be sent to above email address
=> Alert user when job property is overridden in a project

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java, azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
Property defined for this is: azkaban.jobs.java.opts
=> Add an option to add java options to Java process jobs mentioned in commonprivate.properties

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
When the cancel throws an exception, then the flow is not restarted. Even if the flow is not cancelled properly, it is still finalized. Hence restart should happen.
The below PR tries to restart the flow even if the cancel throws an exception.
=> Fixing restart by ContainerCleanupManager

azkaban-common/src/test/java/azkaban/user/XmlUserManagerTest.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobpage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/permissionspage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectlogpage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectmodals.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectnav.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpageheader.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectsidebar.vm, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/propertypage.vm, azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectSideBarViewTest.java
Refactoring UI Pages to reduce the amount of information passed to the front end.
Tested locally on SoloServer.
=> Refactoring UI Pages to reduce Object Load

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/propertypage.vm
There is a typo in the href from #3029. This should fix it.
=> Fixing typo in href

azkaban-common/src/main/java/azkaban/user/UserManager.java, azkaban-common/src/main/java/azkaban/user/XmlUserManager.java
This allows a more efficient validation of user's group membership to be implemented in plugins
=> Change groupName to groupSet in UserManager::validateUserGroupMembership function signature

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java, azkaban-common/src/test/resources/azkaban/executor/container/v1PodTest1.yaml, azkaban-common/src/test/resources/azkaban/executor/container/v1PodTest2.yaml
Also added gobblin jobtype to included list.
=> Add disk resource for flow container pod spec.

.travis.yml, azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java, azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java, azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java, azkaban-common/src/main/java/azkaban/executor/Status.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerizedImpl.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java, azkaban-common/src/test/java/azkaban/executor/ExecutionLogsDaoTest.java, azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java, azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java, azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java
This reverts commit 18706143daeda8cd55aa93138c35df65e209db48.
There is a bug in #3027. This reverts the change, and will open a new PR to remerge after fix.
=> Revert "Log pod details (#3027)"

azkaban-common/src/main/java/azkaban/executor/IFlowRunnerManager.java, azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/TriggerManager.java, azkaban-exec-server/src/main/java/azkaban/execapp/action/KillExecutionAction.java, azkaban-exec-server/src/main/java/azkaban/execapp/action/KillJobAction.java
This PR implements execution SLA checks for jobs in containerized executions.
It also makes some refactoring to the executions SLA feature.
Tested locally in solo server, testing clusters and Kubernes pods. 
Verified that both Flow and Job SLA checks are setup and alert/kill actions are taken upon SLA misses.
Follow up: work on adding tests for the feature overall which do not exist today.
=> Implement execution SLA checks for jobs in containerized executions.

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java, azkaban-common/src/main/java/azkaban/executor/ExecutorApiClient.java, azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java, azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java, azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java, azkaban-common/src/main/java/azkaban/utils/RestfulApiClient.java, azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorApiClientTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewaySystemTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java, azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java, azkaban-common/src/test/java/azkaban/utils/RestfulApiClientTest.java, azkaban-exec-server/src/test/java/azkaban/common/ExecJettyServerModuleTest.java
Using parameterized approach for adding HTTP timeouts.
=> Adding a timeout parameters for all HTTP Clients

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
Cancel flow is currently sending the cancel request to __default_ yarn cluster_. In case **cluster-router** is enabled, it might send the job cancel request to a different yarn cluster, causing the cancel request to fail. _This issue is being seen for Spark Job Type._
With this change, the correct yarn resource configuration file is used to initialize the yarn client.(The yarn resource config path is available in job properties)
=> Use correct yarn resource config file in the cancel job

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerFlowCriteria.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerJobTypeCriteria.java, azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java, azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java, azkaban-common/src/test/resources/flow_filter.txt, azkaban-common/src/test/resources/flow_filter2.txt, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
- If the flow name is in the filter, then the flow runs on bare metal,
- otherwise, the flow runs on container.
=> Implement a flow name based filter. This filter functions as follows.

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
Remove Ignore tag from flowShouldFailWhenConditionalParameterDoesntExist and make it run
=> Remove Ignore tag from flowShouldFailWhenConditionalParameterDoesntExist

azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageVersionDaoImpl.java
**Bug to fix:** 
This is a follow up of #2952
When activating 1 image_version, other previously ACTIVE image_versions (if ant) would be set to a **wrong** 'STABLE' state and their 'modified_on' timestamp is **NOT** updated
**Changes made:**
Modify and correct the SQL execution logic
**Testing done:**
1. Push the built jar to an cluster machine
2. Restart the azkaban-web-server with the new jar
3. Call /imageVersions API to reproduce the image_version activating scenario
=> When activating 1 image_version, correctly set other ACTIVE ones to STABLE state and update their modified_on timestamp

azkaban-common/src/main/java/azkaban/jobcallback/JobCallbackRequestMaker.java
Sometimes, job callbacks fail due to transient network errors. Set MAX_CALLBACK_RETRY_COUNT=3 and CALLBACK_RETRY_INTERVAL=5 seconds for the retry configs.
=> Add retry attempts for job callback

build.gradle
Upgrading spark core dependency to the latest version.
=> Upgraded spark-core version to 2.12:3.3.0

docs/imageMgmtAPI.rst
tested with OmniMarkupPreviewer
=> fix imageMngtAPI.rst format issue

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java, az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/HadoopJobUtilsTest.java
**Why is this needed**: as communicated, the `getApplication()` API should not be used in a potential high QPS scenario. Thus we default to scan log for application ID, and then load tokens and kill the application.
**What's done**: update the feature branching, let `log-scanning + token loading` be the default option.
**Tests done**: tested in containerization pod, the flow and the yarn app both got killed successfully.
=> Yarn App Killing: default to scan log for application ID and read tokens and kill

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java, azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageVersion.java
Allows Stable state images to be run. Images reach a stable state when they have been in active state and a new image is Activated.
=> Allowing stable state images to be run

.travis.yml, azkaban-common/src/main/java/azkaban/executor/container/KubernetesVPARecommender.java, azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java, azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetrics.java, azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java, azkaban-common/src/main/java/azkaban/metrics/DummyContainerizationMetricsImpl.java, azkaban-common/src/test/java/azkaban/executor/container/KubernetesVPARecommenderTest.java
1. Record number of flow executions stopped due to app container OOM killed
2. Record number of vpa recommender get recommendation failure
=> Add OOMKilled metrics and VPARecommenderFail metrics

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java, azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java
**Why need this**: we want to find out the flow executions whose yarn apps needs to be killed.
**What's in this**: creates a method to find EXECUTION_STOPPED executions, and extras a method to find dangling pods of the terminated executions.
**Tests done**: tested in the test web-server instance, the functions works well
=> CleanupManager - find the flow executions whose yarn apps needs to be killed

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java, azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
**Why need this**: we want to find out the yarn applications to be killed for those flow executions need to be killed.
**What's in this**: use a method in `YarnUtils` call getApplciations() API with tags of the set of execution-IDs to find these applications
**Tests done**: tested in the test web-server instance, the functions works well
=> CleanupManager - get to-be-killed yarn applications from execution IDs

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
**Why it's needed**
We still observe that the Yarn KillApplication() call got stuck for ~ 15 minutes before it throws exception, so we need a way to mitigate this by disabling yarn kill feature, to avoid a failed flow stuck for too long and blocks following retry.
Introduce a new "disable" feature flag, when set, will skip doing any Yarn Application Kill;
=> New feature flag to disable Yarn Application Kill

azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java, azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java
Linkedin is migrating to its own mysql libraries and this will allow users to to set the driver.
Still default to the original driver class if not set.
=> Read mysql driver class name from Props, to allow using customizable driver class

azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java, azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm, azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js
To support backExecute Option for user, adding a checkbox in UI page with default by false; 
(Some code refactoring by azkaban Style of saveActionsPlugin)
New UI page please refer to design doc: https://docs.google.com/document/d/1rpgWZfN6aogZRGvPFqlC1QXJyyS9VJnUQX2uLPXC-Lw
=> add backExecuteOnce checkbox in UI

azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
We still observe that the Yarn KillApplication() call got stuck for ~ 15 minutes before it throws exception, so we need a way to mitigate to avoid a failed job stuck for too long and thus breaking the SLA, on Azkaban system side.
Use Future to handle each Yarn KillApplication() call, and add a timeout to each Future usage, so as it will only wait for a short period of time.
=> Use ExecutorService/Future to ensure Yarn KillApplication() call timeout

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
Latency Metrics would show us how busy "Schedule System" is;
Count Gauge would show us the numbers of triggers being looping over and the trends. 
No Alert necessary to attach.
=> add latency and trigger count metrics for scheduling system

azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java, azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java
**Context**: Currently, we limit the size of the flow file to 10 MB, and changing this is possible only through a code change. This PR is to make this property configurable so that we can change the limit in certain clusters. This is needed by ML customers whose flows can be quite huge. Only if we supply the config value, we use that limit. Otherwise, we default to the current limit. ie. No behaviour change if this config is not supplied.
**Testing**: Tested by setting the size to 15MB. I was able to upload the flows of size ~15MB. 
**Additional notes:**
We store the flow object in two places `project_flows`, and `project_flow_files` table as JSON object and as flow file respectively. These two tables have their column type as medium blob and long blob. Because medium blob can store only …
=> Made the flow file size configurable

azkaban-common/src/main/java/azkaban/scheduler/MissedSchedulesManager.java, azkaban-common/src/test/java/azkaban/scheduler/MissedSchedulesManagerTest.java
- add counter for missed schedules
- add counter for missed email notification
=> add miss schedule metrics

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java, az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java, azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java, azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectManagerServletTest.java
- set "true" case for isRootFlow property in FlowLifeCycleEvent;
- pass subFlow info to yarn tag
=> subflow support fixes

az-core/src/main/java/azkaban/Constants.java, azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
Adding Ability to set Service Links In Pod Spec Template allowing for the modification of Kubernetes Behavior, especially ENV variablles.
=> Adding ability to set Service Links in Pod Spec

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java, az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java, az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestAbstractHadoopJavaProcessJob.java, azkaban-common/src/main/java/azkaban/flow/CommonJobProperties.java, azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
- add additional yarn tag in such format: azkaban.subflow.1 = ?, azkaban.subflow.2 = ?, azkaban.subflow.3 = ? and ...
- Add the unit test to ensure the correct generation of tag
Local build pass.
=> Add Yarn tag changes with each subflow name separately

azkaban-common/src/main/java/azkaban/executor/container/VPAFlowCriteria.java
=> Fix warning in VPAFlowCriteria

azkaban-common/src/main/java/azkaban/scheduler/MissedSchedulesManager.java, azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
- Reveal the missed schedule count with back execution feature enabled or not.
- Reveal the count of back execution enabled triggers.
=> split missed schedule metrics with back execution info

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java, azkaban-common/src/main/java/azkaban/storage/DefaultProjectStorageManager.java, azkaban-common/src/main/java/azkaban/storage/ProjectStorageManager.java
=> Extract ProjectStorageManager to an interface to be inherit-friendly

azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
- fix the bug that always show flow.production.marker to false;
=> Persist FlowProduction flag into DB

azkaban-common/src/main/java/azkaban/scheduler/Schedule.java, azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java, azkaban-common/src/main/java/azkaban/trigger/Trigger.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java, azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
Reveal details and add more logs at the server side and project Log side for users to figure out schedules removal reason.
=> Add server log and project logs with schedule removing condition

azkaban-common/src/main/java/azkaban/trigger/Trigger.java, azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java, azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java
This reverts commit 5e144ffd1f693fb3a04dffaac792e65c57e5c92e.
=> Revert "Fix schedule expiration bug (#3307)"
