_includes/docs/2.5/hadoopjava-type.html
_includes/docs/2.5/new-hive-type.html
_includes/docs/2.5/pig-type.html
_includes/docs/2.5/sidebar.html
docs/2.5/index.html

Here's what the documentation for the new Hive jobtype looks like:

Add documentation for new Hive jobtype and hadoop-inject Hadoop configuration injection mechanism

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java

To fix an Issue that leads to complete break down of Azkaban schedule triggering mechanism.  We observed this issue when a scheduled job has SLA dependency on a job which does not exist in flow that was resulting in a null pointer exception.

Catch exceptions in individual triggers

---

azkaban-webserver/src/web/js/azkaban/view/exflow.js

We need to reduce ajax refresh interval for flow status and log update page. Currently we have a 5 sec and 30 sec interval respectively. Such short interval creates a lot of unnecessary jetty connections on webserver and cause delays for real users.

Reducing ajax refresh interval for flow status and log update page #450

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectLogEvent.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectLoaderTest.java
azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java
azkaban-webserver/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

Azkaban already has method cleanOlderProjectVersion in place to hard delete a project version (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java#L1038), which is used by Azkaban to do house keeping when a new project version is uploaded (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/project/ProjectManager.java#L496). I have leveraged this exisitng functionality.

Purge all data for already deleted project #454

---

azkaban-webserver/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

Previously, only flow logs were escaped.

HTML escaping in job logs.

---

azkaban-common/src/main/java/azkaban/database/AzkabanDatabaseSetup.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-sql/src/sql/database.properties

At present, Azkaban neglect update* scripts while automatically creating database when we run Azkaban in Solo Server mode.

Auto upgrade database up to database.properties version and track draining flows

---

azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/JdbcExecutorLoaderTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java

* Fixing single executor to multi-executor transition
* Work around work around for global busy state
* Fixing cold start to refreshExecutors first time we start processing the queue.

Fixing single executor to multi-executor transition and work around work around for global busy state

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/main/java/azkaban/server/session/SessionCache.java
azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerLoader.java
azkaban-common/src/main/java/azkaban/utils/TypedMapWrapper.java
azkaban-common/src/main/java/azkaban/utils/cache/Cache.java
azkaban-common/src/test/java/azkaban/executor/JavaJobRunnerMain.java
azkaban-common/src/test/java/azkaban/jobExecutor/PythonJobTest.java
azkaban-common/src/test/java/azkaban/project/ProjectTest.java
azkaban-common/src/test/java/azkaban/utils/cache/CacheTest.java
build.gradle

* Add gradle-errorprone-plugin to build.gradle and enable for all Java builds.
* Fix compile-time errors raised by error-prone.
* Add @Ignore to PythonJobTests.testPythonJob because it appeared to hang.
Issue: #501

Use error-prone for Java build.

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

Pipelined flow watcher depends on execution ids to be a sorted list.

Fix to use appropriate flow watcher for pipelined execution

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

a number of processed based executor refresh invalidates logic to identify global busy state

number of processed based executor refresh invalidates inferred global state 

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

This change is needed to support rolling upgrade.

Fix to retain flows executing on inactive executors

---

azkaban-soloserver/src/package/bin/azkaban-solo-start.sh

Gets rid of this kind of error:
```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /azkaban-execserver.log (Permission denied)
```

Fix soloserver start script

---

_includes/docs/latest/ajax-api.html

- Easy to check that `action=scheduleFlow` and `action=removeSched` are only handled with `POST`, here: [ScheduleServlet.java#L384-L387](https://github.com/azkaban/azkaban/blob/master/azkaban-webserver/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java#L384-L387)
- Neither of them can be found in [ExecutorServlet](https://github.com/azkaban/azkaban/blob/master/azkaban-execserver/src/main/java/azkaban/execapp/ExecutorServlet.java) – so definitely the URL path should be `/schedule` for both.

Fixed errors in AJAX API documentation of schedule related actions

---

README.md

Just to avoid confusion. The current master is version 3.0.0, so making the README reflect that.

Update README: Azkaban2 -> Azkaban 3

---

azkaban-webserver/src/web/js/azkaban/model/job-log.js

Issue:
There is a hard coded timeout of 10 seconds from the start of the download of execution logs to the end. This is too short for longer logs and for connections that have longer latencies.
The suggested action item to refresh the page won't help either.
"
The log is taking a long time to finish loading. Azkaban has stopped loading them. Please click Refresh to restart the load.
"
Fix:
Removed the limit which is set in the client side Javascript.
Test:
Manually shortened the timeout value to 10 milliseconds to reproduce the behavior. Applied the fix and verified that the log displayed correctly.

Fix #661 : Log download timeout is too short

---

azkaban-execserver/src/package/conf/azkaban.properties
azkaban-webserver/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-webserver/src/main/java/azkaban/webapp/servlet/ExternalAnalyzerUtils.java
azkaban-webserver/src/main/less/flow.less
azkaban-webserver/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-webserver/src/test/java/azkaban/fixture/VelocityTemplateTestUtil.java
azkaban-webserver/src/test/java/azkaban/webapp/servlet/ExecutionFlowViewTest.java
azkaban-webserver/src/test/java/azkaban/webapp/servlet/ExternalAnalyzerUtilsTest.java
azkaban-webserver/src/test/resources/velocity.properties
build.gradle

When configured a button will appear in the execution details page which will query the
the external analyzer with the execution flow url.

Made changes to analyze execution with an external analyzer like Dr. Elephant

---

azkaban-webserver/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This pull request revert the create project permission logic.  If lockdownCreateProjects is true, only admin is able to create project; otherwise, users (including admins) are always able to create project without being checked.

fix create project bug

---

azkaban-common/src/main/java/azkaban/utils/AbstractMailer.java

Fix broken e-mail sending (SLA and SendEmailAction)
- There was an NPE because lately added field `EmailMessage._tls` wasn't set
- This broke SLA alert e-mail sending entirely
Issue: https://github.com/azkaban/azkaban/issues/668

Fix issue #668: SlaAlertAction Error

---

azkaban-webserver/src/main/java/azkaban/webapp/AzkabanWebServer.java

It's not an error, just informative logging.

Fix log level of printing plugin class name

---

README.md

- For people not familiar with gradle (like me), it's nice to tell how project can be cleaned.
- For me the build failed with error like this (and cleaning fixed it):
```
:azkaban-common:linkMainExecutable
duplicate symbol _change_user in:
~/azkaban/azkaban-common/build/objs/mainExecutable/mainC/61ijqvjtfdjwfrkpl4kf313ll/execute-as-user.o
~/azkaban/azkaban-common/build/objs/mainExecutable/mainC/9duz2i01oqevnxg1cn9bywo1k/execute-as-user.o
```

Mention gradle clean in README

---

azkaban-common/src/test/java/azkaban/trigger/JdbcTriggerLoaderTest.java

Was working on this JDBC Test, and found this bug.
Since we always ignored tests by inserting @ignore, no failing message show up. Actually, without this fix, the following individual tests will fail
fixed by this change.

this test missed the type classes, and fixed

---

azkaban-execserver/src/test/java/azkaban/execapp/event/BlockingStatusTest.java

The tests in BlockingStatusTest class often got failed in travis, even though local environment doesn't receive this failure. The team decided to disable these tests at present, in order to be able to merge other pull requests.

disable tests in BlockingStatusTest

---

azkaban-webserver/build.gradle
build.gradle

Yesterday, we faced an issue that build folder (under web-server) doesn't have js files downloaded by bower plugin.
In the previous pull request commit #718 , bowerInstall and **copyJSLibs** are at the same dependency level. As a result, bowerInstall always takes longer time than **copyJSLibs**. JS lib files are often not ready before the copy. In this pull request, we enforce copyJSLibs has to depend on bowerInstall, in order to let bower js libraries are all set before coping them.

fix copyJSLibs must dependon bowerInstall (bowerInstall is not completed before copyJSLibs)

---

azkaban-hadoop-security-plugin/build.gradle
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManagerException.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/SecurityUtils.java
settings.gradle

The current changes consolidates azkaban-plugins/hadoopsecuritymanager-yarn and azkaban-plugins/hadoopsecuritymanager-common into a single submodule azkaban-hadoop-security-plugin in this repo. Following this commit, the Azkaban hadoop security code in the azkaban-plugins will be deprecated but will remain as is. However, future deployments of Azkaban will use this module as opposed to the one in azkaban-plugins.
Motivation: Moving the plugin code into the main repo helps in consolidation. The azkaban-plugins repo is not maintained well. It currently uses hardcoded and uploaded dependencies in the repo which is not a good model for managing artifacts. The new module works with gradle and pulls dependencies using ivys. This allows easier management of the hadoop security code and also …

Moving Azkaban Hadoop Security code from azkaban-plugins to this repo

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm
azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js

Closing #732 for duplicates.
Unix Cron use 0-6 as Sun-Sat, but Quartz use 1-7. Due to later.js only supporting Unix Cron, we have to make this transition.
This change transform 1-7 to 0-6 in Cron's weekday field.
Tests are verified in our experimental cluster.

make later.js output compatible with quartz

---

azkaban-web-server/src/main/tl/flowsummary.tl

As #735 explained, the flow summary page does not have enough info for Cron Expression. We made this change to let the page showing either cronExpression or period depending on which type the schedule is belonged to.
Verified locally, and it works.

[Bux Fix]add cron Expression info in flow summary page.

---

azkaban-web-server/src/web/js/azkaban/util/date.js
azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js

I'm working on the Azkaban Javascript Test initiative. By going through other standard front end projects and javascript lesson make ups, I know that 
1) .this part of code should be placed in **util/model**, for ease of test. 
2). schedule-panel.js is a **view** js, and it should only include DOM operations.
3). moving this cron-util code to date.js, since date.js is a util library file in Azkaban. schedulepanel.vm already imports date.js
Tested locally, and it should all work

refactor js code in schedule-panel js

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm

Users complained that original example <0 5,7-10 ? * 4-6> confused people. Then I reset the example to <* * ? * *> to clarify confusion. Now the cronExpression means running every minute from now on.
Tested locally.

reset schedule example to * * ? * * , in order to make users clear

---

_includes/docs/latest/ajax-api.html
_includes/docs/latest/sidebar.html

Found some typos.
Set up your GitHub Pages site locally with Jekyll.

fix typo in documentation

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm

During last deployment, we enabled flexible scheduling function and met a problem: Web browser kept using cached js, and not fetching the latest js files. In this change, we enforced browser to fetch the latest schedule-panel.js
evaluated in our test cluster and it works.

append version date to the end of js import

---

azkaban-common/src/main/java/azkaban/event/Event.java
azkaban-common/src/main/java/azkaban/event/EventData.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-exec-server/build.gradle
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackUtil.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/LocalFlowWatcher.java
azkaban-exec-server/src/main/java/azkaban/execapp/jmx/JmxJobMBeanManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedJobMetric.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

Fix issue #605: Azkaban HTTP callback may skip notification.
- Instead of getting the mutable node status in callbacks, passing the job status - as at the time of firing the event - in additional event data.

Fix issue #605: Azkaban HTTP callback may skip notification

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

Token toString() and getIdentifier() may reveal sensitive information that should not be visible in logs, if the logs are to be publicly visible. Hence, we are removing logging statements that include this information.

Removed logging of toString() and getIdentifier() of tokens in HadoopSecurityManager_H_2_0 (#761)

---

azkaban-web-server/build.gradle

Since our internal build system uses a custom build directory, the distribution created was missing some files. Changing to $buildDir removes such issues.

Bug Fix: Hardcoded build directory causes some missing files in the distribution

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java

Previous execute-as-user committers left a security hole that users could make use of. In user's job conf, users are able to define EXECUTE_AS_USER_OVERRIDE's boolean value to enable or disable execute_as_user feature.
During this change, we canceled user's capability, and removed all related code.
Verified in our Experimental AZ cluster, and no issues were found.

Fix execute as user override issue

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

Welcome comments to this pull request.
One issue was found in our production cluster: Even though one job is actually running, but it shows preparation state in job graph page. It affects our users checking logs. 
I did an investigation on this issue, and found that it should be something wrong with the cache implementation, since database has the right job state info. 
I just disabled cache fetching logic in getExecutableFlow method. Checked all callers of this method, and they all come from web server logics. Then I believe this should be a safe change.
Verified in our experimental cluster, and no issues were found.

disable cache fetch when it is looking for job state.

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/messagedialog.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm
azkaban-web-server/src/web/js/azkaban/test/test.js
azkaban-web-server/src/web/js/azkaban/util/date.js
azkaban-web-server/src/web/js/azkaban/view/message-dialog.js
azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js

In [Quartz Documentation](http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html):
> `Support for specifying both a day-of-week and a day-of-month value is not complete (you must currently use the ‘?’ character in one of these fields).`
Since Quartz doesn't support both DOW and MOW fields filling in * key, we should warn users about this wrong settings. In this pull request, Users will receive warning/error if they fill in wrong cron strings.

Warn Users that DOW and DOM fields can not have * simultaneously 

---

azkaban-common/src/main/java/azkaban/utils/Utils.java
azkaban-common/src/test/java/azkaban/utils/UtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java

Currently The Verifying capability of CronExpression is not sufficient. During this pull request, I further check validity of a cron expression by obtaining the next available time of cron.
Unite Test is added.
Verified through local environment as well.

Fix cron expression validation

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-common/src/test/java/azkaban/jobExecutor/JavaProcessJobTest.java
azkaban-common/src/test/java/azkaban/jobExecutor/ProcessJobTest.java

The execute-as-user feature is already applied for around 1 year. Every production cluster make it to true in configurations. We should disable this conf now, and let it be always true.
execute.as.user=true
I removed the code to read execute-as-user from configuration so that jobs will always be executed by user instead of Azkaban.
Can you review the changes before I test on the clusters?

Remove execute.as.user in conf

---

_includes/docs/latest/azkaban-plugins.html

By default, execute.as.user is set to true.
Update the documentation to reflect the code change.

Update documentation for execute.as.user

---

azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java
azkaban-common/src/main/java/azkaban/executor/ConnectorParams.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/server/AbstractServiceServlet.java
azkaban-common/src/main/java/azkaban/server/AzkabanServer.java
azkaban-common/src/main/java/azkaban/server/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/JMXHttpServlet.java
azkaban-sql/src/sql/create.executors.sql
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

When an executor server is launched, it uses the configured port or falls back to a default port. This behavior has been modified such that when the executor is not configured to a specific port it defaults to any available port that it can find on the machine. The advantage is that the user doesn't need to worry about port collisions when he/she doesn't need a specific port.
  Also, The executor now automatically adds an entry about itself to the DB post launch. Also, it exposes the following REST APIs to allow users to activate / deactivate itself
  example:
  http://localhost:1234/executor?action=activate
  http://localhost:1234/executor?action=deactivate
On a successful start, the executor writes the port to a file called executor.port by default.
Contains small refactors like …

Executor to use any port if not configured. Added REST APIs to activate / deactivate executor

---

_includes/docs/latest/ajax-api.html

Some instances of "--data" are written as "-data". Also there was a
random single quote floating in one of the commands. Removed them so as
not to mislead new users.

Fixed some typos in example curl commands (#823)

---

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectVersion.java

Since we are moving projects dir to a shared dir among multiple deployments, we have to deal with race condition where multiple deployments are trying to modifying the same project file. 
The commit consists of following changes:
1. make rename operation atomic so that it's safer for multiple deployments to perform rename.
2. For simplicity, only active deployment is allowed to perform deletion of projects.

make project directory as shared among multiple deployments

---

build.gradle

The current LI build infrastructure generates version field in a lazy fashion. More specifically, the version value is not immediately available during the root cproject configuration phase. While this works seamlessly in the open source build, it generates incorrect version number in the jar manifest.
Solution was to simply make this configuration lazy using afterEvaluate. Tested with both open source and LinkedIn build. Both manifest and filenames are consistent with the version number.

Lazy evaluation of version field in jar manifest

---

azkaban-common/src/main/java/azkaban/utils/StdOutErrRedirect.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-solo-server/src/main/resources/log4j.properties
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

Created a class under utils that will tie out and err to log4j. This
class does this in the main functions of AzkabanWebServer and
AzkabanExecServer, so that all out going messages will be caught by
log4j.

Redirect System out and err to log4j (#840)

---

azkaban-common/src/main/java/azkaban/executor/ConnectorParams.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java

The acceptance tests need to specify the target executor ID, which has to be fetched from DB directly. This pull request writes a new API to have it.
Verified in localhost.

get self executor status by writing a simple executor API

---

azkaban-common/src/main/java/azkaban/project/ProjectLogEvent.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/main/java/azkaban/utils/PropsUtils.java
azkaban-common/src/test/java/azkaban/utils/PropsUtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/web/js/azkaban/view/project-logs.js

The AZ production users complained that 
> We've had a number of production issues where config properties had been
overridden in the Azkaban UI as a hot fix but then those changes didn't get
reflected in git. Subsequent deployments overrode those changes which
caused the issues.
To resolve this issue, the first step discussed is to highlight the property override change in project log.
Added Unit Test and Evaluated in my lcoalhost environment.

highlight property override change

---

azkaban-common/src/main/java/azkaban/utils/SystemMemoryInfo.java

Logs are being filled with this message without apparent reason.
Removing this will increase readability of logs.

Remove noisy log message about system memory capacity

---

azkaban-common/src/main/java/azkaban/utils/PatternLayoutEscaped.java
azkaban-common/src/test/java/azkaban/utils/PatternLayoutEscapedTest.java

When we use the log4j Kafka appender, it seems that the appender simply does not log the stack trace anywhere. Seeing as the stack trace is a very important piece of information, we create our own PatternLayout class that appends the stack trace to the log message that reported it, so that all the information regarding that error can be found one in place.

Made a Log4j pattern layout that appends stack traces to messages

---

_includes/docs/latest/building-from-source.html

Mention the location of tar files and how they can be un-archived.

Add docs for files generated by ./gradlew distTar

---

azkaban-web-server/src/web/js/azkaban/test/test.js
azkaban-web-server/src/web/js/azkaban/util/date.js

This changes the method modifyStrToUnixCronSyntax in date.js so that the "#" syntax can be used in the day of week option and the correct dates will be displayed under "Next 10 scheduled executions" on the schedule-panel page.

Fixing date.js function issue #845 and #856

---

azkaban-common/src/main/java/azkaban/trigger/builtin/SlaChecker.java
azkaban-common/src/test/java/azkaban/trigger/builtin/SlaCheckerTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Context:
Azkaban Triggers are checked via the SlaChecker class. The logic is failing for certain conditions where user flows would keep running despite SLA expiry. Though the logic seems to be working for most cases, it seems to be quite complicated + confusing with lot of code duplication.
Changes:
The `SlaChecker` class has been rewritten with unit tests to cover all the relevant code paths. This ensures that the Checker works correctly. 
\+ updated gradle wrapper to match LinkedIn internal version

Refactoring Azkaban SLA Trigger check logic

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Kafka message syncing ensures that the messages are in order. However, the problem is that the syncing also slows down the transaction rate of these messages drastically. This affects the service significantly and is a blocking call. Reverting this change which was added to #852

Change Kafka message syncing to false

---

azkaban-common/src/main/java/azkaban/database/AbstractJdbcLoader.java
azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java
azkaban-common/src/main/java/azkaban/metrics/MetricsUtility.java
azkaban-common/src/test/java/azkaban/metrics/CommonMetricsTest.java
azkaban-common/src/test/java/azkaban/metrics/MetricsTestUtility.java
azkaban-web-server/build.gradle
azkaban-web-server/src/main/java/azkaban/webapp/WebMetrics.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/WebMetricsTest.java

This commits create two singletone metrics classes, CommonMetrics and WebMetrics, which are in charge of dealing with collecting and reporting metrics, like user log fetch latency, the number of get rest call in web side. Also added corresponding tests to verify. This commit kicks off the following metrics:
* the rate of Rest Get Call in Webserver
* the rate of Rest Post Call in Webserver
* The rate of DB connection in both web and executor
* user log fetch latency
More metrics could be added easily after the app metrics structure is created.

constructing new app metrics structure to collect and send app metrics.

---

azkaban-common/src/main/java/azkaban/constants/ServerInternals.java
azkaban-common/src/main/java/azkaban/constants/ServerProperties.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java

User can fill in their own alias in property file. It will be used as hostname in getHost(). If not configured we will use canonical hostname as fallback.

Allow users to specify host alias in azkaban property file.

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

We've seen issues where 'azkaban.job.id' cannot be resolved when building job type:
"Failed to build job executor for job TestJobId_CommandCould not find variable substitution for variable(s) [command->azkaban.job.id]"
'azkaban.job.id' is common to all job types. It should be inserted into jobProps before building job types.

Insert azkaban.job.id before building job type

---

azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/JdbcExecutorLoaderTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java

When shutdown api is called, executor will deactivate itself, wait for all the job to finish, then call system.exit(), which triggers the shutdown hook. In shutdown hook, executor clears the database entry and forces a shutdown of all active threads.

Clean up executor's db entry and exit the application when executor's shutdown API is called.

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java

It is difficult to understand the error message of scheduleCronFlow API.
example
```
Flow test_flow cannot be found in project azkaban.project.Project@13846b77
```
In this case, I don't know the Azkaban project name.
I expect the following
```
Flow test_flow cannot be found in project test
```
This pull request is similar to https://github.com/azkaban/azkaban/pull/566

Improve error message of scheduleCronFlow API

---

azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java

Since the datasource using the Apache DBCP library has the following
Properties set:
setValidationQuery("/* ping */ select 1");
setTestOnBorrow(true);
The library will do the validation of the connection every time
a connection is borrowed from the pool.
See
https://arviarya.wordpress.com/2013/02/15/apache-dbcp-connection-pool-revisited/
The DB monitoring thread is not necessary and adds overhead and
complexity.
Testing:
Ran unit tests.
Ran a simple test flow in solo server mode.

Remove the DB monitoring thread

---

azkaban-web-server/package.json

Issue #975 reported a bug that the name of moment-timezone js is not right, and gradle can not fetch it to distribution package.
Tried gradle build, and figured out that the latest moment-timezone js 0.5.13 is not compatible with 0.5.5, since the js file built's name doesn't keep the same.
We used to leverage `^` to specify compatible js libraries (see details in https://docs.npmjs.com/misc/semver). In this change, we disable it to in order to secure repo.
Gradle Build works, and target-version libraries are downloaded. Also, I made a bit evaluation on google chrome, and no problem.

Fixing js libraries version compatibility

---

azkaban-web-server/build.gradle
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm
azkaban-web-server/src/web/js/azkaban/test/test.js

We previously used timezone-2010-to-2020 js file, which wis working. However, its name got changed when moment timezone upgraded to 0.5.13. In this change, we replace the file by the full-time-range timezone js, which will permanently stay and should not be changed in future. Also, we add some moment js tests to guarantee moment js working.

use full moment-timezone js and add test

---

.gitignore

"temp" directory is ignored so that it can be used to store temporary files such as local testing configurations.

Ignore the top level "temp" directory

---

azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/database/AzkabanDataSource.java
azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java

Fix #932
The getParentLogger method was added in the new JDBC API since Java 7.
The old version of DBCP doesn't support it and causes Intellij to give
an error.
The new DBCP library is not backward compatible.
Changed a method to use a new method available in the new library.
From DBCP release history page
https://commons.apache.org/proper/commons-dbcp/changes-report.html
2.0
"This release includes new features as well as bug fixes and enhancements. Version 2.0.x supports JDBC 4.1, so requires Java 7. The Java package name has been changed from 'org.apache.commons.dbcp' to 'org.apache.commons.dbcp2'. Also the Maven groupId is now 'org.apache.commons' and the artifactId is 'commons-dbcp2' These changes are necessary because the API is not strictly binary compatible with the 1.x releases. …

Update DBCP library to 2.1.1

---

azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/test/java/azkaban/trigger/MockTriggerLoader.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
build.gradle

The update flagged three errors.
"installedVersions.remove(versionKey);"
The type of the value doesn't match the actual type defined in the list.
Upon close inspection, it turns out that if the entry were
correctly removed, it would cause a logical error since the
for loop access the list by an index the list should not be modified
within the same loop.
Since this is only a local variable, it is ok not updating it after old project versions are deleted.

Update Gauva,Error Prone. Fix errors

---

build.gradle

It will make checking the test failure details easier especially on travis. I can't find a way to read the full test report on travis.
see http://mrhaki.blogspot.com/2013/05/gradle-goodness-show-more-information.html
Testing:
```
Introduced a test failure intentionally.
Before:
:azkaban-web-server:test
azkaban.webapp.WebMetricsTest > testWebGetCallMeter FAILED
java.lang.AssertionError at WebMetricsTest.java:62
19 tests completed, 1 failed
:azkaban-web-server:test FAILED
```
After:
```
:azkaban-web-server:test
azkaban.webapp.WebMetricsTest > testWebGetCallMeter FAILED
java.lang.AssertionError: failed intentionally
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at azkaban.webapp.WebMetricsTest.testWebGetCallMeter(WebMetricsTest.java:62)
19 tests …
```

Show test failure details in cmdline output

---

azkaban-web-server/build.gradle

The update resolved a build warning in the web server sub-project:
"The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead."
see
http://mrhaki.blogspot.com/2016/11/gradle-goodness-replacing-operator-for.html

Fix Gradle warning: Task.leftShift(Closure) method has been deprecated

---

azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

E.g.
/Users/ruyang/oss/azkaban/azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java:332: warning: [WaitNotInLoop] Because of spurious wakeups, wait(long) must always be called in a loop
wait(2000);
^
(see http://errorprone.info/bugpattern/WaitNotInLoop)
Fix:
Change to Thread.sleep which is not subject to this issue.

Fix build warnings related to spurious wakeups in execapp.JobRunnerTest

---

azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerLoader.java
azkaban-common/src/test/java/azkaban/executor/SelectorTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java
azkaban-common/src/test/java/azkaban/utils/RestfulApiClientTest.java

See http://errorprone.info/bugpattern/ClassCanBeStatic
e.g.
/Users/ruyang/oss/azkaban/azkaban-common/src/test/java/azkaban/utils/RestfulApiClientTest.java:47:
warning: [ClassCanBeStatic] Inner class is non-static but does not
reference enclosing class
protected class MockRestfulApiClient extends RestfulApiClient<String>
{
^
(see
http://errorprone.info/bugpattern/ClassCanBeStatic)
Did you mean 'protected static class
MockRestfulApiClient extends
RestfulApiClient<String> {'?
Fix:
Made these inner classes static inner classes.
Also removed protected from a few static classes introduced.
See http://stackoverflow.com/questions/24289070/why-we-should-not-use-protected-static-in-java
These classes only need package private access.

Fix ClassCanBeStatic warnings in common sub-project

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java

For some jobs, eg hadoop related, 5 sec is not enough for the jobs to
finish their clean up and exit. Increasing the time to 30 sec in code
to temporarily mitigate issue.

Increasing the job cancel time from 5 sec to 30 sec

---

build.gradle

The update resolved a build warning:
"The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead."
see
https://github.com/cinnober/semver-git/releases

Update com.cinnober.gradle.semver-git plugin to 2.2.3

---

azkaban-common/src/main/java/azkaban/executor/selector/ExecutorFilter.java

Fixed copy & paste error (logging inside CpuStatusFilter should use CPUSTATUS_FILTER_NAME, not MINIMUMFREEMEMORY_FILTER_NAME)

ExecutorFilter: fix debug info

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/server/AzkabanServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

This change refactors the initialization of the server instances. The current code in these classes is quite entangled. Breaking this up into multiple commits. This is a prerequisite to the upcoming Guice changes.
- removed duplicate methods from Azkaban*Server classes
- moved some of the references constants to `Constants` class
- config was getting updated during server initialization. Fixed that. The same change is now applied when we create the config object `Props`
- refactored IntelliJ suggested warnings which simplify the code
- extracted methods and created smaller methods to make it easier to navigate and isolate code
Tested on solo server as well as web and executor separately on dev instances.

Refactored AzkabanWebServer and AzkabanExecServer launch code

---

azkaban-exec-server/build.gradle
azkaban-hadoop-security-plugin/build.gradle

Currently Azkaban doesn't ship the hadoop-security-plugin with the executor.
Although this is clean since the executor doesn't depend on the plugin it
doesn't make Azkaban any usable since most use cases of Azkaban requires
hadoop. For folks who aren't using Azkaban for hadoop, this would be sitting
idle.
However, the strong assumption to use this plugin is that Hadoop classes must
be on the classpath. Else those jobs using the plugin will fail.
Tested this on the solo server and this works fine.

Package hadoop-security-plugin with the executor

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java

It's nice to have returned also the cron schedule at /schedule?ajax=loadFlow endpoint.
Example response then:
{
"items": [
{
"cron": "0 */12 */2 ? * *",
"projectname": "project_name",
"period": 0,
"stats": {
"average": 0,
"min": 0,
"max": 0
},
"length": 3600000,
"flowname": "agency_bill_counter_back",
"time": 1493123181725,
"history": false,
"scheduleid": 2
},
{
"cron": null,
"projectname": "ahoj",
"period": 86400000,
"stats": {
"average": 0,
"min": 0,
"max": 0
},
"length": 3600000,
"flowname": "wallet_deductor",
"time": 1483230600000,
"history": false,
"scheduleid": 3
}
]
}

Add cron attribute to to loadFlow endpoint

---

azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java
azkaban-common/src/main/java/azkaban/storage/StorageManager.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectLoaderTest.java
azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java
azkaban-common/src/test/java/azkaban/storage/DatabaseStorageTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

This changes delegates all get calls via the `StorageManager`. By `get` I mean the process of fetching a project file (blob) from storage. By default, this storage is the database. There are some hacks in the code which can be fixed later as we go.
There are some refactors in the executor codebase. This was done to easily fetch the `StorageManager` class via Guice.
The changes have been verified on solo server locally and also on executors separately.

Wiring get calls via StorageManager

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectFileHandler.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java
azkaban-common/src/main/java/azkaban/storage/StorageManager.java
azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java
azkaban-sql/src/sql/create.project_versions.sql

The `project_versions` table currently stores all metadata corresponding to every upload of a project zip. The newly introduced storage layer in azkaban requires the persistence of an additional field in the `project_versions` table `uri`.
```
CREATE TABLE project_versions (
...
uri VARCHAR(512) DEFAULT NULL,
...
);
```
The changes integrate `uri` in the query APIs in `ProjectLoader` and modify the interfaces in a *backward incompatible* manner. The solo server SQL scripts have been updated accordingly and have been tested to work.
Existing installations of Azkaban *will* require a simple DB migration: `uri` field addition to `project_versions`.
This completes the implementation for `LOCAL` and `DATABASE` storage types. By default, the storage will continue to be `DATABASE`. (DB migration …

Storage schema changes and implementation. Working Local Storage.

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/jobExecutor/AbstractJob.java
azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java
azkaban-common/src/main/java/azkaban/jobExecutor/LongArgJob.java
azkaban-common/src/main/java/azkaban/metric/AbstractMetric.java
azkaban-common/src/main/java/azkaban/metric/MetricReportManager.java
azkaban-common/src/main/java/azkaban/project/validator/ValidatorClassLoader.java
azkaban-common/src/main/java/azkaban/scheduler/Schedule.java
azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/user/Permission.java
azkaban-common/src/main/java/azkaban/user/Role.java
azkaban-common/src/main/java/azkaban/user/User.java
azkaban-common/src/main/java/azkaban/utils/CircularBuffer.java
azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/executor/JavaJobRunnerMain.java
azkaban-common/src/test/java/azkaban/jobExecutor/WordCountLocal.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/JMXHttpServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/ServerStatisticsServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/StatsServlet.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/BlockingStatusTest.java
azkaban-web-server/package.json
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

This is to address the build warnings in issue#1025.
I focused on two areas related to build warnings.  
1) NPM
2) Override annotations.
While I was able to fix a licensing issue with NPM, there's still a version dependency issue with eonasdan-bootstrap-datetimepicker.  Instead of passing in a 0.4.x version of  moment-timezone, we are giving it a 0.5.x version which causes the dependency check to fail.  
I got most of the override warnings but didn’t feel comfortable with blindly putting @Override everywhere the warning occurred.  Hence, there are still a remainder of Override warnings.

Cleaning up warnings generated during build process

---

azkaban-common/src/main/java/azkaban/database/AbstractJdbcLoader.java
azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/user/Permission.java

e.g.
azkaban/azkaban-common/src/main/java/azkaban/executor/Status.java:34: warning: [ImmutableEnumChecker] enums should be immutable, and cannot have non-final fields
private int numVal;
^
(see http://errorprone.info/bugpattern/ImmutableEnumChecker)
Did you mean 'private final int numVal;'?

Fix build warning : enums should be immutable

---

azkaban-web-server/src/main/java/azkaban/webapp/WebMetrics.java

An example is the following:
/Users/afaris/work/public/li-afaris_azkaban/azkaban-web-server/src/main/java/azkaban/webapp/WebMetrics.java:37: warning: [ImmutableEnumChecker] enums should only have immutable fields, the declaration of type 'com.codahale.metrics.Meter' is not annotated @Immutable
private final Meter webGetCall;
^
(see http://errorprone.info/bugpattern/ImmutableEnumChecker)

Fix build warning : enums should be immutable.

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/HistoryServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectServlet.java

Did you mean 'PrintWriter out = new PrintWriter(new BufferedWriter(new
OutputStreamWriter(new FileOutputStream(_output), UTF_8)));' or
'PrintWriter out = new PrintWriter(new BufferedWriter(new
OutputStreamWriter(new FileOutputStream(_output),
Charset.defaultCharset())));'?
/Users/afaris/work/public/li-afaris_azkaban/azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java:1809:
warning: [ClassCanBeStatic] Inner class is non-static but does not
reference enclosing class
public class PageSelection {
^
(see
http://errorprone.info/bugpattern/ClassCanBeStatic)

Removing 'ClassCanBeStatic' warnings.  For example:

---

azkaban-common/src/test/java/azkaban/jobExecutor/PythonJobTest.java
azkaban-common/src/test/java/azkaban/jobExecutor/Utils.java

Warning:
azkaban/azkaban-common/src/test/java/azkaban/jobExecutor/Utils.java:30: warning: [DefaultCharset] Implicit use of the platform default charset, which can result in e.g. non-ASCII characters being silently replaced with '?' in many environments
PrintWriter writer = new PrintWriter(new FileWriter(filename));
^
(see http://errorprone.info/bugpattern/DefaultCharset)
Did you mean 'PrintWriter writer = new PrintWriter(Files.newBufferedWriter(Paths.get(filename), UTF_8));' or 'PrintWriter writer = new PrintWriter(Files.newBufferedWriter(Paths.get(filename), Charset.defaultCharset()));'?
Also:
* refactored it to use try with resource.
* refactored the delete method to simplify it and check results.
* removed all intellij warnings
Testing:
All tests passed.

Fix build warning DefaultCharset in test Utils class

---

azkaban-common/src/test/java/azkaban/jobExecutor/AllJobExecutorTests.java

@RunWith(Suite.class)
@SuiteClasses({ JavaProcessJobTest.class, ProcessJobTest.class,
PythonJobTest.class })

Fix unnecessary junit annotations in AllJobExecutorTests

---

azkaban-hadoop-security-plugin/build.gradle

This is required by the internal build system and it needs to be fixed prior to clean up of this code.

Restoring Distribution code for azkaban-hadoop-security-plugin

---

azkaban-common/build.gradle
azkaban-common/src/test/resources/log4j.properties
azkaban-db/src/test/resources/log4j.properties
azkaban-exec-server/build.gradle
azkaban-exec-server/src/test/resources/log4j.properties
azkaban-web-server/build.gradle

This allows loggers that use slf4j to log properly.
Also added log4j.properties files to test resources to log to console
in tests by default.
Symptom:
example warning when running tests:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (azkaban.jobExecutor.JavaProcessJob).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Testing:
Here is the console output from running a test
2017/05/03 08:35:08.586 -0700 ERROR [DatabaseOperatorImpl] query failed
java.sql.SQLException

Add org.slf4j:slf4j-log4j12 run time dependency to select modules

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectFileHandler.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java
azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/main/java/azkaban/storage/LocalStorage.java
azkaban-common/src/main/java/azkaban/storage/StorageManager.java
azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java
azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java
azkaban-db/src/main/sql/create.project_versions.sql
azkaban-db/src/main/sql/upgrade.3.20.0.to.3.22.0.sql
azkaban-spi/src/main/java/azkaban/spi/Storage.java
azkaban-sql/src/sql/upgrade.3.20.0.to.3.21.0.sql
azkaban-sql/src/sql/upgrade.3.20.0.to.3.22.0.sql

Motivation: String is more generic and gives flexibility to the storage implementation to structure their own keys. 
For example, the storage layer may use a JSON string as an identifier. This is not currently a use case, but going forward it would probably be better to not impose an unnecessary restriction on a top level API.
Tested separately on dev clusters.

Changing Storage API key from URI to String

---

azkaban-exec-server/build.gradle
azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecutorServerTest.java
azkaban-exec-server/src/test/resources/test.file

This patch adds a basic instantiation test to AzkabanExecServer with Guice.
This ensures that injection doesn't break. Also the goal is to reduce 
overhead during object construction.

Added a unit test for Exec server instantiation

---

azkaban-exec-server/build.gradle

This library brings in an older version of junit which causes
Intellij to pick this version somehow and caused compilation error
when building using Intellij.

Exclude junit from the json-simple library

---

azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/main/java/azkaban/storage/LocalStorage.java

Changing the file extension to be hardcoded to zip. The reason is because of the way the
temp file is created, the file extension is 'zip1234761982374'. There are a whole bunch
of random characters added at the end which becomes the target file extension which is
unintended. Since we strictly enforce .zip extensions only I have hardcoded the extension.

Fixing cosmetic storage bug

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Only timeout if `azkaban.server.flow.max.running.minutes` is set greater than 0.
As discussed in https://github.com/azkaban/azkaban/pull/955 and requested by @ameyamk.
gh-pages counter-part: https://github.com/azkaban/azkaban/pull/1118

Don't timeout flows by default

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackRequestMaker.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/JobCallbackRequestMakerTest.java

This test used to take ~5s. Now it's ~0.3s.
Remaining slowest test is `azkaban.execapp.JobRunnerTest`: 2.513s.
All enabled tests now run in ~5s \o/

Faster JobCallbackRequestMakerTest

---

azkaban-common/src/main/java/azkaban/event/EventData.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

This gives nicer debug logs because there's no stuff like `"Job null finished with status SUCCEEDED"`.
It's also cleaner to be able to pass the `ExecutableNode` to the constructor instead of having to always manually call `getStatus()` and `getNestedId()`.

EventData to always include nestedId

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java

Reverted running flows cache and two fixes on top of the changes.
Ignored some unit tests for running flows cache change for now.
Kept query method fetchActiveFlowByExecId() for future usage.

Revert running flows cache

---

azkaban-db/src/main/sql/create.execution_flows.sql

This is to accelerate the query speed when fetching active flows by the status.

Create index on status for execution_flows DB table.

---

azkaban-common/src/main/java/azkaban/trigger/Trigger.java

In this patch, I added two method `setTriggerCondition` and `setExpireCondition` to the Trigger Class. The reason behind is that one of our products relying on Azkaban library needs to modify Trigger object by inserting newly constructed ExpireCondition.
All other changes are made by Smart Intellij.

Having setExpireCondition to help products relying on azkaban

---

azkaban-common/src/main/java/azkaban/utils/PropsUtils.java
azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/jobExecutor/AllJobExecutorTests.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/EventCollectorListener.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
azkaban-exec-server/src/test/resources/log4j.properties
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job-pass.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job-retry-fail.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job-retry.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job1.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job10.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job2.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job2d.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job3.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job4.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job5.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job6.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job7.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job8.job
azkaban-test/src/test/resources/azkaban/test/executions/exectest1/job9.job

Make `FlowRunnerTest` & `FlowRunnerTest2` work, and make them run fast.
Good to have the `FlowRunnerTest2` as well because it has useful test cases for the flow pause feature.
Based on https://github.com/azkaban/azkaban/pull/1115, but:
- Now also `FlowRunnerTest2` runs, and it's all in one commit.
- `FlowRunnerTest` is also now simpler because there's no need for additional `waitJobsStarted(..)` calls: `assertStatus()` handles both waiting and assertion.
----
This is the minimal change to just make the tests pass again. Background discussion can be seen at https://github.com/azkaban/azkaban/pull/1105.
1. Fix setting job status in `JobRunner`.
- It was setting status like this: `RUNNING -> KILLED -> FAILED -> KILLED`.
- Now it's only `RUNNING -> KILLED`, as it should.
1. Make the …

Fix killed job status update and FlowRunner tests

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

Issue:
The javadoc of the FlowRunnerTest2 class uses ascii art to describe
the DAG. When intellij auto format runs, it renders the art
incorrectly.
Fix:
Wrapped the parts affected in ```<pre> </pre>``` blocks.

Prevent IDE auto formatting from messing up ascii art in javadoc

---

azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java

Fix concurrency bug in MockExecutorLoader: it shouldn't modify the state of actual flows, so make a clone of the flows, too.
Also log job logs in `MockExecutorLoader` instead of discarding them, so that it's possible to debug failures in tests.
----
The problem was this (originally revealed when `FlowRunnerTest` still used this mock class instead of a Mockito mock):
- MockExecutorLoader kept a handle to the actual ExecutableFlow instance
- MockExecutorLoader.updateExecutableFlow set the job statuses based on the current flow status, which is not synchronized with the job runner threads
- So this wrote an old job status over the newer one in ExecutableNode
Stacktrace for that:
job4: setStatus SUCCEEDED -> QUEUED
at azkaban.executor.ExecutableNode.setStatus(ExecutableNode.java:141)
at …

Fix bug in MockExecutorLoader

---

README.md

* Point to the intellij's guide.
* Users should be able to use import code style features instead.
* Advised against turning on "Remove unused suppress warning
annotation" option in the save actions plugin since it seems to be
unreliable.

Update codestyle setup guide in the README

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java

Issue:
Three test classes in execapp have the same duplicate prepareProject
logic.
Fix:
Consolidated into one method in a shared test utility class.
Testing:
This change only affects the test code.
All tests passed.
With this change, the FlowRunnerTest2 has no intellij warnings left
except warnings about typos.

Consolidate the duplicate code into one prepareProject method

---

azkaban-exec-server/src/test/java/azkaban/execapp/EventCollectorListener.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

(based on https://github.com/azkaban/azkaban/pull/1150)
Simplify tests: usage of EventCollectorListener#checkEventExists
- Using hamcrest matcher `is` to compare arrays, because it gives an informative error message, like:
```
java.lang.AssertionError:
Expected: is [<FLOW_STARTED>, <FLOW_FINISHED>]
but: was [<FLOW_STARTED>]
```
- `EventCollectorListener #writeAllEvents` deleted because not used anywhere.

Simplify tests: usage of EventCollectorListener#checkEventExists

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

azkaban.execapp.FlowRunnerTest2.testPauseFailFinishAll
and
azkaban.execapp.FlowRunnerTest2#testRetryOnFailure
Issue: #1155

Ignore two flaky FlowRunner related tests

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java

For background, see also: https://github.com/azkaban/azkaban/pull/1120.
This gives guarantees especially for unit tests that need to check for statuses in a multi-threaded environment. But also `FlowRunner` thread vs. `JobRunner` threads benefit from this, although I haven't been able to prove that there would be any critical issues there.
The volatile modifier may not be absolutely needed between the updates made by `FlowRunner` thread and `JobRunner` threads, because most of the time it's fine if there is some delay. `FlowRunner` can check again later and eventually see the updates by the `JobRunner`s. But I wouldn't be surprised if there are also real race conditions where flow gets stuck or flow gets eventually saved with some incorrect job statuses. So all in all, it's good to make …

Make ExecutableNode.status volatile

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlowBase.java
azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java

**Let's have https://github.com/azkaban/azkaban/pull/1159 before this, ok?**
Calling `ExecutableFlowBase#isFlowFinished` from the test thread wasn't a good idea.
In rare cases it failed with this exception (see https://github.com/azkaban/azkaban/pull/1157#issuecomment-306055490):
```
azkaban.execapp.FlowRunnerTest2 > testCancel FAILED
java.lang.NullPointerException
at azkaban.executor.ExecutableFlowBase.isFlowFinished(ExecutableFlowBase.java:398)
at azkaban.execapp.FlowRunnerTestBase.lambda$assertThreadShutDown$0(FlowRunnerTestBase.java:32)
at azkaban.execapp.FlowRunnerTestBase$$Lambda$9/1157486615.apply(Unknown Source)
at azkaban.execapp.FlowRunnerTestBase.waitFlowRunner(FlowRunnerTestBase.java:42)
at azkaban.execapp.FlowRunnerTestBase.assertThreadShutDown(FlowRunnerTestBase.java:31)
at …
```

Test stability: FlowRunnerTest2

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

This bug was revealed by `JobRunnerTest#testDelayedExecutionCancelledJob`:
If job was cancelled early, there was no initial "upload" ([JobRunner.java#L590](https://github.com/azkaban/azkaban/blob/c55e88237ebc252eaedca6e2ea32e38cf853fca2/azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java#L590)) for the `ExecutableNode`, just an eventual "update" ([JobRunner.java#L626](https://github.com/azkaban/azkaban/blob/c55e88237ebc252eaedca6e2ea32e38cf853fca2/azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java#L626)).
This bug also kicks in when running against the DB, because there would be an `UPDATE` without a preceding `INSERT`. So nothing would be written into the DB, because the `WHERE` conditions of the `UPDATE` don't match any row.
Test console output **before** the …

Fix JobRunner bug when job is cancelled early

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

I would suggest having https://github.com/azkaban/azkaban/pull/1167 instead of this, but this is of course a smaller change..
Include stack trace in error logging.
Based on this discussion / request by @chengren311: https://github.com/azkaban/azkaban/pull/1148#pullrequestreview-41936280

JobRunner uploadExecutableNode improvement

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

I intended to guicify `TriggerManager` as part of last [PR](https://github.com/azkaban/azkaban/pull/1110/files#diff-f916ab7306f59ff720753937cf9a9ff1L62). I just realized that it was an incomplete Guice (mistake) without changes in AzkabanWebServer code. As a result, this PR made the fix and completely guicify `TriggerManager`.
Unless this PR gets merged, we will keep using outdated `JDBCTriggerLoader` code.

fix Triggermanager Guice bug

---

azkaban-common/src/main/java/azkaban/utils/OsMemoryUtil.java

azkaban/azkaban-common/src/main/java/azkaban/utils/OsMemoryUtil.java:27:
warning: [MutableConstantField] Constant field declarations should use
the immutable type (such as ImmutableList) instead of the general
collection interface type (such as List)
private static final Set<String> MEM_KEYS = ImmutableSet
^
(see http://errorprone.info/bugpattern/MutableConstantField)

Fix MutableConstantField ErrorProne warning

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlowPriorityComparator.java

http://errorprone.info/bugpattern/BadComparable
https://docs.oracle.com/javase/7/docs/api/java/lang/Long.html
Can anybody think of any negative side-effects of this change?

Fixing BadComparable warning in azkaban-common

---

azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java
azkaban-web-server/src/restli/java/azkaban/restli/UserManagerResource.java

Fixing error reported in LIHADOOP-26732.
sessionId shouldn't be logged anywhere. Looked through related files and couldn't find any other occurrences.
@HappyRay @ameyamk does this look sufficient?

Removing sessionId from logger statements

---

azkaban-common/src/main/java/azkaban/utils/OsMemoryUtil.java

This is the last warning including style check for this file I can find.
Reformatting doesn't seem to correct this problem automatically.

Fix line length style check violation in OsMemoryUtil

---

azkaban-common/build.gradle
azkaban-web-server/build.gradle

We will standardize on assertj library, which has a few advantages.
see
http://randomthoughtsonjavaprogramming.blogspot.com/2017/03/assertj-vs-hamcrest.html
This will speed up the Travis build process a bit.

Remove hamcrest assertion library

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java

MysqlDataSource used to be a singleton class. However, we are trying to apply guicification to it. As one step of completing gucification to this class, we do a refactor. The reason we can not entirely gucify today:
* The class depends on Props, which is in `azkaban-common` module. `Azkaban-db` can not call `Props` today.

refactor MysqlDataSource

---

azkaban-common/build.gradle
azkaban-db/build.gradle
build.gradle

This is to promote consistency.

Declare mockito and assertj as dependencies for all java subprojects

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

When a flow starts to run, it sets the update_time of the flow as the current time in active_executing_flows table. However, this update_time is not used (notice that it is different from the update_time in execution_flows table). As part of deprecating active_executing_flows table, this updateFlowReference logic needs to be removed. To keep backward compatibility with old executors, we have to deprecate the table gradually. Make sure this updating table change on executor is released first, then in the next release I will push another change on web server of inserting into and removing this table as part of cleaning updaterThread.

Remove UpdateActiveFlowReference

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java

Also fixed a logger error which logs only the exception message
instead of the complete call stack.
Warnings fixed:
from gradle:
Note: /Users/ruyang/oss/azkaban/azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
compiler:
Warning:(294, 17) java: propagate(java.lang.Throwable) in com.google.common.base.Throwables has been deprecated
Warning:(306, 17) java: propagate(java.lang.Throwable) in com.google.common.base.Throwables has been deprecated

Fix compiler warnings in AzkabanExecutorServer

---

azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java
azkaban-common/src/test/java/azkaban/trigger/BasicTimeCheckerTest.java

Issue:
The test sleeps for 20 seconds and the comments are wrong.
When debugging the test, the test would fail since it is time sensitive.
Fix:
Switch to use Jodatime utility to get the current time and manipulate
the time in the test.
It's better to use the java time api and use a Guice injected wrapper
class to manipulate time.
However given that BasicTimeChecker is scheduled to be deprecated
soon. It's not worth investing in it now.

Fix slow BasicTimeCheckerTest

---

.travis.yml

see
https://docs.travis-ci.com/user/languages/java/#Projects-Using-Gradle
Testing:
Verified that the caching is working:
First run
https://travis-ci.org/azkaban/azkaban/builds/241850300
116.08s$ ./gradlew clean build
Downloading https://services.gradle.org/distributions/gradle-3.5-all.zip
.....................................................................................................................................
Second run:
https://travis-ci.org/azkaban/azkaban/builds/241850739
66.50s$ ./gradlew clean build
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution with configuration on demand is an incubating feature.
Using the 'clean' task in combination with parallel execution may lead to unexpected runtime behavior.
:azkaban-hadoop-security-plugin:clean …

Enable gradle caching in Travis builds

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java

- Additional stability even if test runner is slow (like supposedly on Travis sometimes)
- This doesn't make the tests any slower than before, as long as they pass
----
Why would this help? Even locally the FlowRunner tests started failing when I put 10 instead of 100 max tries (10 ms wait per try). 1000 should make it pretty robust :)
For background, see:
- PR https://github.com/azkaban/azkaban/pull/1179#issuecomment-307183316
- https://travis-ci.org/azkaban/azkaban/builds/240580566?utm_source=github_status&utm_medium=notification
- PR https://github.com/azkaban/azkaban/pull/1201#issuecomment-307639293
- PR https://github.com/azkaban/azkaban/pull/1186

Test stability: longer max wait

---

azkaban-db/src/main/java/azkaban/db/AzkabanDataSource.java
azkaban-db/src/main/java/azkaban/db/H2FileDataSource.java
azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java
azkaban-db/src/test/java/azkaban/db/AzDBTestUtility.java

When I was refactoring [this code](https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java#L682), I noticed that we need to consider allowsOnDuplicateKey since the original Azkaban database modules has this. So I'm completing now.

Have method to check allowsOnDuplicateKey

---

azkaban-common/src/main/java/azkaban/metric/MetricReportManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/TriggerManager.java

http://errorprone.info/bugpattern/FutureReturnValueIgnored
Errorprone suggests "@SuppressWarnings("unused")" when compiling, but this did not appear to remove the warning.
Following the recommendation suggested in the link above and adding "@SuppressWarnings("FutureReturnValueIgnored")" seemed to do the trick.

Suppressing FutureReturnValueIgnored warnings

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java

Despite authorizing prior to any HDFS call, the HDFS storage code does not seem to work without an existing Kerberos session. The problem is that the `FileSystem.get()` API needs to be called after a successful UGI login. Currently that is not the case. The Hadoop code caches the logged in user at the time of creating the File System object and this is not reflected in the stack traces making it difficult to debug.
Fix: ensure UGI auth prior to creation of file system object.

HDFS instance needs to be created post UGI login

---

azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java

This will shave > 5 seconds of test time.
The triggermanager code is scheduled to be removed soon. It's not
worth fixing these tests. We will avoid changing these classes and if
we have to, the person has to run these tests manually.

Ignore the slow TriggerManager tests

---

azkaban-common/src/main/java/azkaban/executor/ExecutorInfo.java

http://errorprone.info/bugpattern/EqualsHashCode
Used IntelliJ's automatic equals/hashcode creator.
The equals method is only used within a test case.

Fixing EqualsHashCode warning in ExecutorInfo

---

build.gradle

Testing:
Reduced the test time from 15 seconds to 12 seconds on my mac.
./gradlew azkaban-common:cleanTest azkaban-common:test
See
http://mrhaki.blogspot.com/2010/11/gradle-goodness-running-tests-in.html
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html
https://docs.gradle.org/current/userguide/java_plugin.html#sec:test_execution

Enable parallel tests

---

build.gradle

See
https://docs.gradle.org/3.3/userguide/project_reports_plugin.html
http://mrhaki.blogspot.com/2014/08/gradle-goodness-getting-more-dependency.html
Also, add the build-dashboard plugin
see https://docs.gradle.org/current/userguide/buildDashboard_plugin.html
testing:
ruyang-mn1:azkaban ruyang$ ./gradlew azkaban-exe-server:dependencyReport
Parallel execution with configuration on demand is an incubating feature.
:azkaban-exec-server:dependencyReport
See the report at: file:///Users/ruyang/oss/azkaban/azkaban-exec-server/build/reports/project/dependencies.txt
BUILD SUCCESSFUL

Add the project-report gradle plugin

---

azkaban-common/src/main/java/azkaban/ServiceProvider.java

http://errorprone.info/bugpattern/ImmutableEnumChecker
Collaborated with @suvodeep-pyne 
Suppressed the warning instead of guicing the class as done in other PRs.
We want to keep this class an enum because it is the most secure way to build a singleton in Java. We can't guice this class because this class allows hacky usage of guice in places that haven't been fully guiced yet.
This class will be deprecated in the future as the code is transitioned to full guice.

Suppressing ImmutableEnumChecker warning

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java

Applied SaveAction, which was disabled for prior PR. No other changes made.
Also removed unnecessary comment. All occurrences of SERVICE_PROVIDER are hacky, so its existence is a reminder of additional refactoring by itself.
Made this commit because I'll be working on LoginAbstractAzkabanServlet for LIHADOOP-28574 and don't want the changes to overlap.

Small formatting tweak to LoginAbstractAzkabanServlet

---

azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java

An issue was introduced in https://github.com/azkaban/azkaban/pull/1110 that causing schedule end time is set to a past date whenever SLA changes are made.
It's caused by incompatibility of new code https://github.com/azkaban/azkaban/pull/1110 with old schedule metadata. SLA change triggers reloading updated schedules into memory. But instead of using a default schedule end time, which we set to some day in year 2050, it always mistakenly uses a past date as the expiring time of the schedule. 
This fixes the issue by setting appropriate end time of the schedule.

fix end time schedule 

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/LoginAbstractAzkabanServletTest.java

Related to #990 
Users currently can login by passing their credentials through the query string in the URI in this method:
`curl -X POST http://localhost:8081/?action=login\&username=azkaban\&password=azkaban`
This leads to sensitive information being logged in access logs and overall isn't a secure method of logging in.
This PR fails these attempts and returns an appropriate warning to users. It also stops the query string from being logged when these requests are made.
This PR includes testing to replicate this user behavior for future regression testing.

Disallowing users from logging in via URI QueryString

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/utils/WebUtils.java
azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-web-server/src/main/less/azkaban-graph.less
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/less/variables.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/historypage.vm
azkaban-web-server/src/web/js/azkaban/util/job-status.js
azkaban-web-server/src/web/js/azkaban/view/exflow.js
azkaban-web-server/src/web/js/azkaban/view/time-graph.js

Implements https://github.com/azkaban/azkaban/issues/1122: _Azkaban to have KILLING status transition_.
- New status transition after `kill()` is called: `.. -> KILLING -> KILLED`.
- Don't set the status to `KILLED` before all job threads have exited.
Execution graph:
Execution Job List:
History:
----
After this change, I would like to rename these private booleans:
- `JobRunner: killed -> cancelRequested`
- `FlowRunner: flowKilled -> killRequested`
Otherwise it's quite easy to assume that those `killed` booleans mean already having `KILLED` status, when it can also be `KILLING`.

New status: KILLING

---

azkaban-common/src/test/java/azkaban/jobExecutor/ProcessJobTest.java

http://errorprone.info/bugpattern/ClassCanBeStatic
warning: [ClassCanBeStatic] Inner class is non-static but does not reference enclosing class
class SleepBeforeRunJob extends ProcessJob implements Runnable {
^
(see http://errorprone.info/bugpattern/ClassCanBeStatic)
Did you mean 'static class SleepBeforeRunJob extends ProcessJob implements Runnable {'?

Fixing ClassCanBeStatic warning in ProcessJobTest

---

azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectHandlerSet.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerImpl.java
azkaban-common/src/test/java/azkaban/ServiceProviderTest.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java
azkaban-common/src/test/java/azkaban/project/MockProjectLoader.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperator.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperatorImpl.java
azkaban-db/src/test/java/azkaban/db/AzDBTestUtility.java

This change is aimed at re-constructing JDBC project loader class to
allow db retry feature to be leveraged. In order to make this happen,
there are a few changes made in this patch:
* remove some never-use abstract method in ProjectLoader interface.
* guicify JdbcProjectImpl and make it as the only implementation to
Projectloader.
* Seprate All Project related JDBC handler classes to a ourside static class.
* Adding getDataSource method in azkaban-db interface 
Evaluated the basic uses of ProjectLoader.

refactor JDBC Project class to leverage new azkaban-db

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/test/java/azkaban/project/AzkabanProjectLoaderTest.java

The current upload logic is sitting in the ProjectManager class. This change delegates the upload and download to AzkabanProjectLoader class. This makes the upload/download code much easier to manage and test. Added a unit test for upload and download methods.
This change also helps pave the way for subsequent refactors which are required to clean up and simplify the project loading and validating logic.
Note: There is no logic change in this code.

Creating AzkabanProjectLoader class to handle project upload/download

---

azkaban-common/src/main/java/azkaban/user/XmlUserManager.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/login.vm

Some Azkaban instance needs 2FA authentications. In that case, the password field in login UI doesn't only include user's password. We modified the UI and make password placeholder configurable, such that Azkaban admins will be able to define.
Tested on localhost.

make passwordPlaceHolder and password error message configurable

---

azkaban-common/src/main/java/azkaban/user/Permission.java
azkaban-common/src/main/java/azkaban/user/UserUtils.java
azkaban-common/src/test/java/azkaban/user/PermissionTest.java
azkaban-common/src/test/java/azkaban/user/UserUtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/PageUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpageheader.vm
azkaban-web-server/src/test/java/azkaban/fixture/VelocityTemplateTestUtil.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutionFlowViewTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/PageUtilsTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectPageHeaderTest.java
test/src/test/resources/azkaban/test/azkaban-users.xml

Detailed changes:
1. Upload button is enabled only for admin users and users with UPLOADPROJECTS
permission when the property 'lockdown.upload.projects' is set to true.
2. New permission UPLOADPROJECTS is created
3. Handle the case for ajax upload as well
4. Tests included
Verified all changes against the azkaban-solo-server.

Disable the project upload functionality, if user doesn't have the right permissions.

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

This bug was found in local solo server built by July 19th's master code. Our integration test tried to add trigger, which run every minutes. The strange observation is that this trigger never run. We debugged the code and found that the [TriggerScannerThread](https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java#L67) was launched twice, and newly added triggers were put into the should-not-exist thread and never run. I noticed that TriggerManager did not bind to Singleton in Guice Conf. I made this change, and the thread was not launched twice. The bug disappeared.

fix guice initialize TriggerManager twice bug

---

azkaban-common/src/main/java/azkaban/project/ProjectManager.java

This commit is intended to prevent the bug happened on #1283. I simply annotate ProjectManager singleton in this patth. When developers guicify other classes relying on ProjectManager in future, they will not need to worry about generating bugs.
Integration test passed.  Will have follow-up amendment to make Azkaban Guice safe!

Making singleton Guice to ProjectManager

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/executor/AlerterHolder.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/storage/DatabaseStorage.java
azkaban-common/src/main/java/azkaban/storage/HdfsAuth.java
azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/main/java/azkaban/storage/LocalStorage.java
azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerImpl.java
azkaban-common/src/test/java/azkaban/ServiceProviderTest.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperatorImpl.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

This patch refactors the Guice uses, and mainly move all singleton binding to respective classes with singleton annotations. The corresponding tests are added as well. a bit more context is at #1285 .

move singleton to classes's annotations

---

azkaban-common/src/main/java/azkaban/executor/Status.java

When running one of the integration tests - kill the flow right after it executes, we are seeing below error:
Caused by: java.sql.SQLException: Data truncation: Out of range value for column 'status' at row 1 Query: UPDATE execution_flows SET status=?,update_time=?,start_time=?,end_time=?,enc_type=?,flow_data=? WHERE exec_id=? Parameters: [130, 1500497708092, 1500497 ......
Status is TINYINT and the max value is 127, so trying to store value 130 in DB throws an exception. Changing CANCELLED from 130 to 125 fixes the problem.
This change is backward compatible since we never run into the situation where CANCELLED status was stored in DB in the past. This value has never been persisted. With the new change of KILLING status, it could happen that we need to store this CANCELLED status in DB …

Fix value out of range exception when storing CANCELLED status in DB.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Setting the gid bit on the group for a directory causes all items created within that directory to inherit the group of the directory. So all items users create in their /execution/<exec_id> directory will automatically be a part of the azkaban group. This allows the azkaban cleanup thread to properly remove user-generated files/directories.
The gid bit is system-specific, so there is [no java standard library api](https://stackoverflow.com/questions/5045869/change-sticky-bit-with-java) for setting it. The solution I proposed spawns a subprocess that performs the chmod command. I don't think this is very clean, but I haven't been able to find a better way. Anybody have any ideas?
Another option would be to build this executionDirectory as part of our build process, but that isn't how we …

Running chmod g+s on executions directory to enable proper execution cleanup

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

The execution directory can bloat to be relatively large, which could lead to problems if the executor is shutdown and stale executions remain sitting on the executor occupying disk space.
This change deletes the execution directory on executor shutdown. The directory itself is created on executor initialization, so the directory isn't necessary to reset the executor later.
Note that the execution directory will not be deleted until AFTER all flows are done if the executor is brought down via shutdown() - so it will not delete partially-written logs before they are uploaded to the database.

Delete executions directory on executor shutdown to reclaim disk space

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

We observed the long deletion transaction in our production Azkaban cluster. In mysql, if delete transaction is large (The data going to be deleted is too big), it occupies too much undo space (buffer), which affect other transactions and other databases. So we change every day one time's deletion to every hour.

delete rentention logs every hour

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/utils/WebUtils.java
azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-web-server/src/main/less/azkaban-graph.less
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/less/variables.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/historypage.vm
azkaban-web-server/src/web/js/azkaban/util/job-status.js
azkaban-web-server/src/web/js/azkaban/view/exflow.js
azkaban-web-server/src/web/js/azkaban/view/time-graph.js

This reverts commit d1b836a.
Conflicts:
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
From @jamiesjc: When we kill the flow immediately after it starts in our integration test, it couldn't be killed due to some race condition. Users will see on the execution page that the job is in KILLING status but it actually never gets killed. And users cannot click kill button again during the KILLING period.
At the time when we kill, the process might not have started yet or the jobRunner has not yet been added to the activeJobRunners.
You can check more details in the PR description: #1289. We are still working on the fix.

Revert "New status: KILLING (#1172)"

---

azkaban-common/src/main/java/azkaban/server/session/Session.java
azkaban-common/src/main/java/azkaban/user/User.java

This reverts commit 9d079ec665bc7b434fbfa46e8140d5e0949a7c86.
This change removes an API (getSessionData) relied upon by the hdfs viewer.

Revert "remove unused member variables in Session and User class (#1294)"

---

azkaban-common/src/main/java/azkaban/user/XmlUserManager.java

This commit reverts the XMLUserManager code since it is found that we don't need to customize XML error login message, since only headless users access from `XMLUserManager`. Standard users go through `LDAPUserManager`, which we already added this feature.
The original PR is at: #1277

revert XMLUserManager error message customization

---

gradle.properties

See
https://docs.gradle.org/3.5/userguide/build_cache.html
A clean build took 22 seconds vs > 1 minute before this change.
output:
BUILD SUCCESSFUL
Total time: 22.587 secs
120 tasks in build, out of which 81 (68%) were executed
13  (11%) up-to-date
13  (11%) no-source
13  (11%) loaded from cache
6   (5%) cache miss
75  (63%) not cacheable

Enable gradle build cache for faster build

---

azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java

Today, given a schedule, the default option for concurrent setting is `ignore`, that is, allowing concurrent executions whatever schedule triggers. This could be regarded as a bug in current AZ. The reason is that, In UI, the default schedule option is "skip" while API's default option is "ignore". The inconsistency between API and UI should be resolved.
This commit fixes the option to `skip`. When next schedule triggers, as long as the last execution hasn't finished, it won't trigger the next execution. As a consequence, this commit changes API's default option to "skip" and UI's default behavior is not affected. Tested on our staging cluster, and working.

Change API's concurrent default option to skip

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

previously if a job retries, log looks like this:
Starting job 1 attempt 1 at 1502324648910
it makes people misinterpret this as the 1st attempt of running the job, this PR changes the message: 
Starting job 1 retry 1 at 1502324648910

make job retry log more clear

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java

Previously, TriggerManager won't persist updated schedule when schedule gets updated(e.x. add new SLA rule to a schedule). It gets persisted only when schedule gets triggered. So if we add a  SLA rule to a schedule or do a reschedule, and restart the web server after it, these updates will be lost.

TriggerManager needs to persist updated trigger when updating trigger

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

This is a small change to standardize on using System.currentTimeMillis() within the ExecutorManager class.

Standardize on "System.currentTimeMillis()" within the ExecutorManager class

---

azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/test/java/azkaban/storage/HdfsStorageTest.java

Implemented delete API based on a key. The key is the relative path of the project file and is stored as `resourceId` in the DB.

HdfsStorage delete method implementation

---

azkaban-common/src/main/c/execute-as-user.c
azkaban-common/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-common/src/main/java/azkaban/utils/ExecuteAsUser.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

Right now, Azkaban leverages the execute-as-user script so that users' jobs are run via a process of the user's creation instead of as the Azkaban process. This is really important because it restricts users from interfering with Azkaban or reading secure information that Azkaban holds.
While this script works well, it has a bug in which it doesn't remove the "azkaban" group from the users list of groups. This is not secure. It did have a side-effect though that should be kept: it allowed users to write to their /execution/<exec_id>/src directory. This is desired because it gives users the ability to cache temporary data on the executor between jobs in a flow.
This PR does two things:
- It fixes the security bug in execute-as-user.c by calling the initgroups() function for the effective …

Fixing known security bug via proper *nix permissioning

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java

Updating PR #1325.
Instead of simply displaying an error message when assignUserDirOwnership fails, now it throws an Exception using the handleError method.
This is better because if the flow fails later due to unexpected permissions for the user then it would be hard to detect that the failure of assignUserDirOwnership is the root cause. Now the flow will fail quickly and be easier to diagnose.

Throwing error in assignUserDirOwnership in ProcessJob

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-web-server/src/main/java/azkaban/webapp/Status.java
azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java

Adding Process ID to status API info. The pid is read from the pid file which is configurable via `azkaban.pid.filename`. By default this value is `currentpid`.
Example:
```
{
"version": "unknown",
"pid": "69041",
...
}
```

Adding pid to /status API

---

azkaban-common/src/main/java/azkaban/storage/LocalStorage.java
azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java

Fixed LocalStorage: Weird characters in filename

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

activeJobRunners maintains all active job runners, so we should remove inactive job runners when job finishes. As a consequence, activeJobRunners will keep queuing up and querying activeJobRunners by job name will return invalid job runner. This PR fixes this issue.

remove job runner from active job runner list when job finishes

---

azkaban-common/src/main/java/azkaban/storage/LocalStorage.java
azkaban-common/src/test/java/azkaban/storage/LocalStorageTest.java

Delete API was missing for `LocalStorage`. Added it. Updated test.

Implemented delete API for local Storage

---

azkaban-web-server/src/web/js/azkaban/view/svg-graph.js

The "centerNode" function calls getTransformToElement(), which was [removed from the SVG spec](https://www.w3.org/TR/SVG2/changes.html#types) and also from browsers such as Chrome and Firefox, so the "Center" context menu button that appears when right-clicking in the graph view doesn't work. Fortunately it doesn't seem to use this call for anything so simply removing the line makes the button work again.
Tested by injecting the modified svg-graph.js as a Greasemonkey script in Firefox 55.0.1, and locally modifying the script in the debugger in Chrome 60.0.3112.90.

Fixed "Center Job/Flow/Graph" button

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/JMXHttpServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatsServlet.java

Tested on localhost:
1. Add in azkaban-users.xml:
`<user username="azktest1" password="azktest1" group="azk1" roles="all-except-admin"/>`
2. Launch solo server with username azktest1. 
3. Verify azktest1 can access /jmx and /stats page.

Open access of /jmx and /stats page to all users.

---

.gitignore

Intellij generates build output in the out directory.
Gradle uses build directory.
When running unit tests or solo server in intellij, build from intellij
is still required.
See
https://youtrack.jetbrains.com/issue/IDEA-175172

git: ignore out directory

---

.travis.yml

It is stated in Gradle docs that gradle daemon should not be run in CI environments.
https://docs.gradle.org/3.3/userguide/gradle_daemon.html#when_should_i_not_use_the_gradle_daemon

update travis by disable daemon

---

azkaban-common/src/test/java/azkaban/test/Utils.java
azkaban-db/build.gradle
azkaban-db/src/main/java/azkaban/db/DatabaseSetup.java

> azkaban.executor.ExecutionFlowDaoTest > testUpdateExecutableFlow FAILED
azkaban.executor.ExecutorManagerException: Error creating execution.
at azkaban.executor.ExecutionFlowDao.uploadExecutableFlow(ExecutionFlowDao.java:74)
at azkaban.executor.ExecutionFlowDaoTest.testUpdateExecutableFlow(ExecutionFlowDaoTest.java:87)
Caused by:
java.sql.SQLException: Table "EXECUTION_FLOWS" not found; SQL statement:
INSERT INTO execution_flows (project_id, flow_id, version, status, submit_time, submit_user, update_time) values (?,?,?,?,?,?,?) [42102-193] Query: INSERT INTO execution_flows (project_id, flow_id, version, status, submit_time, submit_user, update_time) values (?,?,?,?,?,?,?) Parameters: [1, derived-member-data, -1, 20, 1503088054663, null, 1503088054663]
at …

fix flaky test by creating new DatabaseSetup class

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/StatusTestUtils.java

- Remove some redundant sleeping, replace with more eager waiting
- Add sleep to another place to increase stability
- Extracted common purpose method into a new helper class
Aims to fix this kind of random failure (happened in current master):
https://travis-ci.org/azkaban/azkaban/builds/266111102
```
azkaban.execapp.JobRunnerTest > testDelayedExecutionCancelledJob FAILED
java.lang.AssertionError: expected:<2> but was:<1>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at azkaban.execapp.JobRunnerTest.testDelayedExecutionCancelledJob(JobRunnerTest.java:309)
```

Improve JobRunnerTest stability

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

It was possible that if job is killed just before the job gets inside the sync block currently in `delayExecution()`, it can remain in wait for the full `delayStartMs` instead of exiting. This is fixed by bringing also the checks for `isKilled()` into the sync block in `delayExecution()`.

Fix sync bug in JobRunner#delayExecution

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java

This PR is attempting to solve issue https://github.com/azkaban/azkaban/issues/1363.
Currently if we setup SLA but with no action specified, there will be no warning, and schedule page will show "has SLA" is true.
However, action should be required when setting up SLA. 
This PR added a non empty check on SLA actions when adding SLA for a schedule. Warning window will show up if action is not specified when setting SLA.
Old check was not checking the number of actions at all when updating SLA. The null check was used when uploading project logs.
Verified manually, but will automate the test in the internal integration test framework

disallow no action SLA

---

build.gradle

"The plugin adds an errorprone configuration that automatically uses the
latest release of error-prone. You can override it to use a specific
version "
see https://github.com/tbroyer/gradle-errorprone-plugin
It appears that by latest version it will use the last locally cached
version. This caused inconsistency in builds.
Also, it introduces additional variables in the build. 
e.g. see #1380 
Specify a fixed version
Will update to the latest version after the internal Artifactory
is updated with the latest version.
Delete the gradle cache and run the build again and verify in the
console output that the specified version is downloaded.

build: use a fixed google errorprone version

---

azkaban-common/build.gradle
azkaban-db/build.gradle

This PR is a follow-up of #1361 , which aimed at clearing the submodule dependency management. We explicitly depend on some internals from `azkaban-db`. It would be nice if we could hide this detail.
The solution originated from:
https://softnoise.wordpress.com/2014/09/07/gradle-sub-project-test-dependencies-in-multi-project-builds/

hiding internals of azkaban-db tests in other module

---

azkaban-common/src/main/java/azkaban/executor/ActiveExecutingFlowsDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutionJobDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorEventsDao.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionLogsDaoTest.java

Still, this PR is a follow-up of #1345. Last but not least, I'm migrating remained methods in JdbcExecutorloader to use new DB API. This commit should be the last one of the series.

The final commit for JDBC Executor rewrite

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/storage/StorageCleaner.java
azkaban-common/src/main/java/azkaban/storage/StorageManager.java
azkaban-common/src/test/java/azkaban/storage/StorageCleanerTest.java

Added a config `azkaban.storage.artifact.max.retention` (default: 0)
Based on the storage parameter the files are removed and the project_versions table entries are removed.
```
    /*
     * The max number of artifacts retained per project.
     * Accepted Values:
     * - 0 : Save all artifacts. No clean up is done on storage.
     * - 1, 2, 3, ... (any +ve integer 'n') : Maintain 'n' latest versions in storage
     *
     * Note: Having an unacceptable value results in an exception and the service would REFUSE
     * to start.
     *
     * Example:
     * a) azkaban.storage.artifact.max.retention=all
     *    implies save all artifacts
     * b) azkaban.storage.artifact.max.retention=3
     *    implies save latest 3 versions saved in storage.
     **/
    public static final String …
```

StorageManager to clean up project artifacts based on config

---

azkaban-web-server/src/test/java/azkaban/fixture/FileAssertion.java

This function is currently only used in the testProjectSideBarView test.
This is to make it easier to auto format html files and velocity
templates.

Ignore white space differences when comparing html outputs in tests

---

.travis.yml
build.gradle

Travis CI builds sometimes fail with the following error
```
Process 'Gradle Test Executor 6' finished with non-zero exit value 137 travis
```
See
https://discuss.gradle.org/t/gradle-travis-ci/11928/9
https://discuss.gradle.org/t/travis-ci-org-gradle-launcher-daemon-client-daemondisappearedexception-gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-have-crashed/13106/3

build: reduce gradle build memory usage on the Travis CI

---

.travis.yml

It's useful to see additional information. It's currently difficult to
debug a flaky test that only fails in Travis since there is no easy way
to see the test's console output.

build: run Travis build with --info flag to get more detailed output

---

azkaban-common/src/main/java/azkaban/Constants.java

Adjust `<p>` tags placements to conform to the Google style guide.
Describe more details in the class summary line.
See
https://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs
Also see
http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html
http://blog.joda.org/2012/11/javadoc-coding-standards.html
Note that the Google style places `<p>` after the empty line. It's
different from the Oracle style.

format: properly format the javadoc for the azkaban.Constants class

---

azkaban-common/src/main/java/azkaban/project/validator/XmlValidatorManager.java

Use proper javadoc tags to preserve the formatting of the xml example in
the javadoc.
{@code} is used to prevent javadoc compiler from
misinterpreting the xml tags as javadoc tags.
The `<pre>` tag prevents intellij from attempting to reformat
the example code.
See
http://www.rgagnon.com/javadetails/java-0623.html

format: properly format the javadoc for the XmlValidatorManager class

---

README.md
az-intellij-style.xml

- Modify the style template to preserve line feeds in the Javadoc. This
makes it easier to preserve the Javadoc format in the source file. This
is especially helpful given this IntelliJ issue
"Formatting doesn't apply to an existing Javadoc "
https://youtrack.jetbrains.com/issue/IDEA-178073
- Change the name of the style config file and the style name
to reflect that it is now a customized style config for the project.
And it contains styles for other languages such as JavaScript as well.
- Update the README to reference the new style file. Make it clear that
the new style needs to be activated after it is imported.
- Update the README to require SaveAction plugin. We have finished
auto formatting all the source files.

Customize code style template. Update README

---

build.gradle

This is a follow-up PR for the previous errorprone version change [PR #1382](https://github.com/azkaban/azkaban/pull/1382).
We've updated the errorprone version in artifactory to 2.1.0. We can update the version in Azkaban accordingly.

Update errorprone to latest version 2.1.0

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

Use TemporaryFolder for working dir to increase test isolation / stability.
Maybe this will remove the possibility of random failure in file copying as described here: https://github.com/azkaban/azkaban/issues/1389#issuecomment-326224551

FlowRunnerTests: Use TemporaryFolder @Rule

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/TriggerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecutorServerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

There still exists a few places where we bind class to singleton in guice module class. As discussed a few weeks ago, we decided to enforce using `@Singleton` annotation, rather than the binding statement. The benefit is to manage and view singleton class easily.
This code patch tries to fix/replace this issue.

Enforce using Singleton Annotation rather than binding statement

---

azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/executor/ExecutorInfo.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/SelectorTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java

- Extract the API calling code from ExecutorManager to a new class ExecutorApiGateway
- This way ExecutorManager doesn't handle raw JSON, the gateway always returns some higher level object (once again, this will allow making cleaner unit tests for ExecutorManager).

Refactor only: create ExecutorApiGateway

---

az-exec-util/build.gradle
az-exec-util/src/main/c/execute-as-user.c
azkaban-common/build.gradle

This module doesn't belong to the common module.
It also helps speeding up the build a bit by taking better advantage of
the gradle cache and project dependency management.
Fixes #1227

Move execute-as-user c program to its own module

---

_includes/docs/latest/ajax-api.html

We don't have `queue` option for concurrent settings.
Take a look at code:
https://github.com/azkaban/azkaban/blob/9e89d362b604926e2c087efebc6f429e2f2295c9/azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java#L33-L35

replace unknown concurrent option

---

azkaban-common/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/event/Event.java
azkaban-exec-server/build.gradle
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/LocalFlowWatcher.java
azkaban-exec-server/src/main/java/azkaban/execapp/jmx/JmxJobMBeanManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedFlowMetric.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedJobMetric.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumRunningJobMetric.java
azkaban-exec-server/src/main/java/azkaban/execapp/reporter/AzkabanKafkaAvroEventReporter.java
azkaban-exec-server/src/main/java/azkaban/execapp/reporter/AzkabanKafkaPusher.java
azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecServerModuleTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/EventCollectorListener.java
azkaban-exec-server/src/test/java/azkaban/execapp/EventReporterUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/LocalFlowWatcherTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/RemoteFlowWatcherTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/reporter/AzkabanEventReporterTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/reporter/AzkabanKafkaPusherTest.java
azkaban-spi/src/main/java/azkaban/spi/AzkabanEventReporter.java
azkaban-spi/src/main/java/azkaban/spi/EventType.java
build.gradle

**Summary**
With this change, support for reporting events of interest from azkaban has been provided.
The default implementation uses a kafka event reporter. Users can provide alternate
implementations of the reporter. To begin with, the following events are reported.
1. FLOW_STARTED
2. FLOW_FINISHED
3. JOB_STARTED
4. JOB_FINISHED
In future, this can be easily extended to report other events. The default event reporter
implementation uses gobblin-metrics, which provides conevenient methods for event creation
and submission. Gobblin-metrics also provides a schema for the events. The default
implementation uses the kafka async producer.
**Configuration changes**
Note: All changes must be applied to the executor server or the solo-server if in solo mode.
// Property is used to …

Event reporting for azkaban events.

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java

This method is only used in tests.
Make the name more descriptive.
This is particularly helpful when doing code reviews.

Rename assertFlowStatus method to waitForAndAssertFlowStatus

---

.travis.yml
build.gradle

#1448 
Travis CI builds sometimes fail with the following error
> Process 'Gradle Test Executor 6' finished with non-zero exit value 137 travis
@HappyRay alleviated some of the resource issues with #1402 but we are still seeing sporadic failures. 
Gradle has a tool to investigate builds including metrics like memory, threads GC etc called [scans](https://scans.gradle.com/get-started) .This change enables build scans on travis to help debug failures and also provide insight into our builds.

build: Enable gradle scans on travis CI to debug #1448

---

azkaban-common/src/main/java/azkaban/flow/FlowUtils.java
azkaban-common/src/main/java/azkaban/utils/PropsUtils.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

In order to move metrics foundation class to a common place, I am creating `az-core` sub module. Since Metrics relies on some utils class in `azkaban-common`, the first step of this series of refactor is to clean up some methods in `azkaban-common', and it facilitate me to do those refactor in the following PRs.
In this code patch:
* I move `addCommonFlowProperties` out of PropsUtils, so that we can move PropsUtil to az-core in the next PR easily. 
* Also, this method is not suitable to stay in `PropsUtils`.

move one method out of PropsUtils [Refactor]

---

azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
build.gradle

(Part of fixing https://github.com/azkaban/azkaban/issues/1389)
- Now instead of fixed 1s sleep we wait for max 10s for the node update count to be 2.
- This lets us use the luxury of additional sleep time (1s->2s) before killing the flow, so that there's a better chance for job getting inside its delayExecution() block.
Test failure was:
```
azkaban.execapp.JobRunnerTest > testDelayedExecutionCancelledJob FAILED
java.lang.AssertionError: expected:<2> but was:<1>
```
It was faithfully reproduced when I removed the 1s sleep before assert on getNodeUpdateCount().

Fix flaky JobRunnerTest > testDelayedExecutionCancelledJob

---

azkaban-web-server/src/main/less/base.less

#1335 brought a feature that AZ admins can publish messages in banner bar on the top of AZ UI. There exists an issue reported by the user: 
>I cannot click on the "Job List", "Flow Log", and "Stats" tabs until the orange message banner disappears after about 30 seconds.
The cause is that `container-fill` (css class) uses absolute position, when the top div elements moves down, it will override the div beneath. I figured out there are a number of places using `container-fill`. So I'd like not change the [original place](https://github.com/kunkun-tang/azkaban/blob/e188e943680f7721d9d4ecb677e15ce686880d66/azkaban-web-server/src/main/less/base.less#L9). The proposed fix is that we just let flow view page's div to be `static`, such that it will move downward along with top div.
Basically, we …

Fix not being able to change tab after pulling a note banner

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/FlowWatcher.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/RemoteFlowWatcherTest.java

Blocked by 2 other PRs, see https://github.com/azkaban/azkaban/pull/1248.
----
Fix bug where pipelined execution gets stuck
If you had executed a flow with some subflows disabled and then started another execution in pipeline mode, the next execution remained blocked forever by the jobs inside sub-flows, because they remained in READY state instead of being set to SKIPPED.
**This was a pretty nasty bug because for example next morning's scheduled run can get stuck after you've launched an execution with some jobs disabled on the previous day.**
I think it would make sense to clean this up also on the flow saving side: when subflow status is changed from DISABLED to SKIPPED, all jobs in the subflows would also be marked as SKIPPED.
Indeed was able to reproduce with the new test method …

Fix bug stuck in pipeline mode

---

build.gradle

The dev setup now depends on Intellij specific plugins, styles etc.

Build: remove eclipse gradle plugin

---

azkaban-common/src/main/java/azkaban/sla/SlaOption.java

Using `</br>` is a "closing tag", doesn't exit. The self-sufficient linebreak tag is `<br/>`.
Save Actions plugin moved the imports around a bit.

Fix broken HTML in SLA message

---

azkaban-web-server/src/main/less/azkaban-graph.less
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/less/variables.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/historypage.vm
azkaban-web-server/src/web/js/azkaban/util/job-status.js

FAILED_SUCCEEDED status was missing color in the UI, so add it.
The issue https://github.com/azkaban/azkaban/issues/1451 has some further details.

Add UI colors for FAILED_SUCCEEDED

---

azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
azkaban-web-server/src/web/js/azkaban/view/job-edit.js

Fix duplicate properties in flow execution and job edit when dialog is closed and reopened.

fix bug #1481: avoid duplicate properties when closing/reopening dialog

---

azkaban-common/src/test/java/azkaban/ServiceProviderTest.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperator.java
azkaban-db/src/main/java/azkaban/db/H2FileDataSource.java
azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

Both `H2FileDataSource ` and `MySQLDataSource ` should be singleton. The reason behind is that We would like all database operations to share the same connection pool to guarantee performance. 
Besides, removing singleton from `DatabaseOperator` as no states exist there. It is safe to have multiple DatabaseOperator instances.

Adding missing datasource singleton annoataion

---

azkaban-common/build.gradle
azkaban-exec-server/build.gradle
azkaban-solo-server/build.gradle

#1498 
With change #1069 we introduced hadoop dependencies in azkaban-common/build.gradle which resulted in hadoop jars being present in the lib directory. 
Also with change #1332 we introduced transitive hadoop dependencies through the gobblinKafka dependency. 
When testing against different hadoop versions we noticed azkaban was pulling in its own hadoop jars into the distribution instead of using what's available on the hadoop cluster.
For change #1069 
Gradle has a [compileOnly](https://blog.gradle.org/introducing-compile-only-dependencies) dependency option which is a true compile only dependency as opposed to compile which extend into runtime.
We also needed to add the same dependencies as a testCompile dependency tests. 
For change #1332 
we made two changes, the compile has an …

build: change hadoop gradle dependencies to compileOnly

---

azkaban-solo-server/build.gradle

#1502
With #1499 we broke azkaban-solo-server due to missing hadoop dependencies in solo server which were being transitively included.
Include hadoop dependencies for azkaban-solo-server
Verified by bringing up azkaban-solo-server locally and running flows against it.

Fix azkaban-solo-server by including hadoop dependencies in build.gradle

---

azkaban-common/build.gradle
azkaban-exec-server/build.gradle
azkaban-solo-server/build.gradle

Creating a 3.34.x hot fix branch with changes to remove hadoop dependencies cherry picked from master. 
Tested by building and bringing up the solo-server.
Also verified that no hadoop dependencies exist in the distribution outside of the solo sever.

3.34.x hotfix branch with cherry picks

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java

JOB_OUTPUT_PROP_FILE is a file used to pass properties between jobs. You can read about it here: http://azkaban.github.io/azkaban/docs/latest/#job-configuration
#1325 introduced a regression where JOB_OUTPUT_PROP_FILE became no longer writable due to an upgraded execute-as-user executable that stopped user processes from having the azkaban group permission. This file needs to be written to so properties can be passed from one job to another.
This fix assigns ownership of JOB_OUTPUT_PROP_FILE and JOB_PROP_FILE to `<username>:azkaban` to guarantee user ability to write to this file. It is uncertain whether or not JOB_PROP_FILE is intended to be written to, but I believe it's a good idea to do allow it to be in order to prevent regressions.
This is covered by an integration test that simply …

Fixing regression where JOB_OUTPUT_PROP_FILE was no longer writable by user process

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

If a job is actually not run at all, but it has been marked as killed, the right thing to do is set the status to KILLED. Otherwise the flow would get stuck because this job would send the JOB_FINISHED event with the unfinished status: KILLING.
This was caught by a unit test on a failed Travis. Details can be found in https://github.com/azkaban/azkaban/pull/1509#issuecomment-333196277.

Fix bug in killed quick finish

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java

Because that's what it does.
Keep alternative ajax action name 'loadFlow' for backward compatibility.
This resolves issue #1506.

Rename ajax loadFlow to fetchSchedules

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/event/Event.java
azkaban-exec-server/build.gradle
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecServerModule.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/LocalFlowWatcher.java
azkaban-exec-server/src/main/java/azkaban/execapp/jmx/JmxJobMBeanManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedFlowMetric.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedJobMetric.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumRunningJobMetric.java
azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecServerModuleTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/EventCollectorListener.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/LocalFlowWatcherTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/RemoteFlowWatcherTest.java
azkaban-spi/src/main/java/azkaban/spi/AzkabanEventReporter.java
azkaban-spi/src/main/java/azkaban/spi/EventType.java
build.gradle

**Summary:**
With this change, support for reporting events of interest from azkaban has been provided.
Users should provide an implementation of the AzkabanEventReporter interface.
To begin with, the following events are reported.
1. FLOW_STARTED
2. FLOW_FINISHED
3. JOB_STARTED
4. JOB_FINISHED
In future, this can be easily extended to report other events.
**Configuration changes:**
Note: All changes must be applied to the executor server or the solo-server if in solo mode.
// Property is used to enable/disable event reporting with the default being false.
azkaban.event.reporting.enabled=false
// Implementations of the reporter to be specified using this property.
azkaban.event.reporting.class=com.foo.EventReporterImpl
// Kafka topic name for the default implementation. …

Event reporting for azkaban events - No default implementation

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

(first test runs longer because it includes initial class loading)
The tests that were ignored, but now enabled are:
- testFailedRun
- testCancelRun
- testDelayedExecutionJob

Enable all the rest in JobRunnerTest

---

azkaban-web-server/src/web/js/azkaban/util/layout.js

The broken graph attached to the bug #1508 happens because `animatePolylineEdge` fails: it assumes that each `edge` has always a number of `edge.oldpoints` equals to the number of `newPoints`, which sometimes fails.
`newPoints` is fed by the `moveNodeEdges`: it iterates through all the `edge.guides` (the segments composing the lines connecting the graph nodes) and adds the starting and ending points; this makes sense, because the assumption `edge.guides.length == edge.points.length - 2` should always hold.
The bug happens because this assumption is broken: in `layoutGraph` we sometimes add a new segment to `edge.guides` but we forget to update the points accordingly.
This patch fixes the problem: when a new segment is added to an edge (see the code after the `// Add gap` comment) we also …

fix bug #1508: fix graph visualisation when exploding nested flows

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/HadoopModule.java
azkaban-common/src/test/java/azkaban/ServiceProviderTest.java
azkaban-solo-server/build.gradle

#1499 makes Hadoop dependencies compileOnly, which caused web-server and exec-server can not initialize Guice successfully if users don't specify their own Hadoop jars in the classpath.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethods(Class.java:1975)
at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:132)
at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
at com.google.inject.spi.Elements$RecordingBinder.install(Elements.ja …
```

create hadoop module

---

azkaban-db/src/main/sql/create.execution_jobs.sql

1. add flow_id to key set of execution_jobs table
2. drop two unnecessary indexes.
Previously primary key set of execution_jobs is (execution_id, job_id, attempt).
This is under the assumption where no job shares the same name within a flow. However this is not the case when embedded flow comes into picture, which allows user to embed a smaller flow into multiple places inside a bigger flow.
with new keyset, two indexes becomes a subset of the key set, so we can drop them.

schema change for execution_jobs

---

azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/web/js/azkaban/view/exflow.js
azkaban-web-server/src/web/js/azkaban/view/flow-execution-list.js

The PR fixes a problem when a queued job would disappear from the job list view when its state changes to **QUEUED**.
Currently, you can access job logs for current and failed attempts in the **Job List** tab of an execution.
If some job failed and has retries, it goes into **QUEUED** state while sleeping before the next attempt.
1. If you want to see why any of the previous attempts failed, you can right-click the _grey attempt bar_
2. To see how long it's going to sleep, you can **check the job log**
Without this fix you can't do either of those if the job is sleeping, because it's hidden if the state is **QUEUED**.
Also if you have a job that hasn't yet started to run but is in **QUEUED** state (ie. blocked by pipeline), if you want to know why it's queued, you should **check the job …

Show queued jobs in the execution list

---

azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzSchedulerTest.java

Otherwise getting this error in startup:
```
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) Error injecting constructor, org.quartz.SchedulerConfigException: Thread count must be > 0
at azkaban.scheduler.QuartzScheduler.<init>(QuartzScheduler.java:52)
at azkaban.scheduler.QuartzScheduler.class(QuartzScheduler.java:48)
while locating azkaban.scheduler.QuartzScheduler
for the 11th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:161)
at azkaban.webapp.AzkabanWebServer.class(AzkabanWebServer.java:119)
while locating azkaban.webapp.AzkabanWebServer
for the 1st parameter of azkaban.soloserver.AzkabanSingleServer.<init>(AzkabanSingleServer.java:48)
while locating azkaban.soloserver.AzkabanSingleServer
1 …
```

Disable QuartzScheduler init unless it's enabled

---

azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

This resolves most of issue #1433 _Remove code duplication in tests: createFlowRunner_.
The FlowWatcher tests are slightly different so I thought to leave them for later – can be done once this has been merged.

Issue #1433 part 1: Remove code duplication in FlowRunner tests

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/FlowWatcherTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/LocalFlowWatcherTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/RemoteFlowWatcherTest.java

This completes fixing issue https://github.com/azkaban/azkaban/issues/1433 (1/2 was PR https://github.com/azkaban/azkaban/pull/1533).
"Extras":
- LocalFlowWatcherTest was actually ignored; I made it run quickly and enabled it.
- I also found & fixed a bug in both FlowWatcher tests: they were asserting pipeline level 1 twice, despite the test names. I fixed those "level 2" tests to run with and assert pipeline level 2 instead of level 1.

Issue #1433 part 2/2: Remove code duplication in FlowWatcher tests

---

azkaban-web-server/src/main/java/azkaban/scheduler/QuartzJobDescription.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/main/java/azkaban/scheduler/SchedulerJobFactory.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzJobDescriptionTest.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzSchedulerTest.java
azkaban-web-server/src/test/java/azkaban/scheduler/SampleQuartzJob.java

We recently found Quartz jobs cannot easily inject a dependency. The previously proposal was to add dependencies into Context of Quartz Job. However, it is not recommended, the correct approach is to only inject String or very light weight objects into context. Besides, it increased more complexity for users to leverage Quartz. In this PR, we create a Quartz Job Factory, which is able to seamlessly provide any dependency inside web server.

Build Quartz Job Factory to allow Quartz jobs easily inject dependencies

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/main/java/azkaban/project/AzkabanFlow.java
azkaban-common/src/main/java/azkaban/project/AzkabanJob.java
azkaban-common/src/main/java/azkaban/project/AzkabanNode.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/project/FlowLoader.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderFactory.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-common/src/test/java/azkaban/project/FlowLoaderFactoryTest.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java
test/execution-test-data/basicflowyamltest/basic_flow.project
test/execution-test-data/duplicateprojectyamltest/basic_flow.flow
test/execution-test-data/duplicateprojectyamltest/basic_flow.project
test/execution-test-data/duplicateprojectyamltest/basic_flow2.project
test/execution-test-data/embeddedflowyamltest/embedded_flow.project
test/execution-test-data/invalidflowversiontest/basic_flow.flow
test/execution-test-data/invalidflowversiontest/basic_flow.project
test/execution-test-data/invalidflowyamltest/cycle_found.flow
test/execution-test-data/invalidflowyamltest/dependency_not_found.flow
test/execution-test-data/invalidflowyamltest/invalid_flow.project
test/execution-test-data/multipleflowyamltest/multiple_flows.project
test/execution-test-data/noflowversiontest/basic_flow.flow
test/execution-test-data/noflowyamltest/no_flow.project

1. In Flow 2.0 design, we load project flows from flow YAML files and convert them to azkabanFlow objects. In order to display the flow graph in the UI correctly, we need to further convert azkabanFlow to Flow object with all the necessary parameters filled in, like nodes and edges. 
2. With the flow level definition, we don't need to rely on an endNode to resolve the DAG. The new design will be able to resolve the DAG even without an endNode.
3. Project YAML file is also introduced in the Flow 2.0 design. It contains azkaban flow version. Only when "Azkaban-Flow-Version: 2.0" is specified in the project YAML file, then we treat it as Flow 2.0 design. If the project YAML file does not exist, we just keep the current way of loading project flows from job and properties files.

Flow 2.0 design - Convert AzkabanFlow to Flow. Load project YAML file.

---

azkaban-common/src/main/java/azkaban/flow/FlowUtils.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowPriorityComparatorTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java
azkaban-common/src/test/java/azkaban/executor/QueuedExecutionsTest.java
azkaban-common/src/test/java/azkaban/flow/FlowUtilsTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

This PR consolidates some methods of initialization of ExecutableFlow which used in multiple places  into common static util methods. 
The motivation is to let flow trigger leverage those method to start an executable flow(https://github.com/azkaban/azkaban/issues/1526).
Also changed the azkaban.utils.TestUtils#createExecutableFlow to azkaban.utils.TestUtils#createTestExecutableFlow to avoid name duplication.

make ExecutableFlow initialization methods common util methods

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java
azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
test/execution-test-data/multipleembeddedflowyamltest/embedded_flow.flow
test/execution-test-data/multipleembeddedflowyamltest/embedded_flow.project
test/execution-test-data/multipleembeddedflowyamltest/embedded_flow_b.flow

1. Support API to get flows and job properties from flow YAML file. This is needed when executing the flows and jobs.
2. With the new YAML file format, there is no need to specify the parent flow name as a prefix for the jobs. YAML format provides a structured way to distinguish sub-flows or jobs with same names between different parent flows. To achieve that, we choose to adopt ":" as the delimiter for job path. For example, the job path in an embedded flow could have the internal naming as "flow1: subflow2: subflow3: job4".  As a result, ":" will be restricted for use in the flow or job names. We will add validation to that later.
3. Today we are showing sub-flows in the project UI page together with the parent flow. This is not ideal because sub-flows should not be treated as …

Flow 2.0 design - Get props from flow YAML file.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

This PR is a follow-up of #1552 . We create a job setting "azkaban.job.enable.ssl". When it is enabled, we use Java reflection to initialize the credential provider object, and run the method.

Create a job setting to enable leveraging custom credential provider

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Fix https://github.com/azkaban/azkaban/issues/1559.
After making `attempt` volatile, `attempt++` had to be synchronized because of this check:
http://errorprone.info/bugpattern/NonAtomicVolatileUpdate

Fix issue #1559: Error writing out logs for job on a retry attempt

---

azkaban-common/src/main/java/azkaban/database/AzkabanDatabaseSetup.java

https://github.com/azkaban/azkaban/issues/1569
Issue #1569: "Startup fails: missing tables that need to be installed: quartz-tables-all"
This fix allows `AzkabanSingleServer` to start, and I was also able to run jobs after that.

Temporary fix for startup failure (#1569)

---

azkaban-common/src/main/java/azkaban/utils/Emailer.java

Create a sendEmail method to be used more generally not just limited to failure/success/sla emails. This method will be used by Flow trigger to alert user on flow trigger failure with customized email subject/body.
Since currently Emailer.java can only be tested via integration test, I didn't write unit test but verified by sending a email with the new method in local mode.

Refactor Emailer.java

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

If you execute the fetchflowgraph API in already deleted project, the following error occurs.
I think that null check is necessary.
azkaban 3.37.0 log
```
java.lang.NullPointerException
at azkaban.webapp.servlet.ProjectManagerServlet.fillFlowInfo(ProjectManagerServlet.java:781)
at azkaban.webapp.servlet.ProjectManagerServlet.ajaxFetchFlowGraph(ProjectManagerServlet.java:772)
at azkaban.webapp.servlet.ProjectManagerServlet.handleAJAXAction(ProjectManagerServlet.java:240)
at azkaban.webapp.servlet.ProjectManagerServlet.handleGet(ProjectManagerServlet.java:142)
at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:123)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
at …
```

Fix NullPointerException in fetchflowgraph API

---

azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java

Linux has restriction on shell argument length, it's likely the command to do hard linking project dir of a lot of subdir and files will exceed the restriction, causing flow setup failure. The fix is replacing the logic with java native file API.

use java lib instead of external sh commands to do recursive hard linking

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This is to fix issue: https://github.com/azkaban/azkaban/issues/1597
On job properties page, the properties are a combination of original job properties and jobOverride properties. This does not work when we delete the property from original ones. In project_properties DB table, the jobOverride properties (.jor) contains all the job properties instead of just the delta of changed properties.
It makes more sense to display the jobOverride properties if there is any. Otherwise, we just display the original job properties.

Fix deleting job properties issue on web UI.

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
test/execution-test-data/basicyamlshelltest/bashSleep.flow
test/execution-test-data/basicyamlshelltest/bashSleep.project

A couple of production issues warned us that we should enforce the MAX number of concurrent executions given a flow executable. In case people accidentally schedule flows per minute or endlessly submit flows from the client side, this PR proposes to implement a simple quota to prevent it happening.
Unit Test is added.

Enforcing num of concurrent runs quota given a Flow Executable

---

azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java

In the case where there is only one node for the flow, no edge will be created. This should also be handled gracefully.

Fix the case where there is no edge for the flow.

---

azkaban-common/src/main/java/azkaban/project/FlowTrigger.java
azkaban-common/src/main/java/azkaban/project/FlowTriggerDependency.java
azkaban-common/src/test/java/azkaban/project/FlowTriggerTest.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java

This PR made several changes to FlowTrigger/FlowTriggerDependency class
Made FlowTrigger and FlowTriggerDependency Serializable. This is to required by Quartz scheduler to persist scheduled job.
Added error message when doing argument validation. This is for better user experience when misconfigured flow trigger is uploaded.
Converted dependencies type from list to a hashmap with name as key for convenient lookup.

FlowTrigger and FlowTriggerDependency update

---

azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java

User reported intermittent issues that they sometimes could not get job properties after successfully deploying their project. When they executed the flow, it still picked the old project version and run. Project info like lastModifiedTime was not updated on the web UI after CRT deployment.
This issue could not be reproduced locally and it only happened to certain projects occasionally. Suspect some issue with updating project cache. Add some log messages to help debug the issue.
Related issues: LIHADOOP-33098, LIHADOOP-34114, TOOLS-170605

Add debug logging for upload project issue.

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/CancellationCause.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/DependencyInstance.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/Status.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstance.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceTest.java

PR added two core classes for flow trigger feature: TriggerInstance and DependencyInstance.
Conceptually trigger Instance represents an execution of a flow trigger. It holds execution context such as a historically unique trigger execution id, execution status, start/end time, and a list of dependency instances.
Similarly dependency Instance denotes an execution of a dependency performing availability check on a particular data dependency. It holds execution context such as execution status and start/end time, all dependency Instances within the same trigger instance share the same execution id as trigger instance.
A trigger instance and its dependency instances will be created on scheduled trigger start time. The trigger instance will wait until all dependency instances are available, at …

flow trigger/dependency instance

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

People always get confused when they read 
> See logs at: https://blahblahXXX://
This PR adds another log message before this message, in order to instruct users how to set job ELK logger.

Clarify the ELK instruction logging message

---

az-core/src/main/java/azkaban/Constants.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/plugin/FlowTriggerDependencyPluginManager.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerDependencyPluginManagerTest.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerServiceTest.java

This PR injects flow trigger service(https://github.com/azkaban/azkaban/pull/1627) into azkaban web server. Flow trigger service will start if enabled in the config file. Upon start, flow trigger service initializes all dependency plugins and recover running trigger instance from last run status.

integrate flow trigger service with az web server

---

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm

When users click the show button for executionOptions on /scheduling page, it shows the same info for all schedules, which is incorrect. This is related to a recent change in PR https://github.com/azkaban/azkaban/pull/909
The issue happens because the executionOptions id is the same for all schedules when loading the page. I made the change to specify the executionOptions id for each schedule. Also, I changed the display of executionOptions info and the show button style to make it more readable.

Fixed the UI display issue of same executionOptions for all schedules.

---

az-core/src/main/java/azkaban/metrics/MetricsManager.java
azkaban-db/src/main/java/azkaban/db/DBMetrics.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperator.java

This PR proposes two changes:
* Originally we use `getFifteenMinuteRate` to get transform meter to gauge. 15 mins was too large, and we'd better change it to 1 minute window to reduce smoothing effect
* Adding database transaction metrics if database throws an exception during the query phase.
Tested on the staging environment.

adding db transaction failure metrics

---

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

flow trigger service needs to be started first before scheduler starts to schedule existing flow triggers. This PR puts starting flow trigger service before starting flow trigger scheduler and adds more logging when starting flow trigger service/scheduler.

start the flow trigger service first then flow trigger scheduler

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm

This PR adds an UI page to display current scheduled flow trigger:

flow trigger UI

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerInstanceLoaderTest.java

This PR fixes the bug which includes trigger Instances in cancelling state into recently finished flows.

exclude trigger instances in cancelling status from recently finished flows

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

In order to allow users to debug credential issues easily, this PR proposes adding job logger into the credential instance, so that related log messages will be shown in Azkaban web UI. 
Notice that this PR is backward compatible. In the credential client code side, we have both 2-parameter and 3-parameter constructor. If we need to roll back this commit, it will not fail.
Tested in staging cluster.

adding job logger to credential instance

---

az-core/src/main/java/azkaban/utils/Props.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java

Today `toProperties` in Props API doesn't include parent properties. In this PR, we add an API to import both current and parent properties. 
Tested locally.

Add an API to allow Props to load both current and parent properties 

---

azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java

changed error message from "max wait min must be longer than X min" 
to "max wait min must be at least X min(s)"

flow trigger max wait time validation error message improvement

---

azkaban-db/src/main/sql/create.execution_dependencies.sql
azkaban-web-server/src/main/java/azkaban/flowtrigger/DependencyInstance.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstance.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowtriggerspage.vm
azkaban-web-server/src/test/java/azkaban/flowtrigger/DependencyInstanceProcessorTest.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerInstanceLoaderTest.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceTest.java

This PR switched column mysql data type from datetime to bigint to keep the start/end time of dependency instance. The reason is datetime is not timezone agnostic(https://dev.mysql.com/doc/refman/5.5/en/datetime.html). It's less error-prone to keep UTC timestamp(System.currentTimeMillis()) in db.

use bigint to keep the timestamp of flow trigger dependency instance in db.

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/database/FlowTriggerInstanceLoader.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerInstanceLoaderTest.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/MockFlowTriggerInstanceLoader.java

Flow trigger service currently maintains an in memory list of running trigger instances for fast retrieval of the list of currently running trigger instances. However, it also introduces some issues like race condition and threads being created per request of getting running trigger instances. Removing the dependency on running trigger instances and retrieving directly from DB is a simpler and less error prone option. If retrieval of running triggers starts to have performance concern, we will reconsider it. 
But this PR doesn't remove the running trigger entirely from flow trigger service since the mapping between running trigger instance and and its DependencyInstanceContext still needs to be kept in memory in case where users want to cancel a running trigger instance.
follow up:
1. Add …

retrieve running trigger from db instead of cache in flow trigger service

---

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

Issue description: https://github.com/azkaban/azkaban/issues/1681
Since webServer.scheduler and webServer.flowTriggerService are injected and always non null, even if quartz is disabled, in old code webServer.scheduler.shutdown() will be still executed throwing NPE if quart is disabled.

fix NPE when shutting flow trigger scheduler

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java

Dependency name and trigger instance id should be passed into dependency instance config and runtime props when creating dependency instance context so that trigger instance id and dependency name is obtainable by dependency instance context to identify itself.
E.x.
Dependency instance context could put trigger instance id and dependency name in the log, thus user can easily scope all logging messages produced by a particular dependency instance.

pass dependency name and trigger instance id to dependency instance context 

---

az-core/src/main/java/azkaban/Constants.java
az-core/src/main/java/azkaban/utils/Props.java
az-core/src/main/java/azkaban/utils/PropsUtils.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java
azkaban-common/src/main/java/azkaban/server/session/SessionCache.java
azkaban-common/src/test/java/azkaban/server/session/SessionCacheTest.java

continuation of https://github.com/azkaban/azkaban/pull/1608:
documentation of `SessionCache` enhanced; session TTL config key moved to `Constants`
@HappyRay

SessionCache documentation enhanced; config keys moved to Constants class

---

azkaban-web-server/build.gradle
azkaban-web-server/package-lock.json
azkaban-web-server/package.json

This change is because github flagged the version of `moment`
used by Azkaban as having a CVE.  While updating moment, I also made the following changes.
1) In build.gradle, I updated Node & NPM versions.  
a) The new version of NPM generates a package-lock.json file, which is similar to Ruby's Gemfile.lock file in listing all dependencies and should be checked into the repo to pin versions.
b) Added a `force` flag to allow the NPM gradle plugin to clean the local NPM cache.  This is required by newer versions of NPM.
2) I used the NPM module `depcheck` to look for unused dependencies and updated package.json accordingly

Node, NPM, and moment version number updates

---

azkaban-common/src/main/java/azkaban/utils/AbstractMailer.java
azkaban-common/src/main/java/azkaban/utils/EmailMessage.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java

The removed code is not used even by [ReportalMailCreator.java in azkaban-plugins repo](https://github.com/azkaban/azkaban-plugins/blob/master/plugins/reportal/src/azkaban/viewer/reportal/ReportalMailCreator.java)
(I wasn't able to build azkaban-plugins as a whole, so I copied the `EmailMessage.java` with these modifications on that side and tested that `ReportalMailCreator` still builds in IDEA.)

Delete unused code in email-related classes

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/utils/AuthenticationUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailsheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm

For Hadoop/Spark jobs, the job log first stays in resource manager, after some time, it will be moved to job history server. The current web proxy job link in Azkaban user logs doesn't always work properly. When user click the link, it often expires. Users have to search for the application_id and then manually type the RM or JH link to find the actual job log.
I've added a new button on job log page to provide the dynamic job link. See attached images for the UI change. When user click the "Hadoop Job Log" or "Spark Job Log" button, it first logins to RM using authenticated keytab files, then parses the web content to determine whether the job log has expired on RM and been moved to JHS. It constructs the correct job link URL and returns to the user. If the job fails or is killed, the …

Dynamically generate job link URL.

---

azkaban-db/src/main/sql/create.execution_dependencies.sql
azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerQuartzJob.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerInstanceLoaderTest.java

The initial motivation of keeping project object as part of trigger instance and persist it into db is for consistency purpose - when a new project zip is uploaded, even if web server restarts after that, the running trigger instance would still pick up the old version of the flow to execute for consistency. 
However due to the huge size of project object, the cost of keeping project object for each dependency instance/flow trigger in db is extremely high(suppose a big project containing hundreds of flows, one of which are using flow trigger, then each row of execution_dependencies will contain a large blob field of project json, rendering deserialization costly when recovering incomplete trigger instances before web server restarts).  
So we decided to only keep the project id instead of …

move project json out of execution_dependencies table

---

azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/utils/RestfulApiClient.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewaySystemTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java
azkaban-common/src/test/java/azkaban/utils/RestfulApiClientTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java

Fix for #1653.
Switch to using POST with form params instead of GET with URL params, so that the number of execution ids passed can be longer.
Also deleting some unused code.
Tested manually that it works like this:
- run AzkabanSingleServer in IDEA with debugger
- start a flow via the UI (http://localhost:8081/)
- set breakpoint to check that requests come to `azkaban.execapp.ExecutorServlet` and are handled successfully
- set breakpoint to check that `ExecutorManager` can get the execution updates
(initial PR & discussion in https://github.com/azkaban/azkaban/pull/1655)
Builds on https://github.com/azkaban/azkaban/pull/1707 to validate the fix.

Call executor servlet with POST

---

azkaban-exec-server/src/main/java/azkaban/execapp/JMXHttpServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/ServerStatisticsServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/StatsServlet.java

`ExecutorApiGateway` was changed to use `POST` for all requests, but I missed that azkaban-web also makes calls to `/serverStatistics`, `/jmx` & `/stats` via the gateway, not just `/executor`.
The problem wasn't seen in manual tests with AzkabanSingleServer because it doesn't use multi-executor mode.
Bug was reported by @chengren311 at https://github.com/azkaban/azkaban/pull/1659#issuecomment-376768014.

All executor servlets to use POST

---

azkaban-common/src/main/java/azkaban/metric/inmemoryemitter/InMemoryMetricEmitter.java
azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/executor/SleepJavaJob.java
azkaban-common/src/test/java/azkaban/jobExecutor/JavaProcessJobTest.java
azkaban-common/src/test/java/azkaban/metric/MetricManagerTest.java
azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java

Cut ~40s off `azkaban-common` test runtime. Now they run in ~5s for me. Still leaves room for improvement..

Disable or optimize slow unit tests

---

az-reportal/src/main/java/azkaban/viewer/reportal/ReportalMailCreator.java

This PR is to roll back https://github.com/azkaban/azkaban-plugins/pull/278. People are still calling out for this feature. Will make it configurable in a follow-up PR, so that reportal have the flexibility to enable or disable this feature.

Rollback Email template from azkaban/azkaban-plugins#278

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstance.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/database/JdbcFlowTriggerInstanceLoaderImpl.java

The PR consists of following fix/enhancement around flow trigger service:
1. Cancel non-recoverable trigger instances after web server restarts:
the following situation would cause trigger instances unrecoverable:
1.1. project A with flow A associated with flow trigger A is uploaded
1.2. flow trigger A starts to run
1.3. project A with flow B without any flow trigger is uploaded
1.4. web server restarts
In this case, flow trigger instance of flow trigger A will be equipped with latest project, thus failing to find the flow trigger since new project doesn't contain flow trigger at all.
2. fix edge cases in getIncompleteTriggerInstances
3. shutdown executor service of TriggerInstanceProcessor when shutting down FlowTriggerService.

Flow trigger service enhancement

---

az-reportal/src/main/java/azkaban/jobtype/ReportalPigRunner.java

We found a security hole in #1325 that any job is able to leverage execute-as-user to impersonate any unix account. when we tryied rolling out this fix to Reportal server, we run into an exception for all ReportalPig jobs:
> 13-04-2018 16:54:13 PDT test-pig INFO - Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
13-04-2018 16:54:13 PDT test-pig INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1769)
13-04-2018 16:54:13 PDT test-pig INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.runMethodAsUser(HadoopJavaJobRunnerMain.java:221)
13-04-2018 16:54:13 PDT test-pig INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.(HadoopJavaJobRunnerMain.java:174)
13-04-2018 16:54:13 PDT test-pig INFO - 	at …

fix reportal regression bug introduced by security fix #1325

---

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java

Use **global.properties** even if **common.properties** doesn't exist

Load global.properties even if common.properties doesn't exist

---

az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsExecutionJar.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsResolveJarSpec.java

The two below classes test related Jar functions and were messing /temp/HadoopTest folder. It caused out test fail. 
>Gradle test > azkaban.jobtype.TestHadoopJobUtilsExecutionJar.testLibFolderHasNothingInIt > captured output:
log4j:WARN No appenders could be found for logger (root).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
azkaban.jobtype.TestHadoopJobUtilsExecutionJar > testLibFolderHasNothingInIt FAILED
java.lang.IllegalStateException: the File[] matchingFiles variable is null.  This means an IOException occured while doing listFiles.  Please check disk availability and retry again
at azkaban.jobtype.HadoopJobUtils.getFilesInFolderByRegex(HadoopJobUtils.java:371)
at …

fix hadoop jobtype flaky test

---

.gitignore
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/metric/TimeBasedReportingMetric.java
azkaban-common/src/main/java/azkaban/metric/inmemoryemitter/InMemoryMetricEmitter.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/metric/MetricManagerTest.java
azkaban-common/src/test/java/azkaban/project/DirectoryFlowLoaderTest.java

Tests should produce less false positives *without intervention in the environment* by:
* ~~increasing time interval in a `MetricManagerTest`~~
* fixing the source for computing of the time interval in a `MetricManagerTest`
* closing file descriptors in a `DirectoryFlowLoaderTest`
Also, some typos were fixed.
This MR should not have any functional impact. Goal is to improve development experience.
Consider merging https://github.com/azkaban/azkaban/pull/1647, please. Thanks! :)

Tests should produce less false positives

---

README.md
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java

If I fill in project field and push Filter button in Advanced Filter, search doesn't work.
Here is azkaban web server log
```
java.sql.SQLException: Column 'enc_type' in field list is ambiguous Query: SELECT exec_id, enc_type, flow_data FROM execution_flows  ef JOIN projects p ON ef.project_id = p.id WHERE name LIKE ?  ORDER BY exec_id DESC LIMIT ?, ? Parameters: [%hoge%, 0, 16]
at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:350)
at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:288)
at azkaban.db.DatabaseOperator.query(DatabaseOperator.java:65)
at azkaban.executor.ExecutionFlowDao.fetchFlowHistory(ExecutionFlowDao.java:213)
at …
```

Fix Advanced Filter search bug

---

azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerInstanceServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm

The thinking behind that is scheduled flow trigger needs to be paused if something goes south, e.x: the triggered flow is consuming too much azkaban resource. One way to stop the schedule is reupload a new project with new flow config with flow trigger turned off, but allowing the project admin to pause/resume schedule is apparently much more convenient option. 
Tested manually. Unit test will follow up.

allow project admin to pause/resume flow trigger schedule

---

azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java

- Don't use static fields (to have isolated mocks for each `@Test` method)
- Apply save actions
- Replace static sleep method with async callback to avoid extra wait

Remove sleep in TriggerInstanceProcessorTest

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerQuartzJob.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzJobDescription.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzJobDescriptionTest.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzSchedulerTest.java

A quartz job is identified by job name and group name. Group name is the combination of project id and flow id. But job name was a constant string. This PR replaces it with dynamic job name variable. 
For flow trigger, the job name is FLOW_TRIGGER. This is to provide flexibility in case where same flow could have multiple scheduled quartz jobs in the future.

job name should be customized for different types of quartz jobs

---

azkaban-exec-server/src/main/java/azkaban/dag/Dag.java
azkaban-exec-server/src/main/java/azkaban/dag/DagBuilder.java
azkaban-exec-server/src/main/java/azkaban/dag/DagException.java
azkaban-exec-server/src/main/java/azkaban/dag/Node.java
azkaban-exec-server/src/main/java/azkaban/dag/NodeBuilder.java
azkaban-exec-server/src/test/java/azkaban/dag/DagBuilderTest.java
azkaban-exec-server/src/test/java/azkaban/dag/DagServiceTest.java
azkaban-exec-server/src/test/java/azkaban/dag/DagTest.java
azkaban-exec-server/src/test/java/azkaban/dag/NodeBuilderTest.java
azkaban-exec-server/src/test/java/azkaban/dag/NodeTest.java
azkaban-exec-server/src/test/java/azkaban/dag/TestNodeProcessor.java

Special care is given so that the node and dag instances returned to code outside of this package can't be used to manipulate the internal states of the dags directly. This eliminates a class of program errors caused by changing the dag states while it is running.
The dag creation classes can be used separately in the future. To
detect circular dependencies for example.

Separate dag creation from dag execution

---

azkaban-exec-server/src/main/java/azkaban/dag/DagBuilder.java
azkaban-exec-server/src/test/java/azkaban/dag/DagBuilderTest.java

Throws an exception when circular dependency is detected when building a
dag.

Check circular dependency

---

azkaban-exec-server/src/main/java/azkaban/dag/Dag.java
azkaban-exec-server/src/test/java/azkaban/dag/DagServiceTest.java
azkaban-exec-server/src/test/java/azkaban/dag/TestSubDagNodeProcessor.java

Changed the test to discover the node corresponding to a subdag when
the subdag starts to run.
The find node by name method is no longer needed for now.

Remove the find node by name method

---

azkaban-exec-server/src/test/java/azkaban/dag/DagTest.java

With this test, the Node class has 100% code coverage.

Test multiple ready nodes are canceled when the parent node failed.

---

azkaban-exec-server/src/main/java/azkaban/dag/Status.java
azkaban-exec-server/src/test/java/azkaban/dag/DagTest.java

Test that killing a dag in certain state such as killing won't have
any effect.
With this change, the DAG class has 100% code coverage.
Also make ImmutableSet in the Status enum more strongly typed.

Add new tests to Dag

---

az-core/src/main/java/azkaban/utils/ExecutorServiceUtils.java
az-core/src/test/java/azkaban/utils/ExecutorServiceUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/dag/DagService.java
azkaban-exec-server/src/test/java/azkaban/dag/DagServiceTest.java

Part of #1486
Create a new utility class to encapsulate the generic shutdown logic to
make it easier to test and allow better code reuse.
Also reduced the shutdown timeout from 60 seconds to 10 seconds.
With this change and #1763, the dag package will have 100% line
coverage.

Refactor DagService shutdown method and add tests

---

az-core/src/test/java/azkaban/utils/ExecutorServiceUtilsTest.java

Failure on Travis:
azkaban.utils.ExecutorServiceUtilsTest > force_shutdown_after_timeout FAILED
java.lang.AssertionError:
Expecting:
<11L>
to be less than:
<10L>
at azkaban.utils.ExecutorServiceUtilsTest.force_shutdown_after_timeout(ExecutorServiceUtilsTest.java:60)
azkaban.utils.ExecutorServiceUtilsTest
Cause:
When the test host is busy, the execution time may be greater.
Fix:
Add more buffer and a comment to explain the test.

Fix flaky test ExecutorServiceUtilsTest

---

azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Original error message is misleading -
1. it doesn't clarify the error is from web server or executor.
2. executor service sometimes rejects new flow submission because it's being shut down after executor's shutdown api is called, but the message still indicates the reason as exceeding the thread pool limit.

fix the misleading error message when executor cannot take new flows

---

azkaban-db/src/main/sql/create.execution_jobs.sql
azkaban-db/src/main/sql/create.execution_logs.sql

Users reported that log missed when composed job name was too long. The reason is that Mysql doesn't allow to insert a row when `name`'s length is bigger than 128. This PR increases the length to allow long job name to survive.
Since we don't know the Mysql prefix settings for other Azkaban users, we try to meet the requirement for defaults. In Default Mysql settings, the index key prefix length limit is 767 bytes for innoDB. We have to assume most users using innoDB.
Besides, users should gain difference regarding character seeting in Mysql. In `latin1`, each character is exactly one byte long. In `utf8`, a character can consist of more than one byte, usually 3 or 4. At our settings, we use `latin1`, so we can hold 512 character long name for a job.
Because varchar size enhancement is …

increase job name varchar size in Mysql table to allow long job name to survive

---

az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java

A user is able to `user.to.proxy` any user in Reportal today. This has been a security vulnerability issue for long time. This PR proposes a fix to validate user.to.proxy configuration before the zip being uploaded to AZ. If the session user is not part of userToProxy user, error is returned to browser to prevent users saving the Reportal.

Add user.to.proxy validation before reportal uploads the user zip to AZ

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerExecutionCleaner.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerInstanceServlet.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerServiceTest.java

1. change retention period of historic trigger execution rows to 30 days.
2.  some code refactoring:
2.1 separate runnable code from methods which submit those runnable.
2.2 rearrange method/member variable order to make it more organized
2.3 use constant to keep the hard coded thread pool size.

code refactor on flow trigger

---

build.gradle

Fix #1783
"warning
Task :azkaban-solo-server:compileTestJava
The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.
"
Verified with
./gradlew clean build -Dorg.gradle.warning.mode=all

Upgrade error prone gradle plugin to v0.0.14

---

az-core/src/main/java/azkaban/utils/Utils.java
az-core/src/test/java/azkaban/utils/UtilsTest.java

This is to check whether the unzipped file will be outside of the target directory. If the file has a name which traverses its parent directory, e.g. `../../../`, it might end up overwriting other files outside the target directory, causing security issues.

Fix compression vulnerability.

---

az-core/src/main/java/azkaban/Constants.java

Use '.' to separate name spaces and '_" to separate words in the same namespace. e.g.
* azkaban.job.some_key

Add a comment about config key naming conventions

---

azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java

Since processSucceed is an asyn call, test needs to wait for updateAssociatedFlowExecId to be called before verification of its invocation. So when updateAssociatedFlowExecId is called, the associated countdownlatch is decremented to zero and unit test will wait on the countdown latch before verifying invocation of updateAssociatedFlowExecId.

fix flaky test TriggerInstanceProcessorTest#testProcessSucceed 

---

az-hdfs-viewer/src/conf/plugin.properties
az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/HdfsBrowserServlet.java

What we had for error message was hard-coded static string. But now, we created a configurable error message.

Configurable access error message

---

az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/HdfsBrowserServlet.java

The HdfsBrowserServlet allows a user to view HDFS as their own authenticated user or as any other proxy user. Looking at the validation logic, 3 branches exist for obtaining the username of the current user which the plugin proxies as:
Current user from session
Proxy user via session attribute which validates the user has permissions
A "proxyname" parameter when "action" is set to "goHomeDir"
The final option is implemented as follows:
plugins/hdfsviewer/src/azkaban/viewer/hdfs/HdfsBrowserServlet.java
if(hasParam(req, "action") && getParam(req, "action").equals("goHomeDir")) {
username = getParam(req, "proxyname");
}
This means a user can "proxy" as any other valid user by simple appending "?action=goHomeDir&proxyname=$username" to the URL.
This PR removes goHomeDir action.

remove goHomeDir action

---

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderFactory.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-common/src/test/java/azkaban/project/FlowLoaderFactoryTest.java
test/execution-test-data/recursivedirectoryyamltest/subdirectory1/basic_flow.flow
test/execution-test-data/recursivedirectoryyamltest/subdirectory1/subdirectory2/basic_flow.project
test/execution-test-data/recursivedirectoryyamltest/subdirectory1/subdirectory2/basic_flow2.flow
test/execution-test-data/recursivedirectoryyamltest/subdirectory1/subdirectory2/sample_script.sh

This PR is to enhance the current way of loading project flows in Flow 2.0 design.
When users create the project zip, sometimes they create a new directory first, put their project/flow yaml files inside and then zip the directory. This is different from zipping those files directly. Sometimes users want to create multiple subdirectories inside the project zip.
In order to handle different use cases, I extended the current logic of loading project/flow yaml files to subdirectories as well.

Handling recursive directories for Flow 2.0 projects.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

1. Simplify logic
2. Change activeExecutors from HashSet to ImmutableSet to guarantee thread safety.

ExecutorManager refactor

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This PR implements LRU project purging to prevent project files eating up disk space on executor.
We will encapsulate following logic inside the background cleanup thread:
if(disk space consumed by projects >= predefined threshold) 
List all project files and sort them by creation time in ascending order
Iterate over the project file list, delete the file if the project is not running until disk size of projects drops down below a predefined lower threshold or no more projects to delete.
Why using creation time not last access time:
Directory last access time is not maintained by most file systems so we cannot rely on file system API to get last access time. An alternative considered is to modify the project dir every time the code reads it, then last modification time would be equivalent …

Clean shared project directory when disk usage is too high

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

see comments from #1803 
1. change configurable key name
2. change default value for max cache size to 128GB which is a more standard number.
3. change default value for stop cleanup threshold to 60 to allow more space to be freed.
4. change data type of stop cleanup threshold from double to int.
5. rename the parameter name(projectDirMaxSizeInMB - > projectDirMaxSizeInMb) to align with coding standard.

address feedback from #1803

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executionspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/historypage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm

As mentioned in issue #1778, having a tooltip on the table would let the user know that it can be sorted when the header is clicked. This pull request will add the tooltip on scheduling page and history page which are being mostly used.
Sample screenshot:
This is a duplicate PR (https://github.com/azkaban/azkaban/pull/1780) but from a different branch, I moved these changes from master->sort-text in my repo.

adding text to indicate that columns are sortable

---

azkaban-common/src/test/java/azkaban/jobExecutor/ProcessJobTest.java

Issue:
The test failed today on trunk
azkaban.jobExecutor.ProcessJobTest > testCancelAfterJobProcessCreation FAILED
org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at azkaban.jobExecutor.ProcessJobTest.testCancelAfterJobProcessCreation(ProcessJobTest.java:228)
Cause:
I suspect it is because of the travis CI machine being too busy to cancel
the job before it finishes.
Solution:
Increase the running time of the job from 1 second to 5 seconds.
This will not increase the test running time when the test is …

Make testCancelAfterJobProcessCreation more reliable

---

azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/test/java/azkaban/flow/FlowTest.java

level++ returns the level variable BEFORE it is incremented. This means
the level of a node is never incremented and is always zero.
Hence, we need to increment the value by one before passing it to the
function.
Fixes #1793.
The issue was introduced in #1680

fix node level computation of a flow

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestYaml.java
azkaban-web-server/src/web/js/azkaban/util/layout.js
test/execution-test-data/basicflowwithoutendnode/basic_flow.flow
test/execution-test-data/basicflowwithoutendnode/basic_flow.project
test/execution-test-data/embeddedflowwithoutendnode/embedded_flow.flow
test/execution-test-data/embeddedflowwithoutendnode/embedded_flow.project
test/execution-test-data/failbasicflowwithoutendnode/fail_basic_flow.flow
test/execution-test-data/failbasicflowwithoutendnode/fail_basic_flow.project

Currently, when users create a flow, they have to explicitly add an end node with Noop type to converge all the nodes and indicate the end of the flow. Otherwise, the flowgraph will not show up properly and the flow will not be able to finalize correctly.
With this PR, users no longer have to write one single end node to converge all the end nodes. The flow will be finalized when all the end nodes are finished. And one UI bug of flow layout is fixed so that the flow without one converging end node can display properly on the UI.

Remove the single end node restriction for a flow.

---

azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/utils/EmailerTest.java

Currently, we collect all email sending failures and raise alerts whenever the failure rate is above the threshold. There are some failures caused by invalid email recipient address entered by users. In this case, we do not want to raise the alert to Azkaban admins since it is supposed to be resolved by users themselves. The alerts should be used to only indicate the reliability of our system.

Avoid sending email alerts caused by invalid address from users.

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

This is the correct dependency order. Otherwise it can happen that web server tries to launch an execution, but it fails as executor server hasn't started yet.
Also start ExecutorManager's threads (that periodically call executors to get updates) not sooner than when the web server is started. Those threads used to be started already as soon as Guice injection creates the ExecutorManager instance (which happens before executor server is started – even now that the order is fixed).
----
This is one step towards having everything run in "multi-executor" mode.
As you may know, currently there are two possible modes, controlled by `azkaban.use.multiple.executors=true|false`:
1. multi-executor mode, based on the `executors` DB table
2. single executor mode, based on fixed props `executor.host` …

Solo server to start executor first

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

More improvements needs to be done on project LRU cache feature:
1. The feature needs to be turned off by default.
2. Running disk calculation on our production clusters whose project dir size is 1.8T takes >= 10 mins. 
3. Cleaning thread will be hanging likely due to https://stackoverflow.com/questions/13008526/runtime-getruntime-execcmd-hanging. 
4. An alternative design is considered: 
```
Create a file in each project directory and write the size of the project to the file when the project is created. The project files are not supposed to change after creation. Touch this file each time the project is used. This way, we can have a more efficient LRU algorithm based on last access time, not creation time.
Maintain the total size of the project cache in memory to avoid the overhead of …
```

Revert changes related to project LRU cache

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-common/src/main/java/azkaban/flow/Node.java
azkaban-common/src/main/java/azkaban/project/AzkabanFlow.java
azkaban-common/src/main/java/azkaban/project/AzkabanJob.java
azkaban-common/src/main/java/azkaban/project/AzkabanNode.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/project/NodeBean.java
azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/executor/InteractiveTestJob.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow.project
test/execution-test-data/conditionalflowyamltest/conditional_flow1.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow2.flow

This PR is to demonstrate how we can achieve condition on runtime parameters.
Users can specify the condition on some common job/flow/cluster related properties or runtime variables generated in previous jobs.
In order to achieve that, users need to add a `condition` section for the target job using logical expressions. Below operators will be supported:
- Equality and Relational Operators: `==, !=,  >, >=, <, <= `
- Conditional Operators: `&&, ||`
Use `${}` for variable substitution. 
Use `:` for namespacing. It will separate a job name and the parameter. 
Here is one example of conditional worflow with the condition on runtime parameters.
First JobA will generate param1 and write to $JOB_OUTPUT_PROP_FILE. Similar for JobB. After both jobs finish,  we will check whether the condition for …

POC for conditional workflow design. Condition on runtime parameters.

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java

Upon project uploading, azkaban should be able to schedule the associated flow trigger. This is already achieved when project upload is done from ajax API call(#1631). This PR enables scheduling flow trigger when uploading project from restli endpoint.

Enable project uploading from restli endpoint schedule flow trigger

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm
azkaban-web-server/src/web/js/azkaban/view/schedule-panel.js

As described in #1822, CRON expression allows year to be specified. This pull request will expose year textbox in schedule panel, allow one time execution, and properly update the next 10 executions based on the CRON expression with a slightly improved descriptions. 
Sample screenshots:
One time execution
0 occurrences
A typical CRON expression

Exposing year on CRON expression and next 10 executions logic improvements

---

build.gradle

The task name `jacocoRootReport` has a conflict against our internal gradle system. So replacing a different one.

change jacoco task name

---

README.md

Just add the code coverage banner in README page as well as travis ci one. See what it will like in my Azkaban README page at https://github.com/kunkun-tang/azkaban/blob/master/README.md

add code coverage banner in readme

---

azkaban-common/src/main/java/azkaban/project/FlowTrigger.java
azkaban-common/src/main/java/azkaban/project/FlowTriggerBean.java
azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/test/java/azkaban/project/FlowTriggerTest.java
azkaban-common/src/test/java/azkaban/project/NodeBeanLoaderTest.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/FlowTriggerService.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm
test/execution-test-data/flowtriggeryamltest/flow_trigger_max_wait_min_zero_dep.flow
test/execution-test-data/flowtriggeryamltest/flow_trigger_no_max_wait_min_zero_dep.flow

When no dependency is defined for a flow trigger, it just works like a regular schedule - when the scheduled time comes, flow will be kicked off without waiting for any dependency. In this case, max wait min is not required.

make max wait min non-required when flow trigger's data dependency set is empty

---

azkaban-common/src/main/java/azkaban/executor/ExecutionReference.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executionspage.vm

A more complete cleanup: don't leave executions whose executor doesn't exist any more in some interim state like RUNNING - finalize them as FAILED.
----
To explain the problem scenario, it goes like this:
- if an executor is stopped gracefully (so that it has time to finish at least some shutdown hooks), it removes itself from the `executors` table 
- however, it's still possible that not all executions on that executor were properly finalized ie. status of each interrupted execution is set to one of FAILED/KILLED/SUCCESS
- when an executor is started, it adds itself into the `executors` table with an executor id that is the _next running number_
As a result, there can be executions with status RUNNING (for example) that would never be marked as FAILED, because the executor id of those …

Finalize running flows without matching executor

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectVersion.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java

The problem this PR targets to solve is detailed in https://github.com/azkaban/azkaban/pull/1803 
Drawback of previous design is detailed in https://github.com/azkaban/azkaban/pull/1841
New design:
1. Create a file in each project directory and write the size of the project to the file when the project is created. The project files are not supposed to change after creation. Touch this file each time the project is used. This way, we can have a more efficient LRU algorithm based on last access time, not creation time.
2. Maintain the total size of the project cache in memory to avoid the overhead of re-calculating it. The size shouldn't change too often. This way we can afford to run the check more frequently.
This PR implements part 1.

project LRU cache part 1

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/flow/ConditionOnJobStatus.java
azkaban-common/src/main/java/azkaban/flow/Node.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/ConditionalWorkflowUtils.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow3.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow4.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow5.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow6.flow

Users can use predefined macros to specify the condition on job status. For example, they can write `condition: one_success` for a job in the flow yaml file. And this job will run as soon as one of its parent jobs has succeeded. 
Below is the list of condition macros we will support:
- **all_success** (default)
- **all_failed**
- **all_done**
- **one_failed**: fire as soon as at least one parent has failed.
- **one_success**: fire as soon as at least one parent has succeeded.
- **one_failed_all_done**: fire when at least one parent has failed and all parents have finished.
- **one_success_all_done**: fire when at least one parent has succeeded and all parents have finished.
By default, the condition on job status is all_success.
The execution logic will change under different conditions. …

Condition on job status - Step 1

---

azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/test/java/azkaban/executor/FetchActiveFlowDaoTest.java

Ignore active executions with flow_data=null.
For error details, see https://github.com/azkaban/azkaban/pull/1833#issuecomment-406108760.
Cleaning these up manually would require too many changes, because `ExecutableFlow` object is used in many places.
Note that it's still possible to end up having this kind of rows in the DB if the application fails between creation of an execution id in `execution_flows` and uploading the data. See here:
https://github.com/azkaban/azkaban/blob/2be81ebe5d0a931eee828ca968090c728735ae71/azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java#L71-L74
I'm not sure if doing both inside a transaction is even possible, so I rather just avoid the NPE and log a warning about this corner case that should be rare.
This weakness was in place already …

Fix NPE in FetchActiveFlowDao

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

It was calling `log.error(Object message)`, so we didn't get a stack trace at all. For example this was logged, which is not too helpful: `ERROR [ExecutorManager] [Azkaban] java.lang.NullPointerException` (the value of `e.toString()`, as you can see).

Include error stacktrace in updater thread logging

---

azkaban-common/src/main/java/azkaban/executor/ExecutableNode.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow3.flow

By default, conditionOnJobStatus is set to ALL_SUCCESS. But it could cause potential issues for some old execution flows that don't have conditionOnJobStatus defined in the flow object when finalizing the flows. 
See https://github.com/azkaban/azkaban/pull/1868. This fix adds additional safety guard to the original fix.

Handle the case where ConditionOnJobStatus is null

---

az-reportal/src/main/java/azkaban/viewer/reportal/ReportalMailCreator.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/mail/DefaultMailCreator.java
azkaban-common/src/main/java/azkaban/executor/mail/MailCreator.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/mail/DefaultMailCreatorTest.java
azkaban-common/src/test/java/azkaban/utils/EmailerTest.java
azkaban-common/src/test/resources/azkaban/executor/mail/errorEmail.html
azkaban-common/src/test/resources/azkaban/utils/errorEmail2.html
azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java

This PR adds following information to the failure email template:
overall failed execution among last 72 hours' execution(e.x 3/25 failed)
past 72 hours execution tables(status, start/end time).
The motivation is to capture people's attention if the flow has been failing too many times recently.
Eg:

add past executions for failed flow in failure email

---

docs/howTo.rst
docs/index.rst
docs/plugins.rst

Migrate how-to and plugins doc sections to restructured text format using pandoc and manual editing.

Migrate how-to and plugins doc sections to restructured text format

---

.gitignore
tools/.gitignore

This is done to set up the python virtual environment at the root level
instead of the tools/ level.
This virtual environment will be shared by multiple submodules e.g.
tools and docs.

Move python related gitignore configs to the root level

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

the method updateDirSize is already verified by FlowPreparerTest#testSetupProject, so unit test is not needed.

when loading project dir metadata into memory, create the project size file if it doesn't exist

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopHiveJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsConstructHadoopTags.java

Hadoop/YARN has support for application tags, which MR/Spark can include in its job submission. This PR will add some azkaban metadata into MR config so MR can include them in the YARN application tags when it submits to YARN.

Inject azkaban configurations into hadoop application tags

---

azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java

Having `continue` as the last statement of a loop doesn't change anything.
----
I just happened to notice this, as I was trying to understand the meaning of `skipPastChecks` in this class.

Remove dead code in BasicTimeChecker

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

For example `setupExecutors()` logs a similar message. However fetching active executors is quick.
Loading the active flows is what happens after it, and it may take a while (last time in my case it took ~20s). It's comforting to see in the log what we're waiting for, when the server is starting.
----
As an example, some output from `ExecutorManagerTest`:
```
2018/08/08 13:36:53.900 +0300 INFO [ExecutorManager] Initializing multi executors from database.
2018/08/08 13:36:53.918 +0300 INFO [ExecutorManager] Loading running flows from database..
2018/08/08 13:36:53.918 +0300 INFO [ExecutorManager] Loaded 0 running flows
2018/08/08 13:36:53.940 +0300 INFO [ExecutorManager] QueueProcessorThread active turned true
...
```

Log about loadRunningFlows in azkaban-web startup

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java
test/execution-test-data/conditionalflowyamltest/conditional_flow7.flow

In conditional workflow design, we use scriptEngine to evaluate the condition provided by users. To prevent users from injecting malicious code inside the condition, we need to restrict the permissions like creating a new file or overwriting an existing one, or calling any system method.  
`AccessController.doPrivileged` can be used to reduce the permissions. Also `SecurityManager` needs to be enabled so that the access control will take effect.
Apart from this PR, we will also work on another PR to whitelist the syntax allowed for a valid condition.
Reference: https://wiki.sei.cmu.edu/confluence/display/java/IDS52-J.+Prevent+code+injection

Conditional workflow - Apply security restriction on arbitrary code in the condition

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java

We found that upload API doesn't return an error when a deleted project zip is uploaded. 
When a project is deleted, Azkaban just marks it to be inactive today. In this PR, we fix this issue by adding the check. 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.

check if project is removed while uploading

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java

- Add unit tests for execution dispatch failures
- Fix a minor bug in `ExecutorManager`: off by 1 in check of `azkaban.maxDispatchingErrors`:
`reference.getNumErrors() > this.maxDispatchingErrors`
->
`reference.getNumErrors() >= this.maxDispatchingErrors`
This makes sense to me: for example, if dispatching has failed 2 times and maxDispatchingErrors=2, don't try to dispatch for a 3rd time.

Add unit tests for execution dispatch failures & fix maxDispatchingErrors check

---

azkaban-web-server/src/main/less/base.less

The Flow Log positioning was broken, as you can see here:
This happens if the bar above (the one that has `Submit User`, `Duration` etc.) spans to multiple rows. Even one of them is enough to cause overflowing positioning, but the screenshot above demonstrates an extreme case where the tab is barely visible any more.
As a quick fix, I copied the same rules that are set for `div#graphView.container-fill` (you can find it right above the changed lines).
Screenshot after fix:
As you can see, the fix sets a fixed height to the log textbox, and as the screenshot shows it gets cut off if the window size is not as high. There must be a way to make the position relative properly.. If that is found, why not apply that better rule also for `div#graphView.container-fill`?

Fix flow log CSS

---

azkaban-common/src/main/java/azkaban/project/CronSchedule.java
azkaban-common/src/main/java/azkaban/project/FlowTrigger.java
azkaban-common/src/main/java/azkaban/project/FlowTriggerDependency.java

Flow trigger classes will be serialized and persisted in quartz tables and deserialized back. 
If serialVersionUID is not defined specifically, JVM would generate a default id in runtime which is dependent on compiler implementation, and and can thus result in unexpected  nvalidClassExceptions during deserialization if new deployment has different serialVersionUID from old deployment which has been persisted in db. 
Why choose those numbers(-1330280892166841227L ...)?
To be backward compatible since those are the serialVersionUID of first deployment of flow trigger classes and already have been persisted in database.

add serialVersionUID for serializable flow trigger classes

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerYamlTest.java
test/execution-test-data/basicflowwithoutendnode/basic_flow.flow
test/execution-test-data/embeddedflowwithoutendnode/embedded_flow.flow
test/execution-test-data/failbasicflowwithoutendnode/fail_basic_flow.flow

1. Fix the flaky test #testKillBasicFlowWithoutEndNode.
2. Reduce the sleep time to 0 in the test cases.
3. Rename FlowRunnerTestYaml to FlowRunnerYamlTest.
See more discussions in https://github.com/azkaban/azkaban/issues/1921

Fix flaky test and remove sleep time in FlowRunnerYamlTest.

---

azkaban-common/src/main/java/azkaban/flow/ConditionOnJobStatus.java
azkaban-exec-server/src/main/java/azkaban/execapp/ConditionalWorkflowUtils.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow2.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow3.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow4.flow
test/execution-test-data/conditionalflowyamltest/conditional_flow5.flow

Based on some users' feedback, the definition of `one_success` needs to be modified to: 
At least one parent job has succeeded and all the parent jobs have finished. 
They don't want their jobs to be canceled when the flow finally finishes. So we modify the definition to satisfy most common use cases. If needed in the future, we can add the support back for `one_success_cancel_rest `or name it differently.
Conditional workflow design: https://github.com/azkaban/azkaban/issues/1826

Conditional workflow - modify conditionOnJobStatus macros.

---

azkaban-web-server/src/web/js/azkaban/view/flow.js

Found a UI bug in #1797  , when we deploy latest master to our staging cluster. The observation of this bug is all execution history table is missing, like:
￼
The cause looks like a javascript or backbone grammar issue.
The fix quite simple.

fix PR 1797, a UI bug

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow3.flow

The intention of the original test is to verify if the condition is null, it should take the default value `all_success`. Modify the test case to make it clear and stable.

Fix flaky test of runFlowOnJobStatusConditionNull

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java
azkaban-web-server/src/web/js/azkaban/view/flow.js

#1797 introduced a bug that executions history cannot be displayed in `executions` tab give every project, like:
The issue is that javascript cannot find ${size}. The resolution is simple that we should add "size" to the context so that javascript is able to locate it.
After the change:
Tested in the staging server.

add "size" parameter during initializing a new page.

---

az-reportal/src/main/java/azkaban/viewer/reportal/ReportalMailCreator.java
azkaban-common/src/main/java/azkaban/alert/Alerter.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/mail/DefaultMailCreator.java
azkaban-common/src/main/java/azkaban/executor/mail/MailCreator.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/executor/mail/DefaultMailCreatorTest.java
azkaban-common/src/test/java/azkaban/utils/EmailerTest.java
azkaban-common/src/test/resources/azkaban/executor/mail/failedUpdateMessage.html
azkaban-common/src/test/resources/azkaban/utils/failedUpdateMessage2.html

Not evicting executions, sending an email instead.
This is to fix https://github.com/azkaban/azkaban/issues/1653 instead of https://github.com/azkaban/azkaban/pull/1654.
In practice it's always better to let the executions remain in running state if the assigned executor can't be reached. If azkaban-web is evicting executions without knowing the actual state, azkaban-web will start new scheduled executions and execution concurrency options (skip/pipeline) can be violated (if the same jobs are still running on an unreachable executor).

No eviction, alert email instead

---

docs/getStarted.rst

Change solo server start and shutdown scripts from: 
`azkaban-solo-start.sh`
`azkaban-solo-shutdown.sh`
To: 
`start-solo.sh`
`shutdown-solo.sh`

Update Getting Started doc to point to right scripts for Solo Server

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

The code had a recursion loop like this:
```
selectExecutorAndDispatchFlow
-> handleDispatchExceptionCase
-> selectExecutorAndDispatchFlow
-> ..
```
..with max depth of `activeExecutors.size()`
Iterative approach is easier to reason about, and is totally safe against `StackOverflowError`.
This is also preliminary refactoring to eventually allow configuring higher max for dispatching errors. Currently max dispatch attempts are capped by the total number of active executors (because each executor is only tried once at most). In the future I'd like to remove that limit and rely solely on the `MAX_DISPATCHING_ERRORS_PERMITTED` property.

 No recursion in dispatch error handling

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow3.flow

The previous fix in #1940 did not cover the case where all the jobs have finished early before the null condition takes effect. 
This fix will make sure the condition of jobC is set to null first and then evaluated.

Fix flaky test runFlowOnJobStatusConditionNull_2

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

Since hadoopSecurityManager.prefetchToken is synchronized, one thread might block all others from entering into this method when it's stuck fetching token. So it's important to prompt users about which step the job is stuck with.

add log before prefetching hadoop token

---

azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobpage.vm
azkaban-web-server/src/main/tl/flowsummary.tl
azkaban-web-server/src/web/js/azkaban/view/flow.js

Added the UI support for conditional workflow:
1. Added condition in job info page.
2. Added condition in flow summary page.
Previously, the condition was resolved and updated during the validation step. However, in order to show the original condition on UI page, the condition should remain unchanged until the execution time. Also for the condition of an embedded flow to show up on UI, I explicitly added the condition for flow object.
I also improved some logging messages during the evaluation of the condition.
Example-1 Condition defined on job info page: 
Example-2 No condition defined on job info page: 
Example-3 Condition defined on flow summary page: 
Example-4 No condition defined on flow summary page: 
Users might need to clear the browser cache to see the new UI change. …

Conditional workflow UI - add condition in job info and flow summary

---

az-reportal/build.gradle
build.gradle

Presto jdbc is required by presto reportal jobtype.

Add presto jdbc dependency for reportal module

---

az-reportal/build.gradle
build.gradle

This reverts commit b70ee970be437eed69db45353b3362efbbd15bf5.
Reportal has to work with internal version of presto JDBC instead of OSS version.

Revert "Add presto jdbc dependency for reportal module (#1959)"

---

azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerServiceTest.java

- Temporary fix for https://github.com/azkaban/azkaban/issues/1981
- Those slow tests took 5 & 6 seconds. There shouldn't be any sleeping in unit tests..

Ignore Flaky test FlowTriggerServiceTest & slow tests

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java

Allow more dispatch attempts than number of active executors.
The configuration key `azkaban.maxDispatchingErrors` is thus respected without an upper cap.
Normally azkaban-web shouldn't ever fail dispatching executions to executors as long as there are active executors available. This change allows configuring a limit that is in practice high enough to keep retrying forever, until at least one responsive executor appears.
----
NOTE: The handling of dispatch errors should be improved to distinguish between retriable & non-retriable errors.
The dispatch call itself is simple: it contains the execution id and username. I can't imagine a case where the request would be syntactically invalid/incompatible with the executor.
However, If executor returns a response with "error" in it, the …

Allow more dispatch retries

---

.travis.yml

...in order to reduce Travis CI build log from 4.5 MB to 1.6 MB. Travis does not like logs longer than ~4 MB.

Change `coveralls` logging level

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ActiveExecutors.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecJettyServerModule.java
azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecutorServerTest.java
azkaban-solo-server/src/test/java/azkaban/soloserver/AzkabanSingleServerTest.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java
docs/configuration.rst

This to simplify the code.
This requires users to migrate to `azkaban.use.multiple.executors=true` if not already using it.
After this change Azkaban will refuse to start if the property is missing or if it's set to false.
----
Note: a related pattern on executor side is the RemoteFlowWatcher vs. LocalFlowWatcher, which is used to track pipelined jobs & flows. It would be better to have just a single implementation (remote). However, that doesn't have anything to do with the multi-executor mode per se. Executor picks the FlowWatcher type based on whether the tracked execution is running on the same executor or a different one.

Always use multi-executor mode

---

azkaban-common/src/main/java/azkaban/executor/ActiveExecutors.java

It was only used by one class that's singleton itself, so no harm done for now. But this is how it should be, in case it will be injected to more than one instances later.

Make ActiveExecutors a singleton

---

azkaban-common/src/main/java/azkaban/flow/Node.java

The conditionOnJobStatus info of a Node was not stored in DB previously. When web server is restarted, the conditionOnJobStatus is not loaded correctly, resulting in the unexpected result in running conditional workflow.

Fix an issue in updating conditionOnJobStatus in DB.

---

azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java

The single server first starts executor server, then web server.
If web server startup failed, the single server process was left running, making it harder to realize that there was an issue in startup.
This PR makes it easier to spot a startup error by stopping JVM in case of a startup error.

Shut down single server if startup fails

---

azkaban-common/src/main/java/azkaban/executor/Executor.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java
azkaban-solo-server/src/main/resources/conf/azkaban.properties

In single server startup, set the executor active before starting web.
This fixes the following error:
```
2018/10/23 16:15:53.933 -0700 INFO [AzkabanWebServer] [Azkaban] Azkaban Exec Server started...
2018/10/23 16:15:53.933 -0700 INFO [ExecutorManager] [Azkaban] Initializing executors from database.
2018/10/23 16:15:53.934 -0700 ERROR [ExecutorManager] [Azkaban] No active executors found
Exception in thread "main" azkaban.executor.ExecutorManagerException: No active executors found
at azkaban.executor.ActiveExecutors.setupExecutors(ActiveExecutors.java:52)
at azkaban.executor.ExecutorManager.setupExecutors(ExecutorManager.java:243)
at azkaban.executor.ExecutorManager.initialize(ExecutorManager.java:156)
at azkaban.executor.ExecutorManager.start(ExecutorManager.java:181)
at …
```

Fix single server startup (by activating the executor)

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java

We ran into a bug in the production environment. Users' jars cannot override default pig libraries. It was found that AZ always adds pig additional jar if pig job type defines it under plugin.properties. The fix is straightforward. If a user defines the property, we use it directly by not including system default settings.
To be tested in the staging environment.

Only incorporate user pig additional jar setting or system's but not both

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java

If a flow is scheduled with `concurrentOption=skip`, it's perfectly normal that triggering of a schedule is skipped. This PR changes such ERROR lines in the server log to INFO level.
On a general level, in my opinion ERROR level should be only used for platform errors, ie. when Azkaban fails to do something that it promises to be able to do. If this rule holds, it will be easier to monitor that Azkaban is working correctly by checking that server logs don't contain errors.
Before:
```
2018/10/23 13:41:14.337 +0300 INFO [ExecuteFlowAction] Invoking flow test-project.test-flow
2018/10/23 13:41:14.338 +0300 ERROR [TriggerManager] Failed to do action Execute flow test-flow from project test-project for Trigger Id: 0, Description: Trigger from triggerLoader with trigger condition of …
```

Don't log an ERROR for skipped scheduled executions

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java

1st commit shows the problem:
When trying to execute a cleaned project version, an exception is thrown that says that hash code comparison failed.
2nd commit improves the error message in case of trying to read a cleaned (deleted) version. It also fails _faster_ (don't try to generate a hashcode from 0 chunks).
\+ Move `project.version.retention` to `Constants.java`.

Improve error message for a cleaned project version

---

azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/RunningExecutionsUpdaterTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java

Problem scenario:
1. An executor is stopped [1]
2. Executor is removed from DB table: `executors` [2]
3. Updater thread tries to get an update of an execution that was running on the removed executor
- Request fails as executor is not running any more
- Updater sends alert emails about unresponsive executor
Fix (this PR):
- **If update call fails against an executor, check from the DB directly if the executor still exists or not. If not, finalize the execution.** 
- If executor still exists (or couldn't be checked), do as before, ie. periodically alert about unresponsive executor.
----
[1] This can be a graceful shutdown or a sudden crash, doesn't matter
[2] Executor can be removed from the DB in the following ways
- Graceful shutdown: executor removes itself
- Unexpected shutdown – admin …

Finalize execution if executor doesn't exist

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

Some users are relying on the json response from `fetchexecflow` API call to generate some report. They would like the condition to be excluded in the json response if it is null.  
```
jasun-mn1:~ jasun$ curl -k --data "session.id=<SESSION_ID>&ajax=fetchexecflow&execid=25990" http://localhost:8081/executor
{
"project" : "az_acceptance_test",
"updateTime" : 1541794379559,
"type" : null,
"attempt" : 0,
"execid" : 25990,
"submitTime" : 1541794369342,
"nodes" : [ {
"nestedId" : "IntegrationTest",
"in" : [ "IntegrationTest_jobCommand" ],
"startTime" : 1541794379498,
"updateTime" : 1541794379543,
"id" : "IntegrationTest",
"endTime" : 1541794379536,
"type" : "noop",
"attempt" : 0,
"status" : "SUCCEEDED"
}, {
"nestedId" : "IntegrationTest_jobCommand",
"startTime" : 1541794369455,
"updateTime" : …
```

Exclude condition in json response when condition is null.

---

azkaban-web-server/src/web/js/azkaban/util/flow-loader.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
azkaban-web-server/src/web/js/azkaban/view/svg-graph.js

Improvement:
-The new menu options on Flow, Flow Execution and Schedule/Execute pages prevent users from having to unfold deeply nested flows by clicking one by one.
-Users will be able to browse flows and enable or disable job executions more easily.
-Options are shown and work on projects using both flow 1.0 and flow 2.0

New 'expand/collapse all flows' menu options on flow views

---

azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-common/src/test/java/azkaban/utils/FileIOUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectVersion.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java

a race condition scenarios could happen when multiple azkaban executor process are running: 
It's possible when two azkaban executor process perform deletion in the same azkaban project dir even when one executor is inactive. E.g, flow run on any executor by using useExecutor label. 
If so, the list of azkaban project dir in memory(installedProjects) kept by azkaban executor process, will be out of sync from what's on the disk. 
Another case is race condition between one executor process is deleting a project dir while another executor process is creating execution dir based on the project dir.
This PR 
1. removes the installedProjects from executor. So every time a project needs to be downloaded, a scan of every project dir and calculation of total disk usage sum will be done to decide …

Project dir cache enhancement

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

This PR: 
1. adds more logging and standardize existing logging for each token prefetching methods so that we know prefetching from which service is stuck.
2. removes "synchronized" for doPrefetch(HadoopSecurityManager_H_2_0#doPrefetch). Current design makes it hard to debug which token service the job is stuck with fetching token. Since HadoopSecurityManager_H_2_0 is shared by all jobs in the executor, if one job is stuck with fetching token with a problematic token service, all other jobs will be blocked from entering into this synchronized method. It's impossible to infer which token service jobs are stuck with from job logs as they are just waiting for one job to finish fetching token.

Refactor hadoop token fetch logic follow-up

---

azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackManager.java

Could you please accept this fix of issue #1947?

#1947 wrong 'Host' header in http callbacks deleted.

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopHiveJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopShell.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSparkJob.java
azkaban-common/src/main/java/azkaban/flow/CommonJobProperties.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

Issue: when a user tries to kill a Hadoop/Spark job within an embedded flow the application looks for a log file using the following name pattern "_job.<exec_id>.<job_id>.log" no matter whether the job was embedded or not. But actually if a job is inside an embedded flow the name format used to create its log file is:  "_job.<exec_id>.<parent_flow>._.<job_id>.log"
So trying to kill a job inside an embedded flow before would fail because of the log file name mismatch.

Fix mismatch in name of job log files

---

az-core/src/main/java/azkaban/Constants.java
az-jobsummary/src/main/java/azkaban/viewer/jobsummary/JobSummaryServlet.java
az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecutionChecker.java
azkaban-common/src/main/java/azkaban/trigger/builtin/KillExecutionAction.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java
azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java
azkaban-solo-server/src/test/java/azkaban/soloserver/AzkabanSingleServerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/HistoryServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/JMXHttpServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatsServlet.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzSchedulerTest.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

This is the initial PR for AZ New Dispatching Logic #2038
A new module called `ExecutionController` is created to implement the new polling model on the web server side. When `azkaban.poll.model `is enabled, `ExecutionController` will be injected into `AzkabanWebServer`, otherwise `ExecutorManager` will be injected. Both of the two classes implement `ExecutorManagerAdapter`. In this way, we can develop the new model independently without affecting the current logic and switch between the two models easily. The new `ExecutionController` will ultimately replace `ExecutorManager` in the future.
Todo: 
implement the methods in `ExecutionController`. 
Enable the jmx/stats for `ExecutionController`.
Please see more details in the design description.

AZNewDispatchingLogic - Create ExecutionController module

---

azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java

This PR exposes hit ratio of a project dir cache(https://github.com/azkaban/azkaban/pull/1848) as metrics. Cache miss counts as a flow being setup without downloading its project zip, otherwise it counts as a cache hit.

Expose hit ratio of project dir cache as metrics

---

az-jobsummary/src/main/java/azkaban/viewer/jobsummary/JobSummaryServlet.java
az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecutionChecker.java
azkaban-common/src/main/java/azkaban/trigger/builtin/KillExecutionAction.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/HistoryServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/JMXHttpServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatsServlet.java

When trying to deploy the new azkaban-distribution internally, we found the issue:
```
2018/12/05 04:12:27.976 +0000 WARN [log] [Azkaban] failed azkaban.viewer.jobsummary.JobSummaryServlet-108774737: java.lang.NoSuchMethodError: azkaban.webapp.AzkabanWebServer.getExecutorManager()Lazkaban/executor/ExecutorManager;
2018/12/05 04:12:27.976 +0000 WARN [log] [Azkaban] failed azkaban.viewer.pigvisualizer.PigVisualizerServlet-1897940586: java.lang.NoSuchMethodError: azkaban.webapp.AzkabanWebServer.getExecutorManager()Lazkaban/executor/ExecutorManager;
```
The method name `getExecutorManager` was changed in #2039 and not found by some plugins.
In this PR, temporarily revert the method name back to unblock the release.
Need to further work on two things later:
1. check the azkaban-distribution …

fix getExecutorManager method not found.

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectmodals.vm

The auto formatting performed in #1397 led to an issue with the validator fix link in the upload modal, where it's appended to the target parameter and thus breaks the link. This commit adds the missing space back.

Fix issue with validator fix link in upload modal

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatsServlet.java

As part of the new design in #2038, we want to remove the cache from web server so that it can be stateless. This is also an important step towards the ultimate goal of web server HA.
In this PR, we replaced fetching from cache to direct DB calls in the new module `ExecutionController`. Also created new DB queries for performance improvement. 
Other than that, most of the functionalities remain the same as those in `ExecutorManager`.

AZNewDispatchingLogic - Switch fetching running flows from cache to DB.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java

Bug description:
For an existing project dir on executor, its file count file will be created only when azkaban executor is loading all projects before cache purging(https://github.com/azkaban/azkaban/pull/2032) when project cache size limit feature is enabled. If not enabled, file count check will try to read from the non-existing file count file causing dispatch failure. 
Fix:
1. File count check would populate file count file when it doesn't exist. 
2. File count check would only be performed when project cache size limit is enabled.
1 would fix the bug, 2 would reduce the overhead of file count check when the feature is not enabled.

File count check fix

---

azkaban-common/src/main/java/azkaban/executor/ExecutableJobInfo.java
azkaban-common/src/test/java/azkaban/executor/ExecutableJobInfoTest.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobhistorypage.vm

Issue: when a user tried to access a Job page from the Job History page the application was throwing the error below. This happened only for jobs within an embedded flow.
Also the link to the job's flow in this page was loading the root flow. This PR sets that link to refer to the immediate flow which would be a more expected action here.

Fix access to flow and job definition from Job History page

---

azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerYamlTest.java

Disabled two flaky tests to unblock travis build:
testDispatchFailed (See discussion in #2064 )
testFailBasicFlowWithoutEndNode

Disable flaky tests.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

In the new AZ dispatching design #2038, one important change is to switch from pushing model to polling(pulling) model. Instead of web server selecting an executor and pushing new execution to that executor, now web server will just insert the new executions into DB queue and then executors will take turns to poll new executions from DB.
The PR implements the polling model for submitting new executions. Tested on solo server. Plan to test it on multi-executor mode later.

AZNewDispatchingLogic - Submit flow in Polling Model

---

azkaban-web-server/src/web/js/azkaban/view/flow-execution-list.js

In the Flow Execution page, Job List tab all FAILED jobs are shown by default now. 
-If they are embedded their parent flows are expanded.
-Only flows containing FAILED jobs will be expanded.
This is especially helpful with deeply nested flows because users won’t have to manually unfold each flow to access the logs of FAILED jobs.

Improvement of user usability

---

azkaban-web-server/src/web/js/azkaban/util/flow-loader.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js

Removes graph centering event after expanding/collapsing flows at node level (it makes sense to keep it at the graph level).
In most cases the centering event causes a zoom out so users need to zoom in the graph again to return to previous view.

Removes graph centering after expanding/collapsing flows

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFinalizer.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java
azkaban-common/src/main/java/azkaban/executor/selector/ExecutionControllerUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java

In the new AZ dispatching design #2038, we no longer maintain any cache on web server side. Instead, we fetch all the running flows/ queued flows info from DB directly.
When user cancels a flow, we check DB to see if the flow is already dispatched to an executor. If yes, the executor will be called to cancel the flow. If the flow is still queued in DB, we finalize the flow and update its status in DB.
Testing:
1. Verified integration tests are passing on solo server.
2. Modified the polling interval and verified different canceling scenarios where a flow is already dispatched and is queued in DB.

AZNewDispatchingLogic - Cancel flow

---

azkaban-common/src/test/java/azkaban/utils/UtilsTest.java

The cron test failed because of the hard-coded calendar year 2018. Changed it to get the current calendar year using `Calendar.getInstance().get(Calendar.YEAR)` so that it won't fail when the new year comes.

Fix cron test failure due to new year.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java

In the new AZ dispatching design #2038, the web server will no longer ping executors to get flow status update and alert users when a flow finishes. 
With the new changes in this PR, executors will be responsible for sending alerting notifications instead of the web server.
Verified the changes on solo server.

AZNewDispatchingLogic - Send notification from executor when a flow finishes

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

During deployment, we call `activate` API to set the new executors to active in DB and `deactivate` API to set the old ones to inactive.
With the new change in #2038 design, the new executors should start polling from DB after they are set to active and the old executors should stop polling from DB after set to inactive. 
Todo:
If we want to support `useExecutor `flow parameter in the future, this behavior has to be modified. A new column called `use_executor` will be added to the execution_flows table. Both old and new executors will poll from execution_flows table. The old executors can only poll executions with `use_executor == <polling_executor_id>` while new executors can poll executions with `use_executor == <polling_executor_id> or use_executor is null`.

AZNewDispatchingLogic - Handle active/inactive executors

---

azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/AzkabanProcess.java
azkaban-common/src/main/java/azkaban/jobExecutor/utils/process/ProcessFailureException.java

There have been times when killing an execution has taken over an hour to complete without an apparent reason to do so. This PR helps to debug this type of issues by adding logs to detect kill command failures.
Also we are removing a piece of code that was not in use and was potentially adding a bit of delay to the killing process. The functionality of this piece of code was verified on a test server as well as in solo server. It was repeating logs that are already in the job logs.

Logs kill command failures and removes unused code

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

This PR implements the failure detection for executors in the new AZ dispatching design #2038.
If an executor is shut down and removed from DB, any remaining running flows on that executor will be finalized.
Web server will periodically ping executors and see if they are still alive. If not alive, failure count for that executor will increase. If the failure count reaches max count, alert emails will be sent to AZ admin. AZ admin can decide if that executor should be removed from DB and take action accordingly.

AZNewDispatchingLogic - Executor failure detection

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFinalizer.java
azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerYamlTest.java
test/execution-test-data/alertflow/alert_flow.flow
test/execution-test-data/alertflow/alert_flow.project

In AZ new dispatching design, executors will be responsible for alerting on Flow status change instead of the web server. 
When a user chooses `First failure` in the `Notification` option when executing the flow, it is expected that a notification email will be sent immediately after any job fails and the flow status changes to FAILED_FINISHING. This PR consolidates the code and enables this `alertOnFirstError` option in the new AZ dispatching design.
See more details in design #2038

AZNewDispatchingLogic - Enable alertOnFirstError

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Not only another flaky test fix – this is an actual bugfix.
Split to commits like this:
1. Demonstrate kill by sla bug  …
- This makes FlowRunnerTest2.testFlowKilledByJobLevelSLA fail every time
1. Fix kill by sla bug with a wrapping sync block
- This makes FlowRunnerTest2.testFlowKilledByJobLevelSLA pass every time (but it's 1s slower, obviously)
1. Remove extra sleep that was used to reproduce kill by sla bug
- Keep the fix but remove extra sleep
I expect commits to be squashed when merging this PR :)
First of all, `FlowRunner#killBySLA` is the method under test:
https://github.com/azkaban/azkaban/blob/abdf69127d11cb7d0977ec1c246c90653fae9abc/azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java#L843-L846
The relevant actions this does is set:
- inside a synchronized block: …

Fix kill by sla bug

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java

It's totally normal that `.jor` doesn't exist in the DB if there's no override, not worth logging on WARN level.
https://github.com/azkaban/azkaban/blob/cefb48346c21c3163e4fed0ebd8e5070c3f2c227/az-core/src/main/java/azkaban/Constants.java#L54-L55

Disable noisy logger "property x.jor is empty"

---

azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java

Squashing the lowest hanging fruit from https://github.com/azkaban/azkaban/issues/2114.
1st commit: Prove that sendEmailLatch is not incremented in testProcessTermination
- Adding this assertion makes the test fail
2nd commit: Fix mocking of overloaded method -> test passes quickly now
It's actually best to leave the new assertion on CountdownLatch in place even though the problem was fixed. Because it will make the test fail instead of just being slow & succeeding, if the bug with skipping CountdownLatch is ever introduced again.

Optimize slow test TriggerInstanceProcessorTest#testProcessTermination

---

az-core/src/main/java/azkaban/utils/MemConfValue.java
az-core/src/main/java/azkaban/utils/Utils.java
az-core/src/test/java/azkaban/utils/MemConfValueTest.java
azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java

Users shouldn't need to go view Azkaban source to find out why project upload failed in this kind of a case (from azkaban mailing list):
> I am trying to upload a zip project file and getting this error, could not figure out the reason.
> Users were getting java heap space error very often and by mistake while trying to solve it I have introduced the "job.max.Xmx=" twice in azkaban.properties, one of them empty.
```
Installation Failed.
For input string: "" 
2019/01/24 13:25:02.852 -0300 INFO [ProjectManagerServlet] [Azkaban] Upload: reference of project test_project_for_delete is 101056896
2019/01/24 13:25:02.853 -0300 INFO [ProjectManagerServlet] [Azkaban] Uploading file lte.zip
2019/01/24 13:25:02.853 -0300 INFO [AzkabanProjectLoader] [Azkaban] Uploading files to …
```

Unify jvm memory settings validation & improve upload error message

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobhistorypage.vm
azkaban-web-server/src/web/js/azkaban/view/job-history.js

Fixes a pagination issue on Job History page where it would show an additional empty page if the last page was full. For example:
-with page size 10 and 30 elements it would show 4 pages with the last one being empty.
Simplifies implementation by delegating common pagination functionality to [https://github.com/josecebe/twbs-pagination](https://github.com/josecebe/twbs-pagination) jQuery pagination plugin instead of doing it manually.
With this change we are still loading the entire page every time a user interacts with the pagination controls. Ultimately we want to create an API endpoint that returns pages as data and that we only need to update the view with the new data, but this will not be done now because we are planning to redesign existing APIs soon.

Refactor and bug fix on Job History page pagination

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

In this PR changes are done to add an AJAX endpoint which will provide the information if the user have WRITE access to a given project. This API will be useful for **TuneIn** which is a part of **Dr.Elephant**. Currently, TuneIn show many details like suggested parameters for the job, algorithm etc on the job page and the user would be able to modify these parameters. But since these properties are used by Azkaban(one of the supported Workflow managers by Dr.Elephant), so the user must be authorized to change these properties. For this purpose, Dr.Elephant will call this API with **session_id**(provided by Azkaban after successful authentication) and **project_name** as query params.
This API will have Azkaban user session_id and the project name as query params and as a result a Boolean …

Adding an AJAX endpoint to check if user has WRITE access to a given respective project

---

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecutorServlet.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This PR makes deactivation process block until all flow preparation work finishes.
When deploying new executor, old running executor will be deactivated before new one is activated and only one executor is allowed to delete/hard-linking project directories to avoid race condition(see https://github.com/azkaban/azkaban/pull/2130). So to make deactivation process block until flow preparation work finishes guarantees the old executor won't access FlowPreparer#setup after deactivation.

block deactivating executor until all flow preparation work completes

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/ProjectCacheHitRatio.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java
azkaban-exec-server/src/test/java/azkaban/metrics/ProjectCacheHitRatioTest.java

This PR replaced old project cache hit ratio metrics impl. with a new one which only keep tracks of last 100 cache accesses' hit ratio instead of all past access since Azkaban executor starts. In this way, this metrics is more sensitive to project cache setting change (e.g, cache size is changed on the fly) since hit ratio won't be offset by too much old historical data.

Project cache hit ratio metrics enhancement

---

build.gradle

https://github.com/azkaban/azkaban/pull/1231 configured gradle to parallelize test runs. However, in practice enabling parallel tests actually makes the full azkaban test run slower on some machines (at least mine & @burgerkingeater's machine). There hasn't been any noticeable speed-up on Travis. Hence, changing back to no parallel tests.
Instead of removing entirely, keeping the setting with value 1 & adding a comment to warn about it, so that it will be seen instead of enabling it again in the future without proper validation.
----
`./gradlew cleanTest test` took 3m 42s on my machine. That seemed way too much. I was running tests of each module in IDEA and for sure the total time wouldn't be that long. It lead to think that the command-line gradle runner must be doing something that's …

Optimize gradle build time

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectCacheCleaner.java
azkaban-exec-server/src/test/java/azkaban/execapp/ProjectCacheCleanerTest.java

Currently project cache size is an absolute value indicating how large the project cache could be in MB. This PR makes it a percentage-based value which is a percentage of total size of the disk partition where project cache belongs to. So when disk partition is manually resized, this property won't need to be adjusted.
This PR also:
1. adds more detailed logging
2. use Set instead of List to keep the project directories to delete to guarantee no duplication.

Percentage-based project cache size

---

az-core/src/main/java/azkaban/metrics/MetricsManager.java
az-core/src/test/java/azkaban/metrics/MetricsTestUtility.java
azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java
azkaban-common/src/test/java/azkaban/metrics/CommonMetricsTest.java

We should leverage metrics data type available in https://metrics.dropwizard.io/3.1.0/getting-started/ as much as possible.

Replace Counter with AtomicLong for counter-based metrics

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-db/src/main/sql/create.execution_flows.sql
azkaban-db/src/main/sql/upgrade.3.68.0.to.3.69.0.sql
azkaban-db/src/main/sql/upgrade.3.69.0.to.3.70.0.sql

"flowPriority" is one of the execution options of a flow, which only takes effect if set by an Azkaban admin. By default all flows have a priority of 5 but if a bigger number is specified from the UI that flow will be dispatched for execution first.
With the new Dispatching Logic(#2038) setting a high "flowPriority" means that flow will be polled first by executors.
Note that it has been said "polled first" not "executed first". On the executor server there is a queue to hold executions when the maximum number of threads availables/setup to run flows is reached. This queue is NOT a priority queue.
To implement this feature for the new Dispatching Logic, a new column "flow_priority" needs to be added to table "execution_flows" to speed up access to this info (currently flowPriority is …

Implement "flowPriority" (at the time of polling) feature for new Dispatching Logic

---

azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java
azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-common/src/test/java/azkaban/jobExecutor/JavaProcessJobTest.java

(relates to issue https://github.com/azkaban/azkaban/issues/1566)
Classpath improvements for the `javaprocess` job type:
- Tests for `javaprocess` job with empty or non-existing `classpath` property
- Fail the job with a helpful message if there's nothing to add as `-cp` arg (instead of trying to run `java` command that's doomed to fail)
- If `classpath` property exists, but has an empty value, try to scan the folder for `.jar` files (as was already the case when `classpath` property doesn't exist)
- Improve error message when `ProcessJob` setup fails: print the top-level exception message first, not the cause of it
- For some reason `getClassPathParam()` method wasn't being used. Now it is used again, with a small modification, though.

javaprocess classpath improvements

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerYamlTest.java

This fixes a couple of reasons for FlowRunnerYamlTest failiing intermittently.

Flakey FlowRunnerYamlTest

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

This allows job names to have spaces in them (but not single quotes).

JobRunner: Quote JVM args

---

build.gradle

Reverts azkaban/azkaban#2113.
Quote from @ypadron-in 
This change exposed unit tests failures when tests are run using MacOS's console with ./gradlew cleanTest test command. We will revert it temporarily until we fix the tests.
Failing tests: createErrorEmail, createFirstErrorMessage, createSuccessEmail and testDispatchMultipleRetries

Revert "Optimize gradle build time"

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java
azkaban-web-server/src/test/java/azkaban/scheduler/QuartzSchedulerTest.java

This PR refactors quartz scheduler:
1. Remove unused methods.
2. Reduce visibility of methods that are only used in unit tests.
3. When pause/resume/unschedule a non-existing job, make them return false instead of throwing exception to distinguish this case from exceptional cases. Same apply for schedule an existing job.

Quartz scheduler refactor

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/FlowTriggerServiceTest.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java

Given ExecutorManager is no longer used in new dispatch logic and replaced with ExecutionController(https://github.com/azkaban/azkaban/pull/2039), replace it with ExecutorManagerAdapter  in flow trigger-related code.

Change ExecutorManager to ExecutorManagerAdapter in Flow Trigger

---

azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js

**overrideSuccessEmails** and **overrideFailureEmails** have mixed up its values
`   var overrideSuccessEmails = this.model.get("failureEmailsOverride");
var overrideFailureEmails = this.model.get("successEmailsOverride");
`

overrideSuccessEmails and overrideFailureEmails have mixed up its values

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Motivation
1. Execution dir should be cleaned up when flow finishes, and the case where azkaban admin needs to check execution dir is unlikely to happen.
2. When disk usage exceeds the defined limit, project dir is cleaned from project cache, but its corresponding execution dir would still consume disk until it is deleted. Retention being too long will extends the duration of disk pressure.

Reduce execution dir retention to 1 min 

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/FlowTriggerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/restli/java/azkaban/restli/ProjectManagerResource.java

When scheduling/unscheduling fails(E.g quartz database connection issue), fail fast to avoid inconsistent situation where unscheduling last version of flow trigger fails, but project with new version of flow trigger gets uploaded successfully.

When flow trigger fails to be scheduled/unscheduled, throw exception to terminate the subsequent steps

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectHandlerSet.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java

Before, users couldn't know for sure if a certain project existed or not.
With this changes getProjectId api will either return:
-if project “ABC” exists
```
{
"project" : "ABC",
"projectId" : 29
}
```
-if project “ABC” doesn't exist (either never existed or was deleted)
```
{
"project" : "ABC",
"error" : "Project ABC doesn't exist."
}
```
Follow up work: Verify permissions to access project id information.

getProjectId api no longer returns IDs of deleted/inactive projects.

---

azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java

When dynamically generating job link url, we need to fetch application id from the log.
If the log data length is 0, meaning there is no new data, we don't need to search for application id again from the log data. 
This is related to PR #1695

Fix dynamic job link url

---

azkaban-db/src/main/sql/create.executors.sql
azkaban-db/src/main/sql/create.projects.sql

The UNIQUE INDEX declarations coincide with the PRIMARY KEY, which is
already constrained to be unique.

Remove redundant UNIQUE INDEX declarations in CREATE TABLE statements

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorUtilsTest.java

For some use cases, such as Gobblin as a Service, there is a requirement to be able to run a higher number of concurrent runs for a workflow than the default value of 30. Azkaban configuration parameter azkaban.max.concurrent.runs.oneflow(introduced in https://github.com/azkaban/azkaban/pull/1590) can be set to change the default for an Azkaban cluster, but this will affect all flows running on the cluster. New Azkaban configuration parameter azkaban.concurrent.runs.oneflow.whitelist will allow specific flows to have a higher (or low) max concurrent number of runs. The value lists the project, flow and number for each flow. Flows are semicolon separated, and each field for a flow is comma separated. The value has the format: "<project name 1>,<flow name 1>,<num concurrent>;<project name …

Add whitelist for specifying max number of concurrent runs for flows

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/main/less/project.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/style.vm
azkaban-web-server/src/web/js/azkaban/view/project.js

-  **manager?ajax=setFlowLock** will lock or unlock a flow. 
`curl -X POST --data "session.id=<session id>&ajax=setFlowLock&isLocked=true&project=<project name>&flowName=<flow name>" http://<web server>/manager
{
"isLocked" : true,
"project" : "<project name>",
"projectId" : 2,
"flowId" : "<flow name"`
-  **manager?ajax=isFlowLocked** will return if a flow is locked or unlocked.
`curl -k --get --data "session.id=<session id>&ajax=isFlowLocked&project=<project name>&flowName=<flow name>" http://<web server>/manager
{
"isLocked" : true,
"project" : "<project name",
"projectId" : 2,
"flowId" : "flow name"`
A locked flow cannot be executed or scheduled. The caller of the API must have ADMIN privileges to lock the flow. The lock will persist across project uploads.
Flow page for a locked flow: …

Add APIs for locking a flow

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/utils/OsCpuUtil.java
azkaban-common/src/main/java/azkaban/utils/OsMemoryUtil.java
azkaban-common/src/main/java/azkaban/utils/SystemMemoryInfo.java
azkaban-common/src/test/java/azkaban/utils/OsCpuUtilTest.java
azkaban-common/src/test/java/azkaban/utils/OsMemoryUtilTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Continues the work started in PR #2038 by providing executors the ability to check their capacity before taking new executions. Capacity is defined as: 
-availability of flow threads at the time of polling (don't enqueue executions in the executor)
-free physical memory available (in Gigabtyes)
-cpu usage (in percentage)
Each criteria can be enabled or disabled through properties in azkaban.properties file. Executors will only poll a new execution when all the configured criteria are satisfied.
**Configurable properties**:
`azkaban.polling_criteria.flow_threads_available` - possible values true or false. if true executors can poll a new execution only when there are flow threads available.
`azkaban.polling_criteria.min_free_memory_gb` - any value > 0. At least this amount of free physical …

Implement ability to check executor's capacity before polling for new Dispatching Logic

---

azkaban-web-server/src/web/js/azkaban/view/flow-execution-list.js

For not-so-familiar users it's been confusing to find where the job logs are.
I don't see any reason to use "Details" as a label for the link that points to job log (the latest attempt's log).
I'm still keeping the original table header "Details". I guess that's ok.. For "flow" type nodes there is never log link currently. Maybe something else than just a log link might be added in the future to this column, IDK..
So, those [Log](#log) links on the right were previously called [Details](#details).

Rename job logs link: Details -> Log

---

azkaban-web-server/src/web/js/azkaban/util/flow-loader.js

Job log links have been only available in the `Job List` tab of an `Execution`, not on the `Graph` tab.
However, `Graph` is the landing tab for an `Execution`, and the easiest place to see the overall situation. It would be convenient to access job logs directly from the Graph by right-clicking a job.
This PR implements that.
Now the context-menu (with right-click) includes links to job logs 🎉:
----
^ It works the same inside sub-flows (using nested ID so the URL is correct, too)
----
^ Jobs that haven't been run yet don't have log links
----
^ Disabled jobs don't have log links
----
^ In Flow view (not an Execution) jobs don't have log links

Add links to job logs in job context menu in execution graph

---

build.gradle

"Revert "Optimize gradle build time (#2113)" (#2163)" This reverts commit 3cda04e3.
> I guess we could set maxParallelForks = 1 again.
, said @ypadron-in at https://github.com/azkaban/azkaban/pull/2163#issuecomment-491461276

Set maxParallelForks = 1 again

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java

This is related to PR #1695 
The NPE happens when the job link has expired for a job inside an embedded flow.
To fix that, call `getExecutableNodePath` instead of `getExecutableNode` to get the job inside an embedded flow.
Verified the fix on localhost.

Fix NPE in dynamically generating job link url.

---

azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/JobCallbackUtilTest.java

This can be useful for example when formatting a callback payload that contains some title & more detailed message, and both want to include the job status, or any other provided token.

Job callback to support multiple occurrences of the same token

---

azkaban-common/src/main/java/azkaban/user/FileWatcher.java
azkaban-common/src/main/java/azkaban/user/UserUtils.java
azkaban-common/src/main/java/azkaban/user/XmlUserManager.java
azkaban-common/src/test/java/azkaban/user/FileWatcherTest.java
azkaban-common/src/test/java/azkaban/user/XmlUserManagerTest.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

- `XmlUserManagerTest` is almost instant now, < 1s for sure
- Refactored `UserUtils`: extracted real file watching code to a new class: `FileWatcher`
- `FileWatcherTest` takes 3-4s
-> Better separation of concerns & runs quicker in total
For background, comments in https://github.com/azkaban/azkaban/pull/2240

XmlUserManagerTest to use mocks & avoid sleeping

---

azkaban-common/src/main/java/azkaban/project/ProjectManager.java

Add logs to ProjectManager initialization to better understand a consistent latency at web server startup on some of our clusters. 
The suspicions are that this is related to the existing number of project and flows and the fact that currently all active projects and their flows are loaded into memory at web server startup.

Add logs to ProjectManager initialization at web server startup.

---

azkaban-common/src/test/java/azkaban/user/FileWatcherTest.java

- The test works fine locally, however, it fails on test servers,
possibly due to permission issues
- Using tried and tested method to create PATH which works in other
tests.

FileWatcherTest fix

---

azkaban-common/src/test/java/azkaban/user/FileWatcherTest.java

The failure on [Travis](https://travis-ci.org/azkaban/azkaban/builds/539101458?utm_source=github_status&utm_medium=notification) was:
```
azkaban.user.FileWatcherTest > registerAndTake FAILED
java.lang.AssertionError: expected:<1> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at azkaban.user.FileWatcherTest.registerAndTake(FileWatcherTest.java:75)
```
Which is for line 75:
https://github.com/azkaban/azkaban/blob/505d2847eb88f6dae09fc91127dabc8711a9c391/azkaban-common/src/test/java/azkaban/user/FileWatcherTest.java#L74-L75
This is familiar from previous life where we had a multi-threaded test. That test was working because it retried …

Fix flaky FileWatcherTest

---

azkaban-common/src/main/java/azkaban/user/XmlUserManager.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
azkaban-solo-server/src/test/java/azkaban/soloserver/AzkabanSingleServerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

Bug reported by @jamiesjc: https://github.com/azkaban/azkaban/pull/2244#issuecomment-497119712
Now AzkabanSingleServerTest covers the reflection-created user manager.
----
Please merge https://github.com/azkaban/azkaban/pull/2259 soon so that Travis build can succeed.

Fix XmlUserManager bug: add back the mandatory constructor

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

Loading the Flow Execution page of an execution of a flow that doesn't exist anymore (because an update to a project deleted it for example) causes a NullPointerException because we ask whether that non-existent flow is locked or not to enable/disable "Prepare Execution" button in the view.
More details about "locking flows" feature in #2210.

Handle non-existent flows when asking for isLocked property on Flow Execution page load.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This PR moves execution directory cleanup out from CleanerThread, and deletes execution directory on flow finishing. The motivation is to make sure that execution directory gets deleted on time without leaving any orphan disk-consuming dirs. Previously CleanerThread periodically traverses every execution dir periodically and deletes any directories which haven't been modified for some configurable period. The logic is cumbersome and error-prone as it requires checking against shared data structure like running flows to make sure it's not deleting execution directories which are in use.

Delete execution directory on flow finishing

---

az-core/src/main/java/azkaban/Constants.java
az-core/src/main/java/azkaban/utils/Props.java
azkaban-common/src/main/java/azkaban/server/session/SessionCache.java
azkaban-common/src/test/java/azkaban/server/session/SessionCacheTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/restli/java/azkaban/restli/UserManagerResource.java

This PR adds a configurable upper limit on the number of sessions per IP per User. This is useful when one misbehaving user is creating too many sessions on the same host, kicking out other users' sessions.

Prevent login DDoS by enforcing max number of sessions per IP per user

---

azkaban-web-server/src/web/js/azkaban/view/job-details.js

This pattern catches anything that starts with http:// or https:// until any whitespace.
I'm not sure why the existing, more complicated pattern, is like that and stops already at `#`. I've seen other tools also stop at `(`, that's not too good either..
In practice, IMHO, it's better to catch links with higher tolerance and assume that there will be whitespace after each link.
Here's a real-life example of what would be cut too early by the existing pattern:
`http://kibana-test-elk.domain.com:8080/app/kibana#/discover?_a=(columns:!(loglevel,class,message),filters:!((meta:(index:'logstash-index-*',key:fields.cluster_id,params:(query:j-3W0WSCST0THQX,type:phrase),type:phrase,value:j-3W0WSCST0THQX),query:(match:(fields.cluster_id:(query:j-3W0WSCST0THQX,type:phrase))))),index:'logstash-index-*' …

Simplify pattern for detecting links in job logs

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailsheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm
azkaban-web-server/src/web/js/azkaban/util/flow-loader.js
azkaban-web-server/src/web/js/azkaban/view/job-details.js

Add navigation across logs of job attempts
Extras:
- Link to latest attempt logs also from Graph view (to match with Job List view)
- Include attempt status on job details page (attempt log page)
To test I ran this kind of execution:
When accessing logs, links lead to last attempt. For example:
But it's now easy to navigate to previous attempts:
See how the attempt status is also shown on the attempt logs page \o/

Add navigation across logs of job attempts

---

azkaban-web-server/src/web/js/azkaban/util/flow-loader.js

As [discussed](https://github.com/azkaban/azkaban/pull/2231#issuecomment-510162091) with @jamiesjc, it makes more sense to show `Open Job` and `Center Job` at the top as this is common to every job and `Open Log` options below them since they are only shown for job nodes that have a start time.
With this change:
For the record, [original suggestion](https://github.com/azkaban/azkaban/pull/2231#issuecomment-509851538) was a bit different
> I would keep the first two entries as Open Job and Open Job in new windows, keep the last item as Center, and add the two new entries in the middle.
However this PR puts also `Center` before the log links, as it is also shown in all occasions.

Reorder job context menu: move log links to bottom

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailsheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm

There are cases where a single Azkaban job launches multiple Map-Reduce jobs (for example Pig and Hive jobs) and therefore there can be multiple <application_id>s in the job log.
In the Job Details page, in those cases of multiple <application_id>s, there will be a dropdown button listing all the <application_id>s in the Azkaban job log in the order they were launched with links to their respective logs in Spark/Hadoop history servers.
This is related to PR #1695

Add a dropdown button in Job Details page to support multiple Hadoop jobs in the Az logs

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java

To build the url to job logs in Hadoop/Spark servers (#1695) we currently get the application ids by parsing the Azkaban job logs.
This PR fixes a bug that appears when processing job logs by chunks.
-Application ids can be missed when they are accidentally truncated. For example: 
"application_1556244585372_1234567" truncated to "\_155624458537_1234567" which will not match the pattern "application_(\\d+_\\d+)"
-Application ids can also be invalidated. For example:    
"application_1556244585372_1234567" truncated to "application_1556244585372_1"

Fixes issue with truncation of application ids when parsing logs

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java

Append flow submit user to Hadoop token principal in email format which conforms to Kubernetes.
Above can be configured using HadoopSecurityManager and are not mandatory.
A minor fix to log message.

Append flow submit user to Hadoop token principal in email format

---

azkaban-db/src/main/sql/upgrade.3.76.0.to.3.77.0.sql

User and group permissions are stored in the same database table with the 'name' column as the primary key. Groups are differentiated from users by having the 'isGroup' column set to true. Because the 'isGroup' column is not a primary key, attempts to create permissions for a group with the same name as an existing user end up updating the user of that name. To fix this issue is necessary to make 'isGroup' a primary key.

Fix not saving group permissions when group name matches an existing user's name.

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/permissionspage.vm
azkaban-web-server/src/web/js/azkaban/view/project-permissions.js

The modal for adding a group used to have the input field mislabeled as "User". This fixes that issue and properly labels it as "Group".

fix minor typo on permissions modal

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/permissionspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
azkaban-web-server/src/web/js/azkaban/view/project-permissions.js
azkaban-web-server/src/web/js/azkaban/view/schedule-options.js

.attr() cannot modify the 'checked' property of a checkbox, but .prop() can. So .prop() should be used for this purpose.
Previously this showed up as a minor UI glitch where checking the "Admin" permission when adding or changing a user or group did not properly check all the other checkboxes (i.e. read, write, execute and schedule).

change checkboxes to use .prop instead of .attr

---

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/storage/StorageCleaner.java
azkaban-common/src/main/java/azkaban/storage/StorageManager.java
azkaban-common/src/test/java/azkaban/storage/StorageCleanerTest.java

The cleanup of old project versions should not delete those versions with files still referenced by unfinished executions.
PR #1994 made the changes to prevent those undesirable deletions for project files stored in the database.
This PR complements PR #1994 by doing the same for project files not stored in the database (e.g. HDFS).

Ensure project files referenced by unfinished executions are not deleted in HDFS during cleanup.

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm
azkaban-web-server/src/web/js/azkaban/model/job-log.js

A synchronous Ajax call causes the UI thread to block until the Ajax call completes. While the UI thread is blocked, the page is unresponsive as that is the thread in charge of responding to user input. For large job logs, several Ajax calls are needed, which if made in synchronous in a loop cause the page to become unresponsive for too long.
The solution to the problem: use asynchronous Ajax calls.

Don't use synchronous Ajax call to get job logs

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This PR adds flowLockErrorMessage option in ProjectManagerServlet which allows user to pass customized error message to show in flow page when flow is locked due to calling setFlowLock API.

Add flowLockErrorMessage option to pass customized error message when flow is locked due to calling setFlowLock API

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/util/flow-loader.js
azkaban-web-server/src/web/js/azkaban/view/exflow.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js

Urls to embedded jobs in the Execute dialog's "Flow View" tab are not generated correctly due to the way parent flows are determined. One way to reproduce the issue is to use the option "Expand All Flows" followed by "Open Job in New Window" on any embedded job, we will get a page with content "Job XXX not found".

Fix job link urls of embedded jobs in Execute dialog.

---

az-hadoop-jobtype-plugin/src/examples/java-wc/pig-upload.job
az-hadoop-jobtype-plugin/src/jobtypes/common.properties
az-hadoop-jobtype-plugin/src/jobtypes/commonprivate.properties
az-hadoop-jobtype-plugin/src/jobtypes/pig-0.12.0/plugin.properties
azkaban-exec-server/build.gradle
azkaban-solo-server/src/main/bash/internal/internal-start-solo-server.sh
docs/jobTypes.rst

Adding dependency to needed for execution of az-hadoop-jobtype-plugin jobtypes
Adding classpath to Pig home needed for execution of HadoopPig jobs
Updating some common*.properties to make it easier to install jobtypes on a solo-server
Adding documentation to help set up a solo-server with the hadoopJava and pig jobtypes

Updating hadoopJava and pig jobtypes to allow solo-server installation

---

azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/util/job-list-common.js
azkaban-web-server/src/web/js/azkaban/view/flow-execution-list.js
azkaban-web-server/src/web/js/azkaban/view/job-list.js

Add Expand All button to job lists on both graph job sidebar and execution job list. When clicked, that job and all its sub jobs will be expanded recursively.
Note: The button only appears on jobs who have at least one child who has at least one child :smile: In other words, the button only appears on jobs containing more than one level of nested jobs.
Examples:
https://drive.google.com/file/d/1jhCoFm4INzXV9SUx8Sld_57LEsdAsGZi/view?usp=sharing
https://drive.google.com/file/d/1Fq9hRb1qFSC0ftnHEYTg05W-RqGEBAHW/view?usp=sharing

Add Expand All button to job lists

---

azkaban-common/src/main/java/azkaban/executor/RunningExecutionsUpdater.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java

In the new flow dispatch logic, the flow fail count is always 0. Fix the issue by incrementing the count by 1 whenever a flow fails.
Testing Done:
1. Verified the fail count is incremented by 1 every time a flow fails by adding debug log messages.
2. Verified fail count is reflected on the internal Ingraph dashboard.
3. Verified fail count is incremented exactly once for old dispatch logic as well.
NOTE: this is a new incarnation of PR https://github.com/azkaban/azkaban/pull/2301 which was from a git repo that was lost due to hardware issues.

Increment FlowFail counter in executor server when a flow fails.

---

azkaban-web-server/src/main/less/header.less
azkaban-web-server/src/main/less/log.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/style.vm

Fixes:
Notice that the breadcrumb is not fully visible. It's missing Job name and Attempt.
This is what it would look like after applying the fix:

Fix overlapping of logs with other UI elements when job/flow names are long

---

azkaban-common/src/test/java/azkaban/storage/StorageCleanerTest.java

We can't throw a checked exception using Mockito that the underlying method doesn't indicate it throws. So we'll throw a `RuntimeException`.

Fix StorageCleanerTest

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/Page.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This allows for `<br>` and `<br/>` in string variables passed to be rendered in velocity templates to be left as is and not escaped.
This is a better way of fixing what this previous PR tried to address: https://github.com/azkaban/azkaban/pull/2353

Escape HTML except for line breaks

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java

Use Logger.class instead of class of input logger which is native to HadoopJavaJobRunnerMain only.
This change is required to support jobtype constructors of type,
<String, Props, Props, Logger>

Use Logger.class instead of class of input logger which is native to HadoopJavaJobRunnerMain only.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

This change will allow user to implement customized oauth token provider in azkaban to generate access token to access  resources that needs authN. (Example use case: Azure storage).
Users need to set `azkaban.enable.oauth` to true in order to use it. (default to false)
Refactor `HadoopSecurityManager_H_2_0.registerCustomCredential` so it can be reused to register custom credential provider.

Allow oauth access token fetch by adding custom implemented oauth token provider

---

.gitignore
azkaban-common/src/main/java/azkaban/storage/StorageManager.java

Modified the md5 hash to print the Array of numbers instead of the non-printable characters when there is a mismatch. 
Added few files that are generated locally in the gitignore.
How to test in local?
set the property azkaban.storage.type=LOCAL in the azkaban.properties. This enabled the zip to be stored in LOCAL file system. After that deliberately added few bytes in the validateCheckSum `hash`. When I ran a flow, it failed with IllegalStateException indicating the mismatch between the hashes. 
The flow went through fine when there is a match in the md5 hashes.

[Logging] Fixed the md5 hash non-printable characters

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java

Reverts azkaban/azkaban#2352
YARN currently does not support configurable tag length. (YARN-9954) azkaban job type name could potentially be very long, which will cause app submission to YARN to fail. Hence reverting the change.

Revert "Adding Job Name and Submit user to the job metadata"

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSecureWrapperUtils.java

If hadoop security is off, hadoop proxy user needs OAuth token being available in its UGI credentials. This is to make sure that ABFS(Azure blob file system) driver can still get the token to access azure storage.

Add credentials to hadoop UGI if hadoop security is not enabled.

---

build.gradle

Undo the root `build.gradle` change from https://github.com/azkaban/azkaban/pull/2363 that allows pushing to maven local.
This interferes with the internal deployment pipeline.

Remove publish to Maven local

---

docs/ajaxApi.rst

Old command returns a "Login error. Need username and password" error

Fix Upload Project Zip API command

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java
azkaban-common/src/main/java/azkaban/jobExecutor/AbstractProcessJob.java
azkaban-common/src/main/java/azkaban/jobExecutor/JavaProcessJob.java
azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypePluginSet.java

Propagate plugin's private properties which use HadoopJavaJob so that they can be accessed by plugin code.
This involves changes to the HadoopJavaJob to add 1 more parameter for private props which propagates all the way to AbstractProcessJob.java.
Added util functions to access this privateProp from JobTypePluginSet in JobTypeManager.
Did some code cleanup and refactoring HadoopJavaJobRunnerMain:getMethod()

Propagate plugin's private properties which use HadoopJavaJob so that they can be accessed by plugin code.

---

azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/test/java/azkaban/ServiceProviderTest.java
azkaban-common/src/test/java/azkaban/storage/HdfsStorageTest.java
azkaban-common/src/test/resources/hdfs_conf/hdfs-site.xml

Originally if a project upload failed, the corrupted zip may still be left in HDFS with the finalized name. Then, future uploads will see that the zip already exists and skip uploading it and go ahead and create a new version associated with that zip (causing problems with execution).
Now, we first upload to a temporary file and then rename it only if the upload succeeds.

Fix project upload failure recovery

---

azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/test/java/azkaban/project/DirectoryFlowLoaderTest.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalJobsTest.java
test/execution-test-data/conditionalflowtest/conditional_flow1/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow1/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow1/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow1/jobD.job
test/execution-test-data/conditionalflowtest/conditional_flow2/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow2/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow2/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow2/jobD.job
test/execution-test-data/conditionalflowtest/conditional_flow3/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow3/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow3/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow4/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow4/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow4/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow5/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow5/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow5/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow6/jobA.job
test/execution-test-data/conditionalflowtest/conditional_flow6/jobB.job
test/execution-test-data/conditionalflowtest/conditional_flow6/jobC.job
test/execution-test-data/conditionalflowtest/conditional_flow6/jobD.job

Existing conditional properties in the model simply needed to be set when parsing a properties file. The validation code is copied based closely on the yaml version. Added test cases and test jobs to demonstrate conditional handling.

Implemented conditions support for properties-based projects

---

azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This is a partial fix for Issue #2243: _ExecutorManagerException: executor became inactive before setting up the flow_.
This only fixes the cases where `executor.port` property is defined ie. using a fixed port.
----
A general fix would need to go in this order I suppose:
- guice provisioning
- start executor jetty server (to reserve a random port) but maybe in a state that returns 503 for now (to all requests?)
- init FlowRunnerManager.active from db
- stop returning 503
- However as it's up to jetty server to pick a random port, there's not much point in doing this, other than guaranteeing consistency between executor state & the DB. Any way, if an executor is restarted, it may get the same port as before, but it's more likely that it gets a different port, and in that case the status …

Initialize FlowRunnerManager.active from DB

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

Root flow's start time was set twice: in `FlowRunner.run()` and `FlowRunner.runReadyJob()`. This causes that missed SLAs are not processed occasionally.
SLA checks are scheduled based on the first start time set on the root flow. If this start time is overwritten the SLA check could fail to recognize a miss (it determines that it's not yet time to check SLA) and therefore not kill the flow when it should.

Don't set start time of root flows twice.

---

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-db/src/main/java/azkaban/db/AzDBUtil.java
azkaban-db/src/main/java/azkaban/db/DatabaseOperator.java
azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java

Address a deadlock occurring between:
- the polling query: `SELECT exec_id FROM execution_flows WHERE status = 20 AND executor_id IS NULL AND flow_data IS NOT NULL AND (use_executor IS NULL OR use_executor = ?) ORDER BY flow_priority DESC, update_time ASC, exec_id ASC LIMIT 1 FOR UPDATE; `
- and the query updating a running execution: `UPDATE execution_flows SET status=?,update_time=?,start_time=?,end_time=?,enc_type=?,flow_data=? WHERE exec_id=?`
By: 
- introducing retry logic in the flow update query to mitigate the effect of any deadlocks.
- lowering the transaction isolation level of the polling query to TRANSACTION_READ_COMMITTED to reduce the chance of the deadlock appearing since it requires less locks to be acquired than MySQL's default read mode REPEATABLE-READ.

Address a deadlock occurring between the polling query and the query updating running executions

---

az-jobsummary/src/main/resources/azkaban/viewer/jobsummary/velocity/jobsummary.vm
azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowtriggerspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executionspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectlogpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/util/ajax.js
azkaban-web-server/src/web/js/azkaban/view/exflow.js

The KILL action can take a while to be processed. During that waiting time the user was able to click the PAUSE button. If they did the execution would be marked as PAUSED even though all the running jobs would be killed anyway. In addition to persisting an incorrect flow status this causes that long running flows are not killed automatically and that executor server processes waiting for all executions to finish before stopping will be stuck.
In addition to the backend changes the PAUSE button will be disabled in the UI after the KILL button is clicked. The page will look like:

Don't allow pausing an execution while processing a KILL action.

---

azkaban-web-server/build.gradle
azkaban-web-server/src/main/java/azkaban/flowtrigger/security/AddHardCodedProps.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/security/SecurityPropName.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/security/TokenFetcher.java

This is for proof-of-concept exercise. Therefore certain shortcuts
have been taken, such as hard-coding of property names (SecurityPropName)
and property values(AddHardCodedProps).

Add TokenFetcher, a class to fetch Hadoop tokens and DV-Identity certs.

---

azkaban-common/src/main/java/azkaban/project/CronSchedule.java

Revert back the serialVersionUID in CronSchedule class as the update was not required.

Revert back the serialVersionUID in CronSchedule class

---

az-hadoop-jobtype-plugin/build.gradle
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestAbstractHadoopJavaProcessJob.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsConstructHadoopTags.java

This is in preparation for Hadoop 2.10.0 upgrade - mechanism for passing workflow id from azkaban to Hadoop was changed (see YARN-9760). Now it uses yarn tags.

Add workflow id to mapreduce tags

---

azkaban-db/src/main/sql/create.project_flows.sql
azkaban-db/src/main/sql/migrations/patch-1.sql
azkaban-db/src/main/sql/upgrade.3.83.0.to.3.84.0.sql

BLOB type of json column is small and we are exceeding limit of it for few projects. I am increasing size to MEDIUMBLOB. I have verified that is is not affecting webserver startup time.

Changing json column from BLOB to MEDIUMBLOB in project_flows table.

---

azkaban-common/src/test/java/azkaban/trigger/BasicTimeCheckerTest.java

Fix daylight saving related unit tests that use dates from the past to now use dates from March 2021. 
If the dates are not in the future then these tests break. The previous dates were based on March 2020 daylight saving. Now that we are past it, use dates from March 2021.

Fix Daylight saving related UnitTest that broke due to current date > date in cron expression

---

azkaban-common/src/main/java/azkaban/project/CronSchedule.java

Ensure TimeZone is set to default if CronSchedule is pulled from older serialized class.
This avoid any potential NPE.
Derived from contribution from Andrew Charneski.

Ensure TimeZone is set to default if CronSchedule

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java

Update the kerberos principal to contain host name and execution id. This helps in auditing hadoop logs.

Update the kerberos principal to contain host name and execution id

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This PR is related to #2458
A `FLOW_FINISHED` event is emitted when a flow finishes. Two important things happen when handling that event:
-the flow is removed from the `runningFlows` collection
-the execution directory is deleted
If for some reason `FLOW_FINISHED` event fails to be emitted/handled one side effect of not removing flows from the `runningFlows` collection is that flows can get stuck in KILLING status forever.
This happens when there is an SLA rule set to kill the executions if they haven't reached a final state in a certain time. When proceeding with the SLA `KillExecutionAction` the `runningFlows` collection is examined: 
-if a flow is in the list (regardless of its status) `kill()` will be called and we can transition a flow which is not running anymore from a final …

Check that an execution is not in a final state already before killing it

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/ExecutionLogsCleaner.java
azkaban-web-server/src/test/java/azkaban/webapp/ExecutionLogsCleanerTest.java

Extracted the execution_logs cleanup logic from old dispatcher logic and kept it outside the dispatcher. Independent of the dispatcher logic this clean up would run every 60 minutes. 
Tested manually that the logic is triggered by setting the azkaban.poll.model config to be false and true. I was able to see the ExecutionLogsCleaner getting triggered. Adding unit tests is in progress.

Moved the db clean up logic out of the push based dispatch-logic

---

az-core/src/main/java/azkaban/utils/TimeUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java

Currently flow execution status is stored in 2 places: a column in the DB and in the execution's JSON object. Because flow execution status is not read from the same source all the times sometimes we see inconsistency in the UI where different pages show different flow execution status.
This PR addresses this inconsistency by fetching the execution status from DB everywhere in the code.

Fetch flow execution status from database column only.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

We are seeing Uncaught throwable exception sometimes related to NullPointerException. We do not have full stack trace about where and how this exception is coming. It is not happening that often. But for future cases, it will be better to have stack trace for this issue.

Adding printStackTrace statement to get more information

---

azkaban-common/src/main/java/azkaban/event/EventHandler.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackRequestMaker.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/JobCallbackUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/event/JobCallbackRequestMakerTest.java

FlowManager event handlers are invoked by one of JobRunner event handler. Fix is not to access the runner object in flow event handler during handling of job events.

Fix missing job callbacks issue.

---

build.gradle

We have seen issues where the the AzkabanWebServer freezes due to
connections leaking from the connection pool.
The current version of the library is quite old and there have been related
fixes in the code since.

Upgrade dbcp2 version

---

azkaban-common/src/main/java/azkaban/alert/Alerter.java
azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/main/java/azkaban/executor/mail/DefaultMailCreator.java
azkaban-common/src/main/java/azkaban/executor/mail/MailCreator.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java
azkaban-common/src/test/java/azkaban/executor/mail/DefaultMailCreatorTest.java
azkaban-common/src/test/resources/azkaban/executor/mail/failedExecutorHealthCheckMessage.html

As part of the remediation flows in an `unfinished` state assinged to an unreachable executor are finalized
Additional changes:
- Adds healthcheck alert as a first-class member of alert related interfaces
- Current code was repurposing Flow Failure related alert mechanism in a less
than ideal manner
- Customized email format for healthcheck alert message
- Assumes that only a `single` kind of healthcheck alert message is required.
But makes future extensions easier, if required.

Add remediation for flows assigned to unreachable executors

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/MysqlNamedLock.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java
azkaban-db/src/main/java/azkaban/db/DatabaseTransOperator.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

Changed polling query to lock single row in mysql by using limit condition in nested query.
Enabled serial polling from execution_flows table using GET_LOCK in mysql.

Enable serial polling for executor using mysql lock

---

az-reportal/src/main/java/azkaban/reportal/util/Reportal.java
az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/WebUtils.java

Use getRealClientIpAddr() to fetch uploader's IP
Cleanup older logic to fetch uploader's IP.
This is a followup to #2486

Refactor WebUtils.getRealClientIpAddr() for better reuse.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java

We have seen couple of usecases where executions are stuck in PREPARING state. To unblock these executions, we had to change executor_id to null in database. I am adding these logs to debug the same issue as there was no exception in executor logs for the failure.

Adding logs to debug why flows are getting stuck in PREPARING state for some usecases

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

Separate out logger in its own try catch block. This helps in logging out messages when HadoopJavaJob throws exception.

Use updated kerberos principal to fetch NameNode Tokens

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

This issue can be reproduced when Poll Dispatch model(#2038) is used and `azkaban.polling_criteria.flow_threads_available` isn't enabled (#2195). When there are no more flow threads available executions will be queued on the executor side. If one of them is killed while waiting for a thread a NPE will be seen in the flow logs.

Fix the NullPointerException thrown when an execution is killed before it has started.

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm

This message is causing confusion to the user. While there are multiple things we can do to improve this page, this is a quick fix that will help the users. 
verified that the schedule page loads fine and there no message on the top.

Removed the misleading message in the schedule panel

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java

Fix NPE when SlaOptions have no actions set which cause flow serialization to fail.
This failure causes excessive logging as the flow is stuck in Preparing state.
Make sure that in such case the flow is finalized to FAILED state.

Fix NPE when SlaOptions have no actions set.

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

When the main thread is interrupted subsequent tests fail due to an IO channel being closed by the generated _InterruptedException_ in that test.

Ensure main thread is not interrupted when running testKillBeforeStart test

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/schedulepanel.vm

The current link we are pointing doesn't exist anymore. Pointed to the right link. Tested if it's taking me to the correct page by running the Azkaban WS locally.

Fixed the broken link in the schedule panel page

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectCacheCleaner.java
azkaban-exec-server/src/test/java/azkaban/execapp/ProjectCacheCleanerTest.java

The previous code in ProjectCacheCleaner class had several deficiencies:
1. When a watermark for cache cleaning hits, the code did LRU evictions by deleting old
project directories in a *blocking context*. This can cause flows to get stuck in
preparing state.
2. Every time this class is invoked in response to a cache miss; the code does equivalent
of a "du" command on the project cache directory. On large clusters this directory tends
to get huge thereby making the flows get stuck for several seconds. In extreme cases
for minutes or even hours.
3. The calculation of watermark (deletion thresh-hold) itself was flawed. The thresh-hold
is getting calculated from the partition size; when other things like execution directories
share the same partition. So in many cases the commonly used …

Overhaul Project Cache Cleanup Code to fix inefficiencies

---

az-core/src/main/java/azkaban/metrics/MetricsManager.java
azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java
azkaban-common/src/test/java/azkaban/metrics/CommonMetricsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/ExecMetrics.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/test/java/azkaban/execapp/ExecMetricsTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java

Metrics added:
-`flow-success-meter`: Records when flow executions are marked as SUCCEEDED.
-`flow-killed-meter`: Records when flow executions are marked as KILLED.
-`flow-killing-counter`: Tracks the number of flow executions in KILLING status (the starting point of the killing procedure).
-`flow-time-to-kill-histogram`: Records the time it takes to kill all the jobs in an execution, in other words the time it takes to transit from KILLING to KILLED status
-`job-success-meter`: Records when job executions are marked as SUCCEEDED.
-`job-fail-meter`: Records when job execution are marked as FAILED.
-`job-killed-meter`: Records when job executions are marked as KILLED.
Additional changes:
-fixed `project-dir-cache-hit-ratio`. Call the correct method at the time of emission for a Gauge …

Add more metrics to flow and job executions.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

When a flow didn't define `user.to.proxy` property it defaulted to NULL when sending the _JOB_STARTED_ Kafka event causing a NullPointerException and a failure to send the event.

Use default 'user.to.proxy' value for JOB_STARTED Kafka event when that property is not defined

---

azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java

Currently in case of any uncaught exceptions during executor health check
the health checking stops and the exception is never reported.
This is fixed by introducing a wrapper routine for catching and reporting any
uncaught exceptions.
Includes additional exception handling when finalizing flows for an
unreachable executor.

Fix exception handling of executor health checker

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

Use new instance of HDFS object to fetch NameNode token as URI is unique with updated Kerberos Principal.
With older logic if there exists a FileSystem cache, the cache would blow up very quickly.
Earlier, the UGI for namenode used to be just the proxy user name. If a job with same user requested FileSytem object, it would be fetched from the cache.
With update to Kerberos principal to <user name>/az_<host name>_<exec_id>, the UGI became unique to an execution thus blowing the FileSystem cache up.
Morever, the entry is never fetched from FileSystem cache as it is unique to that particular execution rendering the cache entry useless.
This PR alleviates this by creating a new instance of FS and closing it in the same method.
EDIT : Issac okayed the current logic.

Use new instance of HDFS object to fetch NameNode token as URI is unique

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

Add a metric to track number of flows that have not started running for more than 20 minutes (configurable) after the web server put those in the queue.
The metric provides a strong signal that an underlying problem (system overload or sluggish/overworked executors) have started impacting the overall performance of the system.
This is different from:
- The state where large number of flows are in the queue, but all the flows in there are young.
- Measuring polling interval of executors, which does not indicate whether a slowed down polling has impacted the intake from the queue (Please note there could be multiple executors) 
Unit-Test
Writing unit test for duration-dependent functionality is flaky if the underlying code is using System.currentTimeMillis() calls, which the existing code …

Add metric NumAgedQueuedFlows: Count flows that are in queue for a long time

---

azkaban-common/src/main/java/azkaban/server/SlaRequestUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/SlaRequestUtils.java

This is groundwork for https://github.com/azkaban/azkaban/issues/2509: _Support SLA options in execute API_.
Just moved the code into a util class so that it can be next adjusted to be used also in `ExecutorServlet`.

Refactoring only: extract SLA parsing to new SlaRequestUtils

---

azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/main/java/azkaban/server/SlaRequestUtils.java
azkaban-common/src/main/java/azkaban/sla/SlaOption.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/LoginAbstractAzkabanServletTestBase.java
build.gradle

This implements https://github.com/azkaban/azkaban/issues/2509 _Support SLA options in execute API_.
As a bonus SLA options are now supported also in the schedule call because it's using the same HttpRequestUtils. This is nice because if using the API directly to add schedules (like many users do), the API now allows ensuring that a scheduled execution doesn't start running before SLA has been set for it.
The separate set sla API for schedules remains as well.

Support sla settings in execute & schedule API actions

---

az-core/src/main/java/azkaban/Constants.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java

UI and API changes to prepare Azkaban for OAuth SSO. 
Also takes care of:
Re-enable local XML user interactive login when OAuth is on
Deep-link redirect handling
Error handling for OAuth flow
Full SSO implementation requires corresponding changes to UserManager plugin to (1) validate and redeem authorization code for access (and possibly refresh) token(s) with OAuth provider; and to (2) fetch, populate and return user info (short name, email, group membership).

Login flow changes for OAuth2

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
azkaban-common/src/main/java/azkaban/flow/CommonJobProperties.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Added **azkaban.webserverhost**, **azkaban.job.id**, **azkaban.job.attempt** to mapreduce tags
ApplicationTags from RM webpage:
azkaban.flow.projectname:az_acceptance_test_new,azkaban.host:ltx1-holdemaz04.grid.linkedin.com,azkaban.flow.execid:417785,azkaban.flow.flowid:hadoopyarnflows,azkaban.job.attempt:0,workflowid:az_acceptance_test_new$hadoopyarnflows,azkaban.job.id:hadoopyarnflows_pigwordcount1

Add job props to uniquely identify a job in mapreduce tags

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java

Currently job properties always win over flow override properties.
However in practice it's quite handy to be able to override even those.
The UI currently says:
> Flow Parameters / Flow Property Override
> Add temporary flow parameters that are used to override global settings for each job
Also the [docs](https://azkaban.readthedocs.io/en/latest/useAzkaban.html?highlight=override#flow-parameters) read:
> The flow parameters override the global properties for a job, but not the properties of the job itself.
It seems like the intention has been that only flow level props are overridden, and if a job defines the same property, it still wins.
This is kinda confusing. Because on the other hand an overridden flow property is passed to the job, if the job itself doesn't set that property at …

Flow override properties to also override job properties

---

azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

Fixes test failure like this:
```
azkaban.execapp.JobRunnerTest > testBasicRun FAILED
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at azkaban.execapp.JobRunnerTest.testBasicRun(JobRunnerTest.java:112)
```
Which points to this line:
https://github.com/azkaban/azkaban/blob/783f88d490a65ecbc1283c317eb9f662056f4fba/azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java#L112
At least locally this test was often executed so fast that time in queue was set to 0. That must mean that `System.currentTimeMillis()` had not advanced between the times when job was queued and executed. Add 1 ms sleep to ensure that queue time is always at least 1.

Fix flaky queue duration condition in JobRunnerTest

---

.travis.yml
README.md
azkaban-web-server/package.json

-use a more recent Linux distribution.
-replace travis-ci.org with travis-ci.com in build badge reference.

Update Travis CI configs.

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/WebUtils.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/javascript.vm

1. Some configuration errors resulted in uncaught exceptions from WebUtils that prevented WS from starting.
2. In some environments Velocity template engine failed to process unescaped dollar sign resulting in 500 error to UI.
Tested (1) on local soloserver, (2) on Pokemon and (3) in "certain" environment (where it failed before) by patching `javascript.vm`, splicing patched file into WS JAR file in `lib/, restarting WS and observing the final rendered templates via Dev Tools in Chrome. In all environments the template rendered successfully and correctly.

Fix startup errors in some environments

---

azkaban-web-server/src/main/java/azkaban/webapp/CSRFTokenUtility.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/permissionspage.vm
azkaban-web-server/src/test/java/azkaban/webapp/CSRFTokenUtilityTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectManagerServletTest.java
azkaban-web-server/src/web/js/azkaban/view/project-permissions.js

CSRF token validation for modifying project permissions
We have used "Synchronizer token pattern" for CSRF validation. This code generates CSRF token by hashing session-id hence csrf tokens are not kept in memory. 
CSRF token will be sent as an HTTP header rather than request parameters, as it is the more recommended approach

Add CSRF token validation for modifying project permissions

---

az-core/src/main/java/azkaban/metrics/MetricsManager.java

When we added second public Ctor with a different signature
to the reporter class, MetricsManager started failing sporadically
depending on which Ctor was the [0]-th in the list.
Tested on local soloserver:
2020-10-23 01:33:28,768 INFO [azkaban.metrics.MetricsManager main] metricsReporterClassName: com.linkedin.amf.reporter.AmfReporter
2020-10-23 01:33:28,771 INFO [com.linkedin.amf.reporter.AmfReporter main] AmfReporter Initializing. serverUrl: ltx1-amf.prod.linkedin.com

Make MetricsManager more robust to changes in metrics reporter Ctor

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
azkaban-common/src/main/java/azkaban/cluster/Cluster.java
azkaban-common/src/main/java/azkaban/jobExecutor/JobClassLoader.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/test/java/azkaban/cluster/ClusterTest.java
azkaban-common/src/test/java/azkaban/cluster/HadoopSecurityManagerClassLoaderTest.java
azkaban-common/src/test/java/azkaban/jobtype/JobTypeManagerWithDynamicClusterTest.java
azkaban-common/src/test/resources/plugins/jobtypeswithrouting/anothertestjob/private.properties
azkaban-common/src/test/resources/plugins/jobtypeswithrouting/common.properties
azkaban-common/src/test/resources/plugins/jobtypeswithrouting/commonprivate.properties
azkaban-common/src/test/resources/plugins/jobtypeswithrouting/testjob/plugin.properties
azkaban-common/src/test/resources/plugins/jobtypeswithrouting/testjob/private.properties
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Right now, the per-job ClassLoader takes care of loading the HadoopSecurityManager class and its dependencies. 
Because each job creates its own ClassLoader instance, we are essentially doing loading HadoopSecurityManager class and its large dependencies over and over for each job. This triggers a bottleneck in the JVM under the classloader subsystem when many threads are doing classloading at the same time, contending for a global lock.
By introducing a HadoopSecurityManager ClassLoader per cluster, we only load HadoopSecurityManager class and its dependencies once per cluster, avoiding hitting the JVM classloader subsystem bottleneck.
NOTE we still create an instance of HadoopSecurityManager per job, which we don't see any issue with, in the current stress testing.

Introduce a per-cluster HadoopSecurityManagerClassLoader to reduce the classloading workload on the JVM.

---

build.gradle

joptsimple.OptionParser#acceptsAll(java.util.Collection<java.lang.String>, java.lang.String) 
method singnature has changed to 
joptsimple.OptionParser#acceptsAll(java.util.List<java.lang.String>, java.lang.String)
from 4.3 to 5.0.3 for net.sf.jopt-simple:jopt-simple jar

Updaing dependency jopt-simple to 5.0.3

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

The time difference between when FlowRunner logs when a job is started,
and when the job object is created in JobRunner, can serve as a proxy
of how much overhead it is to set up a job.

log when a job object is created in JobRunner.

---

azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1PodBuilder.java
azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java
azkaban-common/src/main/java/azkaban/container/models/ImagePullPolicy.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest1.yaml
build.gradle

Added builder class for creation of Kubernetes pod-spec
Added dependency io.kubernetes:client-java containing builder classes for creation of K8s pod. This allows type-safe creation of K8s Pod resources instead of writing YAML files.
Added azkaban.container.models.AzKubernetesV1PodBuilder class, a wrapper over builder classes provided by o.kubernetes:client-java to ensure tighter integration of init-containers, volumes, volume mounts, etc. required by the azkaban containerization approach.

Added builder class for creation of Kubernetes pod-spec

---

azkaban-common/src/main/java/azkaban/version/LocalVersionSetLoader.java
azkaban-common/src/main/java/azkaban/version/VersionSet.java
azkaban-common/src/main/java/azkaban/version/VersionSetBuilder.java
azkaban-common/src/main/java/azkaban/version/VersionSetLoader.java
azkaban-common/src/test/java/azkaban/version/VersionSetBuilderTest.java

Introducing version set and added skeleton for version set loader
LocalVersionSetLoader.java is added as of now for functionality testing. Later Actual JDBC-based implementation will be added.

Introducing version set and added skeleton for version set loader

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlowBase.java

Current logic to resolve an embedded flow name adds fully qualified name for each
flow name in the path, leading to a lot of duplication. This change removes the
duplication so the FQN's are shorter, more readable and most importantly take
less space in the DB.
Example:
Before the change, a nested flow id FQN for dag_4:
----------------------------------------
Flow Id FQN: dag_2,dag_3:dag_2:dag_3,dag_4:dag_2:dag_3:dag_4
After the change:
----------------------------------------
Flow Id FQN: dag_4:dag_2:dag_3:dag_4
Verified the change by execution nested flows, accessing flow and job logs and
by running internal acceptance tests.

Remove duplication in embedded flow name.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

Renaming ContainerizedExecutionManagerProperties class to ContainerizedDispatchManagerProperties.

Fixing the name of Property class for Containerized Dispatch. Earlier it was ContainerizedExecutionManagerProperties.

---

azkaban-db/src/main/sql/create.containerization-tables-all.sql

Will use the version_set table available at azkaban-db/src/main/sql/create.version_set.sql

Removing image_version_set table from the ddl

---

azkaban-exec-server/src/main/java/azkaban/cluster/ClusterModule.java

The cluster router may need to reuse some configurations that have been defined for Azkaban Executor Server

Expose Azkaban Executor Server configuration to the cluster router

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

For Containerization project, we want to introduce HadoopSecurityManager version 3. There is a lot of code which version 3 will need from version 2. So reuse all that code, I have created AbstractHadoopSecurityManager with code which can be reused.

Moving common HadoopSecurityManager code to AbstractHadoopSecurityManager so that all the versions of HadoopSecurityManager can reuse this code.

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

When a user requests to kill an execution a check that it's still running is made several times however the execution may finish before the kill action is processed after those checks causing it to stay in KILLING status forever.

Prevent kill action from leaving executions stuck in KILLING status.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiClient.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiClientTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewaySystemTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java

Modifies ExecutorApiClient and ExecutorApiGateway for
- Handling Reverse-proxy based access to Executors/FlowContainers
- Containerized dispatch to FlowContainers
Add executor api call invocations from ContainerizedDispatchManager
- Done indirectly by adding invocation in base class AbstractDispatchManager
- Adds getExecutableFlowLog, getExecutionJobLog, getExecutionJobStats, cancelFlow

Add executor api calls for containerized flows

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1PodTemplate.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest2.yaml
azkaban-common/src/test/resources/azkaban/container/models/v1PodTestTemplate1.yaml

This template design enables the declaration of static initContainers, volumes, volumeMounts, etc. which are not job-types but are useful. For example: init container which will fetch the required certificates/tokens etc. writes to a volume and then that volume will be mounted to the application-container/flow-container.
Items like InitContainers, Volumes, and VolumeMounts for the application-container/flow-container will be extracted from the POD created from this template file. Extracted Items are later merged with the already created pod-spec(builder based approach).
Merging criterion is such that, if the item in the already created pod-spec has the same name as of the item extracted from the template, then it will be retained.

Added template based design to add items to the pod-spec

---

azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPipelineTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm
docs/useAzkaban.rst
test/execution-test-data/embedded2/pipeline4.job
test/execution-test-data/embedded2/pipelineEmbeddedFlow4.job

2 first commits taken from https://github.com/azkaban/azkaban/pull/2246 & rebased.
From the original PR by @toby-allsopp:
> Sometimes it is not acceptable for any nodes in the flow to run concurrently with any nodes in another execution of that flow. For example, exclusive access to some shared resource, such as a staging table in a database, might be required.
> This PR introduces a third level for the pipeline concurrency option in which none of the nodes in a flow can start until the end nodes in the concurrent execution have finished.
There was a bug that parent flow was not resolved recursively, which I have fixed. Without it blocking didn't work in this scenario:
- Two parallel executions, say ex-1 & ex-2
- In ex-1 sub-flow A is disabled
- In ex-2 sub-flow B is disabled
- Before the …

Add pipeline Level 3: block all jobs until the previous flow has completed

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-common/src/test/resources/azkaban/server/list_map_object.json
azkaban-common/src/test/resources/azkaban/server/single_map_object.json
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/resources/conf/azkaban.properties
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-solo-server/src/main/resources/conf/azkaban.properties
azkaban-web-server/src/web/js/azkaban/util/ajax.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
azkaban-web-server/src/web/js/azkaban/view/schedule-options.js
test/local-conf-templates/conf/azkaban.properties

This feature was reverted by @djaiswal83 in https://github.com/azkaban/azkaban/pull/2620.
Now adding it back as [requested](https://github.com/azkaban/azkaban/pull/2241#issuecomment-713893621):
> Can you please make it configurable and disabled by default?
See the PR description of https://github.com/azkaban/azkaban/pull/2241 for the background/rationale of this change.
Content of this PR:
- First, revert commit 21d33f0812c22df0883a3e56fc508ddd5abdc621 ie. PR https://github.com/azkaban/azkaban/pull/2620 to add back the code changes of https://github.com/azkaban/azkaban/pull/2241
- Then, make it configurable with a new property `executor.props.resolve.overrideExisting.enabled`
So, by default there is no change in behavior. That is to **not** override existing job props.

Bring back "Flow override properties to also override job properties"

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

This will provide us a way to make single call to fetch all the hadoop tokens together if we have different implementation for AbstractHadoopSecurityManager.

Fetching all the hadoop tokens from single method and moving call to specific method as responsibility of each implementation

---

azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java

Handling of `null` execution-id in ExecutorApiGateway.callWithExecutionId() was broken by commit
https://github.com/azkaban/azkaban/pull/2715/commits/38f3c103b771d1cf4687f9e97a0e0537dea1a1e4

Fix handling of null executionId in ExecutorApiGateway

---

azkaban-db/build.gradle

Note how `distributions` below collects from "$buildDir/sql" -- *not* from 'build/sql'.
Turns out that $buildDir can be azkaban/build/azkaban-db *or* azkaban/azkaban-db/build,
depending on the build configuration. So it's important to be consistent about (1) where
the create-all-sql-*.sql is created and (2) where it is picked up from into distributions.

create-all-sql-*.sql is missing in some distributions

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java

This change makes sure that poll-based dispatch starts with the flow status READY and once the execution is polled, it will be updated to PREPARING. 
Added the test for the same.

Changed start status to READY instead of PREPARING for poll based dispatch

---

azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1PodTemplate.java
azkaban-common/src/main/java/azkaban/container/models/PodTemplateMergeUtils.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest2.yaml
azkaban-common/src/test/resources/azkaban/container/models/v1PodTestTemplate1.yaml

Probes are static in nature and hence if they are present in the pod template, they should be added to the actual pod spec during dispatch.

Add probes from the podTemplate to the podSpec

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java

If cpu and memory requested for a flow container is higher than limit defined in system properties then flow pod will not launch.
Flow parameter introduced for cpu and memory are:
flow.container.cpu.request
flow.container.memory.request

Adding an option to provide flow container resource requests from flow parameter

---

azkaban-common/src/main/java/azkaban/cluster/Cluster.java
azkaban-common/src/test/java/azkaban/cluster/ClusterTest.java

Jar files added to HadoopSecurityManagerClassloader as search paths could be located under symbolic links.
For example, let's say there are two jars, `A-0.0.1.jar` and `B-0.0.1.jar` under a symbolic link `/export/apps/hadoop/latest`
When these jars are added, effectively two paths are added to HadoopSecurityManagerClassloader,
`/export/apps/hadoop/latest/A-0.0.1.jar` and `/export/apps/hadoop/latest/B-0.0.1.jar`
When the symbolic link moves, HadoopSecurityManagerClassloader breaks. Let's say the symbolic link `/export/apps/hadoop/latest` is updated to point to a newer version of hadoop that contains newer version of A and B, `A-0.0.2.jar` and `B-0.0.2.jar` respectively. Once the symlink is updated, there are no longer `/export/apps/hadoop/latest/A-0.0.1.jar` and …

Resolve symbolic links for jar files added to HadoopSecurityManagerClassloader

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/DispatchMethod.java
azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
azkaban-db/src/main/sql/create.containerization-tables-all.sql
azkaban-db/src/main/sql/create.execution_flows.sql
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

This ramp-up mechanism requires that containerization be enabled and ramp-up percentages are set appropriately. Setting it to 100 will make all the executions use Containerization and setting it to 0 implies they will be polled by the executor server.
This allows ContainerizedDispatchManager to submit/upload some flows to the execution_flows table based on the ramp percentage with an additional column value dispatch_method. Whenever executions are pulled from the execution_flows table, respective dispatch managers will query by filtering the dispatch_method. Any future changes to the ContainerizedDispatchManager will automatically be honored as there is no new DispatchManager.
If this mechanism needs to removed then the only change will be required in the class …

Added mechanism to rampup Containerized from POLL dispatch

---

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/test/java/azkaban/jobtype/JobTypeManagerWithDynamicClusterTest.java

Currently if user specifies a job property e.g. pig.home, and pig.home is also defined in cluster properties, cluster properties will take precedence. This PR gives job properties precedence.

Give job props precedence over cluster props

---

azkaban-common/src/main/java/azkaban/DispatchMethod.java
azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutionReference.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiClient.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/utils/RestfulApiClient.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowPriorityComparatorTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiClientTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewaySystemTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/FetchActiveFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java
azkaban-common/src/test/java/azkaban/executor/QueuedExecutionsTest.java
azkaban-common/src/test/java/azkaban/executor/RunningExecutionsUpdaterTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-common/src/test/java/azkaban/utils/TestUtils.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java

Ramp-up mechanism is introduced in https://github.com/azkaban/azkaban/pull/2779 allowing some flows to be dispatched as Containerized and others as POLL to have a mechanism of ramping the containerization on the already running POLL based Azkaban cluster.
Hence web server, depending on the execution, may need to send a request to the Container via reverse proxy or to the executor server. Column "flow_data" in the execution_flows is a blob containing information regarding flow execution and it will also contain the dispatch_method for that execution. Based on the dispatch_method derived from "flow_data", we can send the request to the appropriate server.
Key changes:
azkaban-common/src/main/java/azkaban/executor/ExecutorApiClient.java …

ApiGateway support for ramp-up mechanism from POLL to CONTANERIZED dispatch

---

azkaban-common/src/main/java/azkaban/utils/ThinArchiveUtils.java
azkaban-spi/src/main/java/azkaban/spi/Dependency.java

Sometimes, to isolate dependencies and avoid conflicts the same dependency jar file is required in different paths in a project. For example:
```
common-libs
|-jackson-annotations-2.6.0.jar
|-….jar
|-….jar
|-other-libs
|-jackson-annotations-2.6.0.jar
|-….jar
```
To allow this we need to take into consideration dependency `destination` when building the _Set_ of dependencies to download.

Allow multiple copies of the same dependency file in Thin Zips.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/Executor.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerImplUtils.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerJobTypeCriteria.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerRampUpCriteria.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageVersionMetadataResponseDTO.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-web-server/src/main/java/azkaban/webapp/ContainerizedClusterStatus.java
azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ServletUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/StatusServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/StatusServiceTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java
azkaban-web-server/src/test/resources/azkaban/webapp/cluster_status
azkaban-web-server/src/test/resources/azkaban/webapp/containerized_cluster_status

- Changed the dispatch method to use ExecutableFlow to determine the job types set for the flow.
- Introduced AllowList for the containerized executions, i.e., if a job-type in a flow is not part of allowList, then it won't be executed as part of Containerization but will be polled by the executor-server.
- Introduced the API to update the property for overwriting, appending to, and removing from the allowlist. It will also allow updating ramp-up percentages.
- Fixed the changes in the status page to show both executors and image statuses.
- Added containerizationRampUp and containerizationJobTypeFilter to the status page.
- Added visibilityChecker to the ObjectMapper in StatusServlet to use only the fields which are specifically marked as JsonProperty as part of converting the object to …

Added jobtype based filtering for containerization ramp-up

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerImplUtils.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerRampUpCriteria.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManager.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java

Current ramp-ups use the random generator to determine the version, which can lead to different executions of the same flow to have different versions.
This implementation uses flow name, compute murmur hash, map it to an integer value between 1 to 100, and determine the ramp-up version.
Implementation of hash is in ContainerImplUtils.java

Flow deterministic ramp-ups for imagetype and containerization

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageRampupDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageVersionMetadataResponseDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageRampup.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageVersionMetadataServiceImpl.java
azkaban-web-server/src/main/java/azkaban/webapp/StatusService.java
azkaban-web-server/src/test/java/azkaban/webapp/StatusServiceTest.java
azkaban-web-server/src/test/resources/azkaban/webapp/containerized_cluster_status

Updated ImageRampup to have releaseTag as a field.
Updated SELECT_ALL_IMAGE_TYPE_RAMPUP_QUERY query to return releaseTag.
Updated FetchImageTypeRampupHandler to put releaseTag from the result-set to  ImageRampup
Updated ImageVersionMetadataResponseDTO to have releaseTag as a field.
Updated the test StatusServiceTest to validate that releaseTag is visible as part of status JSON.

Add release tag as a part of status API for each version

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/utils/ExternalLink.java
azkaban-common/src/main/java/azkaban/utils/ExternalLinkUtils.java
azkaban-common/src/test/java/azkaban/utils/ExternalLinkUtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutionFlowViewTest.java

Changes in this PR:
1. Add new Azkaban configs to support multiple external links in the UI. The configs are:
```
azkaban.server.external.analyzer.topics
azkaban.server.external.analyzer.${topic}.label
azkaban.server.external.analyzer.${topic}.url
```
To have 2 external links, for example, following configs should be added to the web server configuration file (azkaban.properties) :
```
azkaban.server.external.analyzer.topics=myAwesomelLink,anotherExternalLink
azkaban.server.external.analyzer.myAwesomelLink.label= My Awesome Link
azkaban.server.external.analyzer.myAwesomelLink.url =https://my-awesome-link.com/
azkaban.server.external.analyzer.anotherExternalLink.label= Another External Link
azkaban.server.external.analyzer.anotherExternalLink.url =https://another-external-link.com/
``` …

Add support for multiple external links on the Flow Execution page

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/NumExecutionsDaoTest.java

The changes in PR 2778, force webserver and executor-server to be deployed in parallel. If one is on an older version, flows will not be polled. Hence, reverting the change.

[REVERT-2778] Changed start status to READY instead of PREPARING for poll based dispatch

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java

If there are any flow parameters provided with prefix of "_pod.env.var._" then those will be set as environment variable for the Pod.

Adding a way to setup env variables for a pod which can be honored from pod side.

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/HadoopModule.java
azkaban-common/src/main/java/azkaban/storage/HdfsStorage.java
azkaban-common/src/main/java/azkaban/storage/LocalHadoopStorage.java
azkaban-common/src/main/java/azkaban/storage/LocalStorage.java
azkaban-common/src/test/resources/hdfs_conf/core-site.xml
azkaban-common/src/test/resources/hdfs_conf/hdfs-site.xml

Previously, Azkaban always expected the HDFS scheme to be available in a Hadoop installation, so it would choose a default HDFS configuration when it didn't find the corresponding (HDFS specific) properties in the Hadoop configuration files. This is OK as long as a HDFS file system is available (possibly alongside others), but causes problems when it's not.
To fix this I'm removing the default Hadoop configurations provided by Azkaban, since, in practice, HDFS is usually and should be configured in Hadoop's config files. Although this is not a backward compatible change and issues may arise for those with Hadoop configurations not defining a file system properly this should be very rare.
Also, this change includes refactoring of the HadoopModule class (use of constants in the named …

Allow Hadoop to be configured with FileSystem implementations not using the 'hdfs://' scheme.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/server/JettyServerUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiClientTest.java
azkaban-exec-server/src/main/java/azkaban/common/ExecJettyServerModule.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-exec-server/src/test/java/azkaban/common/ExecJettyServerModuleTest.java
azkaban-web-server/src/main/java/azkaban/webapp/WebServerProvider.java

Refactored the getSocketConnector() and getSslSocketConnector() from WebServerProvider class to JettyServerUtils class so that it can be reused in ExecJettyServerModule
Added the ExecJettyServerModuleTest to check if the correct props are set-up when SSL is enabled/disabled.

Making ExecJettyServer TLS aware

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java

In containerization, When the dispatch method is containerized based on the ramp and jobtype filter, then start status should be READY otherwise PREPARING

Set start status for Containerized exectuions based on the dispatch method

---

azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java

Also setting flow execution status to FAILED when dispatch has failed once on Kubernetes

Using lower case for jobtype in volume name

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/index.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/login.vm
azkaban-web-server/src/web/js/azkaban/view/login.js
azkaban-web-server/src/web/js/azkaban/view/main.js

Very simple couple of fixes (mostly to try out the PR mechanics).
When you open the login dialog, the focus is not in the username input field. It would have to be there.
If you start typing, your input is not picked up.
When you open the Create New Project dialog, the focus is not in the project name input field.
It would have to be there.

Focus on Login, Create Project Dialogs

---

azkaban-common/src/main/java/azkaban/database/DataSourceUtils.java
azkaban-db/src/main/java/azkaban/db/MySQLDataSource.java
build.gradle

This change upgrades the mysql connector version and makes code changes
to use the new connector. Using conector version 8 helps with using
MySQL DB version 8 for Azkaban while maintaining compatability with
version 5.x

Upgrade mysql connector version in Azkaban to 8.0.20

---

azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java

A small fix for https://github.com/azkaban/azkaban/issues/1917
This issue is originally caused by the initialization function at https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java#L58 leaving this field null.
Adding a null check, which returns with the same value as the exception would result in. (Empty list)
This change does not change the behavior of anything except the log output.

Adding null check to avoid NPE in logs (Fixes issue #1917)

---

azkaban-web-server/src/web/js/azkaban/util/ajax.js
docs/ajaxApi.rst

because GET has url length limitation, this will cause problem when we have a large flow, and we disable a lot of the job inside, as the disabled jobs list will need to be included in the request param.

use POST instead of GET for executing flow

---

azkaban-db/src/main/sql/create.project_events.sql
azkaban-db/src/main/sql/upgrade.4.10.0.to.4.11.0.sql

User actions on projects are recorded in the DB and available for inspection.
Examples of those actions are uploading a new zip file, granting permissions to users and adding/modifying/deleting job properties in a flow through the UI.
When users update multiple job properties at a time or the value of one of them is very long it can happen (we often see it in the web server logs) that the event fails to be saved in the DB because the log message is too long.
To account for those scenarios the size of the MySQL column storing the log message is increased.

Allow longer project events to be recorded.

---

azkaban-db/src/main/sql/create.project_events.sql
azkaban-db/src/main/sql/upgrade.4.10.0.to.4.11.0.sql

This is a follow up on PR #2841 to adjust VARCHAR size of `message` column in `project_events` table based on the SQL statement in [upgrade.3.43.0.to.3.44.0.sql](https://github.com/azkaban/azkaban/blob/master/azkaban-db/src/main/sql/upgrade.3.43.0.to.3.44.0.sql#L8):
```
ALTER DATABASE <database_name> CHARACTER SET utf8 COLLATE utf8_general_ci;
```
which indicates that the Azkaban DB should be using utf8 charset. 
That encoding uses 3 bytes per character for storage so the max size for a VARCHAR column is 65535 (row size)/3=21845.

VARCHAR column lengths cannot exceed 21845 when DB/table uses utf8 encoding.

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageRampupDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java
azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java
azkaban-common/src/test/resources/image_management/all_image_types_new_and_rampup_version.json
azkaban-common/src/test/resources/image_management/image_type_rampups.json
azkaban-web-server/src/test/resources/image_management/image_type_rampups.json

Make the rampup logic more deterministic by sorting the result images by versionID.
Updated the input JSONs for tests in sorted order as it would be if it were queried from the db.

Make the rampup logic more deterministic by sorting the result images by versionID.

---

az-jobsummary/src/main/java/azkaban/viewer/jobsummary/JobSummaryServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/less/header.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailsheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/propertypage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/style.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm

When you are visiting Job Pages, there is no way to go back to the main flow, not to mention the intermediate sub-flows. The only way you have is either going to the sub-flow where the job belongs, or first going all the way back to the project, and then to the main flow and sub-flows from there:
When you are visiting a Flow Page, there is no way to go back to the main flow, not to mention the intermediate sub-flows. The only way you have is first going all the way back to the project, and then to the main flow or other sub-flows from there:
Nested flows are now directly accessible via detailed breadcrumbs in FlowPages and JobPages.

Adds Granular Breadcrumbs to Flow, Job, Job Properties and Execution Pages

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowgraphview.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/model/svg-graph.js
azkaban-web-server/src/web/js/azkaban/util/flow-loader.js
azkaban-web-server/src/web/js/azkaban/util/layout.js
azkaban-web-server/src/web/js/azkaban/util/svg-navigate.js
azkaban-web-server/src/web/js/azkaban/view/context-menu.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js
azkaban-web-server/src/web/js/azkaban/view/flow.js
azkaban-web-server/src/web/js/azkaban/view/svg-graph.js
docs/configuration.rst

Flows in the graph are now recursively open up to a certain *azkaban.depth* value, set in the Azkaban configuration file , with a default value of 2.
There are 3 new commands in the graph context menu, which allow for the direct recursive flow expansion up to 1, 2 or 3 levels down.
- *Auto Pan Zoom* is now by default preset to ON 
- If *Auto Pan Zoom* is ON, *Reset Pan Zoom* will be automatically applied whenever a flow is collapsed or expanded in the graph.
(Context menu, normally hidden, is shown for demo purposes only)
(Context menu, normally hidden, is shown for demo purposes only)

Graph Manipulation Enhancements

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest1.yaml
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest2.yaml

For some volume mounts like nscd, it needs to be marked as read only for security reason. If it doesn't need to be kept read only then that can be set from property as well
azkaban.kubernetes.pod.nscd.mount.read.only=false

Marking nscd mount as read only

---

az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/AvroFileViewer.java
az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/ParquetFileViewer.java
build.gradle

This reverts commit 5e9c5fd94b0f35bb1693d5b3e187738b9467c36b.
Reverting this change temporarily as it breaks visualization of file contents on the HDFS viewer plugin. 
The issue is: Files that should be handled by the `TextFileViewer` (like JSON files) are now incorrectly handled by the `ParquetFileViewer`.

Revert "Use Apache's Parquet-Avro which uses Avro 1.9.2 (#2810)"

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java

If one token fails to cancel, it's a poor reason to abort the loop
and not cancel the rest of them. Also, for debugging purposes it's nicer
if all the tokens are listed in the log -- not just those up to the failed one.

Make cancelTokens loop robust to individual token failure

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowgraphview.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/model/svg-graph.js
azkaban-web-server/src/web/js/azkaban/view/job-list.js
azkaban-web-server/src/web/js/azkaban/view/svg-graph.js

Since the newer auto-expand feature is not a desired capability for all users, a configuration switch is now included in the flow menu in the graph.
The default value is auto-expand. The setting is saved in local storage. So it applies to the user, on her workstation. It is saved from session to session, but not across devices.
Click on it to expand it.
Click on it to disable the flow auto-expansion feature.  Once you disable it in a graph, it will stay that way for all the graphs, unless you click again to enable the named feature.
Likewise, the **Auto Pan Zoom** setting is now also saved in local storage.

Auto-Expand Toggle Switch

---

azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/propertypage.vm

In the Job page, job inherited properties are not generated properly for flows using Flow 2.0. 
Here is what's currently rendered for an embedded job:
**Issues**:
-The `longLongs.flow` link suggests that root flow properties will be displayed when clicked but in fact the properties of direct parent (emb_5) of job jobE5B are shown instead.
-Properties inherited from parents emb_3, emb_2 and root flow itself are not available for inspection.
With changes in this PR inherited properties from all parents are listed and loaded correctly:
Example Properties Page:
**Test** the changes locally. I verified that inherited properties continue to load correctly for flows using Flow 1.0.
**Follow up**:
-Populate the sections `Inherited From` and `Source of` in the Property Page for flows written with …

[UI] Load all inherited properties in Job Page for flows using Flow 2.0.

---

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/flow/CommonJobProperties.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

**Change:** read the `failure.action` key specified in the Yaml and use it in the ad-hoc executions. Optionally, the user can override the value by explicitly passing the request param failureActionOverride=true. In this case, we will give precedence to the value the user passes through UI or API. 
**Testing:** 
1. Tested by having a sample workflow that has the following config section and another workflow that doesn't have this config section. I was able to see the `failure.action` value getting used in the first case, and in the second case, we picked the default value. 
<pre>
config: 
failure.action: finish_all_possible
</pre>
2. when we pass the additional param `failureActionOverride=true` the value selected in the UI or the value passed in the API gets used. In the UI, we should …

Added a way to read failure action specified in the Yaml

---

azkaban-common/src/main/java/azkaban/utils/FileIOUtils.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java

Turns out that System.currentTimeMillis() is not a safe way to create temporary files.
Also we sometimes fail to delete temp dirs that we create for project downloads.

Intermittent testSetupFlowByMultipleThreads failures

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java

This is an effort in continuation to https://github.com/azkaban/azkaban/pull/2856 (Added meter metrics for Azkaban pod statuses)

Add metrics for time to dispatch a Kubernetes pod, number of flows dispatched to containers and to bare metal executors

---

azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java

Various tests in azkaban.executor.ContainerizedDispatchManagerTest were failing with the error:
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
RegularImmutableMap cannot be returned by selectAndUpdateExecutionWithLocking()
selectAndUpdateExecutionWithLocking() should return Set
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
- with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
**This failure occurs because:**
the mocked …

Fixing intermittently failing ContainerizedDispatchManagerTest

---

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/test/java/azkaban/jobtype/JobTypeManagerWithDynamicClusterTest.java

Post https://github.com/azkaban/azkaban/pull/2786, after JobRunner.createJobParams() is called, the JobRunner may have dangling references in jobProps that it passed in to createJobParams().
This is because in PR-2786, we added the cluster-specific properties to a new instance of Props, `finalProps`, while still adding properties that may reference cluster-specific ones to `jobProps`. The `finalProps` is passed to Job constructors, which is fine. But `jobProps` might be left with dangling references to cluster-specific properties that can never be resolved.
JobCallbackManager is one place where `jobProps` of the jobRunner is consumed after JobRunner.createJobParams(). When it tries to resolve `jobProps`, it fails and drops the callback on the floor. 
In this change, we  reimplement …

JobRunner may see dangling references in jobProps post PR-2786

---

az-core/src/main/java/azkaban/Constants.java
az-jobsummary/src/main/resources/azkaban/viewer/jobsummary/velocity/jobsummary.vm
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/project/DirectoryFlowLoader.java
azkaban-common/src/main/java/azkaban/project/DirectoryYamlFlowLoader.java
azkaban-common/src/main/java/azkaban/project/NodeBeanLoader.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/project/DirectoryYamlFlowLoaderTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerPropertyResolutionTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowtriggerspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executionspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowtriggerspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobdetailspage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectlogpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/svgflowincludes.vm
azkaban-web-server/src/web/js/azkaban/model/svg-graph.js
azkaban-web-server/src/web/js/azkaban/util/ajax.js
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js

Until now Azkaban has only supported setting flat flowOverride properties that affect all jobs. While keeping that capability, this PR allows additionally overriding properties for specific jobs or sub-flows.
On the UI side the flow override is extended to be similar with job level SLA settings: there's a dropdown picker for the nested id (includes all nodes which means leaf job nodes as well as sub-flows).
----
This change is 100% backward compatible.
----
Some screenshots from the UI below.
I used this kind of flow for manual testing:
The new thing in UI is the Flow/Job dropdown:
An example of some rows entered:
And log lines on how that's reflected in the backend: 
----
Should the docs be updated to include this?

New feature: node specific flow overrides

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/executor/container/watch/AzPodStatusMetadata.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java

Introduces a flow parameter `disable.pod.cleanup`, if it's set
the flow-pod will not be auto-cleaned after flow execution ends.

Add param for disabling pod cleanup

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java

This works better when containerization is enabled.

Use Webserver host name instead of Executor host name for Grid Attribution.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypePluginSet.java
azkaban-common/src/test/java/azkaban/jobtype/JobTypeManagerTest.java
azkaban-common/src/test/resources/plugins/jobtypes/commonprivate.properties
azkaban-common/src/test/resources/plugins/jobtypes/default-proxy-users.properties
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java

In the current setup, Azkaban allows users to define a “user.to.proxy” property for each Azkaban Job irrespective of the Azkaban JobType. If such a property is defined, Azkaban will ensure that the Azkaban Job process will get executed as the “user.to.proxy” UID.
Azkaban will honour the “user.to.proxy” only when it is also added as part of the “Proxy Users” section under Azkaban project permissions.
Azkaban Job Type owners/developers require their Azkaban Job to always be executed as a default “user.to.proxy”, irrespective of the property defined in the Azkaban Job Properties or the submitting user.
The solution is to provide the optional ability to define a default proxy-user mapping for the Job Type. If such a mapping is defined then,
- Azkaban won’t check if the proxy user defined in …

Introducing the defaultProxyUser feature for the jobTypes

---

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java

Avoid NPE in FlowContainer.shutdown() if flowRunner is NULL. It happens when for some reason, the flow never starts.

Avoid NPE in FlowContainer.shutdown() if flowRunner is NULL. 

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/WebUtils.java
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/historypage.vm
azkaban-web-server/src/web/js/azkaban/util/job-status.js
azkaban-web-server/src/web/js/azkaban/view/exflow.js

A new state will help identify flow failures due to pod (k8s) related failures.
Needs to account for state showing up correctly on UI
Tested on local dev box solo server and h6 web server.

added flow status for pod failure

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java

In containerized executions, when a pod crashes, the jobs need to be in a terminal state. This PR aims to fix a bug that when a flow was finalized from RUNNING to FAILED/EXECUTION_STOPPED due to pod failure, the job nodes showed KILLING status.

set job status to terminal state when pod goes down

---

azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageVersionMetadataResponseDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java
azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java
azkaban-common/src/test/resources/image_management/all_image_types_active_version.json
azkaban-web-server/src/test/resources/azkaban/webapp/containerized_cluster_status

- After deterministic ramp up, a version is selected based on the ramp-up percentages of job types and the hash value derived from the flow name.
- However when the flow is not specified, currently the first element in the ramp-up plan will be selected. Flow is not specified when loading the status page. This creates an abnormal state on the staus page.
- This change, makes sure that in such a scenario, the latest active version will be shown in the UI.
**Note:** This change doesn't affect the actual flow executions, as the flow object passed won't be null in such cases.

Status page should show latest active version for containerized status

---

azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1PodTemplate.java
azkaban-common/src/main/java/azkaban/container/models/PodTemplateMergeUtils.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java
azkaban-common/src/test/resources/azkaban/container/models/v1PodTest2.yaml
azkaban-common/src/test/resources/azkaban/container/models/v1PodTestTemplate1.yaml

The current merge method for init containers from the pod-spec template and dynamically generated pod-spec is a simple append to the list, i.e. take all the init containers from the dynamically generated pod-spec and take only those init containers from the pod-spec template which are not part of generated pod-spec.
However, the init containers from generated pod-spec are relatively simple with only a couple of env variables, one fixed volume which gets mounted to the init container as well as flow container. There is a need for more complex init containers where the complex part can come from the pod-spec template.
This change updates the merge method for init containers from the pod-spec template and dynamically generated pod-spec, such that:
1) Add all the init containers which are …

Merge containers from pod-spec template and dynamically generated pod-spec

---

azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java

Similar to https://github.com/azkaban/azkaban/pull/2860. Prevent Hadoop env vars from being passed from upstream jobs.

Add Hadoop env vars to list of non-overridable properties

---

azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1PodTemplate.java
azkaban-common/src/main/java/azkaban/container/models/PodTemplateMergeUtils.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/container/models/AzKubernetesV1PodBuilderTest.java

After the PR https://github.com/azkaban/azkaban/pull/2913 
azkaban.container.models.PodTemplateMergeUtils#mergePodSpec 
makes changes in the Pod generated from the Template which is a singleton and has only one instance of Pod stored internally. Hence multiple executions lead to corruption of the same instance of POD in the singleton class.
This can be fixed by making sure that a new instance of POD is generated from the template every time during the course of pod spec creation. Since this instance will be local to the method, multiple threads won't affect it.

Using a new instance of V1PodSpec from the template to avoid corruption from previous merging of pod-specs

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowexecutionpanel.vm
azkaban-web-server/src/web/js/azkaban/view/flow-execute-dialog.js

Proposing an alternative fix for the issue of https://github.com/azkaban/azkaban/pull/2924:
> Users have requested that Azkaban be changed so that Runtime Properties are easier to delete.
> Before: The delete button is only available on mouse over, and is a child element of the Value cell.
After: The delete button is always visible on all rows and has its own "column" in the table:

Always show delete button of runtime properties

---

azkaban-common/src/main/java/azkaban/database/AzkabanDatabaseSetup.java

I tried to run `AzkabanSingleServer` locally (using h2 db), got this error:
```
2021/08/27 22:02:25.501 +0300  INFO [AzkabanDatabaseSetup] [main] [Azkaban] The following are missing tables that need to be installed
'2021/08/27 22:02:25.502 +0300  INFO [AzkabanDatabaseSetup] [main] [Azkaban]  containerization-tables-all'
2021/08/27 22:02:25.502 +0300  INFO [AzkabanDatabaseSetup] [main] [Azkaban] No tables need to be updated.
2021/08/27 22:02:25.502 +0300 ERROR [AzkabanWebServer] [main] [Azkaban] Exiting with error.
```
Fixing this bug in the same way as had been previously done for a similar `quartz-tables-all` script.
But I also tried to improve the check for both of these special cases: making it a bit more strict. Now it should catch if these scripts have not been run at all. So instead …

Fix startup error of missing containerization-tables-all

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/executor/container/watch/ContainerStatusMetricsListener.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetrics.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/main/java/azkaban/metrics/DummyContainerizationMetricsImpl.java
azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

The new metrics `executionStopped` that records number of flow executions stopped due to container infra failure and `containerDispatchFail` that records number of container dispatch failure are essential for health monitoring of containerized azkaban clusters.

Add metrics for pod dispatch failure

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/main/java/azkaban/executor/OnExecutionEventListener.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

This task is an on-going effort in continuation to:
1. added flow status for pod failure (#2892)
2. set job status to terminal state when pod goes down (#2907)
Context:
Add flow cleanup for abrupt pod terminations. Azkaban finalizes the flow and sets it to a new terminal flow state EXECUTION_STOPPED  that better indicates a pod failure. 
This work:
Based on user setting in flow parameters,  the flow could:
1. [default option] remain in EXECUTION_STOPPED state, waiting for further actions from user
2. restart the overall execution with a new execution id

Add restartability when flow is in EXECUTION_STOPPED state

---

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManager.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java

Context:
The IMAGE-A is new so there is no active version or ramp-up plan. It seems dispatch looks for those and errors out like this:
```
2021/08/25 17:31:46.533 +0000  INFO [ImageRampupManagerImpl] [pool-15-thread-7] [Azkaban] After fetching version using ramp up and based on active image version the image types remaining: [image-a]
2021/08/25 17:31:46.533 +0000 ERROR [StdOutErrRedirect] [pool-15-thread-7] [Azkaban] Exception in thread "pool-15-thread-7"
2021/08/25 17:31:46.533 +0000 ERROR [StdOutErrRedirect] [pool-15-thread-7] [Azkaban] azkaban.imagemgmt.exception.ImageMgmtException: Could not fetch version for below image types. Reasons:  1. There is no active rampup plan in the image_rampup_plan table. 2. There is no  active version in the image_versions table. Image Types: [image-a] …
```

Fixed dispatch stuck bug when no active version and user uses pinned image

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-common/src/test/java/azkaban/jobtype/JobTypeManagerWithDynamicClusterTest.java
azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java

When using cluster routing method to execute jobs, some properties required to fetch token from HadoopSecurityManager
are overridden. It happens because the cluster routing properties which contain the specific property become part of jobProps,
whereas the default cluster routing property is part of the job's sysProps.
These properties are merged in AbstractProcessJob.getAllProps() where the default property in sysProps overrides the correct
property from jobProps.
This patch uses azkaban property AZ_PLUGIN_LOAD_OVERRIDE_PROPS to fetch list of properties which must be overridden
using cluster router properties into sysProps.
However, the sysProps object is unique per jobtype so it is cloned and the cloned copy is used thereafter thus preserving the
original copy of pluginLoadProps.

When using cluster routing method to execute jobs, some properties need to be overridden.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/build.gradle
azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-exec-server/src/test/java/azkaban/container/FlowContainerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestBase.java
azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
build.gradle

This change adds the comma-separated list of effective users across all the jobs to the FLOW_FINISHED_EVENT. This enables us to determine at one place all the effective users for a flow.
This change also exposes the method to set CPU and MEMORY Utilization as part of FLOW_FINISHED_EVENT. However, this method is currently called only by the FlowContainer, i.e., for containerized executions. It reads the data of CPU and Memory requested from the Container ENV variables.

Set flow effectiveUsers and resource utilization to FLOW_FINISHED_EVENT

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java

Parent class AbstractExecutorManagerAdapter does implement the doRampActions method which allows making rampup changes for the executors. 
Once containerization is enabled, ContainerizedDispatchManager is utilized. Hence even if the rampup is not 100%, we see UnsupportedOperationException which shouldn't be the case.

Removing method doRampActions from ContainerizedDispatchManager and utilize super method

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageVersionDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageVersion.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageVersionServlet.java

The Image Management APIs allow multiple image versions of same type to remain in ACTIVE state.
This leads to unexpected behavior of getting incorrect version among the ACTIVE ones for executing flows.
Introducing new image version state STABLE.
If an image is set as ACTIVE using the ACTIVATE API, all the other image versions which are currently
set to ACTIVE will be set to STABLE state.

Allow only one ACTIVE image version for a given image type.

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/project/FlowLoaderUtils.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

Add logic to load certain flow properties and merge flow parameters on top of it.
The logic to load flow properties from YAML file is refactored from FlowRunner to FlowLoaderUtils for reuse.
It is used to add support for flow2.0.
Only flow properties with prefix "param.override" are filtered and then flow params are added.

Add logic to load certain flow properties and merge flow parameters on top of it.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java

clusterEnv is the class variable that will be set using property azkaban.cluster.env, which defaults to class variable clusterName for backward compatibility.

Utilize azkaban.cluster.env property to set the AZ_CLUSTER ENV variable for containerization

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java

This also adds requirement for users to create param_override.properties which will contain all override properties.
Updated the tests accordingly.

Use fetchProperty instead of fetchProperties which is compute heavy and has memory leaks.

---

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java

If the version is updated before property files are uploaded there can be a race condition where a flow comes in and uses the updated version and webserver may need to use one of the project properties which are not yet uploaded.

Move the project upload version update to the very end after all the project related files are uploaded in the db.

---

azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

The onExecutionEventListener was not getting initialized and hence when trying to restart the flow we were facing NPE.
This change fixes the issue by instantiating it at the start of the webserver.

Instantiate OnExecutionEventListener for Containerization

---

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java

Limit multipliers are initialized in the constructor which can be configured through AzkabanProperties. However, if the requests are from flow param, then the default values of multipliers are utilized rather than the initialized ones.

Use limitMultiplier from the config rather than default

---

azkaban-common/src/main/java/azkaban/container/models/PodTemplateMergeUtils.java

When pod spec template does not have labels or annotation in metadata, it will fail without the null check added in this PR. For safety reasons, I have also added null check for labels and annotation metadata for dynamic pod spec as well.

Adding null check for labels and annotations for Pod spec

---

azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/test/java/azkaban/project/ProjectManagerTest.java

This change is done to pass on the additional information related to updated UserPermissions and GroupPermissions after a change in permission is made. Since the metadata that is provided to KafkaEvent reporter is of type String so tried to convert the Hashmap's value to a string which can be then split back into String by event reporter later.
**How change is tested:**
Added respective test cases.

Adding UserPermissions and GroupPermissions to the Permission Change Event

---

az-core/src/main/java/azkaban/Constants.java
az-core/src/main/java/azkaban/metrics/MetricsManager.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-web-server/src/main/java/azkaban/webapp/metrics/WebMetricsImpl.java

Azkaban uses the Dropwizard Metrics library to collect metrics to gauge how the app is doing. To report those metrics for proper storage and plotting for example, it allows custom reporters to be hooked in.
Before, to connect a custom reporter the fully qualified name of its class had to be provided in a config property and the class should have a constructor with the following signature: `(String reporterName, MetricRegistry registry, String metricsServerURL, Boolean someFlag)`
This approach leaks LinkedIn specific settings for reporting and forces users to implement a constructor with parameters that might not make sense to them. In addition, it's not extensible as to accommodate new configs, in the past the constructor signature has been modified making it a backward incompatible …

Make metrics reporting more open source friendly.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java
azkaban-common/src/main/java/azkaban/utils/ExecuteAsUserUtils.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java

Where this change will help? 
In case of containers running in Kubernetes, we might not have linux users and groups available. In that case, Azkaban jobs will start failing. With the help of this change, it will add user and group for effective user before any job starts.
How to enable group and user addition for any flow execution?
The property introduced to enable group and user addition is: azkaban.add.group.and.user.for.effective.user. Set this property in commonprivate.properties to true and it will enable group and user addition prior to start of any user job process.

Adding a way to add group and user in case environment doesn't provide it by default. It is controlled by property.

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageTypeDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageTypeDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageTypeDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageOwnership.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageTypeService.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageTypeServiceImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageTypeServlet.java
azkaban-web-server/src/test/java/azkaban/imagemgmt/services/ImageTypeServiceImplTest.java

Adding image management APIs for updating and deleting.
**_Query Params for POST Request:_**
session.id = "Insert session id from browser here"
updateImageOwners = "removeImageOwners OR addImageOwners"
**_Body for POST Request (Required Parameters):_**
```
{
"imageType": "utktest",
"ownerships":[{"owner": "jakhani", "role": "ADMIN"},
{"owner": "djaiswal", "role": "ADMIN"}]
}
```

Adding update and delete APIs for imageType image management API

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java

Verified flow status reported in the flow life cycle event.

Set finalized flow finalFlowStatus so that Azkaban event reporter can report correct flow status

---

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java

Skip executions dispatched to bare metal executors when searching for stale containerized executions.

ContainerCleanupManager logic should only process containerized executions

---

azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java

There's bug when traversing a special DAG like A->A->B->A, where A and B are different effective users. The CWD ownership would be A->A->B->B instead of A->A->B->A. This is because the TEMP_FILE created in the second job would persist (which A always has write permission to this temp file) and violates the logic to check whether current effective user has write permission in CWD.
Therefore, if TEMP_FILE is created, it should be destroyed at the end of the function.
A test has conducted with a flow DAG of job1(proxy user A)->job2(proxy user A)->job3(proxy user B)->job4(proxy user A).
In job4's log:
08-02-2022 23:27:35 PST job4 INFO - Changing current working directory ownership
08-02-2022 23:27:35 PST job4 INFO - Change ownership of …

Fix bug in canWriteInCurrentWorkingDirectory, delete TEMP_FILE user_can_write in current working directory if it exists

---

azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java

The transition to CONTAINERIZED dispatch model from POLL model can be done gradually by splitting the workload between the 2. In the scenario where both dispatch models are in use both of the logics to cleanup stuck executions are needed.
This PR adds a workaround to run the `ExecutorHealthChecker` thread from POLL dispatch when Containerization is enabled. The `ExecutorHealthChecker` thread will start only if the properties `azkaban.executor.healthcheck.interval.min` and `azkaban.executor.max.failurecount` are configured in the _azkaban.properties_ file.
A better solution would be to support multiple dispatch models in the web server instead of just one. 
Testing: 
-Added unit test to make sure the Polling cleanup logic processes executions with POLL dispatch method only.
-Verified that …

Add ability to execute the Polling cleanup logic in Containerized dispatch model

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

This change is done to pass on the additional information related to the source or trigger of Flow's execution to the FlowStatusChangedEvent's metadata.

Adding information about EXECUTION_SOURCE in FlowStatusChangeEvent's metadata

---

build.gradle

When running Azkaban on a new Ubuntu, email sending started failing like this:
```
2021/11/03 11:50:20.237 +0000 ERROR EmailMessage
Connecting to SMTP server failed, attempt: 4
javax.mail.MessagingException: Could not convert socket to TLS;
nested exception is:
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1918)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:652)
at javax.mail.Service.connect(Service.java:295)
at azkaban.utils.JavaxMailSender.connect(JavaxMailSender.java:34)
at azkaban.utils.EmailMessage.connectToSMTPServer(EmailMessage.java:222)
at azkaban.utils.EmailMessage.retryConnectToSMTPServer(EmailMessage.java:232)
at …
```

Upgrade javax.mail to 1.6.2

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedImpl.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java

Verified in test cluster:
```
2022/02/24 07:05:10.161 +0000  INFO [KubernetesContainerizedImpl] [azk-container-cleanup] [Azkaban] Cleaning up containers older than 10 days
2022/02/24 07:05:10.226 +0000  INFO [KubernetesContainerizedImpl] [azk-container-cleanup] [Azkaban] Deleting stale pod fc-dep-xxxxxxx-439102
2022/02/24 07:05:10.226 +0000  INFO [KubernetesContainerizedImpl] [azk-container-cleanup] [Azkaban] Getting Pod Events for execution Id 439102
2022/02/24 07:05:11.439 +0000  INFO [KubernetesContainerizedImpl] [azk-container-cleanup] [Azkaban] ExecId: 439102, Action: Pod Deletion, Pod Name: fc-dep-xxxxxxx-439102
2022/02/24 07:05:11.440 +0000  INFO [AzPodStatusDrivingListener] [Thread-16] [Azkaban] WatchEvent for pod fc-dep-xxxxxxx-439102 : AZ_POD_READY
2022/02/24 07:05:11.440 +0000 …
```

Enable periodic bulk cleaning up stale containers in current Azkaban cluster and namespace via ContainerCleanupManager

---

azkaban-hadoop-security-plugin/src/main/java/azkaban/security/HadoopSecurityManager_H_2_0.java

extraHcatTokenCound should only be checked when extra metastore token is requested. Tested changes on test cluster.

Fix hadoopSecurityManager on bare metal executor

---

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java

Currently public methods of the class `KubernetesContainerizedImpl` do not gurantee any thread-safety. Method `deleteContainer` in particular is executed from several different threads. Arguably 'createContainer` can also be executed from different threads (depending on the exact dispatch logic)
Among synchronized, BlockingQueue, atomic variables and stateless design, synchronized keyword seems to be the best way to go considering that:
1. It is recommended to use coreV1Api class per thread: coreV1Api class is not thread-safe from this github [page](https://github.com/kubernetes-client/java/issues/100).
2. In CreatePod method, we access sql db multiple times and do read+write operations. Guarantee the read-write ordering is much safer (no need to think through the side-effect of …

Thread safe kubernetes containerized impl

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/FlowStatusChangeEventListener.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java

In containerized azkaban executions, auto restart is enabled for flow failed due to Kubernetes failures in PREPARING stage. Right now the Azkaban flow life cycle events emitted for original and retry are the same. There needs to be a way to distinguish between retries and originally failed flow execution in the azkaban events.
Validation:

Get event data distinguishable for flow retries

---

azkaban-common/src/main/java/azkaban/executor/ExecutorHealthChecker.java

Adding a log to the executor health checker class to capture ping time /success/ time-out of ping.

Logging time for executor ping

---

azkaban-exec-server/src/main/java/azkaban/cluster/ClusterModule.java

In the past, routerConfPath should be relative to classpath but it is not what we want when we first look at the code -- error-prune. Changing this to a local file path instead: i.e. relative to the current program execution path.

Use local path instead of name for adding hadoop configuration

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java
azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java

Users can control whether to auto retry the EXECUTION_STOPPED flows.

Retry EXECUTION_STOPPED executions when allow.restart.on.execution.stopped:true is added to flow parameters/runtime properties

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java

Bug fix. Validity should be positive when used to determine if a container is stale or not.

Check validity negative before cleaning up stale containers

---

azkaban-common/src/main/java/azkaban/executor/container/watch/AzPodStatusExtractor.java

Since the pod goes into Running status very quick in AKS, so when the pod is running, the container is not ready yet, which cause https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/executor/container/watch/AzPodStatusExtractor.java#L578 fall into AZ_POD_UNEXPECTED.
In this case,  it make more sense to let it move to AZ_POD_APP_CONTAINERS_STARTING status.

Fix the pod status mismatch when pod is running but container is not ready

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJavaJobRunnerMain.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/JavaJobRunnerMain.java

Remove ConsoleAppender from HadoopJavaJobRunnerMain  as it is not needed anymore.
It breaks compatibility with applications using log4j2.

Remove ConsoleAppender from HadoopJavaJobRunnerMain 

---

az-core/src/main/java/azkaban/Constants.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java

Use ".override" instead of "param.override" to remove c14n properties from pig properties

Use ".override" instead of "param.override" to remove c14n properties from pig properties

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopPigJob.java

Use removeIf API to avoid ConcurrentModificationException while removing params from paramMap.

Use removeIf API to avoid ConcurrentModificationException

---

azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java
azkaban-exec-server/src/test/java/azkaban/container/FlowContainerTest.java

Before my change, FlowContainer assumes log4j.properties file is using "logs/azkaban-execserver.log" as the log file and further uploads that local file into MySQL. The assumption can easily break if we upgrade our log4j.properties or when open source users start using containerized azkaban.
After my change, following things will be done:
1. Check if log4j rootLogger has FileAppender integrated, if yes, use FileAppender.getFile() as the log file and uploads to MySQL when process ends.
2. If not, create FileAppender internally and attach it into log4j rootLogger. Use newly created FileAppender.getFile() as the log file and uploads to MySQL when process ends.
3. Add Kafka log4j appender support into FlowContainer b/c FlowRunner's kafka log4j appender support is disabled when flow is running …

Refactor loggings in FlowContainer and add Kafka log4j appender support

---

az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/AvroFileViewer.java
az-hdfs-viewer/src/main/java/azkaban/viewer/hdfs/ParquetFileViewer.java
build.gradle

1. The changes are needed for potential avro upgrades to 1.9.2 because _EncoderFactory.get().jsonEncoder(schema, g);_ interface will be no longer available there.
2. The issue mentioned in https://github.com/azkaban/azkaban/pull/2861 is fixed by reverting the parquetAvro package changes. Reproduced successfully and verified it can work after my fix.

Revert "Revert "Use Apache's Parquet-Avro which uses Avro 1.9.2 (#2810)"" and fix Avro HDFS file viewer bugs

---

azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java

ProjectManager.createProject checks the DB for a project name twice. First through ProjectManager.getProject which checks the DB in ProjectCache.getProjectByName and then in JdbcProjectImpl.createNewProject. Since JdbcProjectImpl.createNewProject is only used within the ProjectManager.createProject method, it makes sense to remove the duplicated DB call here.
The testCreateProjectWIthDifferentCases already exists in ProjectMangerTest.

Removing unneccesary db call

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java

so that metric of NumQueuedFlows can represent actual number of queued flows; Increase ContainerDispatchFail meter when pod is cleaned up by CleanupManager when stuck in PREPARING and DISPATCHING

Set queued flows as executions in PREPARING state via containerized dispatch method

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlowBase.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalJobsTest.java

Currently the conditional azkaban workflow will return null when
attempting to resolve a variable in the job properties. However,
this leads to strange exceptions such as ones seen here:
https://github.com/azkaban/azkaban/issues/1897
"javax.script.ScriptException: <eval>:1:1 Expected ; but found {"
This is not very helpful and indicitive of what the problem is.
This changeset fails hard if required variables cannot be found,
the job name cannot be found, or the properties don't exist.
It also provides helpful other information like the available properties
that have variables to choose from.

Fail azkaban flow when conditional variable cannot be resolved

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionLogsDao.java
azkaban-common/src/main/java/azkaban/logs/ExecutionLogsLoader.java
azkaban-common/src/main/java/azkaban/logs/JdbcExecutionLogsLoader.java
azkaban-common/src/test/java/azkaban/logs/MockExecutionLogsLoader.java

Since we introduced offline logging fetching recently into Azkaban and every offline logging fetching platform has decent amount of delay from log-is-sent to log-is-available, we need flowEndTime here in order to tell if the offline logs is complete or not, something like:
If flowEndTime + offlineLogAvailableSLA >= currentTime: offline logs are incomplete
If flowEndTime + offlineLogAvailableSLA < currentTime: offline logs are complete

Add flowEndTime to fetchLogs interface

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java

There are reported slowness issues when clicking job logs button in UI when offline logs is enabled. 
The RC is: getApplicationIds function synchronously loads all logs from offline logs batch by batch (default batch size: 50000 Bytes), it can be very slow when log size is huge. Note: Most offline log fetching throughput is great but latency is worse than fetching from Nearline log MySQL.
As short-term mitigation, we will not use offline logs when getApplicationIds.
For long-term, we will improve getApplicationIds soon in these months to remove its dependency over reading job logs so this PR can be reverted after that.

Do not use offline logs when getting application ids

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java

The original logic assumes nearline logs will not be empty if flow/job is crashed (what logPodDetails PR will do). There is no need to guarantee that assumption now as logPodDetails PR is abandoned. Instead, if mysql logs is empty, we can fetch offline logs directly without any additional checking.

Return offline logs if nearline logs are empty

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java

Ignore flowShouldFailWhenConditionalParameterDoesntExist to unblock deployment

Ignore flowShouldFailWhenConditionalParameterDoesntExist to unblock deployment

---

azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/web/js/azkaban/view/exflow.js

There is a bug to load flow logs in UI: if the user click on "Refresh" button multiple times without waiting for the previous log batch to be loaded. Same log batch will be loaded together via Azkaban API and rendered in the UI.
Instead, we should do **wait** for the previous log batch to be loaded and then fetch the next batch.

Only allow fetching one batch of flow log at a time

---

azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerConditionalFlowTest.java
test/execution-test-data/conditionalflowyamltest/conditional_flow8.flow

Testing Done:
./gradlew build 
All tests passed
The tests are flaky seems due to that both runFlowOnJobOutputCondition and flowShouldFailWhenConditionalParameterDoesntExist share the same flow: CONDITIONAL_FLOW_2, which cause issue in the concurrency environment.

Fixing the inconsistent unit test failure  caused by flowShouldFailWhenConditionalParameterDoesntExist

---

azkaban-common/src/main/java/azkaban/utils/DependencyTransferManager.java

We can possibly leverage this metrics in the future to improve our system.

Log the time taken to download all thin archive dependencies

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/ImageRampRuleRequestDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageRampRule.java
azkaban-common/src/main/java/azkaban/imagemgmt/permission/PermissionManager.java
azkaban-common/src/main/java/azkaban/imagemgmt/permission/PermissionManagerImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/utils/ConverterUtils.java
azkaban-db/src/main/sql/create.ramp_rules.sql
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleService.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleServiceImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageRampRuleServlet.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageTypeServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/test/java/azkaban/imagemgmt/services/ImageRampRuleServiceImplTest.java
azkaban-web-server/src/test/resources/image_management/image_ramp_rule.json
azkaban-web-server/src/test/resources/image_management/image_ramp_rule_invalid.json

Support a Rest request to specify a rule_id, image_name, and image_version, in order to fill in denyList for the rule.
Exception would be thrown on:
- Missing requirements rule_id, image_name, image_version
- Not Authorized if creator is not the owner of image_type
- Duplicate rule_id
End2End tests including above failure cases have been operated and validated on Holdem6.
Success request would return:
< HTTP/1.1 201 Created
Otherwise would return:
HTTP/1.1 <ErrorCode> <Error Message>
for example:
HTTP/1.1 404 Unable to fetch image version metadata. Invalid image version: 0.1.169.

Implement CreateRule for RampManager

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java
azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
azkaban-common/src/test/java/azkaban/utils/YarnUtilsTest.java

**Issue to solve**: A part of the fixing / upgrade of the yarn application killing logic: make it easier to add and reuse "call yarn cluster for application ids" method later on
**Changes made**: Some simple refactor of the code, extract all the yarn-client related methods to an azkaban-common util s class
**Testing done**: 
- Added unit tests for killAppOnCluster() method;
- Tested in the bare metal exec-server on a spark flow:
1. upload both jar for az-hadoop-jobtype-plugin.jar and azkaban-common.jar to a cluster machine
2. restarted a exec-server
3. trigger the sparkFlow execution and kill it after the yarn application is created
4. verify the job log that the yarn app is killed

Extract all yarn related methods to azkaban-common as shared util library

---

azkaban-common/src/main/java/azkaban/AzkabanCommonModule.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServerModule.java

[Bug Fix]Move PermissionManager bindings from CommonModule to WebServerModule
This is caused by missing UserManager initializtion config in flow container and fail in pods. Webserver is configured to correct userManager so let's keep authorization in web server only.

Move PermissionManager bindings from Common to WebServer

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/RampRuleOwnershipDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/RampRuleOwnershipRequestDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/permission/PermissionManager.java
azkaban-common/src/main/java/azkaban/imagemgmt/permission/PermissionManagerImpl.java
azkaban-db/src/main/sql/create.ramp_rules.sql
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleService.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleServiceImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageRampRuleServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/test/java/azkaban/imagemgmt/services/ImageRampRuleServiceImplTest.java
azkaban-web-server/src/test/resources/image_management/flow_owners_update.json
azkaban-web-server/src/test/resources/image_management/hp_flow_rule.json
azkaban-web-server/src/test/resources/image_management/image_ramp_rule_without_owners.json

- Add implementation for creating ramp rule for high priority flows /createHPFlowRule Introducing "ownerships" directly in the rule creation for easy managing RampRule and serves as source of truth. For /createRule, missing ownerships would use default ImageType Owners; For /createHPFlowRule, ownerships parameter is madantory since current azkaban system does not maintain concept of high priotity flows ownership.
- Add two APIs to manage ownership management: /addOwners and /removeOwners. update ownership operation only can be done by existing owners or azkaban admin.
End to End test has been performed in the following cases success cases:
createRampRule w/ and w/o designated owners 201 Created createHPFlowRule 201 Created
add/removeOwners appropriate permission 200 OK
Failure cases: …

Implement CreateHPFlowRule and updateOwnerships

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/dto/RampRuleFlowsDTO.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/RampRuleDenyList.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-db/src/main/sql/create.flow_deny_lists.sql
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleService.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleServiceImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageRampRuleServlet.java
azkaban-web-server/src/test/java/azkaban/imagemgmt/services/ImageRampRuleServiceImplTest.java
azkaban-web-server/src/test/resources/image_management/add_flows_to_rule.json
azkaban-web-server/src/test/resources/image_management/add_flows_to_rule_invalid.json

This API supports adding flows into ramp rules. In order to query conveniently in execution layer, the DB format will use flowId (project.flow) which is formatted by ExecutableFlow.getFlowName, with its image deny metadata. For HP flow ramp rules, DB would store flowId with DenyMode.ALL; For normal ramp rules, DB would store flowId with DenyMode.PARTIAL and detailed denyVersion.
Successful request would be return 200 OK.
Failure case would include:
- Unable to authorize: user is not admin or does not pass PermissionManager validation
- Invalid inputs: inactive project or wrong flowName
- No rule created before insert flows.

Implement AddFlowsToRule for RampManager

---

azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

We should follow what we did in FlowContainer: wait for all JobRunners/FlowRunner thread to be completed first and then close the FlowRunner/FlowContainer. Otherwise, some final cleanup operations happened in JobRunners/FlowRunner will be bypassed.

Wait for all JobRunners to be closed before closing FlowRunner

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java

Currently the Trigger Scanner thread can enter a blocking wait when invoked with a timeout value of 0ms. The change prevents this indefinite blocking and adds additional logging around this.

Fix TriggerScanner to prevent a blocking object.wait()

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDaoImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleService.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/services/ImageRampRuleServiceImpl.java
azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageRampRuleServlet.java
azkaban-web-server/src/test/java/azkaban/imagemgmt/services/ImageRampRuleServiceImplTest.java

Update Version for existing RampRule will update version metadata on DB directly; while delete rule will delete all metadata related to the rule. Both API would not introduce new insert but only update existing data. Failure would occur when:
- no existing rule
- input failed validation
- no user permission

UpdateVersion and deleteRule API for RampManager

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java
azkaban-common/build.gradle
azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
azkaban-common/src/test/java/azkaban/utils/YarnUtilsTest.java

Redo #3145: Extract all yarn related methods to azkaban-common as shared util library 
* Extract all yarn related methods to azkaban-common as shared util library
* extract duplicate code to a static method
* amend header for test file

Redo: Extract all yarn related methods to azkaban-common as shared util library (#3145)

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopSecureWrapperUtils.java
azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/AbstractHadoopSecurityManager.java
azkaban-hadoop-security-plugin/src/main/java/azkaban/security/commons/HadoopSecurityManager.java

**What need to be fixed:**
Yarn Client killApplication() call never succeeds in in containerization, as the proxyUser UGI never have proper token loaded.
And this RP in combination to #3164, the yarn application kill function works correctly in containerization.
**What is being done:**
When creating the proxyUser, use HadoopSecurityManager to get tokens from the previously stored tokenFile from file system, and grand them into the proxyUser.
**Tests done:**
- Tested with multiple different flows across different clusters, 
- kill yarn application works correctly, 
- verified in yarnUI that the call is being made from the pod as the proxyUser

Load tokens from HADOOP_TOKEN_FILE_LOCATION file and add to proxy user UGI for permission

---

azkaban-common/src/main/java/azkaban/imagemgmt/daos/ImageVersionDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDao.java
azkaban-common/src/main/java/azkaban/imagemgmt/daos/RampRuleDaoImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java
azkaban-common/src/test/java/azkaban/imagemgmt/rampup/ImageRampupManagerImplTest.java
azkaban-common/src/test/resources/image_management/image_type_rampups2.json
azkaban-common/src/test/resources/image_management/test_image_type_active_version.json

Currently Ramp Manager selects ramp image version based on ramp up plan and the remaining images using current active version. Apply Ramp rule during image version fetch stage would prevent the flows to run versions to be ruled out by ramp rules. Two case for denying selected ramp version:
- flow is inside a HP flow Rule, this is the most highest priority, means the flow would not using any ramping version;
- flow is inside a normal ramp rule, this is only targets certain ramp versions that defined in the ramp rule;

Adding exclude rule into Ramp Manager during image version fetch

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java

If we delete the token file before `killAllSpawnedHadoopJobs` is called, the proxyUser cannot get the tokens from the file, and thus the kill application call will not work.
This PR is to fix this.

Don't delete the token file so as it can be used when killing yarn apps

---

azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerDeadlockTest.java
azkaban-common/src/test/java/azkaban/trigger/TriggerManagerTest.java

This change adds a meter that acts like a heartbeat for the cron scheduler. verified that metrics are emitted. This metric can be one of the signals to check the health of the scheduler.

Added a heartbeat metric in cron scheduler

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopProxy.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestAbstractHadoopJavaProcessJob.java
azkaban-common/src/main/java/azkaban/utils/YarnUtils.java

**Why we need this**: 
In future roll out, this can help fasten mitigation if we need to fallback to the old approach. 
We only need to change the `.properties` file config and ping the new config version to switch the feature.
**What's in this**:
Bring back the old logic of yarn kill, and use a config flag from `System Props` to control which approach to use
**Tests done**:
Tested in containerization, setting runtime property in UI, and the value can be passed to the jobProps for feature flagging

Read config for feature flagging of Yarn App Killing module

---

azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
azkaban-common/src/test/java/azkaban/utils/YarnUtilsTest.java

query applications with execution-id tag and un-finished application states
**Tests done**
Tested together with #3169, in the c15n pod by killing the flow after yarn apps created.

YarnUtils: Add method to call yarn getApplication api to get alive app IDs

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/event/EventData.java
azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRampManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunnerManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/event/LocalFlowWatcher.java
azkaban-exec-server/src/main/java/azkaban/execapp/metric/NumFailedFlowMetric.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java

It is a feature request.
1. If flow life cycle event is coming from subflows,  event object will have `isRootFlow=false` field
2. `subflowName` field will be attached to job life cycle events to represent the parent flow of the job
3. Use `event.getData().getNode() instanceof ExecutableFlow` to tell if an event is coming from root flow or subflow in azkaban main logic.

Emit events for subflows and add subflow names for job life cycle events

---

docs/imageMgmtAPI.rst

As part of image ramp up, Ramp Rule API user manual is added into ImageMgntAPI.rst
it includes 5 APIs:
/createRule, /createHPFlowRule, /addFlowsToRule, /updateVersion, /deleteRule
and 2 ownership management apis:
/addOwners, /removeOwners

add docs for Ramp Rule API

---

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/imagemgmt/models/ImageVersion.java
azkaban-common/src/main/java/azkaban/imagemgmt/rampup/ImageRampupManagerImpl.java

In order to expedite testing and development, any version of an image should be able to launch a pod, when enable.dev.pod is true.

Allowing images versions in all statuses to run for dev pods

---

azkaban-common/src/main/java/azkaban/utils/YarnUtils.java

Testing done:
Try to kill a yarn app which is already killed, the api call returns quickly instead of hang there for 15 mins(which is the current behavior)

Add timeout for yarnClient to avoid the api call hang

---

azkaban-common/src/main/java/azkaban/cluster/ClusterModule.java
azkaban-common/src/main/java/azkaban/cluster/ClusterRegistry.java
azkaban-common/src/main/java/azkaban/cluster/ClusterRouter.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/AzkabanExecutorServer.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/test/java/azkaban/webapp/AzkabanWebServerTest.java

**Why we need this**: WebServer need Cluster related config, so as the Cleanup Manager can get yarn related info so as later can kill dangling yarn apps.
**What's being done**: move `ClusterModule` to azkaban-common, inject to Web Server, and expose Cluster config mapping to Cleanup Manager.
**Tests done**: tested in container, successfully got the config and able to connect to yarn cluster

Refactor 'Cluster' related classes and modules, so as webServer can also read cluster-specific conf

---

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java

**Why need this**: in cleanup-manager, we need to find EXECUTION_STOPPED flows that is updated within a recent time period, and kill their yarn applications.
**What's in**: generalized a method `fetchFlowsForStatusWithTimeValidity` to allow it find flow executions that is `stale` comparing to a certain timestamp, AND also find flows `fresher` than a certain timestamp.
**Test done**: unit tests; also test in a web-server with execution_flow records inserted in DB manually, and works well.

ExecutorLoader - add fetchFreshFlowsForStatus() method to fetch fresh flows with status

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/logs/ExecutionLogsLoader.java
azkaban-common/src/main/java/azkaban/logs/JdbcExecutionLogsLoader.java
azkaban-common/src/test/java/azkaban/logs/MockExecutionLogsLoader.java

FlowStartTime and FlowEndTime timeboxing can help accelerate log search/query especially when logs are DB-indexed/DB-sharded by timestamp: i.e. we can do this after this PR to fetch logs: `select * from logs where execId=<execId> and timestamp > FlowStartTime and timestamp < FlowEndTime` instead of `select * from logs where execId=<execId>` before.

Timeboxing fetchLogs function to accelerate the log fetching

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/utils/YarnUtils.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java

**Why need this**: After get the list of Yarn Applications, we want to kill them in parallel, and report the summarized killing result.
**What's in this**: use a `FixedThreadPool` to handle all the applications' killings: in each thread create proxy user using yarn-user's name, doAs() to create yarnClient and call killApplication() API.
**Tests done**: tested in the test web-server instance with some flows having yarn applications running, the killing and reporting works well

CleanupManager - asynchronously proxy as user and kill the yarn applications

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java

**What's in this** 
1. when robin not enabled, use default `hadoop-conf-dir-path` for yarn cluster connection
2. use `yarn.application.cleanup.interval.min` as feature flag: non-positive value won't start the yarn-kill schedule
3. handle unexpected throwables for all methods, so as 1 failure won't terminate the following runs

CleanupManager - yarn app killing features wrap-ups

---

azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java

There is already a project.setVersion in the tail of this function.
A redundant project.setVersion prior to `uploading project property files` will introduce the bug described in this PR: https://github.com/azkaban/azkaban/pull/3149

Remove redundant project.setVersion line which is added by mistake

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/FlowStatusChangeEventListener.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java
azkaban-exec-server/src/main/java/azkaban/container/FlowContainer.java

1. Emit isOOMKilled and isVPAEnabled metrics to Azkaban event reporter for better offline analysis; Before this PR, isOOMKilled is only emitted to real-time metrics system which is good for monitoring and alerting but hard for large scale offline analysis.
2. LogVPAEnabled message in execution flow log to better inform users about this feature.
Validation:
1. {'isPodSizeAutoscaled': 'true', 'isOOMKilled': 'true'} in azkaban event reporter events.
2. One addition line in flow log if VPA is enabled: `2022/11/21 21:27:37.624 +0000  INFO [FlowContainer] [main] [Azkaban] This flow execution pod 123456 is autoscaled by Azkaban. If this execution ends with Out-Of-Memory Killed, please reach out to Azkaban team for help.`

Emit isOOMKilled and isVPAEnabled metrics to Azkaban event reporter and Log isVPAEnabled in flow logs

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/logs/ExecutionLogsLoader.java
azkaban-common/src/main/java/azkaban/logs/JdbcExecutionLogsLoader.java

In most cases, the timestamp for Azkaban flow logs and job logs is ahead of the flowStartTime (when flow status is set to RUNNING) b/c there are also other logs before we want to mark flow status to RUNNING.

Use flowSubmitTime instead of flowStartTime for log timebox querying

---

.travis.yml
build.gradle
gradle.properties

This PR focus on to reduce build time and fix test failures caused by OutOfMemoryException:
- increase maximum JVM allocation to 4g. (our current travis VM ubuntu has 7.5G memory)
- remove double trigger test process during test coverage report generation.
Subsequent PRs would be placed to fix other flaky tests.
First build succeed within 16m58s
Second build failed with K8sWatchTest, rerun finished in 15min 13s.
tripple time faster than other builds succeeds at 48 min 9 sec. https://app.travis-ci.com/github/azkaban/azkaban/jobs/590570434

tuning gradle build parameters on travis CI to reduce test OOM failure

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetrics.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/main/java/azkaban/metrics/DummyContainerizationMetricsImpl.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java

**Why need this**: emit metrics of counter of yarn getApplication failure and counter of failed-to-killed yarn application, so as can create dashboard and alert amongst this
**Test done**: deployed in our test web server, and verified the metrics was emitted from ingraph

CleanupManager Add YarnApplicationKillFail metrics

---

azkaban-common/src/main/java/azkaban/executor/AlerterHolder.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/executor/ExecutorHealthCheckerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/RunningExecutionsUpdaterTest.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTestUtil.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerYamlTest.java

Changes include:
-allowing multiple alerter plugins to be configured (not just one)
-failing initialization only for specific faulty plugins (not for all)
-simplifying plugin configuration (ie: by eliminating redundant config property `alert.type`) and triggering logic. Now when there is an alert-worthy event, control is passed to each installed alerter for it to decide whether something should be done or not.     
-adding more logging to plugin initialization for better troubleshooting

Refactor Alerter plugins feature.

---

az-reportal/src/main/java/azkaban/viewer/reportal/ReportalServlet.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/FlowStatusChangeEventListener.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectHandlerSet.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/project/Project.java
azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/TriggerInstanceProcessor.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

Modifying the DB query while reading Project Object metadata to ensure the project upload user information is included within it. 
Currently this is not present in the Project table and one extra JOIN us required. Since this read only once during the active project load phase it should add constant memory overhead.

Adding upload user information in project object metadata during Pod dispatch phase

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java

This is because we observe that in addition to "EXECUTION_STOPPED", other termination status flows could also have dangling yarn applications, we need to take care of them all.
Extend the current functions from only check for recent "EXECUTION_STOPPED", to check for recent flows of status in (execution_stopped, killed, killing, failed, failed_finishing, failed_succeeded, canceled).
**Tests done**
Updated & added unit tests;
Deployed and verified in staging cluster, everything works as expected

CleanupManager: check all recent termination status flow to clean yarn apps

---

az-core/src/main/java/azkaban/metrics/MetricsManager.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetrics.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/main/java/azkaban/metrics/DummyContainerizationMetricsImpl.java

So as we can know whether the cleanup manager is alive and functioning well, and get alerted if not, to prevent outages.
**Tests done**
Launched in a test web-server, able to see all the metrics in the graph dashboard.

CleanupManager: add metrics of heartbeat and timer for all cleanup schedule tasks

---

azkaban-common/src/main/java/azkaban/scheduler/Schedule.java
azkaban-common/src/main/java/azkaban/scheduler/ScheduleLoader.java
azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java
azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerImpl.java
azkaban-common/src/main/java/azkaban/trigger/Trigger.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManagerAdapter.java

Previously Schedule system's lock is pretty strict.
- synchronized keywords ensures only one user would getSchedule, and even if viewing a single schedule would require updates the whole schedules.
- syncObj make sure only one trigger can be updated at a time, and it's conflicting with trigger scanning process. 
These locks makes schedule system unable to handle large load as only one of hundreds would acquire the lock and do the operation while all other requests would need to wait for the lock to release, even if those requests are totally irrelevant with each other. (One should be able to update its schedule, while less rely on other schedule updates) 
This PR removes all sync keywords and the global lock to lower the lock level to individual schedule/triggers instead of keeping all of …

remove schedule global lock

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFinalizer.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java

Update job status in DB when calling finalizing flows. Table execution_jobs will be updated with corresponding status in job history page.

job status update on execution_stop

---

azkaban-common/src/main/java/azkaban/scheduler/MissedSchedulesManager.java
azkaban-common/src/main/java/azkaban/scheduler/Schedule.java
azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java
azkaban-common/src/main/java/azkaban/trigger/Trigger.java
azkaban-common/src/test/java/azkaban/project/ProjectManagerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectManagerServletTest.java

Add a back execute flag in the missedScheduleManager as to execute the flow immediately if such flag is marked enabled. Once enabled, every miss detection will trigger an execution of flow, even if there are multiple missed schedule in a single detection. The detection reuses the same logic of previous PR #3209 of email notification.
This PR implements the backend logic of previous PR of #3218 . User can enable this feature by updating their schedule with "Back Execute Once When missed Schedule Detects." on azkaban UI.

add back execute support for miss schedule

---

azkaban-common/src/main/java/azkaban/alert/Alerter.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/main/java/azkaban/server/SlaRequestUtils.java
azkaban-common/src/main/java/azkaban/sla/SlaOption.java
azkaban-common/src/main/java/azkaban/sla/SlaOptionDeprecated.java
azkaban-common/src/main/java/azkaban/trigger/builtin/SlaAlertAction.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-common/src/test/java/azkaban/sla/SlaOptionTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ExecutorServletTest.java

Before, SLA rules with action set to `ALERT` would only support email notifications. 
With this change SLA misses can also be notified via custom notification systems installed as plugins. When defining SLAs through the `setSla` or `executFlow` apis, users can now set configs for custom alerters. For example:
```
curl --location --request POST 'http://localhost:8081/schedule' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'ajax=setSla' \
--data-urlencode 'scheduleId=12345’ \
--data-urlencode 'settings[0]=,FINISH,00:01,true,false' \
--- new params -------------
--data-urlencode 'slaAlerters[myCustomAlerter][prop1]=value1' \ 
--data-urlencode 'slaAlerters[email][recipients]=abc@abc.com'
```
TODO: include the new custom alerter configs in the responses of …

Support custom alerters when defining SLAs with alert action.

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

**What's the problem**
The old code leaves a security hole which allow anyone to hit the UpdateProperty endpoint.
directly return error message, no further operation
**Test done**
Tested in a test cluster, asked some non-admin person to hit the endpoint, and the request is blocked, the property is not changed from status page

UpdateProperty endpoint: if not admin, directly return error and skip operation

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedImpl.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/executor/container/VPAFlowCriteria.java
azkaban-common/src/test/java/azkaban/executor/container/VPAFlowCriteriaTest.java
azkaban-common/src/test/java/azkaban/jobcallback/JobCallbackRequestMakerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

Project and flow name filter file looks like this:
proj1:flow1
proj1:flow2
proj2
proj3:flow1
which means VPA feature will not apply to proj1's flow1 flow, proj1's flow2 flow, all proj2's flows and proj3's flow1 flow.
It serves as the safeguard if there is any flow in production does not fit well with VPA's autoscaling algorithm.
One can use azkaban web api to reload flow filter text at runtime

Introduce VPAFlowCriteria to deny VPA feature based on project or flow name filter

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopJobUtils.java
az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestAbstractHadoopJavaProcessJob.java

To avoid truncated application_tag with insufficient flow/job description.
Local build pass with test successful.

increase single yarn application tag to 250

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/alert/Alerter.java
azkaban-common/src/main/java/azkaban/server/SlaRequestUtils.java
azkaban-common/src/main/java/azkaban/sla/SlaOption.java
azkaban-common/src/main/java/azkaban/utils/Emailer.java
azkaban-common/src/main/java/azkaban/utils/HTMLFormElement.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-common/src/test/java/azkaban/sla/SlaOptionTest.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/AbstractAzkabanServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/main/less/flow.less
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/flowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/scheduledflowpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/slapanel.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/style.vm
azkaban-web-server/src/web/js/azkaban/view/schedule-sla.js

This is a follow up on https://github.com/azkaban/azkaban/pull/3232. It:
-adds custom alerter configurations to the responses of `slaInfo` API.
-allows custom alerters to be configured via UI for SLA miss events. Flow execution failure alerts are configured via properties so no UI changes are required to support those. 
Assuming there is custom alerter plugin named `myCustom` which can be enabled by configuring a parameter called `myCustomAlerterParam` here is how the SLA definition page will be rendered.
Tested the changes in a local Azkaban instance. Verified that SLA miss alerts are set through UI successfully and that the feature doesn't break existing SLAs. In addition, I verified that the custom alerters configs are added correctly to the `slaInfo` responses. Here is an example …

Support configuration of alerter plugins via Web UI.

---

azkaban-common/src/main/java/azkaban/sla/SlaOption.java
azkaban-common/src/test/java/azkaban/sla/SlaOptionTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

Before all existing job level SLAs were set up for each job node in the DAG. In the logs we would see entries like this:
```
2023/03/01 22:38:01.172 -0800  INFO [TriggerManager] [JobRunner-jobZ-14213] [Azkaban] Adding sla trigger SlaOption{type=JOB_SUCCEED, flowName='myFlow', jobName='jobE', duration=PT1M, actions=[ALERT], emails=[abc@abc.com], alertersConfigs={}} to execution 14213, scheduled to trigger in 60 seconds
2023/03/01 22:41:51.873 -0800  INFO [TriggerManager] [JobRunner-jobE-14213] [Azkaban] Adding sla trigger SlaOption{type=JOB_SUCCEED, flowName='myFlow', jobName='jobE', duration=PT1M, actions=[ALERT], emails=[abc@abc.com], alertersConfigs={}} to execution 14213, scheduled to trigger in 60 seconds
```
Note that there is a job SLA rule defined for job `jobE` which is set up in …

Job level SLAs checks should only be set for/on the job the SLA rule matches.

---

azkaban-common/src/main/java/azkaban/scheduler/ScheduleLoader.java
azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManagerAdapter.java
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java

Years ago, we separate schedule and trigger in favor to unify the use of trigger in the backend but aborted in the middle. It creates the sync issues between both. We have "TriggerBasedScheduleLoader" as the intermediate bridge to coordinate while trigger updates and ensure "schedule" updated to serve API request well and correctly.
This PR is to fix the missing sync on web server just restart and loading all the triggers into schedule format so schedule API can serve request immediately on restart, no need to wait for refresh to update them.
local build pass:

Sync Schedule with Trigger when web sever is up

---

azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java
azkaban-common/src/main/java/azkaban/trigger/JdbcTriggerImpl.java

For the legacy reason schedule and trigger are self-maintained and schedule itself maintains a cache to get trigger data more quickly especially when no update on trigger. 
The better and cleaner fix is to remove the schedule layer but link API to trigger directly, in this way we don't have to maintain the status of schedule. However to quickly mitigate this issue, in this PR:
- fix the bug that store new schedule in cache;
- enable more debug level log to help increase debug efficiency.
local build passed.

fix the bug that returned the outdated schedule metadata for getSchedule call

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/test/java/azkaban/executor/ExecutionOptionsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

This is the initial user-interface/contract definition for flow/execution-level restart when one fails.
Defined 3 flow-parameter keys that is exposed to users: 
- `allow.execution.restart.on.status` that describe a set of terminated status when an execution can restart
- `"execution.restart.count"` == how many times can an execution restarts
- `"execution.restart.strategy"` == the strategy (e.g. "restart_from _root", "disable_finished_nodes")
Also Azkaban side controlled config:
- `"azkaban.execution.restartable.status"` the restartable-status allowlist for user to pick from
- `"azkaban.execution.restart.limit"` the limitation how many times an execution can restart
Plus the cross-validation at execution creation time:
- the `user-input status list` …

Add customizable flow-level restart parameters & validation with Azkaban config

---

azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java

Fixes a bug where executions with final status EXECUTION_STOPPED were not shown in the page of Recently Finished Executions.

Include executions with EXECUTION_STOPPED status in the 'Recently Finished' page

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java

Previously Azkaban use only `isExecutionRetried` boolean flag to record and control flow/execution retry info, we now want to allow retrying for a number of times defined by the user.
1. `isExecutionRetried` only means whether an execution is retried
2. At flow submit time, if the `flow.retry.statuses` is set, then `flow.max.retries` fallback value is `1` if not set
3. use `flow.max.retries` to determine how many times can this execution retry at `restartFlow` method
**Tests done**
1. unit tests
2. deploy the change to test cluster, launched an execution with `flow.max.retries=2` and trigger EXECUTION_STOPPED by killing the k8s pod:
The old execution got into EXECUTION_STOPPED and an new execution is being restarted:
The old execution with …

Use flowParameters.executionMaxRetries to control flow retry

---

azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/container/watch/FlowStatusManagerListener.java

Previously when the pod-complete event comes, only if the execution status in Azkaban DB is Non-Finalized, then the `restartFlow()` logic got triggered.
Now to support the flow-retry on `FAILED`, we need to trigger the logic when execution status is Finalized (FAILED is a finalized status).
Since the logic to check for the permitted retry-statuses is already implemented in `restartFlow()` method #3261, now we just need to enter this logic when the execution status is finalized.
**Tests done**
Tested in the staging cluster:
Started the original execution 786255 with `flow.retry.statuses=FAILED,EXECUTION_STOPPED` and `flow.max.retries=1` and failed the flow by killing the hadoop application, a new execution 786256 being retried:
The webserver log for …

Extend pod complete event handling to also check & retry execution in finalized status including FAILED

---

az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/AbstractHadoopJavaProcessJob.java
az-hadoop-jobtype-plugin/src/main/java/azkaban/jobtype/HadoopShell.java
azkaban-common/src/main/java/azkaban/jobtype/JobTypeManager.java
azkaban-exec-server/src/main/java/azkaban/execapp/JobRunner.java

Exceptions like below in the Job logs, often make users think that that was the reason for failure (which is not in most cases if not all). Also, for some jobtypes these exceptions are repeatedly logged. 
Therefore, we are removing them from the job logs and only logging them in the executor server logs. 
```
04-04-2023 19:46:48 PDT my-job ERROR - caught error running the job
java.lang.RuntimeException: azkaban.jobExecutor.utils.process.ProcessFailureException: Process exited with code 1
at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:317)
at azkaban.jobtype.AbstractHadoopJavaProcessJob.run(AbstractHadoopJavaProcessJob.java:64)
at com.linkedin.spark.HadoopSparkJob.runSparkJob(HadoopSparkJob.java:365)
at com.linkedin.spark.HadoopSparkJob.run(HadoopSparkJob.java:261)
at …
```

Remove misleading ProcessFailureException from job logs and fix NPE during Noop job creation.

---

azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/FlowStatusChangeEventListener.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java

Part of the flow-retry feature, and it's improving the implementation: 
* Remove modifying the user-input `ExecutionOptions`, keep them as is
* clearer model to count & control how many times can an execution retry, respectively for non- / terminal originalStatus
* remove `isExecutionRetried` from `ExecutionOptions` because it doesn't distinguish type of retry, and retry count should be execution level info.
* use `systemRetriedTimes` to count retries on `dispatch/preparing/ready` status executions (by default should retry by the system)
* use `customRetriedTimes` to count retries on finalized status `failed/execution_stopped` defined by users
**Tests done**
* updated unit tests 
* tested in a cluster: 
Launched the original execution 786575:
Delete …

Use ExecutableFlow member variables to track and control flow-level retry

---

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionOptionsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/test/java/azkaban/flowtrigger/TriggerInstanceProcessorTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/LoginAbstractAzkabanServletTestBase.java

As a follow up of #3269, this `ExecutionOptions.merge()` method is required for honoring the flow-parameters defined with DSL with the project uploaded.
Also, because previously the logic that add `project-DSL defined flow-parameter` to `ExecutableFlow` happens at database reading time, it creates confusion between webUI display and real execution setting.
1. merge all the defined fields of another `ExecutionOptions` into "this";
2. hot fix some bugs introduced in previous PR.
3. remove loading `project-DSL defined flow-parameter` to `ExecutableFlow` from DB reading time.
**Tests done**
1. unit tests
2. end to end test in staging cluster: 
Uploaded the project with DSL setting `param.overwrite.allow.restart.on.execution.stopped=true` to the flow.
Then …

Implement ExecutionOptions merge() method; remove loading of project-DSL flow-parameter to ExecutableFlow at read; hot fix bugs;

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/ExecutionController.java
azkaban-common/src/main/java/azkaban/executor/ExecutionFlowDao.java
azkaban-common/src/main/java/azkaban/executor/ExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManager.java
azkaban-common/src/main/java/azkaban/executor/ExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/executor/FetchActiveFlowDao.java
azkaban-common/src/main/java/azkaban/executor/JdbcExecutorLoader.java
azkaban-common/src/main/java/azkaban/executor/Status.java
azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/jmx/JmxContainerizedDispatchManager.java
azkaban-common/src/main/java/azkaban/jmx/JmxExecutionController.java
azkaban-common/src/main/java/azkaban/jmx/JmxExecutorManager.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionFlowDaoTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorManagerTest.java
azkaban-common/src/test/java/azkaban/executor/MockExecutorLoader.java
azkaban-db/src/main/sql/create.execution_flows.sql
azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

From our investigations, web server unnecessarily loads too many FlowProps objects from database to memory which causes too high memory footprints and thus causing web server out-of-memory easily under decent load. Each FlowProps object is a user defined hashmap which can be huge in size. As a result, we should prevent loading unnecessary FlowProps from MySQL to Memory if possible.
Warning: Possibly read one commit at a time is easier for review
1. Split ExecutorLoader.fetchUnfinishedFlow to fine-grained methods and onboard to rest of the codebase to reduce unnecessary memory footprint:
1.1. When render Azkaban Job/Flow logs for a given executionId in getFlowLogData() OR cancelling flow using cancelFlow(), no need to read all unfinished executions from MySQL and do filter in application …

Reduce memory pressure on WebServer by preventing loading unnecessary FlowProps from MySQL to Memory

---

azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/main/java/azkaban/executor/container/VPAFlowCriteria.java
azkaban-common/src/test/java/azkaban/executor/container/VPAFlowCriteriaTest.java
azkaban-common/src/test/resources/flow_filter.txt
azkaban-common/src/test/resources/flow_filter2.txt

Originally, we exclude some (projectName, \*) and (projectName, flowName) from VPA flow resource recommendation feature. It does not work for some edge cases where projectName is different but flowName is the same. As a result, we should further add (\*, flowName) support to exclude them from VPA feature.

Add flow name only filter to VPA filter

---

az-core/src/main/java/azkaban/Constants.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java

As the `executionRetriedByAzkaban` is already replaced by `{user,system}DefinedFlowRetryCount`, removing all its reference to be cleaner.

Remove unused field executionRetriedByAzkaban, relaced by retry-count

---

azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java

Remove the Reference of an already deleted import constant

Fix wrong import

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/ArchiveUnthinner.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/utils/DependencyTransferManager.java
azkaban-common/src/test/java/azkaban/project/ArchiveUnthinnerTest.java
azkaban-common/src/test/java/azkaban/utils/DependencyTransferManagerTest.java
azkaban-exec-server/src/main/java/azkaban/container/ContainerizedFlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/AbstractFlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowPreparer.java
azkaban-exec-server/src/main/java/azkaban/execapp/ProjectDirectoryMetadata.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowPreparerTest.java
azkaban-spi/src/main/java/azkaban/spi/Dependency.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This PR is mostly optimization for gcn-38523 where upload project zips was hanging during validationProject, but it is unclear to us which part (download dependency, or validate dependency) failed, or it's possible that upload thread suddenly gone was caused by maybe uncaught exception/throwable (for example, Downloading Dependencies if any exception, the completableFuture.completeExceptionally(Throwable), we throw throwable instead of Exception).
Basically two scenarios could cause a "hanging" upload:
- Downloading itself is hanging, such as waiting inputStream;
- There is a throwable, but our code does not have such logic to handle it, so this thread just dead without telling CRT it is failed;
To address the issue above, a few optimization were made:
- Add default timeout 5 minutes for …

Add timeout to dependency download at project upload stage

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/ExecutionOptions.java
azkaban-common/src/main/java/azkaban/executor/FlowStatusChangeEventListener.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/test/java/azkaban/executor/OnContainerizedExecutionEventListenerTest.java
azkaban-exec-server/src/main/java/azkaban/execapp/FlowRunner.java
azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java

* As the flow-level-retry happens, we should let users know about the which execution is the "child" retried one, and which is the retried's "parent" execution. 
* In following PRs, we will also need to improve the webUI so as this information can be exposed to users in an efficient way.
1. add fields for an `ExecutableFlow`'s flow-level-retry `Root / (Direct) Parent / (Direct) Child` ExecutionIDs;
2. populate and persistent these fields for both the original and retried execution after successfully retrying;
3. log these lineage info + the retry-counts, also report these fields in the flow status event reporter.
4. expose all flow-retry info in ajax `fetchexecflow` endpoint
**Tests done**
1. unit tests
2. end to end tested in staging cluster:
Started …

Flow-retry - store, log & report the parent-child lineage

---

azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java
azkaban-web-server/src/main/tl/flowsummary.tl

Add backExecuteOnce in return schedule and make it visible in summary page.
the page would be shown as the following:

add backExecuteOnce in getSchedule API and UI visible

---

azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm
azkaban-web-server/src/web/js/azkaban/view/exflow.js

As the flow-level-retry backend logic being implemented, we need to develop the web UI so as users can get a better understanding of the retry-related information, and the lineage between the original & retried executions.
In execution detail page, added a "Retries" tab that shows a table of all flow-level-retry information.
Including links to its parent / child executions.
**Tests**
Tested in local solo-sever as well as in an test cluster:
When no flow-retry is config:
For an execution has been retried:

Add "Retries" tab in execution detail page for flow-retry related info

---

azkaban-common/src/main/java/azkaban/scheduler/ScheduleManager.java
azkaban-common/src/main/java/azkaban/scheduler/TriggerBasedScheduleLoader.java
azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectManagerServletTest.java

Azkaban allows users to define flow triggers in HadoopDSL format, they're parsed and scheduled in the process of upload. The initial order is unscheduleTrigger -> handleUploadZip -> some postHandleWork such as rescheduleTrigger. However handleUploadZip step is a bit fragile and might fail due to intermittent issues from infra side, for example, artifatory down. It would lead to project upload in a broken stage where the previous triggers were removed by that broken upload. This PR is to change the order of unscheduleTrigger, moving it after uploadZip.
- adjust order of unschedule QuartzJob, so even if uploadFile fails, the previous trigger remains unimpacted.
- fix remove schedule logic by using getAllSchedule instead of getUpdatedSchedule.

fix flow trigger lost caused by failure project upload

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/executor/ExecutionControllerUtils.java
azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutionOptionsTest.java
azkaban-common/src/test/java/azkaban/executor/container/watch/KubernetesWatchTest.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ExecutorServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/executingflowpage.vm

- Rename flow-retry related constants
- improve wording in the webUI 
- fix logging typo

Rename constants to better reflect "retry" of flows; Improve UI wording

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/project/FeatureFlag.java
azkaban-common/src/main/java/azkaban/project/Project.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/LoginAbstractAzkabanServlet.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpageheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectsidebar.vm
azkaban-web-server/src/test/expected/project-side-bar.html
azkaban-web-server/src/test/java/azkaban/fixture/MockProject.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectPageHeaderTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectSideBarViewTest.java
azkaban-web-server/src/web/js/azkaban/view/project-modals.js

This project aims to protect grid security by attaching an Upload Lock to each project. The Upload Lock can be enabled by setting the config value azkaban.upload.privilege.user to the name of a privileged user who can upload projects. If this value is not set, no lock will be applied and the project will behave as usual. Once the privileged user has deployed a project, the Upload Lock will be automatically activated and prevent any ad hoc uploads from other users, unless the ad hoc upload feature flag is enabled. The ad hoc upload feature flag can only be accessed by azkaban admin. If it is enabled, it will override the Upload Lock and allow any user to upload projects, regardless of whether the privileged user has deployed or not.
- Introduce Project Level Feature Flag as current azkaban …

Add UploadLock in project level and have a feature flag enable.project.adhoc.upload to remove the lock

---

azkaban-web-server/src/main/java/azkaban/imagemgmt/servlets/ImageVersionServlet.java

As short-term solution to make ImageVersion operations visible from Azkaban logs.
Long-term solution: put all API body fields to logs in AbstractAzkabanServlet so that every API call params (already support in logs) & body (missing from logs) can be found at logs for history / analysis.

Add logs to record ImageVersion operations

---

azkaban-common/src/main/java/azkaban/trigger/builtin/ExecuteFlowAction.java

**Background**
With previous changes #3269 and #3273, we aim to:
* load the flow-parameters defined in the project .gradle/.flow files  and then merge with those parsed from webUI call to the ExecutableFlow and persist, at submit time;
* at read/fetch/query time, we simply query DB without any other operation and can get the integral ExecutableFlow object.
**What's missing**
* Without the merging, the executions created by Azkaban scheduling use case will not have the flow-parameters defined in the project .gradle/.flow files persisted, 
* thus creating errors when these Executions being read and used.
**Tests done**
* deploy the change to a testing cluster, and uploaded a project zip that has `param.override`  defined in gradle file for its flows
* scheduled a flow, and for the started …

At scheduled execution triggering(submit) time, merge flow-params from project DSL and from webUI

---

azkaban-common/src/main/java/azkaban/executor/AbstractExecutorManagerAdapter.java
azkaban-common/src/main/java/azkaban/metrics/CommonMetrics.java

* To allow platform admin, partners and users know better about the overall webServer `cancel flow` experience
* So as can react faster if any issue happens, avoid large-scale killing failure resulting in resources not released and later executions blocked
**What's done** 
Define meters, each accordingly mark:
1. trigger whenever a cancel flow action
2. trigger when fail to reach the execution
3. trigger when fail to gracefully call executor cancel endpoint, force killing the pod
4. trigger when fail the whole thing
**Tests done**
Deployed to a test cluster and verified the killing action will be reflected in the in the metrics dashboard.

Emit webServer metrics around cancle flow in general / unreachable / ungraceful kill / failure

---

azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java

As an Azkaban user, I want my flow to fail immediately if one of the image required to run the flow is unavailable as it is a non-recoverable error. Currently, the flow will just stuck at Dispatching until eventually getting cleaned up by ContainerCleanupManager.
The reason is we didn't catch necessary exception when fetchVersionSet.
After this fix, the flow fails immediately under such case with these logs:
> Unable to dispatch container in Kubernetes for : 151842
Reason for dispatch failure: azkaban.imagemgmt.exception.ImageMgmtException: Unable to get VersionInfo for image type: spark, image version: 0.0.19999 that is in one of the following states: NEW,TEST,ACTIVE,STABLE.

Fail fast if jobtype image is invalid during dispatching

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerizedDispatchManager.java

If an execution failed during Dispatching, it means the execution failed without executing any user code/flow/job which matches our definition of EXECUTION_STOPPED.

Mark execution as EXECUTION_STOPPED if failed during Dispatching

---

docs/configuration.rst

I've noticed that some tables (`Multiple Executor Mode Parameters` and `Executor Server Properties`) are missing from the config page.
Performing some tests with https://rubygems.org/gems/github-markup it turns out, that even a single formatting error within the table causes the whole table to be skipped by the RST2html converter.

Fix formatting errors in some tables

---

az-core/src/main/java/azkaban/Constants.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This allows we control and rollout restrictions inside platform gradually and independently to control the effect to users. azkaban.disable.adhoc.upload is set, we can only disallow the adhoc uploads but it would not affect the lock status being updated at the project level.

Add the config control to toggle the ability of disabling upload

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/test/java/azkaban/executor/container/ContainerCleanupManagerTest.java

To fix an design fault that kills the yarn-apps of jobs defined to be "Finish Current Running" or "Finish All Possible".
Removed "FAILED/FAILED_FINISHING/FAILED_SUCCEEDED" from to-be-cleaned statuses for yarn-app-kill task.
**Tests done**
* unit test
* tested in staging cluster

CleanupManager: only cleaning yarn-apps of executions that are canceled by user or is EXECUTION_STOPPED

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerImplUtils.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/container/KubernetesContainerizedImplTest.java
azkaban-web-server/build.gradle

Adding a bug fix for including proxy users from flow param, in addition to users from the DAG.

Fixing bug where proxy user from flow parameter was not included

---

azkaban-common/src/main/java/azkaban/executor/container/ContainerCleanupManager.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetrics.java
azkaban-common/src/main/java/azkaban/metrics/ContainerizationMetricsImpl.java
azkaban-common/src/main/java/azkaban/metrics/DummyContainerizationMetricsImpl.java

By adding these metrics, we got to know the number of stale flows of each concerning statuses, and with this info, we can set up alerts to react to incidents quicker.
**Tests done**
Tested in our staging cluster's webserver, the metrics correctly got published to the metrics system and dashboard can view the outcome.

CleanupManager: emit metrics that count the number of stale flows of different statuses

---

azkaban-common/src/main/java/azkaban/trigger/Trigger.java
azkaban-common/src/main/java/azkaban/trigger/TriggerManager.java
azkaban-common/src/main/java/azkaban/trigger/builtin/BasicTimeChecker.java

When a cron expression has expiration date itself, current system would not handle such edge case properly and everytime the triggers loop over, the trigger that satisfied with trigger condition would try to fire execution everytime. Thus we see the bug presented as the schedule executions flow in minutely frequent level when the schedule should past.
Even at latest quartz 2.5.0, the getFinalFireTime's implementation is still missing: https://www.javadoc.io/static/org.quartz-scheduler/quartz/2.5.0-rc1/org/quartz/CronExpression.html#getFinalFireTime(). To identify the last execution, we simply check whether the getNextCheckTime updated is in the past, usually getNextCheckTime should update to a future time after now, however, if it is returning a past value, we could treat this trigger as …

Fix schedule expiration bug

---

azkaban-common/src/main/java/azkaban/executor/ExecutorApiClient.java
azkaban-common/src/main/java/azkaban/executor/ExecutorApiGateway.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/test/java/azkaban/executor/ContainerizedDispatchManagerTest.java
azkaban-common/src/test/java/azkaban/executor/ExecutorApiGatewayTest.java
azkaban-web-server/build.gradle

This PR allows us to disable the reverse proxy for the executor resources on k8s pods and the web server uses the flow pod's *Service* endpoint to interact with the executor pods.
If the executor pod is deployed with a Service, it usually can be directly reached from another pod in the same cluster. Thus, if the Azkaban web server is containerized and running in the same k8s cluster, the reverse proxy (e.g. Ambassador) is not needed anymore and the web server can talk to the executor pod with the URL: `http://[serviceName].[namespace]:[servicePod]`. Note that it still holds even the web server pod and executor pod are under different namespaces (tho they have to be in the same k8s cluster).
To fully enable this feature, two fields in azkaban.properties might need to be changed:
``` …
```

allow disabling Ambassador on web server and call pod's service directly

---

az-core/src/main/java/azkaban/Constants.java
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/jobpage.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectpageheader.vm
azkaban-web-server/src/main/resources/azkaban/webapp/servlet/velocity/projectsidebar.vm
azkaban-web-server/src/test/expected/project-side-bar.html
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectPageHeaderTest.java
azkaban-web-server/src/test/java/azkaban/webapp/servlet/ProjectSideBarViewTest.java

This PR is the third step to address the security which restricted the permission to edit job properties when project lock is on. This limitation is aiming to protect production projects from any adhoc modifications unless the projects have to be gone through a review process and reuploaded by upload privileged user who intented to be set by a deployment automation user. This restriction would also be put under a feature flag azkaban.disable.job.props.override.on.locked. 
- Disable "Job Properties" Edit via UI and via API when project lock is set;
- Fix the lock status when adhocUpload restriction is not set, we should still properly change the project lock status;
- UI improvements:
1. hide edit button for job properties when lock is on;
2. show adhocUpload editable only when this …

Disable job property edit permission when project lock is set

---

azkaban-common/src/main/java/azkaban/executor/OnContainerizedExecutionEventListener.java
azkaban-common/src/test/java/azkaban/executor/ExecutionControllerUtilsRestartFlowTest.java
azkaban-common/src/test/java/azkaban/executor/OnContainerizedExecutionEventListenerTest.java

To make flow-retry a fully functional feature, adding observability
**What's dione** 
Emit metrics when restarting the executin, separately for each retry-strategy
**Tests done** 
Tested in staging cluster:
* Started a flow with retry option and kill its yarn-app to fail it 
* The flow got retry and in metric dashboard saw the counted data point

flow-retry: emit count metrics

---

az-core/src/main/java/azkaban/Constants.java
azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java
azkaban-common/src/main/java/azkaban/executor/ExecutableFlow.java
azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
azkaban-common/src/main/java/azkaban/flow/Flow.java
azkaban-common/src/main/java/azkaban/project/AzkabanProjectLoader.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectHandlerSet.java
azkaban-common/src/main/java/azkaban/project/JdbcProjectImpl.java
azkaban-common/src/main/java/azkaban/project/Project.java
azkaban-common/src/main/java/azkaban/project/ProjectLoader.java
azkaban-common/src/main/java/azkaban/project/ProjectManager.java
azkaban-common/src/main/java/azkaban/utils/SecurityTag.java
azkaban-common/src/test/java/azkaban/executor/ExecutableFlowTest.java
azkaban-common/src/test/java/azkaban/project/JdbcProjectImplTest.java
azkaban-common/src/test/java/azkaban/project/ProjectManagerTest.java
azkaban-db/src/main/sql/create.projects.sql
azkaban-web-server/src/main/java/azkaban/webapp/servlet/ProjectManagerServlet.java

This PR is to implement a security update in Azkaban to enhance data protection and access control. Grestin certificates will now utilize a new principal name format for those projects that not uploaded by upload privilege user. This change affects all clusters and is designed to safeguard production data integrity. Existing flows remain unaffected, while new flows will require updated ACLs to accommodate the certificate principal name change. Detailed change would come in init containers following this change.
- Introduce SecurityTag in each azkaban resource (project.flow) to identify if a flow should subject to new security cert model;
- Only projects are not uploaded by upload-privileged-user and this is NEW_FLOW, the adhoc cert fetch ENV would be passed into init container;
- …

Azkaban security enhancement by cert management

---

azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java
azkaban-common/src/test/java/azkaban/server/HttpRequestUtilsTest.java

These parameters starting with `azkaban.{flow|job}` should be generated by the system to honestly track the status of the execution / job, but not config-able by users.
**Tests done**
Simple change, unit tests is good enough

Filter out flowParameters starting with azkaban.{flow|job} for non-Azkaban-admin

---

az-core/src/main/java/azkaban/Constants.java
az-core/src/test/java/azkaban/ConstantsTest.java
azkaban-common/src/main/java/azkaban/server/HttpRequestUtils.java

To fix the bug that user see `"[Invalid flow.retry.strategy = retryAsNew. Valid values are: [retryAsNew, disableSucceededNodes]]`
With this change, both the enum name or the readable name can be accepted.
**Tests done**
Added Unit test, enough for small change

Fix the bug so can input FlowRetryStrategy from readable name or Enum name
